[quote.epigraph, , 1 Cor. 1:26-29]
____
Ye see your calling, brethren, how that not many wise men after the flesh,
not many mighty, not many noble are called.
But God hath chosen the foolish things of the world to confound the wise;
and God hath chosen the weak things of the world to confound the things which are mighty;
and the base things of the world, and things which are despised, hath God chosen, yea,
and things which are not, to bring to nought things that are:
That no flesh should glory in his presence.
____

== Preface.

The only former edition of the Life of Oliver Sansom was published in the year 1710,
under the care of Thomas Ellwood;
from the supplement to whose Journal the following paragraph is extracted.

"`This year (1710) our friend Oliver Sansom,
formerly of Farringdon since of Abingdon in Berkshire,
who had long war with the Priests about tithes, dying in the 2nd month,
and leaving behind him '`An Account of some remarkable passages of his Life,`'
which he communicated in his life-time to our friend Thomas Ellwood to peruse;
who being always ready to be helpful and serviceable to all, especially his friends,
transcribed the same and fitted it for the press.`"
This work has now been for many years very scarce.

The present edition is a reprint of the former with the addition of some original letters;
any remarks by the present editor are either enclosed in brackets or in a footnote.
It has been divided into chapters,
and some slight alterations have been occasionally made in the text;
but the sense of the author has in all instances been scrupulously maintained.

The Editor desires to express his obligation to J. W. Roake of Newbury,
(who traces relationship to Oliver Sansom,) for the liberty granted to insert copies
of some original letters in his possession which have never before been published;
and which he believes add much to the interest of the present edition.

It is obviously needful, before the reprint of a work of this kind is undertaken,
to consider whether it is so far calculated to afford
interest and instruction in the present day,
as to justify the attempt to circulate a new edition.
The occurrences related in the following pages being originally and unaffectedly expressed;
the doctrine they uphold being sound, plainly and pointedly declared;
it appears to the editor that a considerable proportion
of the work is far too valuable to be lost in oblivion;
and as, in preparing it for the press,
no part seemed sufficiently wanting in interest to warrant its omission,
it has been reprinted entire.

In placing this volume in the hands of his friends,
the Editor cannot but express the desire which induced him
to commence the work and which still continues with him,
viz. that it may tend to encourage them to maintain in patience and meekness,
but with firmness and in all their integrity those
principles which we are called on to uphold,
and for which our early Friends had so much to suffer; that like them,
we may be made willing, if the will of God be so, to suffer the loss of all things,
for the word of God and the testimony of Jesus.

The Memoirs of our early Friends abound with that
which is calculated to instruct and confirm;
their virtuous and devoted lives, their happy and triumphant deaths,
furnish unquestionable evidence that they did not follow cunningly devised fables,
but the Truth as it is in Jesus; and invite us to follow them as they followed Christ.
They were remarkable for their devotion to and steadfastness in the Truth;
to them it was indeed precious:
they counted all things but as loss and dross that they might win Christ.
They were "`troubled on every side; without were fightings,
within were fears;`" they were treated as the offscouring of all things,
and had to sacrifice their property, their liberty, and in many cases their lives,
on account of their faithfulness to Christ, whom they loved with their whole heart.
They were content to forego their business, their pleasures,
and even what was dearer than either, the enjoyment of their homes and families,
so that they might be faithful to their Lord and Master.
Through faith in Him they obtained victory and found an abundant reward.
In their prison houses and low dungeons they could speak of the goodness of the Lord,
they could pray unto Him and praise Him aloud; they could proclaim under their trials,
what many are unable to acknowledge in the midst of all their outward prosperity;
"`The Lord is our portion,`" "`the lines are fallen unto us in pleasant places, yea,
we have a goodly heritage.`"
How were they blessed in basket and in store,
how were they blessed in what is far more valuable,
the assurance of that eternal life which Christ had purchased for them,
and which he had shown them through his Holy Spirit.

"`Hold such in reputation, who for the work of Christ were nigh unto death,
not regarding their life.`"
"`Whose faith follow, considering the end of their conversation, Jesus Christ, the same,
yesterday, today, and forever.`"

[.signed-section-signature]
James Boorne, Jr.

[.signed-section-context-close]
Reading, Fourth month, 1848.
