== Chapter VI.

[.chapter-synopsis]
* His concern as regards the schism of Wilkinson and Story
* Is summoned to a Court-Leet
* Is elected Constable of the Hundred
* His letter to the Lord of the Manor
* Goods distrained for not taking the Oaths
* Another letter to the Lord of the Manor
* Account of and letter from Joan Vokins
* Twice fined for attending Abingdon Meeting
* Is informed against and fined £20 for preaching in his own Meeting
* Goods distrained but returned after four years
* Clears himself of an untrue report
* Converses with two informers, who inform against m him for attending Meeting
* Appears at the Quarter Sessions at Reading
* Oath tendered to ensnare him
* Refuses to take it and is imprisoned
* Injustice towards Friends who appealed against the Informers.

I have hinted something concerning the spirit of opposition, division and separation,
which had for some time wrought mysteriously and covertly in some,
against the Truth and faithful Friends thereof.
But by this time the same was grown stronger and wrought more openly,
in and through those persons who first appeared for it in our county of Berks and elsewhere.
Which caused great grief, exercise and sadness of heart upon faithful Friends;
amongst whom I had a lot of suffering, through the Lord`'s mercy,
even in this kind as well as otherwise.
For when the paper at the yearly-meeting, in 1677, was subscribed by many Friends,
against this spirit of division as it had appeared through John Story,
John Wilkinson and some others; I being then at the said yearly meeting,
and having a real concern upon my spirit against that rending spirit and its abettors,
did in unity with my brethren subscribe the said paper;
which to this day I never had any reproof from the Lord for, but justification in.
But oh! the bitter enmity and opposition in them
which had joined with the aforesaid bad spirit,
was so much the more fierce and violent against me in particular;
because no other Friend in our county beside me had his hand to that paper.
But although they strove to tread me down in their spite, yet the Lord upheld me,
and still preserved me by His mighty power,
which He was pleased to make known in my great weakness,
and He gave me victory over that wicked spirit in its strongest instruments;
blessed and praised be the name of my tender God, whose the power is,
and unto Him alone the glory belongs forevermore.
Amen.

Yet this exercise and suffering from false brethren,
who had received this spirit of contention, division and separation,
was great and grievous,
and also of long continuance upon faithful Friends of this county;
the dividing work being promoted and carried on by
some who had been of some note amongst Friends there;
but are since gone out,
and most of them yet continue out of the unity of Christ`'s church, in a separation;
having shut up the meeting-house doors against Friends
who had a just right and property therein.
But seeing the works of this wicked spirit are recorded elsewhere,
I shall not in this place enlarge by descending further into particulars.
Yet inasmuch as it hath been the most grievous of exercises,
and the hardest of trials or suffering, I do purpose,
if the Lord give time and ability to commit to writing, for the benefit of posterity,
some remarkable passages relating to my own particular sufferings in this respect,
according to the notes I have by me thereof.
Wherein my chief aim is to commemorate and acknowledge
the mercies and goodness of my tender God unto me;
who did support and uphold me in all my trials and sufferings,
and hath delivered me out of all my distresses,
and ail along hath helped and never failed me; glory and honour,
thanksgivings and praise be rendered unto him over all forevermore.
Amen.
But at present I shall go on, as the Lord makes way,
to give a further account of what other sufferings
and exercises did come upon me for the Truth`'s sake,
from the spirit and people of the world;
which I esteem more easy and far less grievous than
those before-mentioned from false brethren.^
footnote:[The schism, of which Story and Wilkinson were at the head,
is frequently referred to in the writings of some of our early Friends.
It commenced and spread mostly in the north; there were however those in Loudon, Bristol,
and some southern counties, who,
through ease and unwatchfulness having lost their first love, and the discerning spirit,
were deceived by a specious bait,
and became the cause of much exercise and trouble to their brethren.
{footnote-paragraph-split}
The ground of difference was alleged by them to be,
their objection to those meetings for regulating the affairs of the Church,
exercising a salutary discipline over its members,
and more especially against the establishment of women`'s meetings,
which George Fox and other Friends "`were moved to set up.`"
They stated with a show of plausibility which gained some, chiefly the looser sort,
to their ranks, '`that such meetings were needless,
some years having been passed in peace and unity without them;`' and,
'`that every individual ought to be guided by the Spirit, and left free to act;
that meetings for discipline were a form,
and the exercise of that discipline an infringement upon individual liberty.`'
Great endeavours were made for their enlightenment and restoration.
In second month, 1676, a meeting was held at Drawell which lasted four days,
in which '`many Friends laboured much for their preservation,
but they were too far gone in a separate spirit to be reclaimed.`'
They therefore became out of unity with the body,
who, '`walking by the same rule,
minded the same thing,`' fell to jangling and after awhile
the best among them came to see how they had been deceived,
and the rest after having had separate meetings are said to have
'`vanished as snow in the fields.`' See Sewel`'s History,
folio edition, p. 583-4.
{footnote-paragraph-split}
Berkshire,
especially the Reading meeting, was the scene of much division on this account;
many Friends there who had formerly been great sufferers
for their principles being led away.
Amongst these were Thomas Curtis, Benjamin Coales, Leonard Keyes, and others,
whose names are familiar and whole tracts are extant.
Perhaps a better description of the state of things,
so trying to rightly concerned Friends of the county, cannot be given,
than a brief abstract of the first few pages of an old monthly meeting-book.
It commences thus--"`A booke for the recording the proceedings
of ye monthly men`'s meetings of ye people of God called Quakers,
in ye town of Reading, in ye county of Berkse:
Beginning to be thus recorded this twentie sixt day of ye first month, 1685.
Not but there was a monthly booke for many years before,
which Benjamin Coales did keep and did record ye proceedings of those meetings in:
But for som years last past ye sd B. Coales with several others that had
ye sway in those meetings have taken part with ye spirit of opposition
and division which first appeared openly in John Wilkinson,
and their party in ye north against orderly proceedings in monthly and quarterly
men`'s meetings and women`'s meetings and other things too large now to mention.`"
It then, for the information of future generations, goes on to state,
how these individuals deemed "`letters of advice and counsel from good
Friends but papers of contention,`" and would not receive them;
and much that would grieve the spirits of "`all who
retain their first tenderness in the Truth.`"
After reciting "`Ambrose Rigge, his vision concerning John Story;`" also
"`G. F`'s vision or revelation concerning J. S. and J. W.`"
with the "`Vision of Charles Marshall,`" and
"`part of an Epistle of G. F`'s concerning this spirit of opposition after it openly appeared;`"
they add,
"`And now notwithstanding these, and we believe as many more, visions, faithful warnings,
and testimonies, as great part of this book (if not all) would contain if written,
timely signified: yet many that have followed this spirit will not hear,
but still go on in their opposition and gainsaying.`"
Then follows an account of some of its fruits; how, with unkind speeches,
they were refused the use of the meeting-house for
disciplinary purposes and women`'s meetings.
Things went on so far that they could not meet in the house,
Thomas Curtis having fastened up the door,
and one of the first entries is that of a payment to Wm.
Speakman of 9.S. 9d. "`for 4 forms and 2 X legd.
stools for frds.
to sit on at ye meeting-house door.`"
This lamentable state of things prevailed more or less throughout the County,
the rise and progress of it must indeed have caused the burden to be great
on such faithful and well concerned Friends as Oliver Sansom.]

On the 17th day of the eighth month, 1678, one Thomas Blagrave,
who was steward of the court to Sir Robert Pye, lord of the manor of great Farringdon,
where I lived, kept a court-leet there,
and being an envious man against truth and Friends,
and desirous to get an occasion against me,
he sent the bailiff to warn me peremptorily that nothing
must serve but my personal appearance at the court.
I was sensible a snare was intended;
yet I innocently gave up in my mind and intended to appear;
but it pleased the Lord to prevent me by indisposition of body,
so that I found I could not be there.
Wherefore fearing some wrong use might be made of my absence, I wrote a few lines,
and sent them to the steward in the time of the court
to signify the cause of my not appearingthere;
the copy follows:

[.embedded-content-document.letter]
--

[.salutation]
Thomas Blagrave,

Whereas I was summoned to appear at the Court-Leet held this day in this town;
I did intend, by the Lord`'s permission, to have appeared there accordingly,
to offer such service or fealty as a subject to the king, residing in this town,
is by the law obliged, to:
provided my duty and obedience to my Saviour Jesus Christ be not violated.
But it hath pleased the Lord to visit me with sickness,
so that I cannot come to attend there without manifest danger.
Therefore I do herewith send a penny in acknowledgement of my fealty,
desiring that for this time my absence may be excused.

[.signed-section-signature]
O+++.+++ Sansom.

[.signed-section-context-close]
Farringdon, the 17th of Eighth month, 1678.

--

While I was writing those few lines,
it was laid weightily upon me to insert something as a testimony
and warning to my neighbours against oaths and swearing;
which I did by the following postscript.

[.embedded-content-document.letter]
--

And you my neighbours now assembled at the court,
it is in my heart to lay one weighty matter before you in the fear of God,
and shall leave it to your serious consideration;
not knowing whether I may live to see your faces,
by reason of the frailty of this mortal life.
The matter in short is this.

You all profess the worthy name of Christ, and desire to be called Christians;
and also acknowledge the Holy Scriptures to be your rule;
wherein is recorded that plain and express command of our Lord Jesus Christ,
to keep to yea and nay, and not to swear at all.
Now if any of you do swear or cause others to swear,
and that too even upon that very book wherein this command is written;
this seems to me to be as great a contempt of the
Son of God and trampling upon his command,
and also walking contrary to the Scriptures, as possibly can be.
I beseech you lay it to heart; and fear the Lord, in whose hand your life and breath is,
that you may be preserved from this presumptuous sin;
lest you be found of that number who in words profess Christ, but in works deny him.

[.signed-section-closing]
This, in the love of God, is written, and sent as a warning to you all, by,

[.signed-section-signature]
Oliver Sansom.

[.postscript]
====

I desire it may be read openly in the Court.

====

--

When the steward had received this letter, he did not read it openly in the Court; but,
as I was informed, muttered some threatening words; as,
that he would be even with me when time should serve, or to that effect.
However at that time, by reason, as I suppose, of my present sickness,
I was excused from serving the high constable`'s office,
which I understood was designed to be laid upon me,
and another man was appointed to serve it.
But when he came to be discharged two years after, which is the usual time of serving,
and a new choice was made at the Court-Leet, held on the 25th of the eighth month, 1680,
I was nominated for one of the four,
which are customarily presented to the lord of the manor, called Sir Robert Pye,
who doth usually appoint which two of the four whose names are given him,
shall serve the said office of chief constable and the other two are excused.

The court was adjourned from the 25th of the eighth month,
to the 2nd of the ninth month following,
at which I was summoned to appear to take the said office upon me.
This brought an exercise upon me;
and in that exercise I was pressed in spirit to write to the lord of the manor,
who was also a justice of the peace;
which I did and got it delivered to him the day before the court was held.
And thus it was:

[.embedded-content-document.letter]
--

[.salutation]
Justice Pye,

In the fear of God and with due regard to thee as
a Christian magistrate authorised to do justice,
I do write these following lines as an address unto thee,
in relation to my being chosen constable for the hundred,
hoping to find such Christian tenderness and moderation in thee,
as both to peruse and also to vouchsafe a favourable answer to my request herein signified.

As touching this office of constableship, it will I conceive,
if duly performed as it ought to be, require much time and expense.
Therefore it is usually conferred upon persons of considerable estates,
whereby they are enabled to spend their time and to defray the charges of the said office.
But as for me I have but little; so little, that at my coming to this town,
which was but a few years since,
it is well known I was constrained to bring sureties to
be bound that I should not be chargeable to the parish;
and my sureties stand engaged for ought I know to this day.
And moreover, I inhabit but as a sojourner from year to year,
in a house but of three pounds yearly rent;
and have not one foot of land that I can call my own.
Truly,
I am persuaded that hardly any man of so mean and
small an estate did ever bear that office,
and for that reason I desire to be excused.

But if I may not be excused, then this I request of thee,
to admit me to lake the said office and perform it without having an oath imposed;
and I shall endeavour, through the Lord`'s assistance,
to perform my duty faithfully therein to the best of my knowledge,
as well as any that will swear.

If it be objected, that an oath must be taken in such cases,
because it is an engagement the law requires for the performance of that office;
I answer, that a solemn promise under hand and seal,
upon the same penalty in case of default that is due to such as break their oaths,
is full as binding as an oath can be;
and also as effectual in all respects to fulfill and answer the intent of that oath.
And this I offer, if it may be accepted, viz. that I will solemnly promise,
through the Lord`'s assistance,
truly to do and perform the said office according to the best of my knowledge and understanding,
keeping my conscience clear in the sight of God;
and if I break this my solemn engagement,
then let double the punishment be inflicted on me that by law is due to a perjured person.

This I am content to give under my hand and seal.
And the Lord God who searches my heart knows and is witness,
that it is not in contempt of authority that I refuse to take this oath;
neither out of willfulness or obstinacy;
but truly and sincerely in obedience to Christ Jesus, who commanded, saying,
swear not at all.
This is recorded in the Holy Scriptures without me,
and this also the Spirit of Christ bears witness to, confirming the same within me.
Therefore I cannot, I dare not, swear in any case at all, whatsoever I suffer therefor.

In short, this is the sum of what I desire and request of thee at this time;
either to excuse me from the office of constableship for the reason first rendered;
or else if that may not be granted, to admit me to do it without swearing,
upon the engagement before offered;
which is equivalent to if not more binding than an oath.

And lastly, if none of this will satisfy which I have here proposed,
but I must notwithstanding be fined and have my goods taken away;
then unto the Lord do I commit my innocent cause, who will plead it with thee.
And however, this testimony in thy own conscience will stand on my behalf,
that it is not for refusing the office that I shall suffer,
nor yet for refusing to give an engagement for the
performance of it as fully obliging as an oath;
but only and alone for keeping Christ`'s command in refusing to swear.
And if I suffer in this case, it is on His behalf, for my obedience to Him,
and so for His sake.
And I believe that what is done to me for the same, He will take it as done unto himself,
and in the day of account will reward accordingly.
So leaving what is here offered to thy serious consideration,
and desiring the Lord to incline thy heart to justice and mercy,
that of the Lord thou mayest find mercy;
I am a companion to them who desire to manifest their
love to the Lord Jesus Christ by keeping his commands.

[.signed-section-signature]
Oliver Sansom.

[.signed-section-context-close]
The 1st of the Ninth month, 1680.

[.postscript]
====

P+++.+++ S. If thou please to admit me to serve in the said office upon the terms aforesaid,
I doubt not but by practice to make it appear,
that a man may be no less loyal to the king nor less useful and serviceable to his country,
for refusing to swear.
For to all those who know Christ the Truth, in their inward parts,
and are led by him into all truth, both in words and actions,
the occasion of oaths is taken away.

====

[.signed-section-signature]
O+++.+++ S.

--

The next day after the foregoing letter was delivered,
the Court was kept again as it had been by adjournment before appointed,
and I according to summons appearing there, the steward, Thomas Blagrave,
having first commanded the bailiff to take off my hat, spake to me to this purpose.
"`You are elected by the jury to be one of the constables for the hundred,
and the lord of the manor hath allowed of it: and now, seeing there is no avoiding of it,
pray lay your hand on the book, and take your oath.`"

I answered,
"`Forasmuch as I see it is in vain for me to plead to be excused from the office,
which with good reason might be done--I do now only conscientiously
plead to be excused from taking the oath;
and therefore I do here offer an engagement for my faithful performance of the office;
which is to give my solemn promise in writing under my hand and seal,
upon double the penalty of perjury in case of default;`" and having it ready written,
I did deliver it to him.
But he pleaded much, and cited scripture,
and with many words argued for the lawfulness of swearing.
To which I answered him fully, proving plainly by the Scriptures,
that Christ had put an end to all swearing among Christians,
and expressly forbidden it to all his followers.
But when he saw that my words gained upon the auditory,
and that he was not able to withstand the power by which I spake;
he then left off disputing and fell to scoffing and
deriding at the paper which I had tendered him,
seeking by such carriage to draw the people into lightness.

At length, being an obdurate, bad-spirited man, he fined me five pounds;
and instantly sent officers, viz. John Carter, tithing-man, and William Tombes, bailiff,
to my house, without any warrant, save only his verbal command,
to distrain my goods for the said fine; which they did,
and took away seven ends of whitened cotton-fustian,
well worth eighteen shillings an end; which came to six pounds six shillings,
and one piece of dowlass, with other linen cloth,
which cost me three pounds seventeen shillings and ninepence,--in all,
ten pounds three shillings and ninepence.

These goods they brought into the court before the steward and the jury;
and there they were openly measured, and valued at about nine pounds;
and I being present drew an account how and wherefore those goods were taken from me;
and four of the jurymen, then present did set their hands to it; namely, James Mills,
Thomas Talbott, Richard Steed, and William Denman.

And inasmuch as those goods were thus taken away from me,
for a fine pretended to be due to the lord of the manor;
on that consideration it came upon me to write once more to him about it,
and to lay the weight of my sufferings at his door, and there leave it.
Accordingly I did write, and got my letter delivered to him as he sat at dinner,
on the 4th of the ninth month, 1680.
But when he understood it came from me, he would not open it;
but sent it back to my house by one of his servants with this message,
that he could not relieve me unless I would leave the town.

That letter having laid by me ever since, I think meet to insert here,
believing that although it was rejected by him, yet if ever it come to public view,
it may be of service to some hereafter.
It was thus:

[.embedded-content-document.letter]
--

[.salutation]
Robert Pye,

I wrote a letter a few days since,
and sent it to thee as an address to excuse me from the constable`'s office,
which I thought was unequally imposed; urging a valuable reason,
which was the smallness of my estate; or if thou wouldst not excuse me from the office,
then I did request of thee to dispense with me as touching swearing;
that an oath might not be imposed,
but that my yea or solemn promise and engagement under hand and seal,
upon double the penalty of perjury, might be taken;
whereby the end of the oath might have been fully answered and
the justice and righteousness of the law in that case fulfilled.
I therein signified also the only ground and reason,
wherefore I could not take an oath in any case,
and thus laid my innocent cause before thee, and left it to thy consideration;
hoping that since power was in thy hands,
thou mightest have prevented that suffering which since is unjustly inflicted upon me,
for no other cause but my obedience to Christ and
keeping His command in refusing to swear.
But when I came to the court and offered to take the said office upon me,
tendering the engagement aforesaid instead of the oath,
the steward did even deride and scoff, and imposed a fine upon me of five pounds;
for which he sent immediately to my house and took away as much of my goods,
as is worth more than ten pounds.
Consider of it whether this be not great injustice and cruelty.

Now I do not write this as if the loss of my goods were matter of grief to me,
or as being burdened with and weary of my suffering; no, no;
it is cause of joy to me that He who commanded not to swear at all,
hath counted me worthy to suffer for keeping his commands; for he himself is with me,
and gives me faith and patience,
and upholds me by his heavenly power to bear witness for him;
who is the Truth in the inward parts, and leads to all truth those that obey him.
So that through the goodness of the Lord, some can say in this day as was said formerly,
"`that the sufferings of this present time are not worthy
to be compared to the glory that shall be revealed in us.`"

But the cause and end of this my writing to thee, and my intent and purpose therein,
in the love of Christ Jesus who teaches us to love enemies, is,
that as the weight and guilt of my present suffering doth, as I shall prove,
lie upon thy account; thou mayest be concerned to seek to have it removed,
that it may not remain and rest upon thee.
For it was openly said in the court,
that the jury nominated four for the aforesaid office;
and that out of them thou didst choose two that should stand.
So that it appears it was in thy power to excuse me as well as to choose me;
or to dispense with me as to swearing, since thou knewest I could not swear,
upon the engagement tendered.
Wherefore I have cause to conclude that the whole weight
of the guilt of my suffering will lie at thy door,
because it was done with thy consent and allowance.
And moreover I am told, that my goods thus taken away are for thy use and behoof;
and therefore unless thou dost hasten to shake thy hands from this gain of oppression,
it will be chargeable upon thee, when thou shalt come to appear before Him who commanded,
swear not at all; who is my leader and must be thy Judge,
from whom there will be no appeal;
and all that are cruel and hardhearted to his followers may read their doom, in Matt,
xxv, 31, if they repent not in time.
Which I earnestly desire thou mayest do before the door of mercy be shut,
and that decree sealed against thee, viz., He that is unjust let him be unjust still.

Oh!
I beseech thee to consider how little time in the
ordinary course of nature thou hast to live,
having already attained to a pretty full age;
and hearken not to the time-serving daubers who preach for hire and divine for money;
serving their own bellies, and dishonouring the Lord Jesus Christ who said.
Swear not at all.
These men-pleasers will insinuate, that he meant not as he spake;
and so would make the Lord like unto themselves,
who would say one thing and mean another.
But all their daubing will in the end prove to be but with untempered mortar,
and as rottenness unto all that believe them and depend upon them.

But my Christian desire to thee in tender love is,
to turn thy mind to the Light of Christ in thy own conscience, which is truth and no lie,
which will speak the same in thee now, if thou wouldest heed it,
as is recorded in the Scripture,
that thou mayest understand without any invented meaning,
that Christ did really forbid all kind of swearing, when he said, "`Swear not at all.`"
Some may go about to put a false gloss upon it,
pretending that he only forbad vain oaths in ordinary communication; but I say,
vain oaths were forbidden by the third commandment, etc.,
so that Christ saw it not needful to forbid only what was forbidden before.
But it was that solemn swearing, allowed under the law,
that Christ here mentioned and put an end to; placing yea and nay in the stead of it,
whereby the righteousness of the law might be fulfilled;
so that the word of a true believer in Christ,
is of as much weight as the solemn oath of them under the law.
The true Christian`'s yea must be yea, and their nay must be nay,
or else they will fall into condemnation; and whatsoever is more cometh of evil.
So to the Lord I leave thee,
and desiring him to give thee an understanding by his divine inspiration; I remain

[.signed-section-closing]
A friend to thy soul and a witness for the Truth.

[.signed-section-signature]
Oliver Sansom.

[.signed-section-context-close]
The 4th of Ninth month, 1680.

--

It may be marvelled by some why this man appeared so implacable against me in this matter;
seeing he was well known in the country, of late years especially,
to be in the general against persecution for religious dissent,
and was himself indeed reputed a dissenter.
But he seemed to have a particular prejudice against me,
though I can truly say I never gave him any just occasion.
Yet I am sensible he took occasion to be offended with me
about a year before this suffering came upon me;
and as far as I can guess it arose from hence.

There was a Friend in Farringdon under great suffering,
for refusing to pay tithes to the said Sir Robert Pye, who was an impropriator,
and used extreme rigour and severity towards the said Friend.
And I in tenderness sympathizing with the sufferer,
was moved to write a letter to the said Robert Pye in true love,
to persuade him to desist from proceeding any further
in cruelty and spoil against the said suffering Friend.
In which letter I alleged several reasons to provoke him to tenderness;
and also showed the bad consequences of such rigour,
and what reward in the end must be expected for it.
I hinted also something touching the rotten root of tithes here in England;
and how a conscientious concern is upon many in this gospel-day,
to bear their Christian testimony against the imposed payment of them.

This letter, which I forbear to insert at length here,
seeing it did not concern my own personal suffering,
I mention only to show how this great man was offended at it.
For having read part of it, he gave it to his chaplain and ordered him to tell me,
that he was satisfied in his conscience in what he did,
and would not have me trouble myself nor him in writing any further about it;
for seeing he had begun his prosecution of the said Friend, he was resolved to go on;
and he, the Friend, should have but what the law would allow him.
It is probable he might think,
that the said suffering Friend might receive encouragement from me,
to stand faithful in his testimony against tithes,
and not to bow for all that he could do unto him for the same; and thereupon he,
as I suppose, conceived such indignation against me,
that he became thereby hardened against all that I wrote to him afterwards;
and also the more willingly took that opportunity
to inflict on me the suffering before mentioned,
for my not taking the constable`'s oath.
However it was, he from that time carried himself ever after, though friendly to others,
yet unkind to me, and as an enemy; as I shall have occasion further to observe hereafter.

[.offset]
+++[+++About this time O. Sansom received the following letter from his dear sister,
Joan Vokins.^
footnote:[Of this Friend but little is known now,
though in her day she was a patient sufferer and
persevering labourer in the Lord`'s vineyard.
She was religiously inclined in her youth,
and many times cried unto the Lord to reveal his way unto her,
promising to walk therein whatever she endured.
In due time the Lord answered her weary soul and
made known his truth and people unto her;
and sent some of his messengers for her encouragement and confirmation.
Then was she, and many more in a like state, right glad with the tidings brought,
embraced the truth in the love of it, preached it in her life and conversation,
and died in it.
{footnote-paragraph-split}
During the early part of her convincement,
she went through great exercises,
and endured much opposition and sufferings from her near relations, unto whom, however,
she was a good example; so much so, that by her conversation,
through the blessing of the Lord, they, viz. her husband, her father, and her children,
became convinced of and won to the truth.
She is said to have been a very zealous fervent woman,
but remarkably weak and tender outwardly.
She was wonderfully supported in her trying journey to New England,
'`though like to die on the way,`' travelling much by sea and land in those parts,
as the Lord directed her.
After her return, she laboured in Kent, London, etc.,
encouraging Friends in their great sufferings,
and when the prisons were opened and Friends freed, in 1686, she went to Ireland,
and though very weak, travelled up and down many parts of that nation for a twelvemonth,
to her own peace, and the comfort and service of Friends.
In 1690, she went up to the yearly meeting in London,
and having been refreshed with Friends, stayed at Reading on her return home,
where she sweetly died in the Lord, and in unity with his faithful people,
on the 22nd of fifth month;
which event she seemed to have anticipated previous to her starting for the yearly meeting,
having left with her friend Theophila Townsend,
certain papers which she wished to be made public after her decease.
Her exercises and trials were many,
but that which was her greatest grief and heaviest burden, and most grievous to be borne,
was her suffering by false brethren and apostates,
who under the form and profession of Truth,
did make war and kick against the life and power of it.
{footnote-paragraph-split}
At the time of her decease,
her husband and eldest son were lying in Reading jail,
'`under that cruel oppression of tithes.`' Some account of her with her writings,
were collected and printed by O. Sansom in 1691,
entitled "`God`'s mighty power magnified.`"]
As her name occasionally occurs in these pages,
it may not be out of place here to insert it.]

[.embedded-content-document.letter]
--

[.salutation]
To Oliver Sansom and his Wife.

Dear Brother and Sister, Whom I dearly love in the Lord Jesus, our life,
who makes hard things easy, bitter things sweet, and bears up in the greatest trials,
do I salute you with my Mary, my sister Margery and the rest of them,
earnestly desiring your prosperity every way, as for my own soul.
And by this you may know, that though sore exercises and travails attend on every hand,
yet I am alive to magnify that power that hath preserved in dangers great,
and difficulties many, and is able to preserve unto the end;
and therefore I desire that we may trust in it and obey it to the honour of it;
for it hath been manifested in my weak body,
to the admiration of many of the upright in heart,
and they are very loving to me wherever I come.
And my tender Father hath strengthened me to do his service in Long Island and New York,
and in Rhode Island, and Boston, and New Jersey, and those parts of America;
and I was in hopes to have come home when I was clear of New England,
but the Lord hath laid it upon me to go to Barbados,
and in his strength I am going in a vessel that one
George Fletcher is owner and master of,
who professes truth.
Do you not think that a line from you would be very precious to me?
I neither heard from nor saw one of my native land since I left it;
but I cannot blame you, not knowing whither to direct to me.

Remember my dear love to all our dear Friends of our men`'s and women`'s meetings,
earnestly desiring their faithfulness therein,
and in all things else that pertain to the life of truth,
that we may bear our testimonies in uprightness to the end,
that in the end God may be glorified and our souls comforted, forever and evermore.
Dear Anne Lawrence`'s children are in my mind as well as my own.
I hope you will look after them in my absence,
that we may have comfort in their growth in the Truth, if ever we are present again,
and if they grow in the truth and knowledge and love of God,
then will the desire of your tender sister be answered.
And so in that which satisfies our breathings, I remain

[.signed-section-closing]
Your tender sister,

[.signed-section-signature]
J+++.+++ V.

[.signed-section-context-close]
The 1st of Eighth month, 1680.

--

To relate my exercises in order of time as they fell, I must acquaint the reader,
that in the second and third months 1682,
our Friends of Abingdon being disturbed in their meetings there,
I found myself concerned then as at other times,
to take part with God`'s suffering people, and as I did believe it to be my duty,
I went to their meeting at Abingdon divers times,
and was haled about and brought before the mayor with other Friends,
And for the first time I was fined twenty pounds; and again, for the second offence,
as they called it, I was fined forty pounds.
And all that I desired in point of favour of the mayor and his company,
when I was before them, was only this; that none of my friends might suffer for me,
or have any part of my fines imposed on any of them;
for I did assure them that the Lord had blessed me with plenty,
and I had sufficient of this world to suffer those fines, and more.
I also wrote a letter and sent it to the then mayor, to warn him,
as it arose in my heart in the love of God,
to forbear any further persecuting the innocent.
And he was restrained by an invisible power from
making any distress for the aforesaid fines;
and seeing by that means it was so ordered that no further suffering followed thereupon,
I shall forbear inserting the before-mentioned letter,
or enlarging any further concerning that matter in this place;
but shall proceed to give an account of some greater sufferings; which thus arose.

There was one Eustace Hardwick, of Shrivenham in Berkshire,
who by marriage had a pretty considerable estate of some hundreds by the year;
but was an ill-disposed, lewd, wicked man.
He, as was reported, had misbehaved himself,
and abused the said Sir Robert Pye and one Thomas Fettiplace, both justices of the peace;
for which it was said some endeavours were used to apprehend him,
that he might be brought to condign punishment.
This so provoked Hardwick,
that he in revenge sought occasion against these
two justices to get them out of the commission;
especially Justice Pye, whom he thought he might the more easily prevail against,
because of his moderation to dissenters.
Wherefore the better to compass his end, he, being an enemy to all good,
put himself into the vile employment of an informer,
and on the fourth day of the first month, 1683, he with his man-servant,
one Roger Waight, came to our meeting at Farringdon,
and happened to come in when I was upon my knees making supplication to the Lord.
When I had done, he commanded his man to stay there to watch me until he came again,
fearing belike that I would slip away and hide myself,
which if he had known our principles and me, he needed not have done.
Then went he to the said justice to inform against our meeting,
and in the meanwhile we had a very good time, for the Lord`'s opening,
tendering power was over all;
and the serving-man who was left to watch me was so far reached,
that he afterwards acknowledged what he did against us was against his own mind,
and that he would never be so concerned any more.

After some time the said informer Hardwick returned to our meeting,
and brought with him the constable, tithing-man and other officers;
whom he charged to take our names and do their office.
But they being moderate and as yet not accustomed to such work,
did not make haste to obey him; but discoursed with him,
and went forth and tarried about the door until we ourselves broke up our meeting,
the usual time being come.

While this delay was, the said Hardwick and his man slunk away from the officers,
and taking horse got them out of town.
But the officers fearing some suffering,
or at least some blame would be laid upon them if they should let us all go,
took me and one Friend more, and had us before the said justice Pye.
He asked me if I was at the meeting?
I answered, that I had done no evil, and had nought to accuse myself of;
and desired if any had aught against me they might appear to my face.
But he spake very roughly to me,
and seemed to be very full of fury and bitterness against me,
though he spake kindly to the other Friend,
and in conclusion he fined me twenty pounds for speaking in the meeting.
I told him I did look upon it to be a very hard measure
to be fined when no evidence appeared against me.
He thereupon asked the officers where the informers were?
And they told him they were gone out of town; at which he was angry and said,
why did you let them go?

However, he caused his clerk to write a warrant, and he sealed it,
to levy twenty pounds upon my goods;
and then sent one of his men away presently to Shrivenham, which was four miles off,
to fetch the informers again to give their evidence against me,
after he had set a fine upon me and granted a warrant to levy upon the goods.

Then did he fall very foully on me before the officers and many others,
bitterly reviling me, and charging me that I deluded people,
to give away their estates at their deaths to enrich our church like the papists;
and upbraidingly said,
you must take upon you to counsel men to make their wills to ruin their own children!

I knew not in the least what he meant, and so I told him,
and desired him to let me know wherein I had done amiss;
but he would take no notice of what I said,
but in a furious wrathful frame ran on railing against me till he had wearied himself,
and then he withdrew into another room, whereupon the company dispersed and I went home.

In the evening the informers came,
and the officers had me up again to the justice`'s house.
But the informers were very backward,
and seemed unwillingly to take their oaths against me,
till the justice threatened them that he would send them to jail if they refused;
and then they did take their oaths, that they heard me speak in the meeting.

When they had given their evidence the justice presently
commanded the officers to disarm Hardwick.
Whereupon they forthwith took from him his sword and two pocket-pistols,
which upon search they found about him,
and then took him into custody for some misdemeanours by him, before committed.
The same evening came over the other justice, Thomas Fettiplace;
and Robert Pye and he together made a mittimus for Hardwick,
and early next morning sent him away prisoner to the common jail at Reading.
But he was soon at liberty again, for the assizes began on the same day,
and Hardwick served on the grand jury.
For at that time there were some at court that greatly favoured him;
with whom he so wrought that within some short time both those justices,
Pye and Fettiplace, who had committed him, were put out of the commission for the peace.

But I could not be satisfied to lie under the reproach which Justice Pye had cast upon me.
Wherefore I waited next day to speak with him when he rode abroad as his custom was,
to take the air; and I did speak with him, first about my present exercise.
He asked me what I would do about the fine; for, said he,
they will levy twenty pounds upon your goods if you have so much.
I answered, I bless God I have so much,
and it is no grief to me to suffer the loss of it for so good a cause.
But this is more cause of grief and trouble to me, said I,
that thou shouldest be so angry with me, and render me such a great evil-doer;
and yet not let me know wherein I have offended,
or who have been wronged by me or through my means.

Then speaking pretty mildly, he told me,
there were complaints made concerning one Bartholomew Malam`'s will:
that I had advised him to settle his estate, for the enriching our church,
and wronging his own children.
I told him it was altogether false:
for I could prove that the said Bartholomew Malam`'s estate, was by his will,
disposed to his own children, and children`'s children, and was now possessed by them,
and none other.
And that whoever had informed him otherwise,
had abused him with a slanderous lying story:
wherefore I desired him to tell me who had informed him of this matter?
But he would not tell me; only said,
that the complaint came first from one Stephen Barly,
a son-in-law to the said Bartholomew Malam.
Then I entreated him to grant me his warrant, for he was yet in the commission,
to cause the said Stephen Barly to appear before him; that if he could,
he might make proof to my face, wherein I had wronged him or any other:
or else to make me satisfaction for slandering me.
But he would not grant me his warrant, but rode away and left me.

About a week after this, viz., on the 8th of the first month, 1683,
the officers of Farringdon came to my house to make
distress for the aforesaid fine of twenty pounds.
They that came were Thomas Butler, constable, Thomas Reynolds, tithingman,
John Edmundson and Francis Trinder, called churchwardens, and Hatlon Green,
overseer of the poor.
These being there altogether, distrained, took and carried away of linen cloth, serge,
and other mercery goods, and several books of mine,
as much as was worth in the whole twenty-one pounds thirteen shillings and sixpence,
as the goods were then measured and valued by themselves,
and a particular account thereof taken in writing; whereof they left a copy with me.
Which account I think meet not to insert here at large:
but of the disposal of the goods I am willing to give the reader this short account.

The goods were carried to the constable`'s house, and there, not sold,
but kept for about four years;
and then soon after King James`' declaration for liberty came forth,
they were restored to me again without my either asking for or seeking after them.
Some damage there was by the moth in the serge, and what else was made of wool;
and the books which were carried to the tithingman`'s house,
were some of them lost and never restored again,
by reason the man himself was taken away by death.

Thus was the Lord pleased to order things by his divine wisdom,
that after I had freely given up my goods, and had parted with them for four years,
he caused them to be returned to me again; so that surely I may say,
the Lord is worthy to be trusted in, and to be praised and magnified over all,
forever and ever.

That slanderous report which proceeded first from Stephen Barly,
and with which justice Pye was so strongly possessed, namely,
that I did advise Bartholomew Malam to make his will,
so as to deprive his own children to enrich our church--this false charge, I say,
and the exercise which it brought on me, lest not I only,
but the truth and Friends should suffer reproach by it,
remained with so great weight upon me that I found
myself concerned to do my utmost endeavour,
to manifest my innocency and clearness to the said Sir Robert Pye;
that if it were possible, he might be made so sensible of it,
that the prejudice he had conceived, might be removed out of his mind;
and instead thereof, he might come to have a better opinion both of me,
and of the truth which I profess.

Wherefore to effect this, I sought for, and did, with some difficulty,
obtain several opportunities to speak with him when he rode abroad.
For I had no other way to get access to him, for he would take no notice of my letters;
and in his own house I could not be admitted to him;
so that I was fain to wait for him on the highways, as he once a day,
went forth to air himself; having usually two servants attending him on horseback.
And truly it was a pretty great cross to me,
thus to force myself into the company of a person so much above me, and who I knew,
had no favour for me: yet through the strength which the Lord gave me,
and the innocency of my cause, I was emboldened to speak freely to him,
and plead with him again and again, about the matter whereof I was accused.
And sometimes he would seem pretty low and tender, so that the more I had to do with him,
the more love I had to him; but this disadvantage I was under,
that when at any time I was got into a sober discourse with him,
and my words seemed to take some hold of him,
he being on horseback would ride away from me, and I being on foot,
could not keep up with him to clear myself of what I had in my mind to say unto him.

To help myself in this kind, I once took my horse with me,
and so waylaying him as it were on horseback, I rode along with him by his side, for,
I think, two miles and upwards, and then spake my mind freely to him;
and he seemed to resent it well for the present.
But when he came again into the company of some who were envious against truth,
they would make him as bad as he was before.

Which I observing, and thinking that my own plea on my own behalf, and in my own cause,
might not be so taking and prevalent with him as the testimony of others;
I therefore wrote to the Scrivener, that made B. Malam`'s will, and to another Friend,
William Hitchcock of Marlborough, who had been most intimate with him all along,
for about twenty years, desiring them to certify what they knew concerning this matter.
They did both certify severally; and the copy of their respective certificates follow:

[.offset]
That of the Scrivener was thus:

[.embedded-content-document.legal]
--

This may certify all people whom it may concern,
that I have been concerned in transcribing all the
wills and deeds that Bartholomew Malam made,
for the settlement of his estate, ever since the year 1670,
and had the advice of several learned men in the law, as Sir Bulstrode Whitlock,
William Tarrant, John Foster of Marlborough, and others.
And he was never fully satisfied in his mind concerning any will he made,
which were several, till the last will.
Though in all his several wills which I have made, and one will made before,
by Thomas Neat of Chippenham, in the year 1664,
he gave the very self-same legacy to Stephen Barly`'s wife, as he gave in his last will;
and but very little alteration to any of his other children.
In all which wills and settlement, I never in the least,
knew Oliver Sansom advise the said Bartholomew Malam,
or be any way concerned any otherwise,
but that his name was mentioned as an overseer among others.
And as far as I know, when Bartho.
Malam made his last will and testament, Oliver Sansom was at London.
So that the charge of the said Stephen Barly, against the said Oliver Sansom,
appears both false and malicious,
In testimony whereof I have hereunto subscribed my name,
who have been both an eye and ear-witness to these transactions.

[.signed-section-signature]
John Richardson.

[.signed-section-context-close]
Marlborough, the 1st of December, 1683.

--

[.offset]
The certificate from William Hitchcock was thus worded.

[.embedded-content-document.legal]
--

This I can also certify, that I have had knowledge of Bartholomew Malam`'s mind,
in the settlement of his estate, from time to time, for near twenty years,
and have seen all his several wills and deeds of settlement;
and they were all one and the same, as to Stephen Barly`'s wife`'s portion.
For there was not any will or deed of settlement, made by him for so many years past,
but after the rough draught was made, and before it was engrossed,
he would either call John Richardson to my house, and read it in my hearing,
or call me to his house to hear it read there.
And this I can truly further say, that I have reasoned the case with him,
why he gave Stephen Barly`'s wife no more, and he replied,
that he had given her a good portion already,
and more he did account he had done for Stephen Barly;
and he having no child had no need of it, or words to that purpose.
For I know, and can further certify, that Bartholomew Malam was a resolved man,
and did always dispose of his estate according to his own mind and will,
without any man`'s advice whatsoever, unless for the securing it by law.
And as concerning Oliver Sansom, I have known him many years,
and have been intimately acquainted with him,
but never knew him in the least concern himself in any way,
to advise Bartholomew Malam as to the disposing of his estate.
And this I have endeavoured, as I have had opportunity, to satisfy Stephen Barly in,
but his malice is so great, that the naked truth can take no place in his heart.
I am sorry for it, the Lord forgive him for wronging an innocent man.
So for truth sake, and the clearing of Oliver Sansom,
I could do no less than thus to certify;
in testimony whereof I have hereunto subscribed my name.

[.signed-section-signature]
William Hitchcock.

[.signed-section-context-close]
Marlborough, the 1st of Tenth month, 1683.

--

When Robert Pye had received the before-written certificates,
the answer he gave me was this: they, meaning John Richardson and William Hitchcock,
are both of your own company, and I will no more believe them than you.
This showed him to be implacable:
wherefore contenting myself that my innocency was known to the Lord,
and that I had done enough to satisfy any reasonable man,
I determined to forbear seeking him any further in this case,
or using any more endeavours about it.
But one William Brice, who was chaplain to the said Robert Pye,
and to whom I had sometimes spoken touching that matter,
perceiving how fruitless my endeavours had hitherto been, and being somewhat touched,
as I suppose, with a sense of my innocency,
and hoping to satisfy his master thereof also, wrote to one Oliver Curr, of Auburn,
desiring him to go along with me to the said Stephen Barly`'s house at Baydon,
and to hear his charge against me, and my answer when we were face to face,
and to make report of the state of the case as he understood it,
and to send it in writing by me to Sir Robert Pye.

Now, though I had given over the thoughts of stirring any further in this business,
yet lest the chaplain should mistake it for a token of guilt in me, if I refused,
or was backward to go with his letter to his friend Curr,
and so to Stephen Barly about it, I took the letter and another Friend with me and went,
and with much ado prevailed with Curr to go with us to Barly`'s house.
Where after about two hour`'s discourse on that subject,
no shadow of proof could be produced of anything that had been suggested,
concerning my having had any hand,
or being any way concerned about making B. Malam`'s will, or settling his estate.
But Stephen Barly was angry and fierce against me, because I was assistant to Barthol.
Malam`'s daughter, whom he made his executrix, in the speedy proving of the will,
whereby he was prevented from contesting and hindering the probate of it,
and thereby putting the executrix, his wife`'s sister, to charge and trouble about it.

But when all was done, this Oliver Curr refused to give his report in writing,
as was by the chaplain desired; and although I did earnestly entreat him,
yet he would not be persuaded to do it, but put it by with saying,
that in a short time he intended to go to Sir Robert Pye`'s,
and certify him by word of mouth of the true state of the case.
But whether he ever did so or no, I know not,
for he seemed plainly to be one that would rather
carry a charge or accusation against the Quakers,
than any thing in favour of them.
And it was very apparent,
that the said Robert Pye was very much swayed and
biassed by some of those people called Presbyterians;
of whom he had one, and him none of the least, or least mischievous among them,
at his elbow.

For Benjamin Woodbridge, with whom I had formerly had to do controversially,
on truth`'s account, in the year 1673,
was at this time at hide and seek for fear of suffering;
and having left his great flock at Newbury to shift for themselves as they could,
he was fled to shelter himself under the wings of this great man;
and took sanctuary for a long time in his house at Farringdon.
And I remember, I once in discourse told Robert Pye,
that I was jealous Benjamin Woodbridge had incensed him against me,
which I had the more reason to suspect,
because there had been a controversy formerly between him and me;
and I knew him to be no friend to me, nor the truth which I profess;
at which words Robert Pye was much moved,
and angrily told me I was not worthy to mention him or to name him;
whereby may be guessed what a high esteem he had of him.
But this justice Pye being by this time no justice,
for Hardwick the informer had gotten him struck out of the commission;
I had no more to do with him for a long time.

Yet I was not free from exercises and sufferings for the testimony of a good conscience.
For it being a stormy day, and a time of hot persecution, and that same Hardwick,
not finding the trade of an informer agreeable to himself to carry on,
had substituted or at least encouraged two sorry fellows in his stead,
whereby I and many other Friends became great sufferers
for keeping up our religious meetings at Farringdon.

Of these two new informers, one was named Thomas Welman a broken carrier, and the other.
Angel Smith, a wicked, lewd fellow, both of Farringdon.
These two being put on, and animated by the said informer Hardwick,
took upon them to be informers against us at Farringdon,
for our peaceable meeting together to worship the Lord.
And when they first set up the trade,
they were not so hardy as to be seen at our meetings,
but taking up their standing in a house at a distance, and looking out at a window,
they took their observations as Friends passed from the meeting;
whereby they mistook themselves and gave false informations;
and by their false swearing procured fines to be levied on one that was not at the meeting.
Whereupon two appeals were entered; and if justice could have been had,
they might have been brought to the pillory, as by law they deserved.
But of that more hereafter.

Now in the sense and consideration of these evil men`'s wicked designs,
and of the sad recompense they must expect from the Lord in the end,
if they persisted in their bad work,
I was moved to go to them in the love of God to warn them to repent,
and desist from proceeding on in their wicked work, certainly assuring them,
that the just God beheld them in all their designs,
and would in very deed bring them to judgment,
and give them a reward according to their works;
this with more to the same purpose I spake to them, being both together at Tho.
Welman`'s house, on the 23rd of the seventh month, 1683.

And not long after, seeing them in the townhall in Newbury,
while the court of quarter-sessions was sitting there,
on the 2nd of the eighth month following; and observing that they stood lurking behind,
as waiting to do some mischief, I went to them again and tenderly advised them,
and warned (hem to forbear going on with their bad designs against their innocent neighbours.
For they might assure themselves they could not prosper,
neither would their expectations be answered;
and if they did get our goods it would be but little benefit to them;
for thereby they would the sooner be brought to beggary,
and even procure hatred against themselves.

One of them, to wit, Smith, answered,
if they did lose the love of their neighbours they should gain the love of others.

Hereupon I reasoned a little with them,
asking them why they did oppose us and covet our goods?
What harm had we done them?
And directing my speech particularly to Welman, who had been a carrier, I said,
"`I have formerly employed thee, did I ever do thee any wrong?
Did I not pay thee the full of thy demands?
What harm dost thou know by me?`"
He had not a word to say, yet he, as well as the other, seemed much hardened;
and it grieved me to behold that no tenderness at all did appear in them.

Then I asked them what further business they had at the court there?
seeing no more at present was like to be done about the appeals,
which were entered but that day.

Smith said, "`We have to inform against you for being at the meeting last Sunday week.`"
I replied, I hope to live to go to meetings, when you may not dare to show your heads.

Then they threatened to inform against me for those words,
and they were as good as their word; for the next day towards the close of the sessions,
they did inform the court that I had spoken treasonable words.
And truly their information was readily received,
it being the time when informers were rampant, and moderate justices gone off the bench.
The clerk, being a very wicked man, drew an order of sessions, signed by himself,
to apprehend me and carry me before some justice of the peace;
whereupon on the 9th of the eighth month, I was had before Humphrey Hide,
where the informers also appeared and swore against me,
that I said I would meet and preach, when they should be ashamed to show their faces.
When the justice heard the words, he said, the order mentions treasonable words;
but for my part I see little in them.
But yet for fear of the informers, he engaged me, upon a recognizance,
to appear at the next sessions.

Now it is to be noted that the clerk of the peace, whose name was William Grove,
had agreed with the informers that he would frustrate our appeals,
upon condition that he should have all that could be recovered upon the appellants,
for himself.
Therefore he, with the informers did what in them lay, to get me into prison;
lest if I was at liberty,
I should prose cute the appeals so effectually as to bring the informers to the pillory.

On the 15th of the eleventh month, 1683, the quarter-sessions being held at Reading,
and I called in court, I appeared; and the informers swore again against me,
that I said I would preach in meetings when they should not be able to come at me;
adding more words very falsely, and so confusedly,
that the bench of justices seemed ashamed to take notice of it,
so much as to examine me one word about it.
But some that were envious made mention of tendering the oath of allegiance to me;
to which another more moderate answered, "`What shall we tender him the oath for?
we know they will not swear.`"
So a division was between the justices on the bench about it.

Then one Charles Parret, or Perrot, stood up and said of me, he is a dangerous person,
one that goes about the country preaching and dispersing Quakers`' books, for, said he,
he sent two books and a letter to me; he is not fit to be suffered, added he,
with words to the same purpose.

Then two other of the justices, namely, John Wightwick and Anthony Craven,
spake very fiercely against me to the same effect.
Whereupon a lawyer stood up, without being desired by me,
only I had spoken to him to carry on the appeals;
and he told them they ought not to tender me the oath by law.
Upon that the statute-book was searched, and a great bustle they made for a while,
till at length the persecuting party prevailing,
Anthony Craven and John Wightwick went off the bench to the other end of the hall,
ordering me to be brought after them that they might tender me oath there.

Being brought thither before them, I said "`I know your minds,
that you would put me in prison; and you had as good send me thither presently,
and not trouble yourselves about the oath, which is but only to cover your designs.`"

They turned the statute book to and again a pretty time to find the oath,
but could not find it.
Then they called for a clerk, and a young man coming, a bailiff that stood by said,
here is a clerk come now; but they were so busy fumbling in the book to find the oath,
that they did not heed him.
I seeing the clerk standing waiting, said to him,
"`Art thou come to make a mittimus to send an innocent man to prison?`"
He hearing that slipped away; and when they called for him afterwards,
he was not to be found.

So these two justices, so called,
continued tumbling the leaves of the statute book to and fro for a considerable time,
till they were weary, and with all their wisdom they could not find the oath;
for the Lord had confounded them in this their envious design.
Then they called counsellor Dalby to them,
and he came and found the oath for them presently.
Whereupon calling for a Bible they proceeded to tender me the oath, as followeth: First,
justice Craven, asked me, "`Will you take the oath of allegiance?`"
I answered, "`I do practice allegiance, I need not swear it.`"

"`Come,`" said he, "`pull off your glove and lay your right hand on the book.`"
I pulled off both my gloves, and took hold of the book with both my hands, to look in it;
at which Craven seemed angry and fiercely plucked it away from me.

Whereupon I said to him, "`If thou wilt not let me have it,
that I may see what book it is, thou mayst keep it to thyself.`"

Then he offered it me again, bidding me lay my hand on it.
I laid both my hands on it, and plucked it away from him, and opening it said,
"`I see it is a Bible,
and here in this book is that command of Christ written
which expressly forbids all swearing;
now answer me,`" said I, "`is this book to be believed,
and what is written therein to be observed or not?`"

At that justice Craven was very angry, and catched at the book to get it from me again;
but I held it out of his reach.

Then he asked me again, "`Will you take the oath of allegiance?`"
I answered, "`I have practised allegiance all my life.`"
"`Come,`" said Craven, "`say after me,`" and began to read the oath: but I said nothing.
Which he observing, began again and read the oath through;
I standing by the while with the bible in my hand, but saying nothing.
Whereupon he said, "`Will you take the oath or not?`"

I then holding up the Bible in my hand said, "`Christ Jesus commands not to swear at all.
Here it is written in this book,
and his spirit in my heart confirms to me that it is my duty to obey him;
and now you command me to swear.
What shall I do in this case?
Shall I obey Christ and the Scriptures?
or must I obey you contrary to both?
What will you advise me to do herein?`"

This put Craven to a stand; whereupon the other justice, John Wjghtwick putting in, said,
"`We advise you to take the oath.`"
"`What!`" said I, "`to break the command of Christ?`"
"`All the king`'s subjects,`" replied Wightwick, "`are bound to take it.`"

Before I could answer, Craven interposed and prevented me, by saying,
Well I you have refused it; you will not take it.

"`I am a Christian,`" replied I; "`I am willing to obey Christ.`"

Then said justice Craven to a bailiff that stood by, take him away,
and have him to the jailer, and bid him take care of him;
and let him come to me in the evening, and he shall have a mittimus.
Accordingly the jailer, having secured me, went for a mittimus,
and had it in these words:

[.embedded-content-document.letter]
--

[.salutation]
To the Keeper of His Majesty`'s Jail for the County of Berks.

These are in his majesty`'s name,
to require you to take into your custody the body of Oliver Sansom of Farringdon,
for having refused to take the oath of allegiance to his majesty,
being lawfully tendered by us; and him safely keep,
till he shall be delivered by due course of law.
Hereof you are not to fail.
Given under our hands and seals this 15th day of January,
in the 35th year of his majesty`'s reign, Anno Domini, 1683.

[.signed-section-signature]
Anthony Craven.

[.signed-section-signature]
John Wightwick.

--

Now being fixed in prison that I might not prosecute the appeals before-mentioned,
which were to be tried that session;
I think fit to give a brief account how that matter was managed:

I mentioned before that a couple of lewd, idle fellows, viz. Tho. Welman and Angel Smith,
took upon them to be informers against their innocent neighbours at Farringdon.
These giving their informations at random,
informed against a meeting for a preacher unknown, though in very deed,
there was not any one that day who either preached or prayed, but was both well known,
and fined also upon their information.
Besides this they swore against another Friend, for being present at that meeting,
who was not there, but could prove by many witnesses that he was elsewhere;
and upon their information this Friend, who was not at the meeting,
had part of the fine of twenty pounds laid upon him for the pretended unknown preacher.

Thus these vile informers having so plainly forsworn themselves,
that their perjury was apparent to the people;
two of the persons who were thus illegally fined for the unknown preacher,
whom the informers had feigned, and had their goods taken away for it,
whereof one was not at the meeting that day,
looked upon themselves as obliged to use their endeavour`'s
to detect the villany of the informers,
that they might not go on in their wickedness, but be brought to due punishment.

Accordingly they entered their appeals,
and at the next session they entered their traverse,
and at the following session held at Reading, on the 15th and 16th of the eleventh month,
1683, they came on to trial in this manner:

First, a jury was returned by the sheriff of honest, substantial, indifferent men.
But when these were brought to the bar, that the court saw what men they were,
they would not suffer them to be empannelled;
but illegally put them by lest they should do the Quakers justice.

Then presently was another jury picked up, most of them being biased men,
professed enemies to the people called Quakers, and the foreman,
one who a little time before, for lucre`'s sake,
had bought some goods that were taken away from some of the people called Quakers,
upon the conventicle act; which made it reasonable to suppose,
that interest would bias him to promote the informers`' wicked practices,
that he might get the larger pennyworths by them.

This partial jury was empannelled, and the evidence on both sides heard,
wherein three substantial witnesses appearing for the appellants proved upon oath,
that one of the appellants, whom the informers had sworn was at that meeting,
was not there but at another place, remote from thence, all day.

Now though these three witnesses did clearly overthrow the informers`' evidence,
and made it manifest that they had sworn falsely against that appellant;
yet this wretched jury going together to consult a little, quickly returned,
and like men that did not regard either equity, justice, or the oath they had taken,
gave in their verdict against the appellants and for the informers.

Oh! it is sad to consider that ever men should be so void of the fear of God,
and of regard to their own souls, that to protect such vile informers,
and encourage them in their villanies, and save them from the punishment due to perjury,
they would not stick to come under the guilt and penalty of perjury themselves;
for which their abominable wickedness,
they have justly deserved to have their names and memorial exposed to perpetual infamy,
and to the detestation and abhorrence of all good men, in all succeeding generations.

But although this jury brought in their verdict as aforesaid,
many of the justices being sensible of the wrong done,
refused to give judgment at that time; but suspending judgment till the next session,
ordered the appellant`'s counsel to draw up in writing
their exceptions against the convictions,
and deliver them to Sergeant Holt;
which was accordingly done on the last day of the term at London.
And at the next quarter-sessions holden at Newbury,
on the 9th and 10th days of the second month, 1684,
when this matter was again moved by the appellant`'s counsel,
and the exceptions to the convictions pleaded and argued in the court,
the justices that were lawyers confessed that the exceptions were good.
Yet when after some time of debate upon it, they put it to the vote,
the greater number of justices, being blinded with enmity against the Quakers,
gave it for the informers, and allotted twenty pounds cost; whereupon William Grove,
the corrupt clerk of the peace, who had before hand made a bargain with the informers,
that if he could get the cause carried for them against the appellants,
he should have the costs that should be given for himself,
fetched away from Edward Lockey of Farringdon,
shop-goods and household goods to the value of one and twenty pounds,
for but one half of the said twenty pounds given for costs.
And thus was the saying of the prophet fulfilled in our day,
that judgment is turned quite backward, and justice stands afar off;
truth is fallen in the streets and equity cannot enter.
