== Chapter VIII.

[.chapter-synopsis]
* With other Friends to the Quarter Sessions at Newbury
* Are recommitted
* Quarter Sessions at Abingdon
* Again to prison
* Sessions at Newbury
* Back to prison
* Letter to Fettiplace
* Are liberated by a moderate Justice
* Persecution at Farringdon
* Petty Sessions there
* For meeting O. S. is committed to Reading Jail until delivered '`by due course of law`'
* Goes to prison carrying his own court order
* Letter to his wife.

It was not long after this, that the quarter sessions came on again,
and were held at Newbury on the 28th and 29th of the second month, 1685,
to which we were brought and called in court, on the last day of the sessions,
when but three of the justices, viz., Tho.
Staples, Anthony Craven and Henry Fane, were on the bench.
And after the oath was read to us, Staples being chairman, began with Samuel Burgis,
asking him whether he would take the oath.

Samuel desired liberty to speak, and began a little;
but Staples and Craven soon interrupted, and were very rugged and bad,
fiercely pressing upon him and urging him to give a direct answer,
whether he would take the oath or not?

Then the clerk called all five of us by our names,
and being willing to make short work with us,
demanded whether all or either of us would take the oath.
Whereupon I desired leave to ask the court one question, which was this;
whether if the chairman in the court did promise us, the prisoners,
anything touching your proceedings, with us,
we may not have ground to have such promises performed accordingly?

The chairman answered, "`We know not what you mean.`"

"`This,`" said I, "`is the plain case.
At the last sessions at Reading,
an indictment was brought against us for refusing the oath of allegiance; to which we,
being required to plead, did all plead not guilty.
I myself asked Sir Thomas Holt, who was then chairman,
whether that was the same indictment which we should
be tried by at the next sessions at Newbury?
Or whether they intended to have another?
and he promised plainly we should have the very same indictment without any alteration;
I am persuaded justice Staples cannot but remember it.`"
But he would not own that he remembered it,
neither would they give any direct answer to it, but endeavoured to put us by it.
Yet several of us spake to this effect.
That seeing there was an indictment framed against us at the last sessions,
and we were then compelled to plead to it,
we looked upon it to be very unreasonable and unfair in them,
now to seek new matter against us, but either to discharge us,
or else go on to trial upon that indictment.

After some more such like discourse, which they seemed little to regard,
the chairman proceeding, said, "`Gentlemen, this is the second tender of this oath,
and if you refuse, I`'ll tell you the penalty is great; for you will incur a premunire,
which is to forfeit all your goods and chattels, and to be prisoners whilst you live.
Therefore if you have any love to your liberties or regard to your families,
I do advise you not to stand it out thus obstinately against the king`'s laws,
in disobedience as you do; for the Scripture says,
that he that will not provide for his family is worse than an infidel.`"

I presently replied, "`Seeing the penalty is so great,
and justice Staples said this day to the jury, in a case of felony,
that the laws are very tender of the lives, liberties and limbs of the king`'s subject;
and since this seems the last opportunity we are like to have to speak in our own defence;
and our liberties and estates, which, except our lives, is our all in this world,
lie at stake,
and the Lord knows that we would gladly enjoy our liberties as well as other men,
and do honestly endeavour to provide for our families according to our capacities,
but we dare not disobey the Lord by breaking the commands of Christ,
and so hazard the salvation of our souls, whatever we suffer in this world.
And seeing we are a peaceable people, against whom no just ground,
so much as of suspicion of disloyalty to the king,
or of any attempt to subvert the government, can be justly charged;
our conversations having been manifest to be peaceable towards our neighbours,
amongst whom we have lived in this country, almost all our time.
And as justice Staples said very well to the jury of this day, in a case of felony,
that a man`'s reputation amongst his neighbours was very much to be observed,
and would go a great way towards the finding of a prisoner guilty pr acquitting him;
so I hope our innocent deportment hitherto ought also in equity,
to be regarded for the clearing of us from any suspicion
of being dangerous to the king and government.
And since there is no law that compels you to tender us this oath,
who are persons you have no cause to suspect,
for it is not the substance or matter contained in the oath, that we stick at,
but because it is an oath, and we dare not swear at all,
because Christ hath forbidden us;
therefore it must needs be a very hard measure for you to impose this oath upon us,
which is attended with so great a penalty,
whereby to ruin us and our families absolutely as to this world.
I desire you to consider of it, and to do by us as you yourselves, in the like case,
would be done by.
For the Lord knows our innocency, and will surely reward both you and us in due time,
according to our doings.`"

Upon hearing this the justices seemed, for the present, somewhat more mild and calm;
which made way for Samuel Burgis to speak something also, tending to the same purpose,
which they patiently heard.

But then the clerk intimating that we were premunired because we refused to plead;
I thereupon answered.
"`What! premunire us without being indicted!
We know of no indictment there was to plead to.`"

The chairman thereupon said, "`it is the judgment of able lawyers,
that refusing the oath a second time incurreth a premunire.`"

"`What!`" said I, "`without any jury!
This is a strange and a new way to proceed without indictment or jury.`"

The clerk thereupon said, here is an indictment.

I replied, "`Let us hear it then read up in English.`"

Whereupon he filled up the blanks in an indictment he had ready drawn and did read it;
and then they called us to plead to it, guilty or not guilty.
And we all pleaded not guilty in manner and form.
Which done we desired our liberty until the next sessions,
which the chairman told us we should have,
if we could get some to be bound in recognizance for our appearance.
We told him we could not enter into bond in this case, because we were innocent,
and suffered wrongfully; but if, said we, you please to take our words we will promise,
that if the Lord enable us, that we have health and liberty, we will not fail,
but as certainly appear as if we were ever so much bound.

Much was spoken in good will to us by Henry Fane, one of the justices,
to persuade us to give bail, but we still desired our words might be taken;
which being refused, we were remanded to prison again,
where we lay till the next quarter sessions, held at Abingdon,
on the 21st of the Fifth month, 1685, whither we were all brought.

But before we were called in court, a great exercise and travail of spirit came upon me,
under which I cried and breathed to the Lord in secret, that he would undertake for us,
and strengthen us to stand faithful in the testimony he hath given us to bear,
for His name and truth before men,
that He might be glorified in us in the sight of our persecutors.
And as I was thus inwardly exercised in praying to the Lord, and craving help from him,
a Friend acquainted me privately that Thomas Medlicott
did offer himself to be counsel on our behalf,
and that some of our Friends were inclined to accept of it.
But I showed my dislike of it,
and told the Friends that inasmuch as the cause for which we suffered was the Lord`'s,
I did believe the Lord himself would plead it for us, if we depended and relied upon him;
so that we need not be beholden to any of the corrupt lawyers to take our parts,
and my companions seeing me so bent, resolved against it also and spake no further of it.

This Thomas Medlicott was a counsellor at law, and had been a justice of the peace,
and often chairman at sessions; but at this time was out of the commission,
and some said he was put out for favouring dissenters.
But to proceed.

We were all called in court, and the jailer delivered in the order by which he kept us.
But justice Craven demanded the former order upon the first tender of the oath,
which the jailer it seems had left behind him at Reading.
Then Craven charged him to send for it at his peril;
whereupon the jailer was fain to send a messenger presently on purpose,
who returning early next morning brought it.

Then were we all again called in court, Charles Parrett being chairman,
a jury was empannelled,
and sworn well and truly to try the issue between the king as they worded it,
and the prisoners; but they might more truly have said,
between the envious justices and the prisoners at the bar.

An indictment was then produced and read against us; and counsellor Medlicott,
whom we had refused to accept of to plead for us,
being now retained by our adversaries to plead against us,
stood up and said he was counsel for the king.

Then Anthony Craven and Thomas Fettiplace, two of the justices on the bench,
took their oaths as witnesses against us,
that we had refused the first tender of the oath at Reading; and William Grove,
the clerk of the peace, was sworn to witness our refusal on the second tender.
After which counsellor Medlicott pleaded much, as did also some of the justices,
in vindication of the indictment, setting forth the weight of the evidence,
and how clear and plain a case it was,
and out of all question that we had refused the oath as the indictment, said;
and much pains he took in pleading to satisfy the jury of the truth of the indictment
and to incense them against us that they might find us guilty.
But we stood all of us silent,
and they never so much as asked us whether we had anything to say for ourselves.

I let them alone as long as I durst, to see what they would do;
but when I saw the jury was, as I thought, just ready to withdraw,
I asked the court this question, "`May we have liberty to speak to the jury?`"
"`Yes,`" said the chairman, "`you may if you have any thing to say.`"

Then addressing myself to the jury, I said; "`Neighbours and Countrymen:
We might speak largely touching the innocency of
our cause and the severity we have met with,
but I shall pass by that at present, and speak only to this indictment,
which you are to consider of, as well as my memory will serve.
For it is to be noted, that the clerk would not let us have a copy of it,
unless we would give him an excessive price for it;
so that we had no further knowledge what was in it,
than we could remember by hearing it once read.

In the first place said I,
it is there expressed that the first tender of the
oath to us was on the 14th of January so called,
in the thirty-sixth year of the reign of Charles the second,
and in the form of words there set down, which are to this effect,
that we should acknowledge king James the second
to be the true and rightful king of this realm, etc.
Now you must note,
that this oath could not be tendered to us in these words at that time,
while king Charles reigned, for it would have been treason in them to have done it.`"

Upon that the chairman with the counsel,
snatching up the indictment began to look upon Thomas Fettiplace and Anthony Craven,
and to whisper together between themselves with the other justices.

Which I observing said, "`Thomas Fettiplace and Sir Anthony Craven,
insomuch as you are our accusers and witnesses against us,
the law doth not allow you to be our judges too; therefore pray come down from the bench,
or else be silent there.`"
Whereupon justice Fettiplace went off from the bench.

Then stood up the counsel and to smooth over the matter said,
"`This objection you make against the indictment relates only to matter of law,
which the bench is to judge of; but the jury is to judge only of the matter of fact,
whether or no the oath was twice tendered, and you refused it.
Have you anything more to object against the indictment?`"

I answered, "`We have more to object: but we would have this well weighed by the jury,
which of itself sufficiently proves the indictment false.
Yet we have, I say, something to offer touching the second tender.`"

"`Let us hear`" said the chairman, "`what you have to say to that.`"

Thereupon I went on thus,
"`This indictment says that the oath was tendered
to us at the last quarter sessions at Newbury,
before Sir Humphry Foster, Sir Thomas Holt, and the rest on the 28th day of April, etc.
Now to this I object, that there was no oath tendered to us on that day,
neither were we so much as called in court that day.`"

"`Here is Mr. Grove, who hath sworn it,`" said the chairman,
"`shall we believe him upon his oath or you?`"

"`I do appeal, said I "`to Sir Humphry Foster himself here present,
seeing his name is mentioned in the indictment; and I do desire him to speak,
whether he saw us called there, and the oath tendered to us or not.`"

Upon that Sir Humphry Foster said,
"`I must needs say I did not see the oath tendered to them,
nor was I present when they were called,
although I was at the last sessions and took my oath there.`"

"`We desire,`" said I, "`the jury may take notice of this.`"

To wipe this off, the chairman and clerk both spake and said,
"`There is but little weight in this objection,
because the quarter sessions began on the 28th of April,
therefore what was done at that sessions might bear date from that day,
as in other cases of law at the terms held at London.
And as for Sir Humphry Foster`'s not being present when the oath was tendered,
that argues little seeing he was at the sessions.`"

"`Then`" said Edward Swain, "`one of the prisoners,
do not go about to gloss over a false matter.`"

At that word the chairman angrily said, "`If there be any Jesuit among you,
let him read the indictment;`" and in a fume threw it on the table.

I not liking his expression said, "`If we were Jesuits or that way inclined,
it is probable we might find more favour from you.`"

Whereupon Sir Humphry Foster said,
"`You do not well thus to reflect upon the bench as if we favoured papists.`"

"`Truly`" said I, "`the measure we have met with gives us just ground so to speak.
For this oath was provided against papists;
and we have been brought to seven or eight quarter sessions upon it,
but do not know that in all this time one of them
hath been proceeded against for this oath;
though it is well known they don`'t scruple swearing;
I speak not this that I desire their suffering,
but to show that they have more favour than we.`"
To the same purpose spake another Friend also.

Then began the chairman to sum up the matter to the jury,
to inform them what we objected against the indictment,
and to give them his answer thereunto; but he mentioned our objections but mincingly;
wherefore I made bold to interrupt him by saying,
"`Pray let us state our own objections ourselves to the
jury;`" and not staying for his answer went on thus.

"`In the first place I desire the jury to take notice,
that the indictment says expressly,
that the oath was tendered to us on the 14th day of January,
in the thirty-sixth year of king Charles the second, in these very words:
'`that we should acknowledge king James the second
to be the lawful and rightful king of this realm,
etc.`' And to this Sir Anthony Craven and Thomas Fettiplace have both sworn.
Now if this be true they are guilty of treason for so doing;
but if it be false then they are guilty of perjury.`"
This I repeated over again to their shame,
and with great boldness openly showed in the face of the country,
that through their envy against us,
they had brought themselves under the guilt of either treason or perjury;
from which they could in no wise escape or excuse themselves.

When I had done, much was said by the chairman and the counsel to salve the matter,
but they never so much as went about to contradict the conclusion I had drawn;
and when they had said all they could, they were fain to confess it was an error.
And then the chairman proceeded to give the sum of the whole debate unto the jury;
which to give him his due, finding himself well watched, he did pretty fairly.

So the jury went forth, and after a while returning gave in their verdict, not guilty.

Whereupon the chairman called out aloud, "`Jailer, look to the prisoners;
for by and by they shall be called again.`"
And in a little time we were all brought up again to the bar,
and they began to tender us the oath afresh.

But I objected against their doing so, saying: "`We being acquitted by the jury,
we desire you to discharge us, and not seek further against us,
but let us have our liberty, which is our right,
and which in justice you should not refuse.`"
Another of the prisoners said,
"`We being cleared by the jury you will deal worse with us than with felons,
if you deny us our liberty.`"
And to the same purpose spoke another of us also.
But the chairman bid us hearken to the oath.
And the clerk began to read it, but he being interrupted, I took the opportunity to say:
"`We have been prisoners a long time already and no evil doing can be charged upon us;
we are well known in this country, having lived nearly all our time in this county;
let any man come forth and accuse us if he can of doing wrong to any man,
or of plotting against the government;
and as our deportment hath been peaceable hitherto,
so you have no ground to suspect us for the future:
therefore our liberty being our right,
which by the laws of God and man we can justly claim,
we desire you not to bar us of it.`"

The chairman then told us it is a dangerous time,
there hath been a great rebellion lately by the dissenters,
and you are dissenters from the church,
and are likely enough to rebel if you had liberty.

I said,
"`I am persuaded that thou thyself dost not believe
that we would plot or rebel if we had our liberty.`"

Then the clerk read the oath, and they proceeded to tender it,
beginning with Samuel Burgis.

"`Samuel Burgis,`" said the chairman, "`will you take the oath of allegiance?`"

Samuel answered, "`We have lived honestly and peaceably,
and no rebellion or plotting can be laid to our charge,
nor is there any cause wherefore this oath should be tendered to us.`"
This with some more words of like import they took for his refusal.
And then tendered it to John Sansom; who objected against the tendering it,
and that was taken for his refusal.

Then said the chairman to me, "`Oliver Sansom, will you take the oath of allegiance?`"

I answered, "`If I could swear at all I should as soon swear allegiance to the king,
as take any other oath whatsoever.
But we are persons you cannot accuse of evil doing;
yet your dealing hath been with rigour and cruelty towards us,
by confining us in prisons and haling us from one
sessions to another these seven or eight times.
But for my part I must needs say, that in this respect it is no grief at all to me,
in that you have given me so many opportunities to confess Christ my Lord before men,
whose command is '`swear not all.`' And it is He that will be your judge,
before whom ye must appear and receive according to your doings.`"

The chairman thereupon said,
"`Think not that the often tendering the oath will excuse you,
we must continue it still until you take it.`"

"`It seems strange to me`" said I,
"`that wise men should thus trouble themselves to
seek to ensnare and oppress honest innocent men.
Do you think that lying in prison can be without charge?
And do you not believe that our families want us in our business at home?
And besides it is not only a loss and hindrance to us in particular,
but also a damage to the commonwealth; for several of us are known to be industrious,
and have employed many at work.
And further, this oath was made for papists,
as the preamble of the statute plainly shows.`"

Then they read a branch of the statute of the third of James,
to show that the oath might be tendered to any person above the age of twenty-one years,
endeavouring thereby to convince us, that the oath might be legally tendered to us.

"`But pray take notice`" said I, "`what the statute says,
viz. that upon presentment or indictment, the oath might be tendered.
Now I would gladly know where the presentment or indictment is,
that was the first ground of tendering the oath to us; for unless you can show that,
you ought by this statute to forbear,
and not proceed to tender it until some presentment
or indictment be first brought against us.`"

But though we had at that time a good authority over them,
and dominion in the truth to our satisfaction;
yet they entered all our answers or objections against their tendering the oath,
for our refusal.
And then the chairman said to the jailer,
"`You are to take these men back and secure them,
and come to Mr. Grove when the court is over, and take an order for them home with you,
and see that you keep them close; for you let one out to dwell in Oxfordshire,
and another to go about and keep conventicles,
I must take a course with you;`" adding more such threatening words.

But he, poor man! was soon after secured himself and kept close in his coffin,
for he died in a short time.

At parting I left these few words with them; "`The Lord knows,
and our neighbours are witnesses, that we are innocent,
and have given you no just cause wherefore you should deal thus hardly by us;
but alas! for you, you will have the worst of it in the end,
I say you will have the worst of it in the end, if you repent net.`"

So the jailer went to the clerk of the peace and received from him an order of sessions,
to continue us prisoners for refusing to take the oath of allegiance,
being the first time of tender; when we had had it tendered over and over before.

We were committed now, not as sometimes before,
to remain prisoners till the next sessions,
but till we should be delivered by due course of law,
yet we lay there till the next sessions.
Which being held at Newbury on the 6th of the eighth month, 1685,
we were had thither and all called by name in court.
And when the clerk had read the oath of allegiance to us, Thomas Staples,
being then chairman, asked Samuel Burgis, "`Will you take this oath?`"

Samuel answered,
"`I am satisfied that I should break the command of Christ if I should take it.`"

Then said the chairman to John Sansom, "`Will you take this oath?`"
and withal the crier holding the book to him said it is a good book.

"`Is it a Bible,`" said John Sansom.

"`Yes,`" said the crier.

"`Then I will do,`" said John Sansom, "`as that book commands.`"

The chairman then speaking to me said, "`Oliver Sansom will you take this oath?`"

I answered,
"`I do believe and am fully persuaded that it is
not lawful for Christians to swear in any case.`"

"`Then it seems we are all heathens,`" said the chairman.

"`If,`" said I,
"`you could convince me by plain scripture that a Christian might take an oath,
then if I should refuse this oath, it would be time enough to punish me for my refusal.`"

The chairman slightingly replied,
"`I do not know that anybody will trouble himself so far with you.`"

Then had George White, and after him Edward Swain,
the oath in like manner tendered to them, and their answers taken for refusals;
for indeed they heeded not at all what any of us said,
further than to ensnare us by it if they could.

Then having given the jailer a fresh order to keep us still in prison, (and me close,
upon an information of justice Fettiplace against me,
that he had seen me abroad,) they adjourned the sessions for a little time to Wantage,
and we were had back to our old place of confinement; where I had not long been,
before a concern came upon me to write once more to Thomas Fettiplace,
who had very illy behaved himself, both at the late sessions at Newbury,
and in the country where he dwelt.
Wherefore that I might clear my conscience in the
sight of God and leave him wholly inexcusable,
I wrote thus to him.

[.embedded-content-document.letter]
--

[.salutation]
Thomas Fettiplace.

In the fear of God and in true love to thy immortal soul,
I do once more visit thee with a letter, this third time, with desire if it may be,
to dissuade thee from proceeding on in cruelty and persecution
against innocent people for their tender consciences towards God,
who cannot believe that church and worship to be of God,
which thou wouldst force them to conform to.
What, dost thou and others think that your cruelty will
convince them that you are in the right?
Oh imprudent men! will it not rather the more confirm
them in their belief that you are certainly wrong?
Because persecution is an undeniable proof, and a manifest mark of a false church;
and whatsoever church or society shall imprison others or spoil their goods,
merely for their conscientious dissenting from,
or not joining with them in their worship, can never be accounted the Church of Christ,
but of antichrist.
And according to the scripture testimony,
this false church hath been carried and borne up in the
acts of cruelty and persecution by wilful merciless men,
whose rage is so unreasonable and brutish,
that they are termed the beast on which she rides.
From whence proceeds the forcing and compelling about worship,
and imposing upon the consciences of tender peaceable people,
and fining and imprisoning them for their righteous dissenting;
which is absolutely contrary and utterly repugnant
to the precepts and doctrine of Christ Jesus,
who foretold that his followers should suffer such things from their persecutors,
as we do at this day suffer from you; which to you is a certain token of perdition,
if ye repent not; but to us of salvation, and that from the Lord,
if we persevere in patience and well-doing.

Indeed the cry of oppression hath been great, so far as thy authority hath reached,
tor many months past.
And many accounts have come to my hands of abundance of distresses,
made on harmless people for no evil doing; but I may truly say for well doing.
I entreat thee consider what profit or benefit dost
thou see arise by all this great ado and trouble,
that by thy means is made in the country?
Doth it not the more render your worship odious and your church loathsome,
even to those that are at all religious, though as yet conforming to it?
Let me persuade thee to be serious, and ponder well what the end of these things will be.
For the Lord God, who searches thy heart seeth thy rage against him;
and thy life and breath being in his hand, he can take it from thee when he pleaseth.
And thou hast great cause to fear it,
for indeed these thy doings have highly provoked his Divine Majesty,
and greatly grieved his Holy Spirit, and his controversy is against thee for it,
and the stroke of his fury shalt thou surely feel, unless thou repent.

And whereas at the late sessions at Newbury, thou didst inform against me,
that thou didst meet me in Tubiny wood--if thou hadst asked me the occasion
of my being abroad I should readily have told thee the naked truth;
which was that of necessity.
I was in conscience concerned in a Christian care for the performance
of a trust left upon me by deceased parents for their orphan children,
during their minority.
But let me in meekness ask thee, what have I done?
I say, what evil canst thou lay to my charge, that I must be so closely confined,
and that thou shouldst go about to punish the keeper
for giving me a little liberty in so needful a concern?
Truly it doth manifest a merciless mind in thee that is
ready to take all advantages to act in cruelty towards me.
And now if thou hast thy will to shut the prison doors with all straitness upon me,
and seal me up in close confinement, what wilt thou gain to thyself by it?
For my God is with me to comfort and preserve me still,
and my innocent cause w ill he plead by his witness in thy conscience,
which will be a terror to thy soul, from which thou canst not fly.
And now thou wilt show thyself to be the cause of my close confinement,
and the weight of my suffering will lie at thy door,
and of thee will the Lord require it and requite thee for it,
in the day when he shall visit thee.

And further, know this that my end and hearty desire is,
that thou mayest know repentance, and obtain salvation for thy poor soul,
and so escape that approaching misery and destruction which thou art hastening to inherit.

This is sent for a warning to thee from thy closely confined prisoner,
only for keeping Christ`'s commands.

[.signed-section-signature]
Oliver Sansom.

[.signed-section-context-close]
Reading Jail the 9th of Eighth month, 1685.

[.postscript]
P+++.+++ S. One thing more I may remind thee of, which is this.
The poor man of Bourton and his wife,
when thou didst dance after Hardwick the informer`'s pipe, had their goods taken away,
even their very bed they lay on, and their covering that should keep them warm,
by warrants from thee.
And now that, as it is said, there are no more goods to be distrained,
thou with others to complete your cruelty, and as much as in you lies their misery,
have sent them to prison, not regarding if they perish by hunger and cold.
Oh! consider of it.
Is this the charity of your church ye would force us unto?
and the mercy of you the chief members thereof?
Be ashamed and blush for these doings,
which with many more that might be mentioned will stand upon record
unto future generations to the infamy of the actors of them.

[.signed-section-signature]
O+++.+++ S.

--

When the next quarter sessions came,
which were held at Reading on the 12th of the eleventh month, 1685, we expected a trial,
and two of us went with the jailer to the court,
where we waited until the court broke up, for the justices to go to dinner,
and then delivered two papers to a moderate justice named Humphry Foster,
desiring him to communicate them to his fellow-justices at dinner.
He did so, and when they had dined,
they sent to the jailer to bring us all five to the Bear-inn, where they were,
and when we were come thither, Humphry Foster came to us and said,
we have perused your papers, what way do you resolve to take?

We answered, "`We are not resolved on any way,
but do hope the king is inclined to show us some favour.`"

"`What would you have me do for you,`" said he?
"`Are ye willing to be called in court or not?`"
We answered, "`We rather desire to be passed by and not called.`"
"`What will follow then?`"
said he.
"`We shall be quiet, of course,`" replied we; at which he smiled and said,
"`I can do nothing of myself; but do you stay here and I will come to you again.`"

So he went into the room where the other justices were, and consulted with them,
and after awhile came to us again and said, you shall not be called in court,
ye may be sure of it.
Then turning to the jailer he said, "`You need not be strict in keeping them close,
but let them go about their business until the next sessions.`"
So we were dismissed,
and the rest of my Friends did all go to their respective habitations.

But as for me, I had not been at my outward habitation above two years;
wherefore I desired the jailer to let me have the
liberty allowed us by the justices at the sessions.
He said I had a bad neighbour, naming justice Fettiplace,
who he feared would be displeased if he should let me go home.
Yet the jailer, bearing good will to me, and willing to show me what kindness he could,
wrote a few lines to this angry justice to pacify him, and to let him know,
inasmuch as he was not at the last sessions, what liberty was then granted;
and what he had written he read to me,
and then gave it me to carry and deliver as I thought fit.
But indeed, when I had considered of it, I had not clearness to deliver it,
because it seemed a cringing under the said Thomas Fettiplace, who was an envious, cruel,
perjured or forsworn persecutor, as is plainly proved before,
so as to ask his consent for my liberty,
or in case of his dislike to return immediately back to prison again.

However, soon after I came home, I went to this persecutor`'s house to visit him,
as I had formerly written him word I did intend to do.
But when I came to him he looked very big upon me,
and appeared in his words and carriage very fierce and churlish.
And when I began to relate to him how kindly the
justices at the late sessions had dealt with us,
he would not have patience to hear me, but brake forth in opprobrious words,
and bitter railing against the jailer for letting me go.
Wherefore seeing him in such a rage and passion, I came away and left him.

This Thomas Fettiplace was a cruel persecutor of our Friends,
and of other dissenters also when he could catch them, at Farringdon and there-away,
in fining and taking away goods for not going to the worship he did;
and also for their meeting together to worship God.
His inveterate envy and malice he exercised against them with all his might.
The doors of our meeting-house at Farringdon were by his command shut
up and fastened in an extraordinary manner with locks and chains,
and the windows nailed up.
And thus his wilful tyranny was exercised against us for a long time.

But when our Friends heard that I was likely to come home,
and to have some liberty again,
they got open the doors of our meeting-house a week
or ten days before I came out of prison;
which they did in kindness to me,
that this raging persecutor might not lay the blame upon me for the opening of them.

Now when I was come home, he soon began to play his pranks again,
and that he might prevent our meeting together,
he commanded the parish officers not to suffer the Quakers to have their meetings;
threatening to fine them five pounds a-piece, if he found them negligent therein.

He had an instrument or tool very fit for his hand, one John Edmundson,
an envious man and an informer,
one who was very officious to take away goods from our Friends,
to answer the fines unjustly imposed by our persecutor Fettiplace,
and was therefore by him styled Judas that carried the bag.
And this Judas or Edmundson, being then one of the churchwardens, so called,
sent and got together the rest of the officers, viz., Henry Burden, the other warden,
John Knight and Henry Guess, tithingmen, with other assistants,
and on the last day of the twelfth month, 1685, being the first-day of the week,
came to our meeting house in Farringdon,
where we were assembled to the number of about thirty or forty,
sitting in silence waiting upon the Lord.
And when they had pulled and haled till they had got us all out of the meeting house,
the said Judas, Edmundson, plucking a key out of his pocket,
locked the door and so shut us out of our own house.

Then on the third-day following, which was the 2nd of the first month, 1686,
a petty sessions was held at Farringdon,
by the said Thomas Fettiplace and two justices more, namely,
Humphry Hyde and Henry Purefoy, who especially the latter,
did little more than sit like cyphers to fill up
the number and make Fettiplace the bigger figure.
And Edmundson having, informer like,
drawn up a list of all our names who were at that meeting, and set his hand to it,
would have had all the other officers sign it too,
but some of them refusing he complained of them to Fettiplace, who sending for them,
threatened to send them to jail unless they would set their hands to it.

That done, he commanded the constable of the hundred to fetch me forthwith before them,
charging him to search the town for me,
and if he could not find me in the town to search the hundred.
The constable thereupon came to my house,
and when he saw me he wished I had been out of his way that he had not lighted on me.
I bid him not be troubled, for I did not fear what they could do against me,
and readily went with him to the sessions.

But as soon as ever I came in sight of them, Fettiplace thus saluted me.

"`Oliver, I must send thee to jail.
Why didst thou not deliver the letter that Thorp sent by thee?
or was there any letter?
I cannot tell.`"

"`Yes,`" said I, "`there was a letter.`"
"`Why didst thou not deliver it then?`"
said he.

"`Because,`" said I, "`thou didst fall into such a passion,
calling him knave and such like bad expressions, that I knew not how to speak to thee.`"

He said, "`Thou camest to my house to affront me;
and it seems had a letter for me and wouldst not deliver it.`"

I answered, "`I marvel thou wilt offer to speak so,
when as I gave thee no manner of provocation at all,
and yet thou wast so extremely angry.`"

Then his brother Hyde to help him said, "`You should first have delivered the letter,
which might probably have prevented his anger.
Why did you not deliver it first?`"

I answered, "`The letter was written for my sake and about my concern,
and I intended in the first place to relate the matter
more fully than the letter did express,
touching the original cause of the justices`' kindness to us at the late sessions.
Yet I never said I was discharged.`"

"`Thou art discharged`" said Fettiplace, "`I`'ll justify it, thou art discharged.
But I don`'t know,`" added he, "`that I called Thorp a knave;
but yet he being an officer under me, if he do play the knave,
and not do his duty he may be told of it.`"

"`Thou oughtest then,`" replied I, "`to have told him his fault to his face,
and not have railed against him behind his back.
But as for me, I am sure I gave thee no kind of affront when I was at thy house.`"

"`Then`" said Thomas Fettiplace,
"`here is an account that thou and many more had
a meeting at the meeting house last Sunday.`"
And looking about him he said, "`where is one of the officers?
call him.`"
And when the officer came he said to him, "`Was not this man,`" pointing to me,
"`teaching or preaching, or speaking at the meeting?`"

The officer said "`When we came to disturb them, he asked us whether we had any warrant.`"

"`Was he not speaking,`" said justice Hyde, "`when you came in?`"

The officer answered, "`I heard him say nothing else.`"

"`Then,`" said Fettiplace, "`either it must be a riotous meeting or a conventicle;
if a riotous meeting we must fine them and send them all to jail;
but if a conventicle we must proceed to levy fines according to the act.`"

I said, "`You cannot conclude it a riotous meeting by law,
unless we had met with weapons or the like to the terror of the people.`"

"`We know,`" said justice Hyde, "`that they do always meet there for worship.`"

Fettiplace added, "`and there the meetinghouse doors have lately been broken open,
and we will lay that upon thee`" said he, pointing to me.
"`Constable, have him away,`" said he, "`I desire,`" said I,
"`to know what law I have transgressed.`"

"`You are not so ignorant,`" said justice Hyde,
"`but you know the law against conventicles.`"
And with that he bid the clerk read part of the act against conventicles;
"`the beginning,`" said he, "`which shows the reason of the statute;
whereupon the clerk read the preamble of the act.`"

And when he had done, I said, "`If our meetings were indeed such as are here described,
then you might justly proceed against us; but we are no such people;
our meetings are not nor ever were seditious, nor our practices any way dangerous.
Produce an instance either in former or latter times
that can fasten any such thing upon us.`"

Upon that Fettiplace maliciously said, "`What was Monmouth`'s rebellion?
and all the plots and conspiracies that have been?
have they not been all contrived at such meetings?`"
And that I might not have time to answer,
he angrily commanded the constable to take me away.
So that I had only time to say, "`I am an innocent man.
The Lord forgive you all.`"

So the constable had me away to the tithingman,
and in a little time the following mittimus was sent after me.

[.embedded-content-document.legal]
--

[.salutation]
Berks.--To the tithing-man of the port of the parish of Farringdon:
and to the keeper of his Majesty`'s jail in Reading.

These are in his majesty`'s name to will and require you,
that upon sight hereof you convey the body of Oliver
Sansom to his majesty`'s jail at Reading,
for being taken at a public Quakers`' meeting-house
with several others at Farringdon aforesaid,
upon Sunday last.
Which said Quakers`' meeting-house was above a year ago locked
up by command of the justices of the peace of this county,
and did so continue until the said Oliver Sansom was let out of prison by Mr. Thorp,
keeper of the same.
And these are likewise to command the keeper of the
said jail to receive him into his custody,
and him safely to keep until he shall be delivered by due course of law.
Hereof fail not at your perils.
Given under our hands and seals at Farringdon aforesaid, the 2nd day of March, Anno Dom. 1686.

[.signed-section-signature]
Henry Purefoy.

[.signed-section-signature]
Humphry Hyde.

[.signed-section-signature]
Tho. Fettiplace.

--

When the tithing-man had received this mittimus, being at that time full of business,
he desired me to take it myself, and go to prison by myself,
and excuse him from going with me.
So I willing to ease the officer went twenty-five miles by myself to prison,
and carried the mittimus along with me in my pocket.

[.offset]
+++[+++From the prison he wrote the following letter to his wife.]

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

My true and entire love salutes thee in the life which is divine,
wherein our unity is and from whence all our refreshments flow,
desiring and breathing that the God of our lives through his Son Christ Jesus,
who is become a quickening spirit giving life unto us,
may more and more fill our treasures that we through believing,
may come to witness the flowing rivers of living waters even in our own bowels,
to the glory and renown of our Heavenly Father and fountain of living mercies,
to whom be endless praises over all forevermore.
Amen.

By this thou mayest know that I am through the mercy and favour of my God well in health,
and do desire to hear how thou dost, and how Friends do,
and how it is with you as to persecutions.
My dear love is to E. L. and his wife;
I would have him be diligent to get Friends`' sufferings
together by the monthly men`'s meeting,
that they may be brought to the quarterly meeting.
And mind my dear love to thy sister J. v., and let the business be minded about settling;
the men`'s and women`'s meeting both on a day that it may be concluded,
which I hope will be for the better.
And if thou and Friends think fit, you may speak to Jane Turner,
and encourage her to come to the men`'s meeting, and also send word to R. E. to be there,
to the end that they may be appointed a hearing,
that true judgment may go forth according to equity.
I hope to write once more before the men`'s meeting.
So with true and unfeigned love to all Friends, thy brother D. at Charney and his wife,
my sister E. W. and to them at Gooses, Charlow, and Farringdon and elsewhere,
as if named.

[.signed-section-closing]
In haste I rest thy dear husband,

[.signed-section-signature]
O+++.+++ S.

[.signed-section-context-close]
Reading Jail, 10th of First month, 1685.

[.postscript]
Samuel Burgis is ill, he sent for me and I am just going to see him at the mill.

--
