== Chapter IX.

[.chapter-synopsis]
* After lying in prison three years, is with other Friends liberated by the King`'s proclamation
* The end of some of his persecutors
* Visits some meetings
* Travels in the ministry in Ireland
* His epistle to Friends of Reading meeting
* Continued labours in Ireland
* His return home.

I lay in prison till the next general quarter sessions
which were held at Newbury in the second month,
1686,
Before which time king James had published a proclamation
of liberty to prisoners on religious accounts.
Whereupon the jailer made a calender of all our names,
who by this time were come to be fourteen in number,
and of the causes of our commitments,
and delivered it to the justices on the first day of the sessions,
Thomas Staples being then chairman;
and the next day being the fourteenth of the second month,
we the prisoners drew up a short paper to be presented to the justices;
of which this is a copy,

[.embedded-content-document.legal]
--

[.salutation]
Berks,--To the king`'s justices at the quarter sessions for the said county,
held at Newbury the 14th day of the month called April, 1686.

[.salutation]
These humbly show:

That whereas the king by his late proclamation bearing
date the 10th of the month called March last,
hath been pleased to grant a free and general pardon, release and discharge,
unto such of his subjects as are convicted of a premunire or indicted thereunto,
or prosecuted for not coming to church, etc.
And we being persons under such prosecutions, most of us now near three years,
do hereby desire you also to commiserate our sufferings
and grant us the benefit of the said proclamation,
so as to be discharged of our imprisonment to follow our lawful
callings as the king`'s subjects fearing God ought to do;
who desire and pray for the peace and welfare of all men.

From the prisoners called Quakers,
who are now attending the court to know your pleasure concerning us.

--

This paper was given into the hand of lord Sterling,
and soon after was read by the clerk in open court; whereupon we were called for,
and the jailer was commanded to show the warrants for our commitments.
And Thomas Fettiplace bid him bring forth the last mittimus for me, which being read,
the chairman said, "`this is also before the date of the proclamation.`"

I observed upon it to the court,
that my last mittimus did exceed the severity of
the statute that was mentioned to be proceeded by,
which was 22 Car.
2, against conventicles; which if I had been found a transgressor of it,
extended no further than to fining, not to imprisoning.

The chairman answered, "``'Tis true, that act extends but to pecuniary punishments.
But you were not discharged from the former.`"
"`Justice Fettiplace when he committed me,`" said I "`was discharged,
and he would justify it; but what can justify him for saying such a false thing?`"
"`Therefore,`" said the chairman,
"`you might be committed again if a justice of the peace saw meet,
without any other crime objected.`"

"`But now,`" added he,
"`you should have brought your plea to exemplify your case to be within the proclamation.
What can you plead for yourselves?`"

"`I know no need,`" replied I, "`that there is to plead or say so much in this case,
for the proclamation is plain, and our case is clearly included in it,
and we ought to be discharged according to the true intent thereof.`"

Justice Fettiplace taking hold of the chairman`'s words, viz.,
that we should have brought our plea to exemplify our case,
and grudging us the king`'s favour, said, "`were it to me they should exemplify it.`"

But he was taken down by justice Whitfield, who said,
"`I spoke lately with the attorney-general,
and he certified me that the king`'s pleasure was that such
people should have the full benefit of the proclamation;
and that he had a peculiar favour for that sort of
people for their quiet and peaceable demeanour.`"

Fettiplace hearing that said, "`Is it so?
I did not know so much.`"

The chairman, then speaking to us the prisoners, said,
"`If you are discharged today and you keep meetings again,
you will quickly be in the same condition, if you will still break the king`'s laws,
unless the king will extend mercy to you every day.
And by your keeping conventicles,
you show yourselves to be some of the greatest enemies to the church.`"

While he took breath, I interposed and said, "`We worship God in sincerity,
according as he hath given us to believe in our consciences;
and herein I cannot see how we can be enemies to the true church.`"

When I had so said, the chairman went on with many words,
and admonishing us to be subject to the laws,
now that the king had showed us so much mercy as to pass by what is past;
and then pronounced us cleared, and discharged by the king`'s proclamation, yet added,
"`If you will not take warning, you will quickly be in trouble again.`"

"`I will assure you,`" said Fettiplace, "`I will not be afraid to commit you again,
if I find you transgressing the laws, while the same laws are in being.`"

Then stood up the clerk of the peace, and asked us for fees;
and the chairman seconding him said,
although the king discharge you from your imprisonment,
yet he doth not discharge you from paying your fees.

I asked the clerk "`What should we pay thee fees for?
Is it for drawing up indictments against us, and swearing against us,
and that falsely too, as thou hast done?
But,`" added I, "`if there be any laws that allow thee fees, I question not,
but the same laws prescribe a way to recover them; and if we, being at liberty,
do not fulfill the law, when we know it, thou mayest take thy course against us.`"

The chairman thereupon said, "`Inasmuch as he is our officer,
if you refuse to pay him what is his due,
we must commit you to prison until you do pay it;
that is the remedy the law provides for him.
But if he demands more than his due we will take a course with him.`"

I answered, "`If we must be committed to prison again,
I hope the Lord will give us patience to bear it.`"

Then a friendly man that stood near, asked the clerk how much he demanded.
And he, after some little pause, answered, that it came to nearly three pounds a man;
"`For`" said he, "`I have had nothing from them all along.`"

I over-hearing that, said, "`Before I shall consent to this,
I shall choose to lie in prison as long as I live.`"

The clerk, fearing he should get nothing began to sink, and said, "`I do but mention it,
I shall leave it to yourselves to give me what you will;
give me anything what you please, but come to my chamber, or one of you at least.`"
I seeing him come down, and that he rather asked something of us as a gift,
than demanded it as his due, asked him, "`Why may it not be as well to come to thy house,
at any other time, when thou mayest be more at leisure?`"
he answered, "`I would have you rather come to my chamber, when the court breaks up.`"

I replied, "`If we should, it is like thou wilt be very busy then.`"
At which some of the justices smiled,
as if they thought we sought to avoid speaking with him.
Which I observing, said to them, "`William Grove the clerk, hath some knowledge of us;
he knows we are no shirkers; if we engage or promise anything,
he knows we don`'t fail in performing it.`"

The clerk owned it, saying, "`I know you very well that you may be trusted.`"

The chairman added, "`I must needs say this for them, they are a sort of people,
that when they say the word, they do look upon themselves bound to perform it.`"
Thus at length were we all discharged, after we had been prisoners,
most of us near three years, and some above.

Now as touching the clerk, we considered together about him,
and calling to mind that he had formerly showed some kindness
when our Friends were presented and indicted as popish recusants;
we found freedom, seeing he now left it freely to us, to make up a small sum;
and towards the evening two or three of us went and gave it him at his chamber,
and he was thankful for it.
But as to the man himself, though he carried himself atop towards us; yet in the main,
he was in himself a wretched wicked man.
He had joined with Welman and Smith, those two perjured informers,
to frustrate us in our appeals that we could not have justice done us;
whereby they escaped the pillory, and he got twenty pounds costs from us to himself,
as is before related.
And as he lived a wicked life, so he made a wretched end;
for soon after we were set at liberty, he died very miserably,
being in great horror of mind, and fearing, as was confidently reported,
that the devil would fetch him away.
And in that terror death fetched him away.

As for those perjured informers; Welman became miserably poor,
and within four years after was taken with a sore disease,
of which in a few days he died.
His wife fell sick also about the same time, and died soon after him.
His eldest daughter, who was a lusty maid and at service,
was about the same time taken with a grievous lameness, so that she became a cripple;
and with the rest of his children became a great charge to the parish of Farringdon.
Angel Smith, the other informer, grew very poor also; and ran so far in debt,
that not daring to show his face, as I foretold it would be with him,
he was fain to fly the country, leaving his wife and children in a poor condition.

Now when I was got home, I settled to my business with my wife and family as before.
And when I felt the drawings of the love of God in my heart,
to visit Friends in their public meetings abroad, I went often forth,
both in our own county of Berks, and the adjacent counties, as Oxfordshire,
Gloucestershire, Wiltshire, to Bristol and other places.
And after a year was thus spent,
I had a pressure upon my spirit to visit my dear Friends once more in Ireland;
and it pleased the Lord to provide me a fellow traveller for that journey.
For while I was preparing for it,
it was so ordered that I did meet with my dear friend and brother in the truth,
John Beard,^
footnote:[At this early period of our Society,
it is probable that few of its faithful members escaped the rage of persecution,
then so prevalent.
In very many instances when no other particulars respecting a Friend are to be met with,
his name may be found on record as having been in
some way or other a sufferer for the cause of Truth.
Such is the case, as far as the editor has been able to discover,
with respect to John Beard.
{footnote-paragraph-split}
A few years before the journey was undertaken,
viz., in 1677, he, with some others,
was accustomed to meet for divine worship at the house of a poor blind man,
named Thomus Holborrow, who afterwards died a prisoner for his testimony to the Truth.
On one of these occasions, the informers took J. B. by the hair,
beat his head against a post, and threatened to cut off his ears;
they followed him half a mile, beating, kicking and pinching him in a barbarous manner.
At another time they put a rope about his neck, and so led him up the street.
In the year 1683, he and two others,
having come to the Sessions to hear the trial of one of their Friends,
had the oath of allegiance tendered them, and +++[+++on refusing to take it]
were sent to prison,
where they lay fourteen months.
{footnote-paragraph-split}
After this,
he and another Friend were recommitted to prison for refusing the oath,
then again tendered to them in court.
He was also one of fifty-six Friends who were discharged from prison in Gloucestershire,
in the year 1686, by virtue of King James the second`'s Proclamation,
the same by which O. Sansom and others were liberated in Berkshire.]
of Nailsworth, in Gloucestershire; and when he understood how my spirit was engaged,
he was made free to be my companion in that service.
And thus we set forward.

On the 18th day of the second month, 1687, I left my own habitation in Farringdon,
and having visited Friends in my way at Cirencester, I went to Nailsworth at night.

Early next morning, John Beard and I set forward on our journey, and coming to Painswick,
tarried a while with Friends there, and then passed on to Gloucester;
where also we made a little stay with Friends, and passed to Tewkesbury that night;
but had not a meeting there though we saw most of the Friends.

The next day we went to the weekly meeting at Parshur, where the Lord was good to us,
which greatly comforted and encouraged us in our journey; blessed be his name forever.

The day following we went to Worcester, and had a good meeting with Friends there;
wherein the faithful were refreshed and strengthened; and the Lord,
in whom all our fresh springs are, was glorified;
who is worthy to be blessed and praised forever.

From thence we went next day to Bewdley, where, through the Lord`'s continued love,
we had also a good meeting with Friends to our mutual satisfaction.

We came next day to Shrewsbury, where was a Friend of Broseley buried that day,
which was the 23rd of the second month.
And although we could not get thither early enough for the meeting at the burial,
yet we came in before the Friends that accompanied the corpse were gone out of the town.
Whereupon they all, save one or two, tarried there that night,
that they might be at the meeting next day, which was the first-day of the week;
and by that means the two meetings of Shrewsbury
and Brosely were mostly joined together that day.
And the living God who doth never fail them that trust in him,
did graciously appear to refresh and strengthen the
tender-hearted to their great joy and encouragement;
for which let the praise and glory over all, be ascribed to him forever.

Next day we went to Welch-Pool, and visited Friends there; and the day following,
being the 26th of the second month, we came to Dolobran, where Charles Lloyd lived.

At this place was the yearly meeting for all Wales held that day,
and the blessed presence of the Lord was wonderfully manifested among Friends,
to the tendering of many hearts.
And his overcoming love did so prevail,
that many precious testimonies were given forth through many vessels,
as well in the Welsh tongue as in the English, to the praise and glory of the Lord,
and to the edifying of the assembly, which at that time was exceeding great,
and held about seven hours.

We tarried there also the next day at their weekly meeting; where also, as before,
the Lord was pleased to renew a precious sense of the continuation
of his love and goodness to his waiting ones;
blessed and praised be his worthy name forevermore.

From thence we passed next day to Llanoothin,
where we had a good meeting amongst the Welsh people.
And the same day we went to Thoingally near Baffa,
where we had a little meeting the day following in the evening;
in which the Lord according to his wonted kindness
rewarded them that diligently waited on him,
answering the sincere desire of their souls.

There we stayed till the first-day following,
which was the first day also of the third month,
and then had a pretty large meeting there in the meetinghouse,
that was near to the Friend`'s house where we lodged; and a precious meeting it was,
for the Lord`'s power and presence was over all, blessed be his name forevermore.

Then early next morning we set forward for Holy-head,
being by Friends accommodated with a guide, and we got thither in two days;
it being fifty long miles, and most of it mountainous, rough, and very bad way.

There we parted with both our guide and our horses, giving him money to bear his charges,
and to have back the horses to the Friends to whom we had sold them;
for we had sold them some days before, only agreed to have them to carry us to Holy-head.

Here we tarried waiting for a passage, until the eighth of the third month.
And that day about four in the morning we went on board a vessel,
some call it a packet-boat,
which commonly carries post-letters and packets between England and Ireland,
They hoisted sails, but had much ado to get forth of the harbour,
but when once they were got clear of the land, the ship sailed mighty swiftly,
the wind blowing very stiff from the south.
And it being a misty rainy day,
the seamen fearing to fall to the leeward of the haven of Dublin,
bore up hard towards the wind, so that when we came to discern the land,
we found ourselves just right against Wicklow, twenty-four miles south of Dublin.
But they soon tacked, and sailing before the wind, got safe into the haven;
and the tide serving, went clear over the bar,
and getting ashore were in the streets in Dublin about the sixth hour at night,
just as Friends were going from their afternoon meeting.
It was the first-day of the week, and abundance of Friends were there,
it being the time of the national half-yearly meeting,
which drew Friends thither from all parts of that nation.

Next morning the national meeting began at the great meetinghouse, at the ninth hour.
And the glorious presence of the Lord was manifested to
the great refreshment and confirmation of his people;
unto which several testimonies were borne for the space of about three hours,
and concluded in prayer and praises to Lord.

Then the women withdrawing into an upper room,
the men continued their meeting in the same place, and entered upon their business;
and in great unity, love and sweetness things were proposed, debated,
managed and concluded, to the mutual comfort and satisfaction of all faithful Friends;
and then between the fifth and sixth hour in the afternoon, the meeting broke up.

And so sweet and pleasing was this meeting of our Friends,
that they agreed to meet again the next day at the same time and place,
and to have the meeting as near as might be in the same manner as the other was;
which was accordingly performed in all points.
And the presence of the Lord and his living power
seemed more plentifully to overflow the meeting,
and break forth through many vessels, even in the time of business,
which did pleasantly obstruct it for a time;
and so in great sweetness the meeting concluded at that time.
But another was appointed to be held next day as a parting-meeting
to conclude the national half-year`'s meeting.

Accordingly Friends came together at the ninth hour in the morning,
and an heavenly openness and tenderness by the Lord`'s power, was over the meeting;
and therein many living testimonies of the love and goodness of the Lord,
were borne to the great satisfaction of faithful Friends.
And about the second hour the meeting concluded, and Friends parted with comfort;
rejoicing in the Lord, who had been so exceedingly good unto us,
in our solemn assemblies, even all the time of this half year`'s meeting.

We were next day at the weekly meeting in Dublin,
where also we had renewed cause to bless and praise the Lord our God;
who never fails to refresh and strengthen them that sincerely wait upon him.

But my dear companion and I, not being yet clear of that city,
we tarried there the next first-day also, and had two very large meetings;
in which we found very great openness, through the Lord`'s heart tendering power,
and refreshing presence which was over all; blessed be his worthy name forever.

The next day we left Dublin and travelled northward,
several Friends accompanying us to Drogheda, and lodged at Killeneer;
and on the morrow had a meeting at the town of Drogheda, where much people came in;
whereof many were said to be papists; and five or six, as we were informed,
were friars if not Jesuits.
But whatever they were,
the word of Truth was preached in the authority of God`'s power amongst them;
and most of them demeaned themselves soberly, and tarried a considerable time;
and many of them stayed until the meeting ended.
And the Lord was pleased in tender mercy to manifest his precious presence,
to the comfort and refreshment of his breathing people;
unto whom he gave dominion in his own life over the dark unclean spirits;
to the glory of his holy name and precious power, to whom it belongs forevermore.

After this meeting we went to Garlandstown, being accompanied by Friends;
and the next day about forty miles to Leggekory;
and on the day following were at the burial of a Friend, where was abundance of people;
among whom we had a good opportunity at the grave; and afterwards the same day,
we went to the weekly meeting at Ballihagan;
and still the Lord`'s power did support us to the great comfort of the faithful.

Thence next day we went to a meeting at Charlow Mount, and the day following,
which was the 21st of the third month, to a six weeks`' meeting, held at Ballihagan,
for the province of Ulster, which lasted two days;
and the sweet and heavenly sense of the power and
presence of the Lord was blessedly felt,
to the refreshing and confirming of his heritage, who never sought his face in vain;
wherefore let honour, glory, and thanksgiving be offered up to him forevermore.

From hence, after meeting we went to John Robson`'s, at a place called Tunificarbet;
and were next day at a meeting with Lurgan Friends;
it being a particular six weeks`' meeting;
where the Lord`'s overcoming love was again renewed; to the refreshing of his people,
and to the glory of his ever blessed name.

Next day we went to Ballinderry,
where was a precious meeting and heavenly openness among Friends;
through the lively operation of the power of the Lord;
to whom be all living praises ascribed forevermore.

We went from thence to Lisnegarvy, on the 26th of the third month,
where was also a very precious open meeting, especially towards the latter end;
for the Lord`'s heart-tendering power was revealed
to the great satisfaction of the faithful;
and reproof of the slothful.

Then early the next morning we set forth for Carrickfergus;
where was also a good meeting; Friends were well refreshed,
and the name of the Lord praised and glorified, who is worthy and blessed forevermore.

From thence we travelled next day to Antrim; and on the morrow,
being the first-day of the week, were at the meeting there;
and the Lord in his wonted goodness refreshed the souls of his waiting ones.

Next day we took our journey to James More`'s, nigh to Ballymony;
and on the morrow had a meeting there among Friends;
which the Lord made good and precious to us,
to the glory of His own name and to the mutual comfort of the upright in heart.

After the meeting, we came the same day to Grange; and the next day,
being the first of the fourth month, went over the band to a weekly meeting at Toberhead;
where a precious sense was again renewed of the love and goodness of our tender God;
blessed be His name forever.

We returned back to Grange at night, and were next day at the weekly meeting there.
And the day following we went to a meeting appointed at Glanavy;
to which many Friends came from about Ballinderry: and at both these meetings,
the Lord gave us good cause to acknowledge his great goodness,
in answering the sincere desires of his tender waiting people;
blessed and praised be His holy name forever.

Next day we went to Killmore; and on the morrow, being the first-day of the week,
we were at Ballihagan meeting; and a large, good and precious meeting,
through the goodness of the Lord, we had with his people; to our mutual satisfaction,
and to the honour of his glorious name.

We went next day to Armagh, and there in the afternoon had a meeting;
wherein the Lord`'s power was eminently manifested,
to bear up our spirits in our testimony to his truth and way of life,
among many brutish people and soldiers that thronged in.
And after the meeting broke up,
there was one more wicked than the rest broke out in a clamorous manner,
villifying Friends and our principles, and our meetings;
but the more sober of the soldiers appeared against him on behalf of Friends.

We took a long journey next day to Belturbet,
in order to be at the weekly meeting there on the morrow;
and a very tender open meeting it was, to the glory of our gracious God,
whose overshadowing power and refreshing presence was blessedly enjoyed,
to the satisfaction of his waiting people.

After the meeting we went that night to Cavan,
and were next day at a weekly-meeting there;
w here the Lord in his wonted kindness crowned our assembly with his refreshing presence;
blessed be His worthy name forever.
And after that meeting, we went to Old-Castle at night,
and were at a weekly meeting there next day;
and the Lord`'s mercy and goodness was still continued to us;
blessed and praised be his name forevermore, Amen.

The next day we travelled on to the Moat of Grange.
And the day following, being the first-day of the week,
there was a large and precious meeting.

From thence next day we went to Edenderry, and had a meeting there on the morrow,
where many soldiers came in and sat soberly to the end;
and the Lord`'s heavenly power was over all to the comfort of the upright in heart.

Next day we went to Mount-mellick to the weekly meeting there;
where again the Lord`'s tender love was renewed,
and his living refreshing presence witnessed in the midst of his gathered ones;
blessed be his worthy name forever.

Here we made a little stop, and having no opportunity for any meeting,
we spent three days in visiting Friends at Athy, Castle-Dermot and Philips-Town.
And in this vacancy I wrote several letters for England;
whereof one was directed to Friends of Reading meeting,
and elsewhere in the county of Berks; and it was thus worded:

[.embedded-content-document.epistle]
--

[.salutation]
Dear Friends,

To whom my entire love sincerely reaches in our Lord Jesus Christ, and salutes you all,
my dear Friends and faithful brethren and sisters
who are concerned in your souls for God`'s cause,
and engaged for the Truth as it is in Jesus our Lord; against him that is out of Truth,
whatsoever likeness he transforms himself into.
I can truly say you are often in my mind,
and my soul is concerned for you in sincere breathings to my God and your God;
that he would give you, in the riches of his goodness, power and patience,
in his meek and lowly spirit,
to stand steadfast and to travel on in the pure leadings
and guidance of him who is the Lamb,
that perfect victory through his life, in the end may be obtained.
When I consider the greatness of the power of darkness
which gradually in many vessels hath prevailed,
and in that deep subtlety and deceiveableness of unrighteousness,
whereby many unwary souls have been beguiled and ensnared;
and so through affection or by-ends giving up themselves to obey the transformed enemy,
they have come by degrees to lose their tenderness;
and jealousies and prejudices have entered and hardness
and darkness have grown upon them insensibly.
So it is, even as when the good is embraced by believing and heartily joined unto,
then a growing, and being leavened into the good is known; so likewise on the contrary,
when the love of the Truth is not received and watchfully lived in,
then the enemy beguiles with a likeness, and a little of his evil leaven given way to,
leavens the whole lump.

O my dear Friends, what great need of watchfulness is there,
and of Christian circumspection by every one of you,
in an especial manner to be constant in! that a double
portion of heavenly wisdom that is pure and peaceable,
gentle, etc., may be breathed after and waited for;
that in all your practices your lights may shine,
and your conversations may preach and prevail where words can have no place.
For the time is come that a serious inspection will be made
into the lives and deportment of disagreeing parties,
whose words may be alike, and conclusions will be drawn therefrom,
that where the power and spirit of Christ doth indeed rule within;
there the fruits of it may be discerned without.
And so on the contrary where the evil root of bitterness is embraced,
the fruits thereof cannot be hid;
but will manifest themselves to that eye which God
opens in his people to try and prove all things by.

O my Friends, my soul`'s desire is,
that we all may quit ourselves like men and women really concerned for God;
and cast off every weight and burden, or whatever would encumber our minds,
or any ways hinder us from making full proof of our faithfulness to our God,
for his glory, and for the good of all people, in this our day and time.
And that we take great heed lest the cares of this present life,
do choke the precious seed, or hinder the spreading of it in our hearts,
and the appearances of it in all our practices.
For this is certain, we cannot serve God and mammon.

If the mind be hurried and encumbered with the concerns of this world,
the heart will soon be overcharged and surfeited; and then the soul is distempered,
hurt and oppressed; and at length comes to be taken prisoner, captivated and enslaved,
and so rendered wholly incapable of serving the Lord while in that state.

Wherefore let all who through the knowledge of the Truth,
have obtained freedom in any measure;
O let every such an one stand fast in that liberty wherewith Christ hath made them free;
and take great heed lest in heart there be a drawing back, and a coming to be entangled,
and so brought into bondage again.

And Friends,
I desire that a tender regard may still be had to
those that are gone into opposition and separation,
that no occasion may be given, which may be any obstruction to their returning;
for while any of the sheep`'s nature, or lamb`'s innocent life is abiding in them,
there is some hope of their returning to the fold.
And now our Christian skill is with all diligence to be employed in a continued care,
that not only all occasions of stumbling may be avoided,
but that all holy endeavours may be used to recover
and bring them back again to the fold;
even in that love which would take up the strayed sheep upon the shoulder,
that cannot be got to go, and cheerfully bring it to the fold with joy.

Oh! my Friends, in this exercise it is not words will reach,
nor verbal reasonings or disputings prevail;
it must be deeds and daily practice which will be effectual, either to clear ourselves,
or recover any of them.
And for this end, Friends, let our moderation be known to all men; give open evidence,
that we are not immoderate in our desires,
not excessive in our exercises in matters relating to this world;
and let our daily doings declare that we are seeking a kingdom that is not of this world,
and are laying up treasures in heaven, and are coveting to grow rich towards God.
And if we do not exceed them in our deportment,
and give open evidence of our moderation in our management of earthly matters,
that our hearts are redeemed from the earth,
and our love and affections fixed on heavenly things; I say,
if this do not openly appear, we cannot be excusable before the Lord,
but guilt will lie at our doors, of unfaithfulness towards our God,
and of being short in our duty towards others as aforesaid.

So dear Friends, I, knowing in some measure the enemy`'s snares and workings,
and how many this way have been beguiled, in giving way,
to let their minds be drawn out in an eager pursuit,
and earnest reaching after earthly riches,
whereby a discomposure of mind hath unawares been run into,
and deep sorrow brought upon the soul as the reward of it; wherefore in true,
tender brotherly love,
I could not be clear without sending these lines
as a token of that love and Christian care,
that is in my heart for you all; sincerely desiring your welfare and preservation.
And in that love and life, wherein we may feel one another present in spirit,
though absent in body, I do dearly salute and greet you all,
desiring your prayers to the Lord for me, who am your dear brother,

[.signed-section-signature]
Oliver Sansom.

[.signed-section-context-close]
Written at Mountmellick in Ireland, the 16th of Fourth month, 1687.

[.postscript]
====

P+++.+++ S. Mind my love very dearly to Friends at the next quarterly meeting,
if this comes timely to hand, and let this epistle be made public among Friends,
as in the wisdom of God, a service is seen.
Things here in Ireland are quiet, meetings large and full, and Friends are lively,
and zealously concerned for the interest of Truth.

====

--

Having dispatched this with other letters for England,
we left Mountmellick on the 19t`'h day of the fourth month,
being the first-day of the week, and went to a meeting at New Garden,
where notice beforehand had been given.
It was a very large meeting;
and through the Lord`'s living presence and power manifested among us,
it was a good time and a season of refreshment,
and of comfort unto the breathing obedient ones,
and of reproof to the slothful and disobedient.

On the 21st we had a meeting at Ballinakill, and the next day another at Mountrath;
and the day following at Knockballymaher (James Richardson`'s castle,) we had a meeting,
where many others besides Friends came in.
And at all these the Lord our God was exceeding good unto
his people in their assembling to wait upon Hirn;
for which let the glory and praise be ascribed to Him forevermore.

From thence we travelled the next day thirty-two long Irish miles to the city of Limerick;
and went the day after to their six-weeks`' meeting,
where we bad good service for the Lord, to the comfort of faithful Friends.
Here we tarried the next day also, which was the first-day of the week,
and had two meetings, in which the Lord`'s tender love was still continued to us,
blessed be His name, to the great encouragement and comfort of His people.

Next day we travelled to Charlowfield, and bad a meeting there on the morrow;
and another the day following at Mallow,
in both which the Lord our God still attended us
with his goodness and mercy to our soul`'s satisfaction;
blessed and praised be his holy name.

After the meeting, we rode that evening twelve miles to the city of Cork,
in extremely wet weather; and passed thence next morning to Bandon,
to a meeting before appointed there; where also our tender God was very good unto us,
in refreshing our souls together with his people;
glory over all and endless praises be given to Him forevermore.

Next day, being the 1st of the fifth month,
we returned to the city of Cork to the weekly meeting there,
and it being the time of the general six-weeks`' meeting for the province of Munster,
we tarried there three days.

On the first-day of the week there were two meetings,
in both which the blessed refreshing presence of the Lord,
was sweetly and comfortably enjoyed in the midst of his gathered people,
to their great satisfaction.

Next morning the meeting began about the ninth hour,
and continued in worship until the twelfth;
in which time many testimonies were borne of the Lord`'s great goodness to his people;
and divers exhortations were given to Friends to stir them
up to faithfulness in obeying and serving the Lord,
and to be diligent in doing their duty in all points wherein they are concerned;
especially in educating and training up their children carefully in the Truth.
And the Lord`'s blessed power was witnessed to be over all, to the tendering many hearts,
and convincing and reproving for remissness in that matter, and so concluded in prayer.
And then Friends sat down again and applied themselves to consider
of their business relating to Truth and the affairs of the church;
which was proposed, managed and concluded in much calmness, love and unity;
and about the fourth hour the meeting ended;
and all along the Lord was exceedingly good unto His people,
in vouchsafing His living refreshing presence in the midst,
to their great comfort and encouragement, for which let all the honour and glory,
and pure living praises,
be ascribed unto Him who is the God of life over all blessed forever.
Amen.

Next day being 5th of the fifth month, we left the city of Cork,
and my dear companion John Beard and I, finding it convenient for the service of Truth,
agreed to travel apart for two or three days;
so he went to a meeting at John Fennel`'s house, at Kilcommonbig; and I went to Youghal.
And the same evening there was a little meeting at Deborah Sandhams`', which was lively,
fresh and comfortable to the upright in heart.

The day following a meeting being appointed at the meetinghouse in Youghal,
many of the world`'s people came in as well as Friends;
and the enjoyment of the good presence of our tender God was known in the midst,
which made it a good time to the sincere-hearted.

The same day I went to Tullow, and having stayed there a short time,
went afterwards to Cuppoquin to lodge;
and from thence next morning went to a meeting at Clonmell.
Where, according to agreement, I met again with my dear companion; and the living,
opening power of our tender God was sweetly enjoyed,
to the refreshment and satisfaction of his breathing people,
and to the honour and glory of His everlasting name.

That evening and again next morning we visited a
Friend that was kept a close prisoner in Clonmell,
for refusing to pay tithes; his name was Gershom Boate, a tender sensible Friend.
And after we had been refreshed together, taking leave of him,
we went forward to Waterford; where on the 10th of the fifth month,
being the first-day of the week, we had two large precious meetings,
at which many people besides Friends came in to hear;
and the heart-tendering power and overcoming love of our God was over all,
blessed be His name forever.

From thence we went next day to Ross, and so to Wexford;
and on the morrow had a meeting in that town,
wherein our tender God was pleased as at other times to renew his refreshing
love and life to the satisfaction of his hungry and thirsty ones,
who in the sense thereof did praise His holy name together.

The same evening we went about four miles to Francis Randall`'s, at the Deeps;
and the next day to a meeting at Lamb`'s-town, at the widow Cuppage`'s;
and the Lord our God, who never fails them that fear him,
did also make this a time of refreshment to his waiting people.

The next day we had a meeting at Edward Goddin`'s house near Enniscorthy,
which was very large and precious.
And the same day after the meeting, we travelled thirteen miles to Kilconner,
where John Watson lives.

Then early next morning we went with many Friends in company
towards the sixweeks`' meeting for the province of Leinster.
And as we went by Carlow, we visited a Friend that lay sick,
with whom we spent some time in waiting on the Lord,
and I was moved to supplicate the Lord on the Friend`'s behalf.
Which done we passed on to Athy.
Where also we spent some time with Friends,
and there my companion was free to tarry that night;
but I passed on with the Friends to Mountmellick.

Next morning, being the 16th day of the fifth month, we met together again at Rosenallis,
at William Edmundson`'s house, where the province meeting was to be held that day.

About the tenth hour it began,
and continued about three hours in testimonies to the mercy and goodness of God;
and also in doctrine, exhortation, reproof and admonition,
tending to the building up one another in the most holy faith,
and so concluded in prayer.
Then Friends went to consider of the business relating to the affairs of the church,
which being dispatched about the sixth hour in the evening,
the meeting comfortably concluded.

Next day being the first of the week, the meeting began there again at the tenth hour,
and was very large, for Friends came thither from all parts of the province,
and it lasted near five hours, and the Lord was exceedingly good unto us, his people,
beyond expression, in crowning his assemblies with his refreshing presence,
and the over-shadowing of His glorious power was sensibly witnessed;
endless praises and thanksgivings be offered up and ascribed unto Him over all,
forevermore, Amen.

After this province meeting was ended and we were clear at that place,
we passed away the same evening in company with many Friends, to Mountmellick,
and had a meeting there that evening; to which many people came in,
and some so late that the meeting lasted until the tenth hour at night or after;
and the Lord`'s precious presence was still enjoyed in great love and favour,
according to the sincere desires of his tender ones; blessed be His name forever.

Next morning we went to a meeting appointed at Athy,
where many of the world`'s people came.
Among the rest there were two Friars,
who desired the Friend of the house to let them in a back way,
that they might not be seen, because they saw several papists about the door.
So they stood in a by-roorn privately where they might hear and not be seen.
And the Lord`'s goodness was extended in the clear openings of his life and power,
so that the testimony of truth went forth very convincingly
for the informing the inquirers and answering the opposers,
and discovering and detecting the erroneous doctrines and principles,
and superstitious practices of that dark generation of the Romish sect.
And the meeting concluded quietly and well.

The next day we had a meeting at Kilconner, at John Watson`'s house;
and the Lord did still graciously accompany us with his presence and power,
to our comfort and encouragement amongst his people; blessed be His worthy name forever.

Here at John Watson`'s we rested one day,
most part of which we spent in writing letters to several Friends.

And having sent to appoint a meeting at Bellinacarge, in the county of Wicklow,
we had a meeting there the next day; another on the morrow at Kilmurry,
at John Wickham`'s house;
where still we had great cause to acknowledge that God is good to his Israel,
and never said to the wrestling seed of Jacob "`seek my face in
vain;`" for which great favour let the glory over all and pure
eternal praises be breathed forth unto Him forevermore.

Next first-day being the 24th of the fifth month,
my companion went to a meeting that he was not clear of, in the county of Wexford.
But I went to a meeting newly set up at a place called Crownolea,
in the barony of Shillelah, and John Watson went with me;
and abundance of the world`'s people came in and were tender;
for the Lord`'s power and life were over all,
to the refreshing and comfort of the longing souls;
blessed and praised be His worthy name forever.

Thence we went to Wicklow, where we had a good meeting and pretty large;
and the next day another at Bellcane.
In both which the Lord our God was very good unto us,
refreshing and supporting us in all our exercises
among his people with his power and presence;
praised and magnified be His holy name forever.

From thence next day we travelled twenty miles to Dublin,
and reached the weekly meeting there;
and in the sense of the renewed love of our God to us,
both we and Friends were well refreshed together.

Here we tarried until the first-day following, and then were at two large meetings there;
and the Lord`'s blessed presence was livingly witnessed in the midst as at other times,
to the refreshing of his people, his own heritage; blessed be His holy name forever.

On the third-day of the week, being the 2nd of the sixth month,
we went a little way into the country again, and had a meeting at a place called Kilteel;
and another on the morrow at a place called Baltehois;
and at both these meetings also the Lord`'s love was renewed,
and his goodness largely extended to the comfort of his tender-hearted people,
and to the glory of his heavenly name.

After the meeting at Baltebois, we returned that evening to Dublin,
and on the next day were at the weekly meeting in that city;
where also we tarried till the next day following,
and were at two large meetings that day.
And the Lord`'s blessed refreshing presence was sensibly enjoyed,
to the comfort and satisfaction of his tender breathing ones.
And indeed, we have good cause to acknowledge, and that to the glory of our God,
that he was pleased to manifest and shed abroad the precious
savour of his grace and life in all places where we went.
Oh! unto Him, who revealed and renewed strength in our weakness, unto Him, I say,
be all the glory, honour, and thanksgiving rendered and returned, and wisdom,
majesty and dominion over all ascribed, who is the King eternal, the only wise God,
blessed forever and forevermore.
Amen.

The next day there was a meeting to which I went,
but my dear companion not being well did not go.
I found it a refreshing meeting,
and was encouraged in my service in the sense of the love
and goodness of the Lord among His waiting ones.

The men`'s meeting for that city was on the next day, to which we both went,
and were truly comforted and refreshed among them who were concerned in good earnest,
for the glory of God and the prosperity of his holy Truth,
and the good and welfare of his people.

The last meeting we were at there was on the 11th of the sixth month, 1687,
and there was a marriage solemnized there that day.
And the Lord our God, whose mercy endures forever,
and his lovingkindness never fails them that trust in him,
was exceedingly good unto his people there; so that we were mutually refreshed together,
and made joyful in his house of prayer.
And indeed, all along throughout our whole journey,
although with continual and hard travel we much spent ourselves,
yet did our tender God still give us fresh encouragement
by renewing our strength from day to day;
and made his way, wherein he led us, pleasant,
and his yoke we did indeed find to be easy; for which let the glory over all,
and eternal praises be ascribed unto Him, who is God over all, blessed forever.
Amen.

And now, feeling our spirits clear of any further service in that nation,
and an opportunity presenting for a passage to England, by a ship called the Dolphin,
bound for Chester, we went on board the very same evening, after the meeting;
many Friends accompanying us to the ship; and in endeared love and unity in the Truth,
even in much tenderness of brotherly affection we parted there with them.

But the tide being much spent before the ship was ready,
we could not get out of the haven,
but were fain to cast anchor and tarry there all night.

Next morning we weighed anchor and got over the bar about the ninth hour,
and with a fresh gale of southerly wind sailing on, we came near Holyhead about sunset.

But in the night the winds rose and the weather was stormy and tempestuous,
and the ship tossed extremely; insomuch, that many were in fear of being cast away;
for sometimes the ship did seem as if she were plunged quite under water;
which made many of the passengers often cry out, and fall to their prayers,
and a great noise they made of various notes,
according to the diversity of their humours, for about two hours.

But as for us (my dear companion and me,) through
the love of our God we found an anchor for our souls,
both sure and steadfast;
so that we sat quietly trusting in the Lord with our souls resigned up to Him.

And in this time of great distress, we spake to the passengers,
who were about sixty in number, concerning the condition of their souls.
And they were willing to give ear then, being low in their minds, and, as they thought,
in great danger: some of them promised that if the Lord would deliver them this time,
they would live a new life; and many such like expressions they had.
But the Lord, in his own time,
was pleased to abate the winds and the swelling of the waves;
and in his great mercy brought us all safe to land on the 13th day of the sixth month,
about the twelfth hour of the day; and we went to Chester that afternoon,
which was twelve miles.

The next day, being the first of the week, we were at the meeting in Chester,
and notice having been given over night, it was pretty large;
and the tender love of our God was preciously renewed amongst us,
to the comforting and refreshing the sincere travailing ones.

From thence we passed next day to Shrewsbury, and on the morrow,
we had a meeting with Friends there; and the next day another at Broseley,
and so went to Bewdley at night;
and from thence nest day to the weekly meeting at Worcester.
In all which meetings since we arrived in England, the Lord was exceedingly good to us,
even as He had been in Ireland.
So that, to his glory, we have good cause to acknowledge;
that as He was pleased to lead us forth from our outward habitations,
so he preserved and supported us by his power and
conducted us all along by the hand of his love,
in all our exercises, travels and services that he had led us into;
and also by the same heavenly hand brought us back again safe to our outward habitations;
after we had travelled in this journey more than eleven hundred miles.
