== The Life of Oliver Sansom. Chapter I.

[.chapter-synopsis]
* His birth and parentage
* Early religious impressions
* Convincement and profession of the Truth
* Marriage
* Settles at Boxford
* Reasons for not attending Church (so called)
* Exercise about the oath
* Conference between a Friend and the Priest
* Testimony against tithes
* Is made constable
* The primary rule of faith and life
* Continued persecutions of the priest
* Goods three times distrained for neglecting to hear divine service (so called).

Before I come to speak particularly of the dealings of the Lord with me,
and the various exercises he led me through,
after he had brought me to a knowledge of his saving truth;
I think it necessary to give the reader a brief account
what my condition was in the world,
and how it was with me before I was called into the service of the Lord.

I was born at Beedon in Berkshire, on the 8th day of the seventh month,
(called September) in the year 1636;
and was baptized (as it is called) on the 14th day of the same month,
as the parish register there relates.

My father`'s name was John Sansom, and my mother`'s Elizabeth.
They were honest; but of small substance in the world at the first:
but in process of time the Lord was pleased to bless them with an increase pretty considerable;
whereby they were enabled to live handsomely and comfortably,
and to bring up their children in some degree of learning answerable to their condition.
When I was about six years of age, I was put to school to a woman, to learn to read,
who finding me not unapt to learn, forwarded me so well,
that in about four month`'s time, I could read a chapter in the Bible pretty readily.
After I was seven years of age,
my father sent me to board at a sisters of his at Charney, to learn latin and writing;
where I remained until I was ten years of age:
and in that time learned more than I retained.

From there I was removed to another school; but stayed not long there,
my father having occasion to take me home to keep his book,
and look after what I was capable of in his business;
which was dealing in timber and wood.

My parents were of the Church of England; and being themselves religiously inclined,
they would often give good counsel to us their children (for I
had one brother and two sisters:) and they did teach us,
in their way, to pray to God, and to avoid evil company, and the like.

Now being thus bred up in a sober way, and in a religious awe to God,
it pleased Him to visit me in my tender years;
and He raised desires often in me after heavenly things: so that even in my childhood,
and more in my youth, there was a fear in my heart of offending the Lord;
and I was restrained from running into the follies and vanities,
which I observed many others delighted in;
but I did not then know that power which restrained and preserved me,
and which inclined my mind after the Lord.

I took great delight also, even in my tender years,
in reading the Holy Scriptures and other godly books which I met with,
and to hear sermons from such as were accounted the best preachers in that day;
and with much diligence did I attend on their doctrine,
with earnest cries in my heart to the Lord that he would satisfy my soul;
for there was such a hunger begotten in me after the Lord as could
not be satisfied by any of the wisdom or invention of man,
although at sometimes my heart was somewhat broken and tendered,
and I was affected when I heard the sound of words from some preachers;
for the Lord was pleased to visit my soul as I was waiting on him
and yearning after him even in those assemblies at that day;
but I did not know Him, neither did I think he was to be known within my own heart.
So I greatly mistook,
and thought it had been the preacher`'s words that reached me and affected me,
and from there I had the greater esteem for such men.
But alas! when I came to lay down my head at night my sorrow returned,
and my lack of true satisfaction continued;
though much of that which I had heard when I was so affected, my memory still retained.
But he that tendered me was withdrawn,
and I knew not where to find him nor where to seek after him.

In this so great distress have I cried many times to the Lord,
that he would vouchsafe to show me the way in which I should go,
and make known his way certainly to me that I might
but be satisfied that it was the right way,
and the real truth indeed, and I would gladly walk and live in it,
whatsoever I might suffer for it.
But the enemy beset me so sorely with his temptations,
to overthrow (if he could) my faith and hope in the Lord,
and was allowed sometimes to prevail so far upon me,
that I was sometimes even almost ready to faint in my mind,
and to reckon myself to be but a castaway;
doubting that there was no ground of hope for me,
but that I was even as one cut off and decreed for reprobation,
and could have no part or lot in the land of the living.
Thus for many a day did my poor soul travail under a sad and distressed state,
which none but the Lord is witness of,
till I was come to about the twenty-first year of my age.

And then in the year 1657 I was invited to a meeting of the people called Quakers,
where I went and there heard one of them declare the Truth.
And he testified of and directed to that very thing which I so greatly needed--the inward
Seed--the light within shining in the heart and discovering the darkness there;
which when I had heard,
I came to be fully convinced and satisfied in myself
that that was the Truth and the way of God,
which was matter of great joy and comfort to me,
for now I hoped to go forward and to walk in it without any obstruction.

But alas! the enemy now bestirred himself to throw blocks in my way,
to hinder me from`' being obedient to the conviction I had received;
and through his working there appeared to me so many impediments on every hand,
more especially from my parents and those altogether unexpected,
that they prevailed over me, and stopped me from going on;
so that for fear of offending or too much displeasing my father,
I submitted to go to the public worship again to hear the priests as before,
and so instead of going forward I went backward, yet had this reserve still in my mind,
therewith to quiet it,
that if ever I came to be at liberty from under the government of my parents,
I would then walk in the way of Truth;
and indeed I used endeavours to get abroad into service,
that I might have been more at liberty and at my own disposal as to religion,
but I could not.

Thus through the subtlety of the enemy I was prevailed
upon to give way to reasoning and fleshly ease,
and to fly the present cross which I should have taken up;
so that what by persuasions and what by commands
from them whom I thought I was bound to obey,
(as I was indeed in all things of a civil nature,
though not in matters of religion and conscience) I yielded
to go again to that worship which I was dissatisfied with.

But for disobedience herein trouble from the Lord came upon me,
and his righteous judgments pursued me close, which brought sorrow and sadness upon me.
My parents observing this, and fearing lest I should become melancholy,
gave not only liberty but encouragement to me to follow the pleasures of the world,
and put me on to associate myself with wild young men at their vain sports and pastimes,
as ringing, dancing, and the like;
and I having through my disobedience lost my strength before,
was easily drawn to make trial of madness and folly,
so that in a short time I became much worse and more loose than ever I was before,
even as it were insensible and almost unconcerned for my poor soul.

Thus I continued and went on in a vain conduct,
making merry over the Witness within and seeking
peace in worldly pleasures until the year 1661,
at which time it pleased the Lord to visit me with sore sickness and lameness together,
which brought me near unto death.
And this was the great lovingkindness and mercy of the Lord to me;
for in that time of weakness and distress, under which I lay for many months,
the Lord was very good unto me,
both in his judgments and also in his infinite love and tender mercy.
And in this great distress, which for a purpose of good unto me,
he allowed to come upon me, I cried unto him, beseeching him to raise me up again,
that I might praise his name and become as a monument of his mercy in my day and generation.
And the Lord was pleased to hear my cry, and did grant my request,
and restored me again to health, for which I gave hearty thanks unto him,
and praised his blessed name, and did often seek him in secret;
but through the workings of the enemy upon the weak
part in me I could not as yet confess him openly.
Yet I abstained from my former vain courses and was much reformed in my conduct.

While I thus walked, somewhat like Nicodemus,
having a secret love and regard to the Lord in my heart,
but not daring through weakness and fear to follow
him in an open profession of his Truth,
I altered my condition in the world by marriage, taking to wife Jane Bunce,
daughter of Thomas Bunce, of Charney, in the county of Berks,
who was of a good yeomanry family,
and had been brought up in a sober and suitable way of education.
Yet did not my marriage make any alteration in my outward behaviour,
but I walked as before in great seriousness of mind
and spent much time in reading good books,
the Holy Scriptures more especially; with which my wife and her relations,
as well as my own, were greatly affected.
But still I did conceal my judgment,
not in any part openly denying the worship which was wrong,
nor standing up in a testimony for that which I was satisfied was the right.

Not long after I was married it so fell out or was so ordered,
that upon occasion of outward business which I was then in, I was much alone,
my wife for the sake of convenience, and at her father`'s request,
continuing to live with him; yet all in much love and with mutual satisfaction.

That solitary season the Lord made precious to me and of great advantage;
for I had a book which was written by Isaac Penington,
the title whereof was "`The way of Life and Death made manifest,
and set before men,`" etc.
That book was of great service to me,
the Lord at that time visiting me afresh and opening my heart and clearing my understanding,
so that I plainly saw how I had been ensnared and prevailed
upon by the enemy of my soul to fly the cross,
which was to be taken up by all that would walk in the way of Life.
And hereupon fervent desires were raised again in
me and earnest cries were poured forth to the Lord,
that he would be graciously pleased to pardon what had been amiss,
and to forgive and pass by my great transgression in having so long disobeyed him;
and in great humility and fear I promised that if he would
be pleased to afford me the assistance of his Holy Spirit,
I would henceforward give up and forsake all to follow Him.

O the riches of the goodness and mercy and long-suffering of my tender God!
Surely I have great cause to admire his wonderful patience and long forbearance
in waiting to be gracious to me and in seeking to recover me.
O let this be recorded,
that it may remain to future generations as a thankful
remembrance and memorial of his admirable mercy,
and as a humble acknowledgment of his unspeakable lovingkindness and goodness and truth,
which he has manifested and extended unto me who had been so extremely foolish and disobedient.

Now I had lingered so long that the times were grown
more stormy and tempestuous than before,
which made it seem more difficult and hazardous than it would have been,
had I been faithful and answered the requirings of
the Lord when first he reached unto me.
And had I now looked out again to consult with flesh
and blood I might have found discouragements enough;
for my way seemed as it were quite hedged up even as with sharp thorns:
but through the lender love of the Lord,
who made the Valley of Achor as a door of hope to me,
I was strengthened and enabled to give up in His power who
had now at length made me willing to endure the cross;
and with earnest cries I besought him to be with
me and lead me in the way he would have me walk in,
and strengthen me to follow Him fully therein unto the end.

And now persecution coming fast on, many Friends being in prisons,
and sufferings growing sharp and great in most places,
I could no longer keep back or conceal myself;
but a necessity came upon me to show myself,
and take my part and lot with the sufferers that suffered for righteousness sake.
Thus were the bonds and sufferings of faithful Friends made a means to
confirm and embolden me to profess the Truth and right way of the Lord.

Towards the latter end of the year 1663,
I went with my wife to dwell at a place called Boxford, near Newbury, in Berkshire,
where I had some estate in copyhold lands given me by my father.
And I went diligently to Friends`' meetings,
but my wife continued for a time to go to the priest`'s worship.
And I had earnest desires and breathings for my wife,
that she might be gained and brought to the knowledge of the truth:
in order whereunto I did not only myself walk in much love and tenderness towards her,
but did often prevail with ministering Friends to lodge at my house,
that she might have opportunity to observe their
grave and weighty deportment and godly conduct,
and to confer with them about the things of God.
And the Lord was pleased to hear my prayers on her behalf,
and to bless the endeavours which were used for her;
so that after some time she came to be convinced also and publicly to own the truth,
and deny the priest and his worship.

But before that, the priest of the place, whose name was James Anderton,
being my near neighbour, did bestir himself to prevail over me;
first using flattery to have drawn me; and when he saw that would not do,
then fell to rough and forcible ways to have driven me from the truth,
and have gained me to himself.
The first attempt he made upon me was as we happened
to ride in company together towards Newbury.
He falling into discourse with me desired to know
of me the reason why I came not to "`church?`"
I told him my reason was,
because his church and ministry was not according
to the church of Christ in the primitive times;
and seeing I could not for that reason come to it in sincerity,
I would not come to it in hypocrisy.
He replied,
that he did not desire any to come to hear him but those who came in sincerity.
Then he desired to know in what particulars I differed from him,
whether in preaching or in baptism or about any of the ceremonies then used in the church?
I told him I could not own him in any thing of his ministry, neither in his call to it,
nor in any of his practices in it.

This put him upon vindicating his call; in doing which he used many words,
comparing it with the call of the ministers of Christ in the primitive times.
"`For,`" said he, "`there was then fasting and praying and laying on of hands;
and the like,`" added he, "`are used now in the church of England.`"
But yet he could not say that any of them, with all their fasting,
praying and laying on of hands, had received the Holy Spirit,
as the ministers of Christ in the primitive times had.
Then he ran into many words and questions concerning the ten commandments,
the sabbath and other things, to provoke me to speak of many things,
and seeking by subtlety to betray my innocency so long as we rode together.
And at parting he used many smooth expressions,
entreating me to come to his house that we might have some further talk together;
and he protested that he,
would be as willing to be convinced by me if he were in an error,
as he desired I should be convinced by him if he found me in an error.
I told him I should consider of it, and so we parted.
But when I came afterwards deliberately to consider and seriously to weigh the matter,
knowing him to be a man that abounded in words and was versed in circumventing arguments,
I was not free to go to him to discourse with him by myself alone in private;
but thought it best,
and likely to be of more advantage to the truth and more conducive to the good of others,
to get some Friend to come, and dispute with him openly;
in order whereunto I sent him a few lines, a copy whereof follows:

[.embedded-content-document.letter]
--

[.salutation]
James Anderton,

Seeing your words and carriage have appeared mild and temperate towards me,
as it ought to do,
in manifesting an earnest desire in a neighbourly
way and friendly manner to have a meeting,
for the clearing of truth and for your own and others`' satisfaction,
who are (as you said) offended with me for absenting myself from your public worship;
and you said further,
that you would as willingly be convinced by me if you were in an error,
as you desired to convince me if you did find me in an error;
and that you would have none come to hear you but those that could come in sincerity,
or words to that effect; now if you will stand to your words in fair and open dispute,
and admit of trial of you and your ways, worship and ministry,
by and according to the Scriptures of the old and new Testament;
some of us that hold forth the truth that we profess,
will admit of the like trial in any or every part of our religion;
provided that we may proceed with humility,
in order for the clearing of the truth and the satisfaction of the people,
especially those that have taken offence;
so that the kingdom of the Lamb may be enlarged and the God of Truth glorified;
which is the prayer, hope and desire of me, who am

[.signed-section-closing]
A friend to all that love the Lord Jesus Christ in sincerity, called,

[.signed-section-signature]
Oliver Sansom.

[.signed-section-context-close]
The 21st of the Twelfth month, 1663.

--

When the priest had received and read this letter,
he sent me word by the messenger that carried it to him,
that he would not have any public meeting because it was contrary to law;
but if I would meet him in private with one or two friends, he should be willing to it;
and either we might come to his house, or he would come to mine, when I would appoint.

But notwithstanding all his smooth pretences,
he soon after went to a justice of the Peace, who was called Sir Thomas Dolman,
and complained of me to him;
who thereupon immediately sent his warrant for me
to appear at a Petty Sessions to be held at Speenhamland,
there to take the oath of allegiance.

That very morning that I was to go, my own father and my wife`'s father came to visit me,
and laboured much with me to take the oath; and indeed,
their endeavours and persuasions were more grievous
to me than if I had gone at once to prison.
Wherefore with weeping eyes, I entreated them to forbear and leave me to the Lord.
Then taking up a Bible which lay near, I opened it providentially on 1st Peter iv.
12, which I read to them to the end of the chapter; whereupon they became pretty mild.

So I left them and hasted to appear at the sessions;
and when I came there the said justice Dolman arose from his seat and came to me,
and said I was a perverse fellow, with other such-like expressions.
Then he told me I had affronted the minister in questioning his call; which, said he,
is according to the law of God and the government of this realm.
He also charged me with breach of the sabbath, for travelling on those days;
and in conclusion said,
if I would not be ruled by the minister and submit myself to him and go to church,
but continue in the way in which I was going, he would make me an example to all others.
So after pretty much chiding and some threatening he dismissed me,
not allowing me to speak in my own defence;
but he did not tender me the oath of allegiance as was mentioned in the warrant.
For he was a man not inclined of himself to persecute;
but what he did was at the instigation of the priest and to satisfy his importunity.

Yet this priest Anderton still when he met me would speak smoothly to me,
endeavouring thereby to divert me from walking in the way of truth,
telling me how much he prayed for me,
and telling others what great pains he had taken
with me but could do no good with me at all.
He also gave out speeches how equally and fairly
he had offered to dispute with me privately,
as is before mentioned;
and complained how unreasonable I was in offering a public dispute,
which if he should grant he should come within the lash of the law.

After this, about the beginning of the third month, 1664,
a Friend whose name was George Robinson^
footnote:[It is difficult to identify this Friend;
but circumstances seem to encourage a belief,
that it is the same as is mentioned by Sewel, page 173, folio edition,
also in Besse`'s Sufferings, vol. II. page 392,
and in Gough`'s History, vol. I. page 418.
These authors speak of a George Robinson, a young man of London,
who travelled to Jerusalem, etc. from a conviction of duty,
to testify against superstition, etc.,
(see accounts above referred to.) The cautions manner in which
replies were then given to the questions proposed by the Friar,
is strikingly similar to these answers to priest Anderton,
and such as might be expected from one and the same individual.
The dates also seem to favor this conclusion, as it is stated,
he went abroad on religious service, a young man in 1657,
which was about seven years before the conference spoken of by Oliver Sansom.]
coming to my house, I acquainted him with what had passed between the priest and me,
and desired him to stay, if he found freedom, and give the priest a meeting; to which he,
after he had weighed the matter, consented.
I thereupon gave the priest an invitation to come on that occasion to my house,
if he pleased, the next day.
He came accordingly,
and brought with him near half a score of the chiefest of the neighbours.
Then after a few words had passed,
the priest taking the Bible in his hand propounded the following question to the Friend:
Whether that, meaning the Bible, was the Word of God and the Rule of Faith,
and that by which we must be judged and by which we must be saved?
adding, "`Answer yes, or no.`"

The Friend thereupon asked the priest.
"`What is your end in asking this question?
Is it upon a religious account, or have you any other end in it?`"

"`It is no matter,`" said the priest, "`what end I have in it;
but do you answer the question yes, or no.`"

"`Let me hear the question again,`" said the Friend; "`and I will answer as I see good.`"

The priest thereupon repeated the question, though not without some material additions,
viz:
Whether this (holding the Bible in his hand) is the Word
of God and the Rule of Faith to all that ever were,
and that by which we must be saved; and bid the Friend answer plainly yes, or no.

The Friend seeing the snare the crafty priest had laid to entangle him,
and misreport him if he had given a single and positive answer by a bare no,
to a question that required distinction, warily answered; "`First,
I believe that Christ is the Word of God;
and I believe also that the Scriptures are not Christ.`"

This answer disappointing the priest`'s design,
he interrupted the Friend and thrusting in more questions upon him,
and pressing for his direct answer,
would not permit the Friend to open the case and clear the matter to the people;
but did what in him lay to darken it by interposing fresh questions,
and several times he called the Friend a Jesuit,
and by other expressions showed his malice.

Among other things that passed in the discourse,
the Friend told the priest that he was in the steps of the false prophets,
that preached for hire and ran before they were sent,
and did not profit the people at all.
This being spoken before so many of the priest`'s prime hearers,
touched him to the quick; wherefore, to help himself,
he affirmed that several had been converted by him;
and he pointed out one man there present for an instance:
Whereupon the Friend asking that man if he was converted, the man answered,
that he knew not his own heart.
The priest thereupon to help the man and himself out said,
"`The heart of man was deceitful and desperately wicked, who can know it.`"
And from there he asserted that the hearts of all men that ever were,
were deceitful and desperately wicked, and they did not know them.
But when the Friend began to answer to this,
the priest being sensible that he had overshot himself,
and that it was like to be returned upon him with a blow,
diverted him from answering by chopping in other questions upon him,
that he might cover himself,
and his own folly and weakness might not be laid
open in the sight of his hearers there present.
Wherefore cunningly sliding off from the subject he was upon,
he took upon him to prove that Tithes were due by divine right;
and to that end cited several places of scripture
which he endeavoured to wrest for his purpose;
but all proved too narrow to cover him and hide his nakedness;
which when he perceived and saw that he still lost ground,
he broke forth into a railing fit at the Friend, calling him Jesuit again,
and so went away.

From this time forward this priest Anderton appeared more open and bare-faced,
in acting maliciously against me;
and in the harvest following a fresh occasion he took to show it:
for I was by this time more fully convinced and satisfied
that both his ministry and maintenance were wrong,
and I could no longer feed him with tithes or wages.
But it was laid upon me to stand clear in a testimony against him,
and not to have any hand in upholding him in his false worship and ministry.
This made him rage,
and when he came into the field where I and my servants were at work upon my corn,
and saw that I did not set out his tithes (as he
called them) he thus broke forth upon me.
"`I see now,`" said he,
"`that I have dallied too long and that it is high time to take a course with you;
for now I plainly see that you and I cannot stand together, but one of us must fall;
and if you are permitted to stand then I must fall;
but if I stand you shall be sure to fall.`"
I only said to him, "`Do your spiritual weapons fail,
that now you must needs make use of carnal?`"
He replied, "`I will make use of carnal;`" and so rode away.

Now although I had denied to pay this priest any tithes,
and had told both him and his man that I could not do it
for conscience sake whatever I suffered for it,
and had charged them not to meddle with any of the increase God had given me,
for if they did I should look upon it to be no other than robbing or stealing;
yet nevertheless they in their own wills took away from me what they saw good,
without giving any account to me of what they thus forcibly took from me.

Not long after this, namely, in the eighth month 1664,
I was summoned to a Court Leet held by one Richard Jones, who was then lord of the manor,
at his house in Welford; where I being then a customary tenant to that manor,
appeared with the rest, and the steward asked me to be one of the jury,
to which I readily offered my service.
But by reason that I refused to swear he put me by, although some of the jury said,
they would take my word without swearing; but the steward would not allow it.

The lord of the manor being then sick and keeping his chamber,
the priest Anderton was with him most part of the day;
yet would sometimes leave him and come into the great hall where the Court was kept.
And understanding that I had refused to swear,
he thinking to have gotten an advantage over me, opposed me openly about it,
and asserted that Christ meant no such thing, as to forbid all swearing.
I asked him, if Christ did not put an end to oaths and swearing, in Matt. 5.
and in James 5.; and he said "`No, not at all.`"
Then said I, "`If what you say is true, then the Scripture which says,
'`Swear not at all,`' must needs be false; but I believe the Scriptures are true,
and your words are false.`"
Thereupon he made a loud clamour with a seeming confidence,
endeavouring to daunt me before the people,
who were the greater part of the men of four parishes.
But the Lord by his power upheld me; blessed be his Name forever.

But this envious priest not yet getting the advantage he hoped for over me,
that he might in some measure satisfy his revenge upon me,
stirred up my landlord (the lord of the manor) to
command the jury to present me to be constable;
for it was said he had power to appoint who should be constable.
This the priest did to ensnare me,
that he might make me either swear or suffer for not swearing.

When I understood this,
I sent word to my landlord that it was not my turn to serve that office,
and that the jury did all well know it to be so; whereupon he returned answer,
that he would leave it to the jury to do therein as they should judge right.

When I understood this, not doubting but the jury would do that which was right,
I left the Court with the steward`'s leave, and went home.
But the next morning I was informed that the jury had presented me constable;
whereupon I asked some of them why they did it, and they said, they could not help it;
for the priest (they said) had so incensed the landlord against me,
that he commanded them to present me for constable
or else they should not be discharged all that night.
This unkind and unfair dealing of my landlord with
me brought a concern upon me to write to him as follows:

[.embedded-content-document.letter]
--

[.salutation]
Landlord,

It has been in my heart to lay before you some considerations concerning
the office of constableship that is now laid upon me;
which the most part of the parish can testify is unjustly and unequally imposed on me,
contrary to right and good reason.
For they say there are six livings in the possession of able sufficient men,
which have not served that office since the tenant served it for the messuage^
footnote:[A dwelling house with outbuildings and the land assigned to its use.]
I now hold.
And as I am informed, there was not one man of the jury but desired I might be excused;
and so the cause, as they say,
is only in yourself in forcing and compelling them to leave out him they had agreed upon,
or else they should not be discharged all that night.
Now I desire to know the cause or reason why I should do
that work which of right belongs to another man to do.
What is my transgression or my sin, wherefore you should favour another to oppress me,
and compel the jury so to do,
who were upon their oaths not to go for favour or
affection or malice or hatred to any man,
but according to truth in every presentment?
These things I lay before you to consider of,
and do leave it to the witness of God in your own and every man`'s
conscience to plead my cause and to be judge between us.
For yet a little while and we must both give an account to God,
and receive for the deeds done in the body whether they be good or bad;
and there is no respect of persons with Him.
Therefore while the day of your visitation lasts, prize it;
before the decree be gone forth, that "`he that is filthy, let him be filthy still;
and he that is righteous, let him be righteous still.`"
This in love to you is written, by him that wishes good to all and evil to none,

[.signed-section-signature]
Oliver Sansom,

[.signed-section-context-close]
The 30th day of the eighth month, 1664.

--

This letter was delivered to my landlord on the 1st of the ninth month,
and when he had perused it, he sent word by one of his servants,
that he knew not but the jury were willing to present me constable;
but that seeing it was done he could not now help it.
He continued sick about two months, and then died.

Now as touching the said office it may be expected
that I should give some account what I did in it.
Truly I must acknowledge that I did very weakly and like a child.
For indeed I was but young in the truth,
and exercises fell fresh still one after another upon me;
and the priest sought by all means to bow me to him and to his way.
But my neighbours were generally kind and loving to me,
and they knew that this office was wrongfully imposed upon me.
And one of them, who had served that office the year before,
offered me that for ten shillings he would continue it and
serve it for me and in my stead and acquit me of it.
Which offer I hearing and not duly weighing the matter,
but considering that the trouble would be more than the value of the money asked,
foolishly made an agreement with him,
not then minding my testimony which I should have
borne for the truth in the execution of that office.

Not long after this, I met with one Francis Green, who was a journeyman, or curate,
under the aforesaid priest Anderton.
This man it seems had long desired to try his skill upon me,
not doubting to prevail over me who appeared so plain and mean.
When we met he set forth at large what abundance of love he had for me,
and made great protestations what he would do for me to do me good.
I told him I did not desire anything of him.
Yet he pressed me very much to come to him at his lodging,
and entreated me with much importunity.
I told him I had no business with him that I knew of,
yet nevertheless to answer his desire,
it was likely I might call upon him when I passed that way.

After I had more thoroughly weighed the matter,
I saw his words were but feigned and deceitful.
Wherefore it came into my heart to write a few queries
and send them to him before I went to him myself.

Those queries were concerning the general Rule of faith and life,
which the priest had asserted to be the Scriptures only.
And the tendency of them was to show, that the saints of old,
before the Holy Scriptures were written, had, and all men since,
even where the Scriptures have not yet come, have,
a sufficient rule to guide them in their respective duties, both to God and man:
and that that Rule was the divine Light shining in their own hearts and consciences.

[.offset]
I enclosed them in a few lines to him thus:

[.embedded-content-document.letter]
--

[.salutation]
Francis Green,

Seeing you have pretended so much good will towards me and
have been very importunate with me to come unto you,
using many verbal protestations of love,
telling me you would sacrifice your blood to do me good and the like,
(the vanity of which words I shall not meddle with,
but leave it to Him who knows your thoughts;) I thereupon tell you,
that if the Lord has given any gift freely unto you to do others good,
surely then you ought as freely to communicate it
and not sell it as you and your master do.
But because of your fair pretences I thought it convenient
to propound to you these few queries,
that by your answer thereunto I may be somewhat satisfied
concerning your knowledge in spiritual things.
For I have some ground to question whether your knowledge is from the
same principle which the apostle Paul and the saints of old witnessed;
which was from the Light which shined in their hearts,
and gave them '`the knowledge of the glory of God,
in the face of Jesus Christ,`' 2nd Cor.
iv. 6. Now seeing Christians ought always to be ready to give an answer
unto every man that asks them a reason of the hope that is in them,
and that with meekness and fear; I think I have ground,
especially considering what you pretend, to expect from you an answer to these queries.

[.signed-section-signature]
Oliver Sansom.

[.signed-section-context-close]
The 10th of the tenth month, 1664.

--

This was delivered to the said Francis Green by one that was present
when he made so much ado at me to come to his lodging.
And I having occasion to go that way afterwards did then call upon him
and asked him if he had not received a paper with queries from me.
He said he had, and showed it me, and invited me to go in with him then;
but I told him I could not stay at that time, but did expect a plain answer in writing;
so I left him, but did never receive one word in writing from him.

Soon after this I happened to meet the master priest, James Anderton himself,
near my house; and he presently fell to railing on me, though it was in the open street,
calling me heretic over and over,
because I could not own the letter of the Scriptures
to be the only rule of faith and life,
neither could own his sacraments, as he called them.
And so hot he was that he said, if the law of the nation did command it,
he would be one of the first that should set a fagot to a heretic`'s tail.
Whereby he plainly manifested an anti-christian persecuting spirit.
And although for lack of power, he could not go to fire and fagot,
yet as often as he had power,
he ceased not continually to pursue me and do me all the mischief he could,
notwithstanding all his deceitful and flattering pretences of love and kindness before.
Some account of his malicious prosecutions and persecutions of
me having been formerly given in a little book printed in 1667,
entitled "`The Tree known by its Fruits;`" I may here recount
some particulars thereof in substance as follows.

About the beginning of the fourth month, 1665, one William James, of Denford,
called a justice of the Peace, dining with this priest Anderton at his house in Boxford,
the priest took that opportunity to complain to him
against me for not coming to hear him.
Whereupon the justice sent for the churchwarden,
(so called) whose name was Simon Goddard,
and examined him if he saw Oliver Sansom at church the three last Sundays;
who answering that he did not see me there, the justice made him swear it.
And then the said justice James presently made a warrant and sent it to the constable,
requiring him to bring me before him.
In the warrant it was expressed,
that information and complaint had been made upon oath before him,
that Oliver Sansom did neglect to come to the parish church to hear divine service, etc.
For which cause he did require me to come before him,
to show some reason for this neglect,
or else to pay three shillings to the use of the poor, etc.

When I was brought before him I declared the cause
and reason wherefore I could not come to that worship;
and then added, that "`though I did not come there,
yet I did in sincerity worship the true God,
according as he had persuaded my heart and conscience; and surely,`" said I,
"`no man ought to be punished for so doing.`"
I told him also,
that I did believe he did desire liberty of conscience
himself to worship God as he was persuaded,
and not to be compelled to act contrary to his own conscience,
and therefore he ought to allow it to me.

But notwithstanding all I could say unto him he issued forth
his warrant to distrain and make sale of my goods.
Whereupon, on the 13th day of the fourth month, 1665,
those officers unto whom the warrant was directed,
went to the priest`'s house to consult with him about the execution thereof,
who soon set them in a way.
And then they, namely, James Basford, constable, William Knight, tithingman,
John Ironmonger and Simon Goddard, churchwardens, (so called) and John Winch,
overseer of the poor, having some of the priest`'s children with them, came to my house;
and bringing with them the priest`'s scales, weighed out twelve tods of my hay,
which the priest bought of them for threepence the tod,
and sent his man and fetched it away.

But this is fit to be noted in this case, that this unjust priest,
who thus bought my hay (which was wrongfully taken from me) at threepence the tod,
had the evil conscience to rate the tithes of the same hay at sixpence the tod,
(double price!) and sued me for it at that rate, and recovered the treble value upon me,
and made a prey of my goods for it, as shall be showed in its place.

Shortly after, the priest meeting me fell on me about his tithes as he called them,
and could not forbear threatening what he would do to me if I did not pay him.
He said he would toss me from one place to another and would throw me into prison.
I asked him if he were the man that had complained against me to justice James.
He said he had complained against me and would do so again.
And further, said he, for every Sunday henceforth that you do neglect to come to church,
you shall be as sure to pay twelve pence as your hat is on your head:
and accordingly he drove on.

For on the 25th day of that month I was excommunicated, as I was informed,
for not paying the steeple-house tax.
And on the 25th of the fifth month, 1665,
he procured another warrant from the said justice James,
requiring my appearance before him, to show reason for my not going to the parish church,
so called.
But I being from home at that time,
visiting my suffering friends who were then prisoners in Reading jail,
the time prefixed for my appearance was past before I returned home,
so that I did not appear upon that warrant.
But as evil will commonly think the worst,
I suppose they thought I had absented myself on purpose
that the warrant might not be served on me.
For shortly after the said William James, being spurred on by the priest,
issued forth another warrant against me,
in such strict terms as if I had committed some heinous crime;
whereas the only matter they had to charge me with was my not going to hear the priest.
Which warrant, because it was in an unusual form, I here give a copy of:

[.embedded-content-document.legal]
--

[.salutation]
Berks.--To the Constable and Tithingman of Boxford, or to either of them.

Whereas information and complaint has been made and given in unto me upon oath,
that Oliver Sansom, resident in your parish, did upon the second, the ninth,
the sixteenth, and three-and-twentieth days of this present July, being Sundays,
neglect to come to your parish church, to hear divine service,
contrary to the laws in that case made and provided:
These are therefore in his Majesty`'s name, to charge and command you,
and every of you to require the said Oliver Sansom to appear, and in case of his refusal,
to bring him before me, and others His Majesty`'s justices of the peace of this county,
at our Petty Sessions to be held at Newbury this next thursday.
And in case he shall hide out of the way,
so that you cannot give him notice personally of
this warrant before our said Petty Sessions,
that then as soon as you shall meet him, you attack him,
and forthwith bring him before me, that if he can,
he may show some reasonable excuse for this his neglect,
and to be provided to make due proof thereof;
or else to pay four shillings to the use of the poor of your parish,
and to be further dealt with as to law and justice does appertain.
Hereof fail not at your peril.
Dated at Denford in the said county, the 25th of July, 1665.

[.signed-section-signature]
William James.

--

When the constable had received this warrant,
he told me the day of appearance was on Tuesday following; but therein he did mistake,
and by that means the Petty Sessions were past before I had seen the warrant.
And although it was the constable`'s fault that I did not
appear at the time and place mentioned in the warrant;
yet he, fearing the displeasure of the justice,
compelled me to go with him afterwards to his house at Denford.
Where when I came,
much discourse passed between the justice and me concerning worship and compelling thereto.
But all that was said to him was in vain;
for he was resolutely bent to prosecute the work the priest had put him upon.
And after two or three days he sent another warrant to distrain my goods.
Whereupon those officers which were called the churchwardens, with the tithingman,
came to my house on the 16th of the sixth month, (then) called August, 1665,
when nobody was at home; and going into my barn, they took away my winnowing fan,
which was worth eight shillings, and carried it to the priest`'s house,
while I with my family, was in the field at harvest work.

Within a few weeks after this the said justice James sent
another warrant to require my appearance before him again,
to show some reasonable excuse for my not coming to their worship.
Which when I heard of,
I considered that my appearing before him was for no other end
than to make his further proceedings against me seem the more legal;
for notwithstanding whatsoever I said to him, when I was before him,
he resolved to go on to answer the priest`'s design.
Wherefore I went to the tithingman who had the warrant,
and fold him I did not intend to appear personally, but would send my answer in writing,
and desired him to carry it; which he did, and this is a copy of it.

[.embedded-content-document.letter]
--

[.salutation]
William James,

Whereas I have been accused or complained of to you
for neglecting to come to the parish church,
etc., and thereupon you have sent a warrant to require me to come before you,
to show some reasonable excuse for the same, etc.
These are therefore to certify you or any other that shall question me on that account,
that I have not only reason to plead for me in this matter, but I have the law of God,
the Gospel of Christ,
and the testimony of the saints and people of God recorded in the Holy Scriptures,
and also the witness of God in my own conscience, to plead on my behalf in this matter.
Whereby I have assurance, that a persecuting church is a false church,
which I ought to deny and turn from.
And the Lord has given me patience to endure what he is
pleased to permit unreasonable men to do unto me.
'`For all men have not faith.`' 2 Thess. 3:2. And again,
'`The devil shall cast some into prison.`' Rev. 2:10. Yes,
'`And all that will live godly in Christ Jesus shall suffer persecution.`' 2 Tim. 3:12.
And seeing there is no matter of fact that I am accused of,
so far as I understand,
and I have been summoned to appear at the Bishops`' Court upon the same account,
and there I am liable to answer; though I do not contemn any authority,
yet if no matter of fact be proved, nor so much as charged against me;
I suppose I am not liable to a trial at two courts, for the same thing.
But if any matter of fact can be charged against me commanding my accusers to be present,
I will appear to answer at any time, if the Lord permit.

[.signed-section-signature]
Oliver Sansom.

--

When the Justice had received this letter,
he without more ado issued out another warrant for distraining my goods,
unless I would pay four shillings, for not coming to their worship;
which I not having freedom to do, Simon Goddard, one of those they call Churchwardens,
came to my house on the 30th of the eighth month, 1665,
and distrained and carried away a good new harrow, worth seven shillings.

Again, towards the latter end of the tenth month, 1665,
the said justice James issued out another warrant of like import with the former.
Upon which the said Simon Goddard came again,
on the 29th of that month and took away two pewter dishes,
for my not going to their worship.
Thus they took away my goods three several times,
for my not going to their place of worship, after I was, by excommunication,
shutout and debarred from going there.
And the said William James (called the justice) did blame the officers for not
selling my goods and threatened to punish them if they did not sell them.
And when they alleged that they could not sell them to the worth,
he told them if the goods were worth twenty shillings,
and they sold them for five shillings, he would bear them out in it.
Which showed he had but little justice in him.
