== Chapter II.

[.chapter-synopsis]
* Presentiment of an Imprisonment
* Meeting broken up by the Priest
* Is imprisoned for having a Meeting at his house
* Letter to his Wife
* His second imprisonment
* Letter to his Wife
* His Goods distrained to the value of £30
* Extraordinary persecutions by the Priest
* His Epistle to the Neighbours and one to the Priest
* His third imprisonment
* Letter to his Wife.

On the 25th of this tenth month, 1665, as I lay in bed in the morning early,
I heard as it were an audible voice which said unto me, take no care for your business;
for you must go to prison for three months.
Thereupon I presently arose, and related to my family what I had so plainly heard;
and we all thought that if I went to prison it would be for not paying the priest,
he having so often threatened me.
So I let it pass for the present being given up in my mind to suffer,
if the will of the Lord were so.

Three days after a ministering Friend came to my house to visit me; and I desired him,
if it stood with his freedom to have a meeting there that evening;
because several of my neighbours had told me that
if ever there should be a meeting at my house,
and they had notice of it they would come to it.
The Friend consenting I sent my servants, both man and maid,
to acquaint all my neighbours therewith,
both in that town and also in a village which was near,
and I bid them deliver their message thus;
that if they had any desire to hear the Truth declared,
they might come to my house at such an hour that evening.
There was not one family, besides the priest`'s, but was invited.
For I thought the priest would prove a troublesome guest;
and therefore neither he nor any of his family were invited.
But most of my neighbours came, especially the men; and the room was full,
and the Friend declared the Truth for near the space
of an hour to the great satisfaction of the people.

While thus we were solemnly assembled together,
and were exercised in that which was indeed Divine service; the priest,
being at home in his own family, and others with them, playing at cards,
had tidings brought him of our meeting.
Whereupon leaving their card-playing, the priest sent immediately for the tithing-man,
who dwelt near, to come away forthwith and break up the meeting.
But neither he nor the constable were at home;
for they were both of them at my house peaceably assembled with many others in the meeting;
not in the least suspecting, that the priest would be so wicked as to make a disturbance.
But when the priest saw he could not get any officer to do his work for him,
he came himself to my house, having the card-players with him,
and he began to threaten the people that they should
all go before the Justice on the morrow.
Some of the people being so threatened were afraid, and would have gone away.
But one Francis Doily, (who was then the priest`'s journeyman or curate) kept the door,
and told them he must know who they were before they went forth.

The Friend was declaring the Truth when the priest
with his company of card-players came in;
and the priest interrupted the Friend in speaking,
demanding of him his name and place of abode,
and charged the constable to see him and the friend
that accompanied him forthcoming the next morning.
Then the priest going away called forth the constable after him and commanded him privately,
to set a guard of men upon the two strangers to keep them until the morning.
But some of the people over-hearing what the priest had said to the constable,
and disliking these doings of the priest, came to the two Friends,
and intending kindness to them,
thrust them out at another door into the orchard that the constable might not see them,
it being pretty late in the evening.
By which means, when the constable, who dared not disobey the priest,
came in again though much against his will to apprehend the Friends,
he could not find them; at which he was glad and so passed away.

Early next morning the priest sent one Lodowick Yeomans, the parish clerk,
who had enviously opposed the Truth,
to give information of this meeting to William James, the Justice,
(so called) who thereupon sent his warrant to the constable of the hundred,
to bring the constable and tything-man of Boxford and as many more
as the said Lodowick could name that were at the meeting,
to appear before him and other justices of the peace,
at the "`Three Swans`" in Hungerford, on the 30th of the tenth month, 1665.

I being particularly named in the warrant went with the rest;
and they intended to have taken my servant-man also,
but they having mistaken his name in the warrant he went not with us.

When we came there we were brought before three justices; namely, John Elmes,
William Dormer, and the said William James; but not altogether,
for I was not permitted to be present when the others were
called but was kept by myself in a room at a distance.

First they called the constable and the tithing-man of Boxford
and the others that were brought with them,
but they lacked a witness to convict them;
for they had but one witness (the parish clerk) and they ought to have two.
Wherefore seeing a poor man among the company they tampered with him,
promising to set him free if he would turn informer,
and upon his oath give them the names of the rest
of his neighbours whom he had seen at the meeting;
which the poor man for fear of suffering himself presently did.

Having by this means convicted them, they then called for me last of all.
And when I came before them they pressed me much to discover
the names of the two strangers that were at that meeting:
urging that thereby I might free myself from the suspicion
of entertaining Jesuits or other dangerous persons.
I told them "`They were friends of mine and well known to be honest men,
and were never suspected to be Jesuits or dangerous to the peace of the government,
or of doing injury or harm to any.`"
They replied, my words would not satisfy them nor clear myself; for, said they,
if they were honest men, why did I fear to tell their names?
"`Because,`" said I, "`I would not occasion their suffering;`" but, added I,
"`if you will promise me, that they shall not be troubled or molested for it,
I will presently tell you their names.`"
Then William Dormer promised for himself and the rest,
that if they were honest men they should not be meddled with:
whereupon I told them both their names and where they lived.
And he was as good as his word, for they were not meddled with.

After examination they proceeded to impose fines.
And first they fined James Basford the constable, because he was constable,
ten shillings; and caused him to pay it down presently.
The rest they fined twelve-pence a-piece.
But when they came to me, because I could not promise, as the others did,
that I would go no more to meetings,
and to confess myself guilty as an offender in that which,
in the sight of God and of all just men was no offence, they fined me five pounds;
or to endure three months`' imprisonment,
as for the first offence (as they called it) upon the Act for banishment.
And I not consenting to pay the fine,
was committed prisoner to the county goal at Reading, for three months.

Now did I call to mind, and thankfully acknowledge the goodness of the Lord unto me,
in fore-showing me of this three months`' imprisonment
by that voice which I had heard as I lay in bed,
three days before.

Within four days after my imprisonment,
the said Justice James sent his warrant for my man-servant whose name was William Cowless,
and committed him to the house of correction at Abingdon, for four months,
calling this his second offence upon the Act for banishment; for he,
having been taken at another meeting,
had been committed not long before to the house of correction at Reading,
and was but lately discharged from there.
And herein their injustice to him, un kindness to me, and severity to us both, appeared.
To him, in committing him to prison, for being in his master`'s house, where his place,
as a servant, required him to be.
To me, in sending my man to prison, when they had sent me to prison, just before;
thereby leaving me destitute of a man to look after my business.
To us both, in imprisoning us at such a distance one from the other,
that we could not be any ways helpful one to the other.
And indeed I soon needed help;
for I had not been long in the prison before I fell sick
and continued ill and weak for about two weeks`' time.

And now,
not being so mindful and regardful as I should have been of that
warning and charge which the Lord had so wonderfully given me,
not to be thoughtful in my imprisonment of my outward concerns at home,
as I began a little to recover I let the cares thereof enter my heart,
taking thought what my poor wife would do with my business,
my man being in prison as well as myself, and she left destitute of fit help.
Wherefore having obtained leave of the keeper I went privately home,
that I might be helpful to my wife in advice and counsel at the least.

But the journey being too hard for me eighteen miles on foot, in the winter season,
and I but weakly, I took cold again and my sickness returned and was very sore unto me;
so that I was nigh unto death.
Then cried I unto the Lord for help, beseeching him to give me a little strength,
that I might be but enabled to get to my prison again,
and then I should be satisfied to die, if he had so appointed.
Oh! it was a sore trouble and exercise to me to be thus out of my place;
and to be so seized with sickness as not to be able to return back again;
whereby instead of being assistant to my wife I was but a hindrance to her,
and brought great grief and trouble on her, seeing me in that weak condition,
like to die,
and she could not have the help of her neighbours because she was afraid to let
them know that I was at home lest it might bring blame upon the jailer.
But after two or three weeks`' time it pleased the Lord in his
tender mercy to abate my illness and give me some strength,
and then I got privately back to my prison again.
And glad I was when I got there; intending for the future never to do the like again,
but to rest satisfied in my sufferings, and to resign up all unto the Lord,
who saves all those that put their whole trust in him.

It was weightily upon me to record this passage as a thankful
remembrance of the Lord`'s mercy and goodness to me therein;
and I desire it may be a caution to all tender Friends who may have the knowledge of it,
to cast all their care upon the Lord, and lean solely upon him,
whatever their exercise and suffering may be.

[.small-break]
'''

+++[+++During his confinement he wrote the following letter,
addressed "`For the hands of my dear and loving wife, Jane Sansom, dwelling at Boxford,
these, with care.`"]

[.embedded-content-document.letter]
--

[.salutation]
My dear and tender wife,

In the living sense of the free and unlimited love of the Father of mercies and God
of consolation who has freely loved us and given of his Spirit into our hearts,
I say in the sense of that pure love, do I dearly salute you,
beseeching the Lord God of my life to preserve you in continual watchfulness against
the secret enemy and to keep you in true humility and contentedness in all conditions.
Dear heart,
in the meek and quiet spirit be cheerful and fear not the
fury of the adversary nor any of his instruments,
but learn to know Him that is in us and with us to be greater than he that is against us;
and therefore, my dear lamb, be strong in the strength of the Lord,
and in the power of His might wait to be established,
and be not careful concerning me for I lack nothing,
and I have pretty well recovered my health,
and I have pretty much liberty out into the town to go and come as I see good.
Friends are all well and the sickness^
footnote:[This no doubt refers to the fearful plague which was then raging in London.]
is not anywhere in this town that I can hear of.
Let me hear from you, if you have opportunity,
how it is with you and how you do make a shift with your business; but dear heart,
let not your mind be cumbered with it; so with dear love to you and to Ruth,
and to Friends at Oare, and at Woodlands, and to dear Richard Greenway,

[.signed-section-closing]
I rest your dear husband,

[.signed-section-signature]
Oliver Sansom.

[.signed-section-context-close]
Reading Jail, 2nd of Twelfth month, 1665.

--

When my three months`' imprisonment at Reading was
at an end I was discharged and went home.
But I was not long permitted to enjoy my liberty there.
For on the first-day of the fifth month, 1666,
I being with other of my friends peaceably assembled at
the house of Bartholomew Malam in Lambourne Woodlands,
to wait upon and worship the Lord,
we were violently haled out of our meeting by armed soldiers of
the trained band under the conduct of Charles Garrard their captain,
and many of us carried to Lambourne before Humphrey Hide, Thomas Garrard,
and Charles Fettiplace, called Justices,
who committed eleven of us to prison--seven to the house of correction at Abingdon,
and four, whereof I was one, to the common jail at Reading for three months,
upon the Act for Banishment; where I continued a prisoner very near fourteen weeks.

[.offset]
+++[+++He wrote the following letter to his wife during this imprisonment.]

[.embedded-content-document.letter]
--

[.salutation]
My dear wife,

These are to let you understand that through the goodness of the Lord
I am very well in health and at present feel not the lack of anything;
for I know the living God to be my Shepherd who does
guide and lead me in the green pastures of comfort,
joy, and peace; so that satisfaction is by me daily enjoyed and witnessed.
Dear heart,
feel me in that living spring from which our refreshment and daily satisfaction comes,
and be steadfast and immovable,
always having the eye of your mind inwardly opened in pure fear,
watching over your thoughts, words, and actions.
Oh dear heart, my true breathings often to the Lord have been,
that we both may be preserved faithful and single to the Lord;
that in all trials and sufferings that at present do or ever hereafter may attend us;
I say my earnest desire is, that we may not look out,
nor murmur at the Lord`'s dealings with us,
but that we may always be given up to do or to suffer whatever
the Lord shall be pleased to exercise us with;
knowing that we are the Lord`'s, and he may do with us what pleases him,
and assuredly he will not allow us to be tempted or tried any further than he will give
us strength to bear and endure as we stand faithful to what he makes known to us.
With dear love to all faithful Friends at Oare or elsewhere, I remain your dear husband,

[.signed-section-signature]
O+++.+++ Sansom.

[.signed-section-context-close]
Reading Jail, 14th of Fifth month, 1666.

--

And when I was set free from that imprisonment and came home again,
it was not long before my old adversary gave me another toss,
as he had before threatened to do.
For though I never went to hear the priest,
nor ever had one pennyworth of service from him, yet was he always restless till he had,
by one evil way or other, gotten away my goods from me for his pretended wages;
ruling by force and cruelty over the consciences of men,
like those whom the Prophet was sent to cry woe against, Ezekiel xxxiv.
Wherefore I think fit to set forth some more of his proceedings against
me after I was come home from my second imprisonment in Reading.

First I was summoned by a subpoena to appear in the Court of Exchequer at Westminster,
at his suit, in the ninth month, 1666.
Where when I appeared, according to the express words of the order,
I found none to prosecute me or lay any thing to my charge;
for he had changed his mind and would not proceed any further in that Court.

But in a few months after, he procured a warrant called a Justicias from the Sheriff,
out of the County Court; and with that warrant he sent two bailiffs,
who took away my horses, which they kept in the bailiff`'s hands at Newbury,
and put my cows in the pound at Boxford and locked them in;
and so hard-hearted were both priest and bailiffs,
that they took no care nor gave any order that the cows should have food given them;
so that if I had not carried fodder to them, they might have suffered much,
and have perished.
This coming to the hearing of one of my relations,
he (unknown to me) went to the under-Sheriff and passed his word,
that the cattle should be forthcoming when he should demand them;
and thereupon after they had been so detained for the space of eight days,
they were returned to me again.

On the 8th day of the second month, 1667, the Sheriff kept his Court at Abingdon,
where this priest repaired; and his lawyer drew forth a declaration against me,
which contained many untruths.
Then some of my relations caused an attorney to give an appearance;
and the attorney`'s opinion was,
that the priest could not have a trial for tithes in that court.
After which I heard no more of this proceeding for four or five months;
so that I was ready to think the priest had let fall his suit there also.
But on the 26th of the sixth month 1667,
he stole (as I may say) a trial in the same Court.
For it was so subtly and privately carried on, that I had no certain knowledge of it,
before the bailiff came upon me with an execution;
and that too was early the next morning after the trial.
The bailiff`'s name was Richard Smith, who rushing suddenly in, searched my house,
and took away three pounds in money, and drove away all my cows and sheep,
amounting in all to the value of thirty pounds or thereabouts,
though the single value which the priest sued for was six pounds and eight shillings.

The wickedness of this priest was so great that I am willing
to hope there were but few worse in the nation;
for he was not only greedy, but exceeding envious.
Insomuch that when a certain man of my acquaintance, out of natural affection to me,
without either my consent or knowledge,
sent to him by some of his neighbours to let him
know that if he would take two indifferent men,
and let them value what the tithes of my living was worth, he would engage to pay it;
the priest would not accept of it, but said he would root me out of the town,
or words to that effect.
And so high was his malice that it made him not only break forth into those bad expressions,
as that, if the king would but grant a law for it,
he would be the first man that would have me burnt,
and that would set a fagot to my tail, which he uttered more than once; but also,
after he had caused me to be excommunicated he told the people,
that now none must have anything to do with me, either to buy or sell or the like;
and even the miller was forbidden to grind my corn.

Yes this envious priest threatened one man that did use to work for me,
that if he did not leave off working for me he would present him into Oxford Court,
and the severity of the law should be prosecuted
against him and bid him work for me again if he dared.
The poor man for fear of the priest left off,
and did not dare to work for me any longer at that time.
But about a year after having forgot it seems the priest`'s threatenings,
he ventured to work for me again.
But the priest had not forgot to deal wickedly by him,
as the poor man soon found to his cost, for he was presented,
and the apparitor came and summoned him to appear at their Court;
which so affrighted the poor man, that being in doubt what the issue of it might be,
he gave the apparitor money to make it up and settle the matter,
that he might have no further trouble about it.

Another occasion of no small difference happened between us, which was this:
the tower of his worship house, called by him the Church, had formerly fallen down;
and my house adjoining to that which they call the Churchyard,
the rubbish thereof lay so high against the side of my house, that it did me much hurt.
Wherefore I took my mattock,
and went to dig a trench or gutter under the eaves
of my house on that side next the graveyard.
But the priest seeing me at work there,
came at me with open mouth as if he would have devoured me,
and violently took my mattock from me; and not only so,
but threw down my garden bounds on that side which
was next the said graveyard flat on the ground,
and caused the trench I had digged to be filled up.
And so great a clamour and noise he made,
that it drew several of the neighbours in to know what the matter was.
When he saw them flock in, he in his rage and thinking to startle me,
asked me before them, whether I would own that letter which I had lately sent him?
I bid him produce it and read it to them and I would assuredly own it.
But he seeing me not daunted at it would not produce it.
Now true it was, that I had sent him a letter not long before;
the occasion whereof was this.

After he had taken away my goods for tithes, as is before related, some of my relations,
seeing that my goods were like to be sold under-hand,
made an agreement with the priest to pay him twenty pounds,
and they to take the goods to sell for as much as they could; intending, as they said,
to keep the overplus money for him till another time if he should fall upon me again.
This agreement between the priest and them,
I was so far from having any hand in or giving any consent or countenance to,
that I endeavoured to the utmost of my power to hinder and withstand it; as the Lord,
who knows my heart, bears me witness.
And when this blind bargain was thus patched up and the money paid,
there was a general release under the priest`'s hand and seal sent to me;
which I returned back to him, enclosed in the letter he mentioned,
which was of this tenor:

[.embedded-content-document.letter]
--

[.salutation]
James Anderton,

I have lately received a general release under your hand and seal.
I much wonder you were so impudent as first to steal my goods and
rob my house for wages though I never set you at work;
and then deceitfully you make it out as if I had paid your demands,
and thereupon have acquitted me.
Be it known unto you, O hypocrite, that I never consented to pay you anything,
because I owed you nothing;
your release I return back to you again as a testimony against your deceit.
But as for the goods and money that were by you violently taken from me,
I can look upon it to be no other than theft and robbery,
which will assuredly be upon your account before
the righteous God unto whom I have committed my cause,
whose truth and servants you have reproached,
and whose worship you have disdainfully opposed.
For at Chewly, on the 10th of the seventh month,
you did prefer card-playing before the true worship of God.
Oh full of all subtlety, how do you pervert the right way of God!
You shall as assuredly feel the vengeance of God and his
fiery indignation for these things as you have done them;
and with the murderer, swearer and liar you shall be shut out except you speedily repent.
O repent, repent; if you can find a place.

[.signed-section-signature]
O+++.+++ S.

[.signed-section-context-close]
The 24th of the Eighth month, 1667.

[.postscript]
====

P+++.+++ S.--And now, James Anderton,
consider with yourself what you have brought to pass by
your striving in cruelty against me these four years;
you have but made your folly manifest.
Alas! what am I, that you should thus strive against me?
But it is the living God that is on my side and has preserved me hitherto;
living praises be to His name forever.

[verse]
____
In the Truth of God, unto which all must bow,
At first I was not so strong as I am now.
Holy Praises be to my Rock and Strength forever;
For from his Love no earthly thing can sever.
____

====

[.signed-section-signature]
O+++.+++ S.

--

After this I had little more to do with him for some time,
till the Court Leet came which was in the second month, 1668,
to which being summoned I did appear there;
and the priest being there also he soon fell upon me,
charging me with having printed lies against him in a book,
which he said was almost filled with lies.
I desired him to instance in anyone particular, and prove it false if he could,
before all the people; there being the chief men of three or four parishes.
He would not give an instance; but went on exclaiming against me with a loud voice;
saying I held erroneous principles, and that I denied the Trinity^
footnote:[The Society of Friends always believed
in the "`three that bear witness in heaven:
the Father, the Word, and the Holy Spirit`" (1 John 5:7),
they only objected to calling the Father, Son,
and Spirit three distinct "`persons,`" not feeling free in conscience
to give other names or appellations to the one true God,
than what are given in holy Scripture.]
and the Sacraments.
I answered that I denied no principle of religion that can be warranted by the Scriptures.
But he not willing that I should be heard went on still,
and made a long clamorous speech against me, using many bitter reviling words.
And not satisfied with that,
he in his fury with his own hands violently plucked
my hat from off my head two several times,
in the presence of all the people, and the last time kept my hat from me for a while.
And thus he spent much of the time until he went to dinner,
endeavouring as much as in him lay to render me odious and contemptible,
and to make me a gazing-stock to the whole assembly.
But when the priest was gone to dinner it came in my mind to write a few words,
for the better information and satisfaction of the people; which I did in these words:--

[.embedded-content-document.letter]
--

Whereas I, Oliver Sansom,
have this day been charged by James Anderton with printing lies in a book against him,
and also with holding erroneous opinions,
both which charges are absolutely false and untrue,
as will plainly be made appear if he will but commit them to writing;
and therefore I desire it may be so done.
But if he refuse,
may it not then be justly suspected that he cannot prove what he has charged me with:
let the wise in heart judge.

This is written, that things may be fairly tried, and false reports stopped, by

[.signed-section-signature]
Oliver Sansom.

[.signed-section-context-close]
The 6th of the Second month, 1668.

--

This little paper I fastened to a post in the middle
of the great hall where the Court was kept,
that it might be seen and read of all there present.
And after it had stuck there some time and was pretty well viewed,
one of the company took it down and carried it up to the priest.
And whether it was that he was sensible he had overshot himself and was
not willing to have his false charges at that time further opened,
or that having had his dinner he was in a better humour, I know not;
but all that afternoon he carried himself more quietly
towards me and with a show of kindness.

Mention was made how the priest having taken away my goods for tithes,
some of my relations had made an agreement with him and paid him twenty pounds,
that they might have the disposal of the goods,
and keep the overplus money for him until another time.
One of those relations was Thomas Bunce, my wife`'s father, who some time after,
observing that what he had done had made me very uneasy,
and did but make the priest more greedy after his prey,
was troubled in his mind that he had meddled in that matter;
and being desirous to be rid of that money which was left in his hands
on that occasion and to clear himself from being further concerned therein,
he sent the money to the priest, and with it the following letter.

[.embedded-content-document.letter]
--

[.salutation]
Mr. Anderton,

Whereas there did arise a difference between you and my son-in-law Oliver Sansom,
which did grow to such a height and on your part was managed with such rigour,
that about a year ago you did cause his house to
be searched and took away what money was to be had,
and also seized and drove away all his sheep and cows.
Whereupon I sent my other son-in-law Richard Vokins to assist
my friend John Sansom to make an agreement with you;
fearing lest you should make such a spoil of the goods of the said Oliver,
as might be to his undoing.
And so an agreement was concluded, and you being paid your demands in money,
then the goods (that by your procurement were taken away
as aforesaid) were by you delivered into their hands;
that is to say, to John Sansom and Richard Vokins,
and the said goods being sold did arise to more money than was paid to you for them.
The overplus whereof being now in my hands and I considering
seriously with myself that the man from whom the goods were
taken detains his tithes only upon a conscientious account,
therefore I think he should not be so hardly dealt with;
for sure I am it is contrary to the doctrine and commands of Christ,
which was to love enemies, and to forgive trespasses as we desire to be forgiven.
And it is also contrary to the Apostles`' practice who did not make the Gospel chargeable,
for they testified to them among whom they preached,
that they sought not theirs but them.
And seeing you do profess the Scriptures to be your rule,
I desire you would compare your practice with them.
As for my part I am sorry that ever I meddled with those
goods taken away by you on that account and in that manner;
and I do hereby let you know,
that I do intend never to be concerned in such a business again.
In witness whereof I do herewith return the overplus money back again to you,
desiring I may be as clear before the Lord as I am in doing wrong to you in this matter.

[.signed-section-signature]
Thomas Bunce.

[.signed-section-context-close]
Charney, October 30th, 1668.

--

There was also another letter written to the priest upon the same occasion,
by Richard Vokins; who had been an agent or instrument in the before-mentioned agreement;
and thus it was:

[.embedded-content-document.letter]
--

[.salutation]
Mr. Anderton,

These are to let you know that I intend never to be instrumental any way
in making any more agreements or compositions between you and Oliver Sansom.
For I see it does on the one hand but add grief to his sufferings and
on the other hand it encourages you in your oppression and violent doings.
Therefore I advise you to take heed and look to it;
for he that does wrong shall receive of the Lord for the wrong he has done,
and there is no respect of persons with him.
And besides I may tell you that your dealing with us in
that composition was not like a civil honest man;
for you did beforehand promise to bring a particular account with you to Cheveley
(where we met you) what your demands were that you did sue for.
But when you should have produced it, you shuffled and shifted it off;
pretending a mistake.
However to satisfy us you did then and there punctually promise again and again
that Oliver should have it of you whensoever he would desire it;
and thereupon we did agree and compose the matter with you and paid you money,
so that you had your desire.
But when Oliver did ask you to perform your promise, you did deny him with these words,
'`I have done with that now.`' Meaning, that having got the money you had your desire,
and did not intend to perform your promise.
But I must tell you that if you had not promised,
and covenanted in that manner I suppose we should have made no agreement with you,
however not at that time;
for it would have been unreasonable for us to have paid
you so much money and not expect to know for what,
and why, in the particulars.
And seeing you have dealt so by us,
I have just ground if it be but for that cause to deny any further dealing with you;
for plainly I have not often found the like deceit among the worst of men.

[.signed-section-signature]
Richard Vokins.

[.signed-section-context-close]
West Charlow, October 31st, 1668.

--

These letters were first delivered to my own father,
in hopes that he also would clear himself from being concerned any more
for the future in the controversy between the priest and me.
For my relations meddling in it had been and was a great exercise and trouble to me;
and I laboured with my utmost diligence to prevail with them to engage
themselves from meddling any more in this matter for the future.
And having prevailed with my father-in-law and brother-in-law,
as aforesaid (who both of them were afterwards convinced of the blessed Truth and became
honest Friends and lovers of it;) I besought my own father also to do the like.
But he for a while refused, intending to make a further agreement with the priest;
and for that end sent several times to him to invite him to meet him at
some convenient place that they might treat together about it.
But when he saw that the priest kept off and would not come to speak with him,
he sent to him, desiring a particular account of his demands.

At length the priest sent him a few words in writing after a slight manner,
altogether insignificant as to particulars, and therefore unsatisfactory to my father.

Whereupon seeing himself so slighted and his expectation frustrated,
my father was offended with the priest,
and became willing also to acquit himself of that business;
and thereupon after he had laboured in it near three months,
he sent both the money and the letters,
which he had some time before received from my father-in-law Thomas Bunce,
and my brother-in-law Richard Vokins, (which he had kept till now,
that they might not anger the priest and render him less tractable
in his intended treaty with him;) and together with them,
he sent the priest a few lines from himself also, in these words:

[.embedded-content-document.letter]
--

[.salutation]
Mr. Anderton,

Whereas I have received a paper containing a certain value of tithe of Oliver Sansom`'s,
but nothing in particular nor any name subscribed to it,
I having received of my friend Thomas Bunce the money
that is left of the goods which you took away,
I do herewith send it to you with a letter that came from the said Thomas Bunce,
and also one from Richard Vokins;
intending never any more to have anything to do therein.
So with my love to you, I rest,

[.signed-section-signature]
John Sansom.

[.signed-section-context-close]
January 1st, 1668.

--

My relations having thus (through my importunity) discharged
themselves of this matter it was greatly to my satisfaction.
But when these letters were delivered to the priest,
he was very angry and refused to take the money.
Whereupon the neighbour that carried it to him came
to my house and throwing it down on the table said,
the priest would not have it, and he thought I had most right to it;
and so left it and went his way.

After this, at the time called Easter following,
the people of Box ford (where I lived) being gathered
together in the house they called their Church,
to choose officers for the parish;
the priest took occasion at that time and in that place,
to accuse me in a malicious manner before all the people there assembled;
and spoke also contemptuously against the Truth and way of God,
which I and my Friends made profession of.
Which when I heard of I was much grieved,
and felt a concern lie upon my spirit to write something in answer thereunto,
for the information and good of the people and for the vindication
of the precious Truth from his slanderous suggestions;
whereby he sought to render both it and them that professed it odious to his auditory.
And that which I wrote was as follows.

[.embedded-content-document.epistle]
--

[.salutation]
Friends and Neighbours,

Forasmuch as James Anderton has opened his mouth wide against
the innocent people of God called Quakers in general,
and me in particular; but chiefly against the Truth which we profess;
now it is well known to most of you that his enmity has
been openly manifested towards me both by words and deeds.

Yet he could never justly charge me with evil doing, though he has sought for it;
to the praise of the God of my life be it spoken, who by his grace has preserved me,
and by his own good Spirit has led and strengthened me hitherto;
blessed be His holy name forever.

Now as to what he has charged me with from the printed book,
wherein some of his envious doings are laid open and discovered;
for the truth of what is therein contained you know I need not go far for witnesses;
because that many of you can testify from your own
knowledge that the greatest part thereof is true;
and as to that passage in the latter end of the said book, namely,
that he preferred card-playing before the true worship of God,
you know that in your hearing he said,
that he did prefer card-playing a hundred times before
our meetings for worshipping of God.

Now if it can be proved,
that the true worship of God is in that very way
which we meet together to worship him in,
and in that very way wherein we meet together and
worship God in is the true worship of God performed;
then it is evident,
that he that speaks against our meetings speaks against the true worship of God:
now it can be so proved,
therefore he that speaks against our meetings speaks against the true worship of God.

For proof hereof, First,
we can and do in truth testify that we have the seal
and witness of the Spirit of Christ in ourselves,
that in our meetings we do worship the only true God in Spirit and in Truth,
according to the words of Christ, (John iv.) And therein we do find acceptance with him,
and are also led and guided by the same Spirit to do those things which please him.
And as many as become faithfully obedient thereunto come
to know the effectual working of his mighty power,
to redeem them from the bondage and captivity of sin and death inwardly,
and from a vain conduct outwardly; so as to live soberly,
righteously and godly in this present world.

Secondly.
We do abide in the doctrine of Christ and do keep his commandments;
as might be largely evinced according to the Scriptures of Truth.

Thirdly.
Our meetings are according to the examples of the
Apostles and saints in the primitive times,
who worshipped God in the Spirit and rejoiced in
Christ Jesus and had no confidence in the flesh;
and if anything was revealed to him that sat by, the first was to hold his peace;
that all might be comforted and edified in the Truth.
1st Cor.
xiv. 30.

Fourthly.
We are also come to witness the fulfilling of the Scriptures
which were spoken before by our Lord and Saviour Jesus Christ,
namely, that against his followers,
persecutors would arise who would say all manner of evil against them for his sake;
and that they would cast them out of the synagogues; yes, said he, the time shall come,
that whosoever kills you will think he does God service.

Now see and mark well, whether James Anderton be not exactly here pointed at; as First,
for saying all manner of evil falsely.
Secondly, for excommunicating or casting out of his synagogue.
And Thirdly, for putting to death, if he had power to his will.
For he has told me in plain terms, that if the king would but grant a law,
he would be the first man that would set a fagot to my tail.
A sure sign that he is not a true Christian, not a follower of Christ Jesus.
For we have the express testimony of the Apostle Paul,
that all who will live godly in Christ Jesus shall suffer persecution; not persecute,
but be persecuted.
And as the Christians of old had these things done unto them,
so we have now the same done unto us; and that for no other cause but for godly living,
innocent walking,
and bearing our faithful testimony for the truth
and worship of our God against all false worships.
And like as they of old did,
so we now for the same cause do take joyfully the spoiling of our goods;
knowing in ourselves that we have in Heaven a better and more enduring substance.
So that we are not terrified by our adversaries;
"`Which is to them an evident token of perdition; but to us of salvation,
and that of God.`" Phil. 1:28.

So it is clear, first, by the witness of the Spirit of Christ in ourselves,
(see 1 John 5:10) and by our lives and conducts whereof the fruits thereof appear.
Secondly, by our keeping the commands of Christ.
Thirdly, by our exercise and practice in our meetings.
And Fourthly, by our sufferings for righteousness sake,
that our meetings are of God and that the worship
performed therein is the true worship of God.
And therefore whosoever speaks against our meetings
and worship speaks against the true worship of God.

And whereas he says we are worse than the papists;
I know no ground he has so to say or think, unless it be for this;
that the pope and papists first set up the anti-christian yoke of tithes
in this nation for the maintaining a company of priests in ease,
idleness, pride and fulness, to the great oppression of the people.
And now the Lord has raised a testimony in the hearts of his people
against all such false ministers and deceitful workers,
so that we cannot put into their mouths;
for which cause they have prepared war against us.
But it is not to be wondered at if these men (whose god is their belly,
and who mind earthly things) do so kindly remember their father the pope,
for having left them this sweet legacy of tithes, and prefer him far before us,
who would have them live as did the ministers of Christ in the primitive times,
who preached the gospel freely,
and did receive no more than what was necessary for food and raiment,
and were therewith content;
which also was freely given them by those that received and owned their doctrine;
as may be seen at large in the Scriptures of Truth.

And as for all his other accusations which he in a clamorous manner vented against us;
surely he had no more ground for them than his forefathers,
the priests and persecutors of old, had against Christ and his followers.

And now I may say, as the apostle Paul once did to his persecutors,
that after the way which this priest calls heresy,
do I (with many more) worship the living and true God;
believing all things that are written in the Holy
Scriptures which do bear testimony of Christ Jesus,
the true Light, in whom I have believed;
being freely given up to follow him through the many tribulations,
hoping to keep the word of his patience, even unto the end.
And then I have an assurance,
that he will keep me in the hour of temptation and in the day of trial,
which will come upon all that dwell on the earth.

And unto all you, my loving neighbours, is true love in my heart,
with earnest desires that you would consider your own states and standings,
every one of you, whether you are not in the broad way.
For plainly I testify to you in the fear of the holy God,
that James Anderton your priest is not in the way that leads to life;
and if any of you do think to receive any good or benefit to your souls from his ministry,
you may as reasonably expect to gather good fruit from an evil tree; which Christ said,
could not be.

Wherefore in Christian love to your souls I write this,
to warn you not to trifle away your precious time;
but turn to the Life of Christ and the manifestation of the Holy Spirit,
which is the gift of God, shining in your own hearts and consciences,
which will reprove for and condemn sin in your mortal flesh,
and through believing will lead you out of sin into a state of acceptance with God;
in which continuing, through obedience,
you may come to be redeemed from the bondage of corruption,
and be brought into the glorious liberty of the children of God,
who are all led by his Spirit.

I am a real friend to all tender-hearted people but a living witness against deceit,

[.signed-section-signature]
O+++.+++ Sansom

[.signed-section-context-close]
The 28th of the First month, 1669.

[.postscript]
====

P+++.+++ S. If James Anderton or any other has anything to charge us with,
who are in scorn called Quakers,
let it be produced in writing openly to the view of all sober people;
and they may expect a sober answer in plainness.
And so let them and us be tried by the Scriptures of Truth;
and whoever is found guilty of error, let him be censured accordingly.

[.offset]
"`Prove all things; hold fast that which is good.`"

====

--

I appointed my man to read this foregoing letter in the audience of the people,
when they came forth from their worship,
the next first-day after the priest had so despitefully clamoured against me,
as is before expressed.
The priest it seems was gone that day to his other quarter;
for he had two places or quarters from which he sought his gain.
And as my man was standing in my garden,
which adjoined to that which they call the churchyard,
and began to read my letter to the people as they came forth, who thronged near to hear;
it so fell out,
that at that very instant the priest himself came
home from his other shop or place of trading-worship;
and seeing the people soberly giving attention to what my man was reading,
he hasted there himself also, and pressed near to the place where my man stood.
And at first, in a deriding manner he put off his hat,
endeavouring with mocks and scoff`'s to raise up lightness in the people;
and often interposed questions to interrupt the mart in his reading.
But when he saw all that would not do,
and that he could not baffle or hinder the one from reading nor the others from hearing;
he then, in a sort of furious madness leaped at my man,
and having torn the paper out of his hand rent it in the midst.
Then told my man, he had behaved himself honestly hitherto;
but if he would do such knacks as this, he should go to prison.

Though the reading this paper (so far as it was read)
unto his hearers angered the priest for the present;
yet he grew quieter upon it for awhile, so that for some months he said little to me;
but afterwards, his belly still craving, he would take occasion often when he met me,
to threaten me with a prison if I would not pay him tithes; and in the eleventh month,
1669, seeing me in the street, he told me,
he had favoured me the longer because of the cold weather, but now,
if I would not pay him, I should be sure to go to prison.
Whereupon I asked him, how his heart could be so tender as not to hurt me with cold,
and yet could burn me with fire, as he had formerly said.
Then he seemed to warn me and threatened me before a witness, that if I did not pay him,
I must expect to go to prison; and desired me not to take it ill,
I told him I could not take it as from a minister of Christ;
for I never read that any of them did ever go to law for their wages.
So in the conclusion, he seemed to carry himself more smoothly than formerly,
with feigned words pretending to pity me and the like.
But I having a sense of his dissimulation and deceit,
felt a concern upon my spirit to write some lines as a warning to him;
which were as follows.

[.embedded-content-document.letter]
--

[.salutation]
James Anderton,

I have considered of your warning or rather threatening of me yesterday.
And in the consideration thereof, there did arise a word in my heart,
as a warning from the Lord to you; that you take heed what you do unto me;
for the Lord Jesus, the righteous judge, in the dreadful day of account,
will reckon it as done unto himself.
Because he, by his pure light has let me see, that the work and ministry which you,
for filthy profit`'s sake, have crept into, is not of God,
neither were you led into it by the good Spirit of the Lord, but by the contrary spirit,
which does always resist the Spirit of God, and despises his light in the conscience.
And the Lord has not only let me see this;
but has raised me up to bear a testimony for his Truth,
against your deceit and hypocrisy.
And this is to certify you, in God`'s fear, from my very heart, that I cannot,
neither dare I, pay you wages, which unjustly you do claim,
for fear of offending the Lord God, who has given me life.
I tell you plainly, I had rather die the sharpest death that can be invented,
than willfully to grieve the good Spirit of the Lord
and rebel against his light in my conscience.

And this is further to let you know, that Jesus Christ, the Light of the world,
that enlightens every man that comes into the world, even He is my strength and my stay;
yes, He alone is my hope of glory; and by His power it is,
that I do stand this day a witness on his behalf for his blessed Truth,
in opposition to your ways and practices.
And seeing what I do herein is not of myself but by him alone;
therefore whatsoever you do against me in this matter,
he may justly impute it as done unto himself, (read Matt,
xxv.) for he alone is both the Author and Finisher of my faith,
and also the defender and preserver of me in it.

Therefore in tender love to your soul,
I advise you to be warned and to take heed what you do;
and repent and turn to the Lord and obey his light in your conscience,
while his Holy Spirit strives with you; lest your day pass over and you are cut off,
and there be no remedy for you.

Written by one, unto whom, through the mercy of the Lord,
it is given on the behalf of Christ,
not only to believe but willingly to suffer for his sake.

[.signed-section-signature]
O+++.+++ Sansom.

[.signed-section-context-close]
The 14th of the Eleventh month, 1669.

--

This letter I sent to his house by my man;
and the priest being then in his chamber was called down,
and the letter delivered to him, who with a fierce and wrathful look took it in his hand,
threw it back into the man`'s face; and turning about,
ran up stairs again without speaking one word.
At which strange deportment of his, they of his own family that beheld it,
seemed to be astonished.
But my man came away and left the letter there; which,
as the priest`'s children reported, was afterwards burnt.

About a month after this, I met both the priest and his wife on horseback,
on the highway, near unto a gate, which I opened for him; and the weather being cold,
he said to me, "`Honest Oliver,
you may pray for the continuance of this cold weather to keep you out of jail.`"
I asked him, why he threatened me with a jail, seeing he confessed to my honesty?
"`Surely,`" said I, "`the jail was not made to confine honest men.`"

But my honesty could not secure me against this priest`'s dishonesty and cruelty.
For shortly after this, having procured an order against me,
he sent it to the bailiff of Lambourn, who was then to go to the court session,
desiring him to come early in the morning,
to arrest a man who he did believe would bear him company to Reading.

The bailiff came accordingly and brought his man with him;
and they taking the priest`'s son with them to direct them, waited for me,
and as I passed along the street laid hold of me;
and the priest having counselled them before not to trust me,
the bailiff would hardly allow me to go into my house to put on other clothes;
yet at length he did let me go in, himself and his man going in with me.
So while I was making myself ready, I caused the bailiff and his man to eat and drink;
and then being ready to go with him, my dear wife and I kneeled down and prayed together,
committing each other to the Lord, and so took leave of each other,
knowing it was for the Lord`'s sake alone that we were thus parted asunder.

Meanwhile the priest`'s own horse was made ready to carry me to prison;
and he himself with his wife and children came into the street,
to behold me carried away;
and he scoffingly said he would have me remember to carry a pen and ink with me;
for he thought I might have leisure now to write more books.
Truly I was grieved in my spirit to see him harden himself so in
his wickedness and in his rebellion against the Lord and his Truth,
and even against the light in his own conscience;
which I was sensible had at some times reached unto him,
and in some measure opened his understanding.
Wherefore just before I got upon the horse I made a little stand;
and fixing my eyes earnestly on him, in the dread of the Lord I thus spoke unto him:
"`James Anderton, if you had done this ignorantly as not knowing what you did,
then I could have besought the Lord to forgive you; but seeing you do it willfully,
against the light of your own knowledge, I have now only this to say,
the Lord look upon it and require it.`"

Having said this I sat on horseback and was conveyed to Reading jail,
on the last day of the twelfth month, 1669,
where I was kept a close prisoner two full years and upwards.
In all which time I never saw my own habitation, nor indeed as much as desired it;
but rested satisfied in the will of my heavenly Father;
being willing to drink that cup which he had appointed for me.

[.offset]
+++[+++The following letters are here inserted according to their dates,
having been written from Reading jail during this imprisonment.]

[.embedded-content-document.letter]
--

[.salutation]
My dear Wife,

These are to let you understand that I am well; praised be the Lord over all forever.
Has made hard things easy and bitter things sweet unto us; so that we feel his yoke,
who is meek and lowly in heart, to be easy and pleasant unto us,
so that we have even our heart`'s desire.
The Lord has wonderfully preserved us when men rose up against us,
and did spread and furnish our table in the sight of our enemies.
Oh let us not forget His manifold mercies, nor let his benefits slip out of our minds,
for He has done that for us that none other could do;
therefore let us with all diligence look to the Lord with a single eye at all times,
and wait upon Him to receive of his counsel to guide
and direct us at all times in all we take in hand;
that whatsoever we do, it may be to His praise and glory, who alone is worthy over all,
blessed forever, Amen.

My dear love is to you and also to T. V. (Thomas Vokins) and I desire
that your conduct may be without covetousness and such as becomes Truth,
that you may be a good savour unto God and all people,
both in your buying and selling and in your ordinary communications,
that you may be serious, sober, meek,
and quiet towards all and one towards another in the fear of the Lord;
and never heed the frowns of the enemy nor the threats of the adversary,
for none can harm us if we follow that which is good.
So with my entire love to you all,
and desiring your preservation and perseverance in the precious truth,
which is more to be prized than all things else besides,
therefore hold it fast and sell it not.
I desire to have my dear love to Katharine Evans,^
footnote:[Katharine Evans was the wife of a Friend named John Evans, who lived near Bath,
"`a man of considerable estate,`" who bore a good testimony to the Truth,
and was on that account several times imprisoned.
In 1664, he laid down his life in prison, for obeying our Saviour`'s command,
"`Swear not at all.`"
{footnote-paragraph-split}
Katharine Evans
and Sarah Cheevers were among the earliest Friends who visited Scotland,
being there in the year 1654.
In 1657, "`for exhorting the people to repentance,`" at Salisbury,
she "`was stripped and tied to a whipping-post in the market and there whipped.`"
She "`travelled in many countries, and suffered much for her testimony.`"
In 1658, she with Sarah Cheevers went towards Alexandria,
but the ship putting in at Malta, the Friends going ashore were soon taken up,
and suffered a dreadful confinement, for about four years in the inquisition;
of which an account is published.
{footnote-paragraph-split}
After their return to England,
they travelled in the service of Truth, and went through England, and Ireland.
In the year 1664 (in which her husband died,) she and Sarah Cheevers, her companion,
were imprisoned at Wirdscombe; and in 1666, she was imprisoned in Welshpool,
Montgomeryshire.
{footnote-paragraph-split}
She was
almost constantly engaged in her Master`'s service,
and private records alone tell of most of her devoted labours.
It appears from the above letter, that at its date, 1670,
she was travelling in the ministry in and about Berkshire.
{footnote-paragraph-split}
In 1682,
we find her among the Friends suffering a cruel imprisonment in Newgate, in London,
where indeed she appears frequently to have been;
"`she was also among the 116 Friends who suffered imprisonment at Bristol,`"
when meetings were kept up in that city by children only,
under 16 years.
"`After many adversities and great sufferings, having lived to a great age, she died,
and so entered into everlasting rest.`"
Her decease was about the fourth month, 1691.]
and do accompany her as much as you may;
my love is also to A. H. and S. L. and to friends as you are free.
I desire to have my love remembered to Martha Weston, and to friends at Care and Newbury.
I intended to send a copy of the observations upon the Act, but I could not have leisure,
for I have been very much employed of late,
and I would have Robert Wilson to borrow Ann Head`'s copy,
and let him and John Normanton write as many as they can,
for they may be very serviceable, and let William Austell of Oare do the like.

Mind my dear love to them.
I desire that John Wightwick may take care that this
enclosed letter be safely delivered as it is directed,
and let him keep the paper that I gave him a week longer before he make it public.
So with dear love to every honest heart, farewell,

[.signed-section-signature]
O+++.+++ Sansom.

[.signed-section-context-close]
Reading Jail, 4th of Third month, 1670.

--

[.embedded-content-document.letter]
--

[.salutation]
My dear Wife,

In the pure living Truth, which changes not, does no love truly reach forth unto you,
earnestly desiring your growth and perseverance therein in the true fear of God,
which keeps the heart clean and single to the Lord at all times.
Dear heart, by this you may know that I am pretty well,
and S. B. his dear love is to you, and to J. W,
and A. H. and T. V. But some of us are pot well,
for Joseph Phipps was taken ill yesterday and Thomas Curtis
and Christopher Cheeseman and Anthony +++_______+++ are not well.
So having not much at present but my dear and entire love unto you all,
desiring that you may all with one heart and mind keep single
and watchful in the pure light of the Lord,
that no one of you may lose ground nor lose any part of
that good state and condition unto which you have attained;
for a good state and condition may be soon lost if the watch be not truly kept.
Therefore take heed and hold that which you have gained,
and press forward in the heavenly race with patience
and meekness in the true fear of the Lord.
And keep in the diligence, and out of that which seeks itself or its own ease;
but in the cross of Jesus continue,
even in that cross which is the power and wisdom of God,
wait to be preserved and kept unto the end; which is the desire of my life for you all,
as for my own self, and remain, your dear husband.

[.signed-section-signature]
O+++.+++ S.

[.signed-section-context-close]
Reading Jail, 26th of Fifth month, 1670.`"

--

[.embedded-content-document.letter]
--

[.salutation]
My dear Wife,

My dear and tender love does truly reach forth unto you,
and in the singleness of my heart does truly salute you,
earnestly desiring and daily praying in the sincere breathings
of my life that you may be preserved single and sincere,
daily growing more and more in the pure, tender,
meek and lowly spirit of our Lord Jesus Christ,
and that the precious fruits thereof may more and more appear
in your life and conduct to the glory of the Father.
Herein is my Father glorified, (said Christ) that you bring forth much fruit.

Oh that you did feel the blessed operation of the
pure Spirit and Power of the Lord Jesus,
that your heart and mind might be thoroughly cleansed
and purified thereby from all sin and iniquity,
and from all vain and wandering thoughts;
that you might sensibly witness that to be removed and separated from you,
which would separate you from the Lord;
that in true stayedness of mind you may wait upon the Lord,
and watch against every appearance of evil,
striving with all your might in the strength of the Lord against
every thought that inwardly arises to hinder you from enjoying
the sweet refreshment of the presence of the Lord of Life.
For truly the watch must be duly kept at all times, with prayer in the Holy Spirit,
or else the thieves will get in and the enemy of your soul will prevail with his temptations.
But if you do abide watchful, with your heart poured forth in prayer to the Lord,
he will surely arise and deliver,
and make way for you to escape all his subtle snares and baits,
and if you do abide in patience and well-doing waiting on the Lord,
you will witness his power to arise that will tread down Satan under your feet.

My dear love is to Richard Daniels, and Alice Glover, and Thomas Vokins,
earnestly desiring and breathing unto the Lord for you all, even as for my own soul,
that you may be preserved in cleanliness of heart and clearness of mind,
being wholly given up to serve the Lord in sincerity and uprightness of heart;
that you may patiently pass the time of your sojourning here in humility and godly fear.
And so the God of peace and love be with you,
and fill you ail with joy and peace in believing.
My dear love is to Friends at Oare, Newbury, and at Woodlands, and in the Vale.
I would have you remember me dearly to your sister,
and let her know that I received her letter and was sweetly refreshed
in the sense of the love of God which is manifested in and through her;
and although I have been hindered from coming that way,
my love and union with her and all the upright in
heart in the living Truth is not at all straitened,
but does remain in a living remembrance.

I believe the Lord will make way for me when my coming will be most serviceable,
for unto Him who is strength in weakness and a very present help in time of need, yes,
I say, unto Him who is become unto us as a fountain open, and as a place of broad rivers,
(though unto the wise of the world as a spring shut up and as a fountain sealed;) to Him,
I say again, be the glory and the honour, with all true and hearty obedience,
for he is worthy forever and forever more.
So desiring that we may remember one another in our
breathings and requests unto the Lord,
in tender love I bid you ail farewell.

[.signed-section-signature]
O+++.+++ S.

[.salutation]
And this to Friends:

Let every one of you be diligent to follow your own business in the fear of God,
and meddle not with that wherein you are not concerned;
and although your hands are employed in your labour, let your hearts be after the Lord,
meditating continually on his goodness and his large
lovingkindness and his tender mercies,
with which he visits us morning after morning, and evening after evening,
and also at noon day; he has never failed to do us good.
Oh! that the sense of the rich love of our God might always remain upon our spirits,
that as his tender mercies are daily renewed unto us,
so our thanksgiving and sincere obedience might be
returned unto him from the bottom of our hearts,
which is his due forevermore.

Oh let us never forget the Lord our God, who has been so good to us,
but let him be always the first in our thoughts at our uprising,
and the last at our lying down, and let our meditation be of Him all the day;
for from the rising of the sun to the going down
of the same the Lord`'s name is to be praised.
He alone is worthy of all, who is over all.
King of kings and Lord of lords,
who is able to do for us far more abundantly than we can ask or think;
to Him be the praise and honour ascribed, for His is the kingdom,
the power and the glory forevermore.
Amen.

[.signed-section-context-close]
Reading Jail, 7th of Ninth, 1670.

--

[.embedded-content-document.letter]
--

[.salutation]
My dear Wife,

My dear, tender,
and entire love does truly flow forth unto you in the living
sense of the tender mercy and infinite love of our God;
whereby the day-spring from on high does daily visit and refresh
the souls of all those that faithfully wait for it,
so that they do grow and flourish as trees of righteousness,
even of the Lord`'s own planting, that he may be glorified.
Dear heart, my love does truly reach forth unto you all,
and you are often in my remembrance,
and the sincere desires of my heart are daily for you all, even as for my own soul,
that we may all be preserved single and sincere to serve the Lord,
and to follow him fully in this our day and generation,
and to be at all times given up in our hearts unto him,
to do those things that are acceptable and well-pleasing in his sight.
I desire and exhort you all to be watchful and careful,
so as to adorn the profession of the blessed Truth
with a right honest and unblameable conduct,
even without covetousness and eagerness after the things of this world;
but let us with one heart and one consent, do that which may advance the Truth,
and be a good savour therein,
unto the witness of God in the hearts of all with whom we have to do;
that our light with which we are enlightened, may so shine before men,
that they may see our good works and glorify our Father which is in Heaven.

My love is dearly to your sister in the living truth,
and in the living sense of the same she is often in my remembrance,
making request with joy in a living hope,
that the Lord will raise her up as to the outward,
and make her further serviceable unto his truth and people,
unto the which I desire we may be given up in the uprightness of our hearts,
and may daily wait for the renewing of the right spirit in every one of us more and more,
and feel a being gathered into it, so as to be led and guided by it.
So in that which is meek and lowly, my love is to and with you all,
and also unto every upright heart and faithful friend, as if I named them particularly.

[.signed-section-closing]
I rest your dear husband,

[.signed-section-signature]
O+++.+++ S.

[.signed-section-context-close]
Reading Jail, 12th of Second month, 1671.

--

[.embedded-content-document.letter]
--

[.salutation]
My dear wife.

In true, tender, and entire love to you,
and to Richard Daniel do I write these following lines, as a word of advice;
that you may stand faithful and single in your hearts to the Lord,
in that testimony for the Truth concerning tithes, for which at this day, I suffer bonds.

I desire you to observe when any corn is marked or
set out for the priest you be sure to go,
before they do fetch it away, and set it, * * * * * +++[+++word not clear]
and unmark it, and this will stand as a faithful testimony for the Truth,
although they steal it away afterwards, and see that you do unmark it,
and in the authority of Truth tread the pope`'s marks under foot openly.
But take heed and keep low in your minds; that in the spirit of Jesus,
you may stand as witnesses for his pure Truth in this your day, in meekness and humility,
and in the pure fear of the Lord will your testimony be acceptable unto him;
and watch against that spirit that would desire revenge,
or use force or violence to keep it through covetousness;
and let all that you do be done in the obedience of Truth,
and for no other end than to glorify the Lord our God,
and that our testimony may be acceptable in his sight.
And take no thought as to hurry or hurt, or hasten overmuch,
but let your eve be to the Lord in all things,
and he will preserve you clear and clean in your testimony, and make it easy to you;
for all that come to`' Christ who is meek and lowly in heart,
can witness that his yoke is easy and his burden is light; and all those, and those only,
do find rest and peace to their souls.

So desiring that every one of you may watch over your thoughts, words, and actions,
that in the pure fear of the Lord you may always abide,
and therein be preserved to order your conduct aright to his praise and glory,
who alone is worthy by us all to be praised and glorified above all,
who is God over all in heaven and earth, blessed forevermore.
Amen.

[.signed-section-closing]
I remain your dear husband,

[.signed-section-signature]
O+++.+++ S.

[.signed-section-context-close]
Reading Jail. 12th of Seventh month, 1671.

--
