== Chapter III.

[.chapter-synopsis]
* His losses while imprisoned
* Address and queries to his neighbours
* Letter to the Priest
* Death of the Priest
* His religious experience and firmness in his testimonies
* Thoughts of removal from Boxford
* Letter to the new Priest
* Two letters to his wife
* Sufferings by the priests widow
* Letter to her
* Continued troubles
* Two letters to the Mayor of Newbury
* Objects to employ an attorney to defend his conscientious scruples.

Now in this time of my confinement, the greedy priest took away my goods by force;
what and how, as he pleased.
Of which I received the following account from my man that then lived with me,
whose name was John Wightwick.

[.embedded-content-document.letter]
--

[.blurb]
=== An account of the proceedings of Priest Anderton, and his man, Lodowick Yeomans, for the tithe of my master Oliver Sansom`'s living, while he was kept a close prisoner, in the year 1670.

About the middle of the fourth month, we having made our hay,
Lodowick Yeomans with James Basford and his man came
into the mead very early in the morning,
before we were got there, and carried away a load of hay;
and towards the latter end of the same month they came again for another load;
and as they were loading it, I being then there, I asked them,
"`By what authority they did it?`"
Lodowick said.
"`What`'s that to you?`"
I told them it was to me as I was entrusted with my master`'s business;
and that I did look upon it to be no better than theft.
But for all that they carried away the hay.

And on the 28th day of the fifth month, we having reaped two acres of wheat,
and set it up in shocks, Lodowick came and threw it all down;
and with the priest`'s other man began to set up a shock across the land,
in the manner as they usually set their lithe-shocks.
Whereupon I came to them and asked them if they would
set up the corn again which they had thrown down?
Lodowick said, "`No: you m may set it up yourself if you will.`"
And further he said.
"`Now I have set out the tithe, if you, Wightwick, do touch it,
you shall be whipt or burnt in the hand.`"

On the morrow we went to fetch home the corn,
and when we came to the cross-shock we began to take it up;
but Lodowick being not far off came and bid me throw it down again, or he would make me.
I told him I should not do so;
whereupon he threw it down himself and guarded it all that day.

On the next day we came to another land, and when we loaded and bound our load,
Lodowick came and bid me throw down his sheaves, I told him he had none there.
He said he would not dispute that.
But he pulled out his knife and went to cut the cart-rope;
threatening if anyone did move the horses, he would knock him down.
So he did cut off the rope in two places and threw down the load;
and said he would make us let it stand in the field, until they did make their rick;
yet they carried it away the same day.

On the 6th day of the sixth month we went to carry some oats;
and after we had taken them up and were gone away to another land,
Lodowick came full of envy and fury and began to cut our traces;
and said he did intend to do so before harvest.
So he cut off all our harness on one side;
and threatened that next time he would cut the cart.

On the 10th of the sixth month this same Lodowick went with
James Basford`'s cart before us and took up our barley,
what he pleased.
And on the next day we went to carry some fitches
upon the same land where our harness had been cut;
where were also some oats left, which Lodowick had thrown off the cart at that time.
So we took up the oats and the fitches, and Lodowick said,
he would make us carry it to the parson`'s. And as we were to pass by the priest`'s gate,
Lodowick stopped the horses, and beat them about the heads,
and punched him that led the fore-horse.
And with the noise that was made, the priest came forth; and my dame told him,
he made a great ado for his belly.
So they forcibly took away the horses, cart, and corn,
and drew it into the priest`'s barn; and when they had taken off what corn they pleased,
they turned out the horses and cart into the street again.

[.signed-section-closing]
This is attested to be a true account, by me,

[.signed-section-signature]
John Wightwick.

--

As thus the priest dealt with me this year, so he continued to do in the next year, 1671.
For at shearing-time he took from me by violence ten fleeces of wool;
and in hay-time he took away my hay, as before.
And in harvest, when my wheat was all reaped, and set up in shocks,
his man Lodowick came, and scattered the sheaves all about the land;
and having brought a cart, he carried away what he pleased;
leaving the rest in that condition as he, in his envy and madness,
had scattered it about.

While thus the priest kept me in prison and made havoc of my goods;
it arose in my mind to write to my neighbours,
to put them upon considering what spirit their teacher
(whom they heard and followed) was of,
who brought forth such evil fruits as these.
This letter I sent to my wife,
and she took an opportunity to deliver it to the people
as they came out of their worship house on a first-day.
This enraged the priest, that meeting my wife soon after in the street,
he reviled her much, and told her,
if he had been there he would have laid her by the heels.
Of that letter the copy here follows, thus directed.

[.embedded-content-document.epistle]
--

[.salutation]
To my loving neighbours, dwelling at and near Boxford, These.

All you my neighbours who are inhabitants in Boxford and Westbrook and the parts adjacent;
even all such of you more especially who sit under James Anderton`'s ministry,
and uphold him therein by paying him wages;
I desire you to judge by his fruits whether he is a minister of Christ or of antichrist.
For Christ Jesus said, "`By their fruits you shall know them.`"

It is not unknown to most of you,
how he has dealt with me for these six or seven years`' space,
which is too long here to be expressed; how furiously, enviously,
and wickedly he has proceeded against me, and all tor filthy profit sake,
because for conscience sake I could not pay him wages;
but in obedience to the Lord was constrained often to testify,
that his work and ministry was not of God, but by the traditions and inventions of men,
contrary to God.
And for denying his work and ministry, and refusing to put into his mouth,
he has prepared all this war against me.
And if, with a single eye, you do but view his actions,
I know you cannot but confess and say with me,
that he is one that serves not our Lord Jesus Christ, but his own belly;
and surely his reward will be according to his works.
And I would have you all to know,
that my refusing to pay tithes is purely a matter of conscience to me;
and I do it in obedience to the will of the Lord, which I dare not gainsay;
and not out of willfulness or obstinacy or for any covetous end.
And that you may be satisfied in this thing,
I have propounded some queries for you to consider of, and your priest to answer.
They are as follow:

Query 1. Whether to pay tithes or to receive tithes
be not a denial of Christ`'s being come in the flesh;
seeing he came to put an end to the first covenant
and priesthood who only were to take tithes?

Query 2. Whether when Christ did come and change the priesthood,
he did not also disannul the commandment whereby tithes were to be paid?
see Heb. 7:12-18.

Query 3. Whether Christ gave power to any pope or prince to set up tithes again,
after he had disannulled them?

Query 4. Whether there be any Scripture, in all the New Testament,
that gives the least intimation,
that tithes were or should be the maintenance of the gospel ministry,
after Christ`'s disannulling them?

Query 5. Whether they that are true gospel ministers,
do not receive a gift freely from Christ, whereby they are made able ministers;
as the Apostle says, "`As every one has received the gift, so let him minister the same,
as good stewards of the manifold grace of God?`"
1st Peter iv. 10.
But they that minister by human learning or natural parts,
without a gift from Christ;
having got a form of knowledge and of godliness without the true power,
are such as the Apostle Paul said should come in the last days,
whom he warned the true Christians to turn away from, 2nd Tim.
iii. 5; and are not such to be turned away from now?

Query 6. Whether they that receive a gift from Christ and minister therefrom,
ought not to do it freely?
"`Freely you have received,
freely give,`" said Christ to his ministers and messengers whom he sent forth to preach.
Surely, as the gift of God is free, so the exercise of it ought to be free;
and not to be sold for money.
God is a free giver and sends his gospel freely;
he did not intend that people should be compelled to pay for it.

Query 7. W`'here the gospel is preached freely,
and people`'s hearts are reached and opened by the power thereof;
can they do otherwise than love that minister who ministers spiritual things to them?
And is it possible but that in this love they should minister outward things to such?
Thus they that preach the gospel may live of the gospel;
the gospel which is the power of God opening people`'s hearts,
and inclining them readily to communicate to such what is needful and convenient.
But should the ministers of the gospel live of the gospel?
or of a law forcing maintenance from men against their wills?

Query 8. Did Christ ever intend that his ministers should be maintained
by men of this world who despise him and his message and walk in looseness;
yes some of them in all manner of wickedness and profaneness?
Or did he intend that they who fear him and love him,
and refuse to pay tithes or other maintenance in true conscientiousness
unto him should be forced to it by laws and penalties?
Is this of Christ?
or came this from the pope who with his ministry has departed from the way of Christ,
and set up inventions of his own?

Query 9. Is not the gospel a gospel of peace, love and gentleness?
Should not the ministers of it be such?
Should they strive?
Should they provoke men?
Should they contend about their maintenance, and make the gospel burdensome to any?
Where men`'s hearts are opened and they give freely, there it is not burdensome;
but where men are forced (some against their wills, others against their knowledge,
belief and conscience) to maintain and uphold that which they know is not of God;
is not that burdensome?
does this at all become the gospel or ministry of Christ?

Query 10. Had not we better give our testimony against this false
ministry and against this false way of maintaining it by tithes,
which Christ put an end to; and so confess Him in His priestly office,
which stands forever, and in his ministry and ministers,
which minister by a gift received from him and minister freely not for filthy profit;
than be condemned by Christ, for owning them and denying Him.

Truly, I had rather suffer the loss of all my goods and endure imprisonment all my days,
than deny Christ here before men in paying tithes,
and owning a ministry which I know is not of him;
and so to be denied by him before his Father.
For I am satisfied in my heart, as in the Lord`'s sight, that if I should pay tithes,
I should be denied by Christ, my Lord and Master,
in whom alone I expect and am assured of salvation,
through faith in his name and in obedience to what he requires.
But they that obey not his Gospel which disannulled tithes,
on them will he reveal and execute wrath, 2 Thess. 1:8.

Consider of these things seriously, in the fear of the Lord;
and require your priest in plainness to answer according to the Scriptures of Truth,
and send his answer in writing to me.
For I do hereby declare, that if he can make appear by the Scriptures of Truth,
and by the examples of Christ and his followers therein recorded,
that Christians ought to pay tithes; I say, if he can make this appear,
by sound words which cannot be condemned,
then I shall be content not only to pay tithes for the time to come;
but whatsoever I have kept back in the time past, to restore sevenfold.
But if he refuse to answer these queries plainly, according to the Scriptures,
and show the rule of his maintenance therefrom; then let him not for time to come,
call the Scriptures his rule any more:
but let him go to the pope and claim his tithes by his rule;
for the pope and his popish princes were the first
that made laws to compel Christians to pay tithes.

It is in love to you and for your souls`' sake that I have written these things,
otherwise at this time I had been silent; for I am satisfied in my testimony,
that it is for the Lord;
to whom I have committed my cause and who has hitherto preserved me,
all holy praises be to Him forevermore;
and I know that in his due time he will deliver me.
So in his love I rest and remain A true friend to all your souls,

[.signed-section-signature]
Oliver Sansom.

[.signed-section-context-close]
Written in Heading Jail, the 25th of Fifth Month, 1671.

[.postscript]
====

Where I endure imprisonment,
for bearing witness for the Lord against the false shepherds,
who feed themselves but not the flock; and by violence tear their wool from off them.

====

--

This is that paper which so enraged the priest, that he let loose his unruly tongue,
in reviling language and threats upon my wife for delivering it;
though not to him but to the people.
But he would not be persuaded to answer it.

I was still kept a close prisoner upon the priest`'s suit for tithes,
and he had often said I should never have my liberty
but should lie in prison till I rotted.
And to make the more sure of me,
this wicked priest had procured an order (_de excommunicato capiendo_)
to be taken out and served on me while I was in prison;
that having two strings to his bow, if one of them should slip or break,
the other might hold me fast still.

In this both the enmity and subtlety of this priest appeared;
for hereby he both strengthened my bonds,
and cunningly but falsely excused himself to his people.
For when any of my neighbours did at any time speak to him on my behalf (which
every now and then one or other of them did) desiring him to set me at liberty;
he would wipe his mouth and tell them,
that I was not his prisoner now but the king`'s upon a order of excommunication;
for said he,
though I did indeed send him to prison yet it is not I that continue him there now.
But this shift of his by which he thought to hide and cover his deceit,
did serve to lay him and it more open and naked afterwards.

For after I had been confined more than two full years,
a close prisoner (not having seen my outward habitation
in all that time) a declaration came forth from the king^
footnote:[The King`'s patent or pardon is referred to in [.book-title]#The Christian Progress,
etc. of George Whitehead#, and a copy of it given at page 351 of vol.
8th of Friends`' Library.
The original contains the names of 491 Friends,
most of whom had long laid prison and were now to be liberated;
among them are Thomas Curtis, Christopher Cheeseman, Samuel Burgis,
Oliver Sansom and others, whose names appear in these pages.]
to suspend the penal laws;
and thereupon it was expected that all prisoners
upon the account of religion should be set at liberty,
except those that lay for tithes.

Now had I freedom to ask the jailer, which in all that time I had not done before,
to grant me a few days liberty to go home; which he readily granted,
provided I would go privately; but that I could not accept of.
Wherefore I told him, if he would not allow me to go home as openly as I came from home,
I must be content to stay in prison until way should be made for my enlargement.
When the jailer heard me say so, he gave me leave to go home as I desired.

It was about the middle of the day when I came to Boxford, the place of my habitation,
and I going openly through the town, many of my neighbours seeing me,
came running to welcome me home; and said, they were glad to see me at liberty.
I told them I was not yet released from my imprisonment;
but that it was likely I might be in a short time, if their priest did not withstand it.
Some of them said, they were confident he would not keep me in prison on his account;
and then related to me the words which they had heard him say to that purpose:
that though he had sent me to prison, yet he did not continue to keep me there.
When I heard that and had well considered of it,
something came upon my mind to write to the priest after this manner.

[.embedded-content-document.letter]
--

[.salutation]
James Anderton,

You may remember that above two years since you did
cause me to be arrested and cast into prison,
where I have remained more than two full years in close confinement;
which is not a light nor a small matter.
For I tell you truly, that not any thing nor all things that this world can afford,
if they were offered me, could have induced me to have endured it.
But I submitting to it in true tenderness and conscientiousness
towards the Lord God of my life,
and he beholding the integrity of my heart,
and seeing that towards him innocency was found in me,
and that towards you I had neither done, nor intended to do any harm;
therefore has the Lord in the exceeding riches of his love and tender mercy,
which fails not towards them that fear him,
been very nigh unto me and has sustained and preserved me all along;
blessed and praised be his Holy Name forever.
For it is He and only He, who is the God of the spirits of all flesh,
that can make difficult and hard things easy, and a prison pleasant.
Glory over all be to him forevermore.
Amen.

Now the cause of my writing to you at this time is,
by reason that some do report you did say, that although you did cast me into prison,
yet I was not kept there upon your account now,
but upon the king`'s order of excommunication; now I desire, in meekness,
to ask you one question.
Suppose the king should make void the aforesaid order; then my question is,
whether you would be willing to release me from that
warrant by which I was first cast into prison,
or whether you would continue my confinement by that old
warrant if the said order of excommunication be made void?
And if you are willing I should be at liberty and not lie in prison upon your account;
then I desire you to manifest it by a few lines under
your hand which may free me from your aforesaid warrant;
and thereby I shall know that I have not been kept
prisoner all this time upon your account.
But if you refuse to free me from your first warrant,
then all people may justly conclude, that not only for the time that is to come,
but even for all the time past, you would have kept me in prison,
if the order of excommunication had never been; and so in the sight of the Lord,
and of all people, the cause of my sufferings will be imputed to you only;
and I know that the Lord, in whose hand is your breath and the breath of all living,
will require it of you, when he shall come near to judgment.
So leaving it to your consideration and expecting an answer,
I remain,

[.signed-section-closing]
A friend to all that love Truth in uprightness of heart.

[.signed-section-signature]
Oliver Sansom.

[.signed-section-context-close]
The 4th of the Second month, 1672.

--

This letter was delivered to him by a neighbour,
unto whom he had endeavoured to excuse himself from
being the cause of continuing me in prison,
as is before expressed.
And when the priest had read it over,
he did acknowledge that he had spoken such words as the letter did recite; but yet,
said he, he must pardon me for that, for if the king do release him, I will not.
This more plainly manifested his deceit; and when his answer was brought to me,
it was in my heart to say; I do believe it will turn to his confusion:
and I bid his hearers consider how false their priest was,
and how little credit could be given to what he said.

Soon after this I returned to prison again.
But when I came there, I found that the Friends whom I had left prisoners there,
being about four score in number, were all set at liberty;
and I alone was continued in prison upon the priest`'s account for tithes.
But mark what followed.

Upon that very self-same day that I was detained alone in prison,
the priest was smitten by the Lord.
For, as I was informed, he rode forth that day and came home very ill;
and so strange and unusual was his distemper that
the physicians could not find out the cause of it.
In a suffering condition he continued about seven weeks;
so that it was supposed he himself did rot while he lived; who had so often threatened,
that I should rot in jail.
And most of the time of his illness, he lay in extremity of pain and torment,
so that it was judged he died rather of pain than sickness;
and so exceedingly restless was he unto the very last,
that one of his nurses told me that in the last hour before he died,
she did believe he lay down on his bed and rose again at least six times.

Thus he miserably ended his life, on the 24th of the third month, 1672.
The Lord having made him an eminent example to all hard-hearted persecutors;
who I heartily wish may consider his end and take warning thereby in time.

Upon the priest`'s death I was set at liberty.
But ah! how can I proceed without mentioning a little of the Lord`'s goodness and mercy,
which he was pleased to show unto me in that time
of my solitude and lonely confinement by myself!
The Lord was pleased graciously to visit me and wonderfully
to break in upon me in that needful time,
to the overcoming of me with the sense of his heart-tendering love,
which made me in secret say, surely the Lord brought me here,
on purpose to show kindness to me.
And through the breakings in of the power of an endless life into my heart at that season,
my God did both mightily tender and enlarge my heart,
and also opened my mouth and gave me utterance,
to show forth his praise and to declare of his goodness
openly in the assemblies of his people.
O blessed and praised and magnified be his worthy and honourable name forevermore!
who raises the poor from the dust and the needy from the dunghill,
to tell of his goodness and to proclaim the exceeding
riches of his love to the children of men.
And now it is clearly seen that the Lord is pleased to reveal the
divine mysteries of his kingdom to babes and little ones;
and to hide them from the wisdom of this world,
that no flesh may boast or glory in his presence.

And now having a little eased my spirit in a thankful acknowledgment of
the lovingkindness of the Lord to me and his gracious dealings with me,
I proceed to recount some of the many exercises which befell me after I was set at liberty.

This priest, under whom I had suffered, had many children;
whereof his eldest son was educated to be a lawyer, and the next to be a priest.
This young priest, by making friends,
got in to succeed his father in the parsonage of Boxford;
yet came not at first to dwell there,
but let the tithes to two or three men of the parish;
for his mother and the whole of the family, upon the death of the old priest,
removed from that town and went to dwell elsewhere.

Now when I understood who were the men that were
about to farm or rent the tithes of this young priest,
I went to them and forewarned them,
that they should not meddle with anything which the priest might claim from me;
for I told them, I could no more pay them for him, than I could pay the priest himself.
They gave me fair words and said they would not meddle with it;
but yet afterwards they agreed together and took the tithes of my living with the rest.
And when afterwards I spoke to them about it and blamed them for it,
they did but mock at me,
pretending they did it in kindness to me to prevent my future sufferings.

They were for the most part of them, a sort of sordid, sottish people;
inclined much to drink, smoking, vanity and folly; and as it were wholly senseless of,
and unconcerned for their souls.
And though while I was in suffering they seemed sometimes
to be something tender and loving;
yet now that they saw me at liberty again they grew hard;
so as to slight the truth and make a scoff at the testimony of it.

And indeed the sense I had of their unworthiness and the small
ground I had to hope for any good to be brought forth among them,
made me sometimes think I might have been of more
service to the truth had I lived in some other place.
But the testimony I was engaged in there against the idle shepherd of that parish,
would not permit me to entertain a thought of removing from there,
until that war which he had raised against me was over,
lest I should thereby seem to fly, and let fall my testimony,
and thereby strengthen him in his wickedness and give him occasion to boast over,
not me only, but the blessed truth which I contended for.

But now that the priest was cut off in so extraordinary a manner,
and the war which he had begun and so long and vigorously carried on,
was in all outward appearance put to an end, and that to the advantage of truth;
the thoughts of removing from there, and going to dwell at Farringdon,
came afresh and more strongly upon me.
And because the exercise it brought with it was very weighty upon
me I laid the matter before Friends at the men`'s monthly meeting.
And as I related my condition and the exercise that was upon me therein,
the Friends were much tendered and had great unity therewith,
and found clearness to encourage me to go on in my purpose;
for they were sensible that I might be of more service to truth at Farringdon,
than where I then was.
So having clearness in myself and the consent of Friends I gave up to remove,
though not without some cross to my own will and against my outward interest,
and made preparation to depart from there by disposing
of my living and what I had at Boxford.

But the enemy of truth and righteousness stirred up the priest`'s
widow and her sons to oppose and persecute me again,
upon the old account which I had suffered for so long before.
This occasioned some words to pass between me and the young priest,
wherein I reproved him for his vanity and folly; and he, to be even with me,
threatened me, as his father used to do,
with a prison for what he pretended was due to his father.
This brought a weighty concern upon me to write to him, who bore his father`'s name,
which I did thus:--

[.embedded-content-document.letter]
--

[.salutation]
James Anderton,

Your late carriage and deportment has brought a weighty
and serious consideration upon my spirit concerning you;
and in the light of the living God,
I see your state and standing to be sad and dangerous;
and in tender love to your immortal soul I am even constrained
to write these lines in the fear of the Lord as a warning to you,
that you turn in your mind to the light with which Christ has enlightened you,
that you may see and discern your own state and condition,
how it stands between the Lord and your immortal soul.
For I testify to you, you are in the way of death and destruction;
and if you do not repent and turn to the Lord,
even to his light and Spirit which is given you to profit,
but do go on in rebellion against him, eternal ruin,
destruction and misery will be your portion forever.
Therefore,
as one that desires your wellbeing both in this world and in that which is to come,
I exhort and warn you that you speedily repent and turn to the Lord,
while his Spirit strives with you and his mercy and
long-suffering is extended towards you;
lest his spirit cease striving, and he give you over to a reprobate mind,
and his wrath come upon you, and there be no remedy for you.
Therefore prize your precious time and your day before it be too late.

And if you will turn in your mind to the light of Christ, as aforesaid,
you may see your ways and practices to be contrary to the mind and will of God,
and also contrary to the example of the ministers of Christ;
and you may also see and know in your own conscience,
that the Lord never sent you nor ever called you to that ministry.
And therefore how can you expect to profit the people
at all or to turn any of them from their evil ways;
seeing you stand not in the counsel of God, do cause the people to err,
and the hands of evil doers are strengthened by you to go on in wickedness?
For you make yourself vain and spend your precious time in card-playing and the like;
and then bring Scripture to justify your practices therein.
Oh! blush for shame and cease wresting and perverting the Holy Scriptures,
which were not given forth to justify or tolerate profaneness; for the drunkard, swearer,
or liar,
or any other profane person may hereby be encouraged
in their abominable practices by your example.
They may plead in this manner, '`Our minister says, all things are lawful,
and thereupon he can take liberty himself to sporting, carding, and the like.
And if all things be lawful, then drunkenness, etc., they may say,
is lawful.`' O consider and take heed, and harden not your heart; but while your day is,
turn to the light which discovers and condemns all the deeds of darkness.
And thereby you may come to know in your conscience,
that they that preach for hire and take tithes by force and violence from people,
are not ministers of Christ, but deceivers and of Antichrist;
and the servants of the Lord must bear witness against them now as well as formerly.

So to the light of Christ Jesus in your own conscience I once more direct you;
therein to wait for a clear understanding;
for that will make manifest to you your evil deeds and reprove you for them.
And if you turn at its reproof, happy will you be;
but if you do go on in rebellion as you are now going,
it is and will be your condemnation forever and you can not escape.
And whether you will hear or forbear; yet this light which I have testified of,
will stand a faithful witness for the Lord that cannot lie;
and from it your most secret thoughts cannot be hid.
O that you would prize your precious time,
and consider in this your day the things that belong to your soul`'s peace
before they be hid from your eyes! which is the desire of him,
who is a well-wisher to your soul, but a witness against your deceit.

[.signed-section-signature]
Oliver Sansom,

[.postscript]
====

P+++.+++ S.--And whereas you have threatened me with a prison
if I did not pay what you pretend was due to your father;
this I have to say and testify in the presence of the living God,
that for conscience sake towards the Lord could not
give your father anything nor pay him any wages,
because he was a deceitful worker and a false minister;
and the Lord God of my life required me to bear witness against him in his day.
And if you do seriously weigh and consider what cruelty your father acted against me,
and the wrong and injury he has done me, and all for my obeying the Lord;
surely you might easily see that in equity it is your concern rather to make
restitution for the goods he wrongfully took from me and the long imprisonment,
which through his means was unjustly inflicted upon me;
than to be so impudent as to demand anything now of me.
Yet in all my sufferings the Lord my God did uphold me,
and stood by me in my testimony against your father;
and preserved me so that I knew no want; blessed be his holy; name forever.
And when your father after many faithful warnings refused to hear,
and hardening his heart went frowardly on in his evil way,
in provoking the Lord until his measure of iniquity was filled up;
then did the Lord arise to plead the cause of him that had no helper in the earth;
and did remove the oppressor out of the way by cutting him off from the earth.
Therefore I desire you to look back upon your father`'s
ways and practices and consider his miserable end.
And let that be as a warning to you, not to follow his steps,
lest you come to the like end.
But the Lord knows my heart, that I did not desire your father`'s ruin;
but often in tender pity warned him to return from his evil ways.
And in my sufferings I committed the keeping of my
soul with all that I had unto the Lord;
who was unto me as a tender father and has kept and preserved me all along;
and has also delivered and set me at liberty: Glory over all be to Him forevermore.

And now, James Anderton, take heed to yourself what you do concerning me.
Think not that because you have a law on your side,
an unjust law will excuse you in the sight of God;
for in all ages the servants of the Lord suffered
under the pretence of the breach of a law,
by their persecutors.
And know this, that it is by the Spirit of the Lord that I am raised up,
to stand a witness for him against your ways I and practices;
and unto Him I commit my I cause,
who alone is able to preserve me and keep me in well-doing, unto the end of my days.

So in the coolness of your spirit I desire you to consider of what I have here written;
and to the just witness of God I appeal to testify to the truth of it:
and whether you will hear or not,
yet that will one day bring to your remembrance that you have been warned.

====

[.signed-section-signature]
O+++.+++ S.

[.signed-section-context-close]
Written and delivered in the Twelfth month, 1672.

--

My purpose of removing from this place to go and dwell at Farringdon
continued still with a weighty exercise upon me.
Yet I hastened not in it, but waited to see how the Lord would make my way clear;
desiring of the Lord that he would keep me always single to himself;
that whatsoever I did, or whatsoever state I was in, I might enjoy contentment, peace,
and satisfaction from him.

And as I had before laid my intention of removing before
my friends and brethren in the spiritual relation,
with respect to my service for truth in going or staying,
who approved my I purpose of removing; so now,
that I might act with a decent regard to my outward relations also,
I went first to my own father who had given me that small estate and acquainted him,
that I had some thoughts to part with it provided he would give his consent; else not.
He very readily gave his consent, and did his endeavour to help me to a chapman to buy it.

Then went I to my wife`'s father also, and desired his consent for my parting with it,
which he also freely gave; and thus for awhile things went on very easy and well,
in order to my removal, beyond my expectation.

[.offset]
+++[+++Oliver Sansom appears to have visited Bristol and
London during the early part of this year,
1673; the following letters, dated the I third month,
were written from those places to his wife.]

[.embedded-content-document.letter]
--

[.salutation]
My dear Wife,

My dear and tender love is entirely unto you in the living unchangeable Truth;
earnestly desiring, and the breathing of my soul is,
that we may be preserved in the same, without wavering, unto the end,
that we I may faithfully fulfill our generation,
according to the will of the Lord our God who is blessed forever.
Dear heart, this may let you know that I am well, and my dear companion,
whose love is dearly to you and to Friends; we have had many precious meetings;
we met with William Dewsbury at one meeting, and Katharine Evans at another,
her love is to you.
John Moon intends to come that way towards London next week,
and be at the Mill on the fourth-day if he can;
and if I come not with him then I intend to be at Farringdon the first-day after.

But if things fall out contrary to my present expectation,
you may hear from me on the fifth-day at Newbury;
but if there is haste of my return home, send by the next post.
So with dear love to Richard Daniels and Betty, and T. V., and to Friends,
thinking to return shortly, I rest

[.signed-section-closing]
Your dear husband,

[.signed-section-signature]
O+++.+++ S.

[.signed-section-context-close]
Bristol, the 3rd of the Third month, 1673.

--

[.embedded-content-document.letter]
--

[.salutation]
My dear Wife,

These may let you know that I am come well to London,
and here are abundance of precious Friends, that in times past were kept asunder,
but are now, through the tender love of the Lord, met together,
to the great joy and refreshment of one another.
Oh! the tenderness, the love,
and the life that is felt abundantly to flow in the blessed unity of the Holy Spirit,
to the honour and glory of the Father, who is blessed forevermore.
Dear heart,
I clearly see the tender love of the Lord abundantly manifested
in giving me this precious opportunity to be here at this time,
to behold the faces of so many dear brethren,
bearing the Father`'s mark in their foreheads,
and feeling his life flow through their vessels as a river,
and his love as a mighty stream.
Glory to the Lord over all, and to the Lamb forevermore.

I desire you not to look for me so soon as I spoke of,
for I think I shall hardly get out of the city this week, or however,
not before the seventh-day, to be at Reading on the first-day;
but Theophila Townsend is here, and she has no company,
and if a horse can be conveniently had I think to come back
with her through Hertfordshire and Buckinghamshire,
which will take up some time, therefore look not for me till you see me.
So with my dear and tender love to you,
desiring that in a waiting and watchful state you may be kept and preserved
with your eye turned inward to that power which is able to do it;
and in the same love to R. D., E. W., and T. V.,
and to all my dear Friends both at Newbury and elsewhere.

[.signed-section-closing]
I remain your dear husband,

[.signed-section-signature]
O+++.+++ S.

[.signed-section-context-close]
London, the 19th of the Third month, 1673.

--

Now although I then was, and yet am fully satisfied,
that my purpose of removing was of the Lord; yet with respect to the time for doing it,
I afterwards found (which I did not then presently foresee) that the Lord had a further
service and testimony for me to bear for his name and truth in those parts,
before I left that place; which was brought about after this manner.

The widow of the old priest that was lately dead, and her eldest son, John Anderton,
who was bred to the law, consulted together;
and thinking they might get some advantage upon me by straitening me about my removal,
which they understood was in hand,
and hoping that some one or other of my relations would
compound with them and give them some money to set me free,
proceeded against me for that end, in the Corporation Court of Newbury, thus.

Upon the 18th day of the seventh month, 1673, as my man led my horse, loaded with corn,
into the market at Newbury, the said John Anderton met him and said, "`How now Quaker!
I`'ll have this horse and corn too, before you shall go out of town.`"
When my man had set down the corn and was going to fetch more,
John Anderton met him again and stayed the horse until the
sergeant came with a warrant from the mayor to attach him.
Of which the copy here follows.

[.embedded-content-document.legal]
--

[.salutation]
Burgas de Newbury in Com Berks

Attach Oliver Sansom by his goods and chattels,
so that he be and appear at the next Court,
to be held for the said borough to answer Charity Anderton in a Plea of Trespass.

[.signed-section-signature]
Geo. Cowslade, Mayor.

--

My horse being thus arrested I had no freedom to give bail;
but did choose rather to rest satisfied with the loss of my horse than to contend in law.
But there being many people present,
some of them would not allow my horse to be led away:
but in love to me went (though quite contrary to
my mind and freedom) and gave bail for my appearance;
which afterwards became a trouble and a snare both to me and them.

When I understood this action was entered against me in the name of the priest`'s widow,
it was weightily upon me to write to her as follows:

[.embedded-content-document.letter]
--

[.salutation]
Charity Anderton,

Whereas there is an action entered against me in
your name in the Corporation-Court of Newbury,
where I am to appear the last day of this month to answer you in a plea of trespass;
I do not know that I did ever trespass against you in all my life.
But if you think I did,
then I do wish that you from your heart could forgive all men their trespasses,
that the Lord might forgive you yours.

But if this suit be upon that old demand for which your husband did cast me into prison,
and cruelly kept me there until his death; then I desire you to consider in your heart,
and let God`'s witness in your conscience answer,
whether I have not suffered double for that already.

But if you are resolved to go on to prosecute this matter,
then this I have to say to you,
that the same God that did strengthen and preserve and uphold me under that persecution,
and pleaded my cause with your husband then; I say, the same God is with me still,
to keep and preserve me, and to plead my cause with you;
and into his keeping and protection +++[+++myself]
with all that I have, is committed.
And I know and believe that he will allow no more to come
upon me than he will give me ability and patience to bear;
and my sufferings shall all redound to his glory, and to my soul`'s everlasting good.

Therefore I do in tender love to you, advise you to take heed what you do against me,
for he in whom my confidence is, is greater than all;
and his tender love and care have been and still are over me;
and what you do against me in this matter he will take as done unto himself:
and if you do proceed in this course of cruelty,
the wrath and indignation of the Lord will break forth against you,
which your soul shall feel to your sorrow, if you repent not in time.
And besides, though it should prove to your outward profit as you may expect,
yet it will occasion a stinking savour to arise again from the actions
of him who first began this unchristian controversy against me;
the remembrance whereof will by this means be afresh revived;
and so that Scripture will be fulfilled which says,
"`The memorial of the wicked shall rot.`"

It is likely your son and you may think you have entangled and caught me in your snare,
now in this juncture of time, when you heard I was to surrender at the Court-Leet;
for your son said he would send me to prison and prevent my being there.
Now this I say, if you do seek this way to prevent my being at the court,
it is possible you may have your end;
for if I do not surrender when at liberty I intend never to surrender while a prisoner.
But this does not at all straiten me,
for I am not so far engaged but I may safely hold it,
and to the praise and glory of God I can boldly speak it,
that it was not for any outward need or necessity that I went about to part with it.
For notwithstanding the cruelty, spoil, and violence,
which by your husband was acted against me,
yet the blessing of the Lord my God has been so largely upon me,
that he has not allowed my outward estate to be impaired, but has rather increased it.
And this I further say,
that as the Lord through bis tender mercy has hitherto preserved
me and given me victory overall that has opposed me,
so my hope and confidence is,
that the same God will continue his kindness and mercy to me, so that,
if ever I remove from Boxford,
I shall go away as one who through faith and patience has obtained the victory.
So it is in vain for you to strive against the Lord,
who has manifested his blessed Truth; which as it is abode in gives the victory,
and through the power of it shall surely overcome
all that do oppose or rise up against me for it.
Wherefore I wish you would be warned by him who desires
your soul`'s present and eternal good.

[.signed-section-signature]
Oliver Sansom.

[.signed-section-context-close]
The 28th of the Seventh month, 1673

--

Two days after, the Newbury Court was held, and the new mayor, Richard Pocock,
first sat as judge there;
where I appeared in person and offered to render
my body a prisoner to discharge my bail;
but it would not be accepted.
My appearance also in my own person was refused;
and because I did not employ an attorney to appear for me,
the mayor presently gave judgment against me for non-appearance,
although I did appear according to the express words of the warrant,
and answered to my name when I was called three times in court.
So judgment being entered against me I expected to be taken up with an execution;
and therefore I desired the Sergeant,
that as soon as an execution should come to his hand he would let me have notice of it,
that I might render my body to him a prisoner to discharge my bail;
and he promised me I should know as soon as an execution was come forth against me;
which I relying on and hearing nothing of it in the
interim I did not go to the next court.

But, as I was informed, John Anderton,
being at the mayor`'s house before he went to the court,
desired one of the Sergeants there present to set his hand to a paper.
The sergeant asked whether he might safely do it without danger;
and the mayor telling him he might safely do it, for there was no danger in it;
the sergeant, thus encouraged by the mayor, did set his hand to he knew not what;
which when he had done,
J+++.+++ Anderton gave him sixpence and bid him take the paper and throw it into the court.

This paper it seems was the execution,
which was returned _"`Non est inventus`"_ by John Anderton;
who got the sergeant to set his hand to it as his return,
not knowing that it was an execution,
but thought it had been a _"`Scire facias;`"_ as he affirmed the next court-day
in open court and offered to take his oath of it.

Upon this false return on the second court-day of this mayor`'s sitting,
a _"`Scire facias`"_ was granted against my bail.
Whereupon being advised to render my body to be actually
a prisoner before the _"`Scire facias`"_ was returned,
I went to the mayor`'s house on the court-day before he went to the court,
and offered to render my body to be his prisoner,
desiring him to commit me to one of his sergeants then present
that there might be no farther proceeding against my bail.
The mayor said he could do nothing until he came to the court,
and he bid me be there and then I might be committed.
But when I came to the court, which was but the third day of this mayor`'s sitting,
though I had at that time an attorney there who moved and pleaded on my behalf,
and showed an error in the return of the execution,
the mayor permitted my adversary to amend it there in the open court;
and when I there also offered to render my body into custody
often desiring that I might be committed to discharge my bail,
he refused to accept the tender of my body,
and ordered the _"`Scire facias`"_ to be returned and filed;
and that being then pleaded to, the trial was ordered to be on the next court-day;
whereupon my adversary did boast that he would have a judgment against my bail.

When I had well considered of these proceedings,
perceiving plainly that the mayor was bent to gratify my adversary,
that if it were possible he might have his design,
though altogether unjustly carried on against me;
my spirit was stirred within me and in the sense of his unjust dealing by me,
I wrote to him as follows:

[.embedded-content-document.letter]
--

[.salutation]
Richard Pocock,

Forasmuch as the Lord has given you authority as
chief magistrate in this borough of Newbury;
I say the Lord God of heaven and earth has put the sword of justice into your hand,
and he requires you to do true judgment and justice in your place;
to relieve the oppressed and to be a refuge for the innocent and a terror to evil-doers.
But you have disobeyed the Lord and abused the power which he has given you.
For the very first day of your sitting as judge in the court,
you gave unjust judgment against me, who am an innocent man, without a hearing or trial;
only because I did appear in my own person, according to the plain words of the warrant,
and did not hire another to appear for me, whom I knew not;
nor whether he would speak for me or against me.
And for this only cause and no other that I know of,
you took occasion to give judgment against me,
whereas the charge and accusation against me is false and a very lie.
And so you have encouraged the liar in his lying,
and strengthened the hands of the wicked and have grieved and oppressed the just,
and allowed the law to be perverted by wicked instruments,
to be made a snare to the innocent which should be a refuge for such.

And for your proceedings since,
at the second and third times of your sitting in the court;
to the witness of God in your conscience I appeal to plead my cause
with you and to show you the deceit of your own wicked heart,
how you have acted towards me, and also to manifest my innocency unto you.
And therefore my desire is, that you may fear the Lord,
and consider that you must give an account to him, both of your trust and authority,
and of all your deeds done in your body, whether they be good or bad.
For verily,
for that which you have done and allowed to be done since you came into authority,
is the Spirit of the Lord grieved; and his anger and indignation is kindled against you.
And if you go on in provoking the Lord, he will arise in his own due time,
and will plead the cause of the oppressed; and his wrath will break forth against you,
and his judgments will overtake you and bring you down from your seat, except you repent.

Therefore in true and tender love to your soul I warn you in the fear of the Lord,
that you take heed of what you do:
for the Lord is on my side who will take account of what you do against me,
whether in public or in private;
and to him have I committed my cause who will plead it with you,
and with all that oppose me for his sake.
So I desire you to turn to the just principle of truth and justice,
the light of Christ in your conscience;
that thereby you may be ordered and directed to rule for God;
and then you will prosper in your government and be happy
both in this world and that which is to come.
But this I testify to you, that you are now in the broad way that leads to destruction;
and take heed lest you arrive there before you are aware.
O that you would be warned and repent before it is too late, is the desire of my soul,
who am,

[.signed-section-closing]
A well-wisher to you and all men,

[.signed-section-signature]
Oliver Sansom.

[.signed-section-context-close]
The 15th of Eighth month, 1673.

--

When the next court-day came, which was the 21st of the eighth month, 1673,
my adversary was confounded or disappointed in his proceedings;
for his declaration was found so faulty, that he was ashamed of it,
and the judgment was set aside; and then my attorney pleaded for costs,
but the mayor would allow only two shillings, which my adversary paid down in court.
Then the mayor ordered that we should go to trial upon the merit of the cause,
but I laboured to withstand it;
for I well knew what the event would be if I did go to trial before them;
wherefore I urged to have my bail first discharged.
But whether I would or not,
my attorney agreed with the mayor to go to trial upon the merit of the cause,
by which I saw more plainly the disadvantage of having an attorney.

Wherefore when the next court-day came, which was on the 28th of the eighth month, 1673,
not having freedom to gratify the corrupt covetous mind in the lawyers,
I forbade my attorney acting any further in my defence without fresh order from me;
and when the cause was called, I spoke to the mayor desiring my bail might be discharged;
for I told him I was informed by those that understood the law,
that if the principal did render his body in discharge of his bail,
it ought to be received and the bail discharged.

The mayor said there was no need for me to be a prisoner yet,
and asked me why I would be a prisoner before there was a necessity;
with more words to that purpose.
I replied, "`My reason is because in all your proceedings against me hitherto,
I perceive there is a snare laid, to cause the poor man to suffer who is engaged for me;
and therefore, to prevent the like snare for the future,
I desire he may be discharged and set free from his engagement,
whatsoever I suffer myself.`"
And then again I offered to render my body desiring my bail might be discharged;
"`which,`" I said, "`was but justice and according to law.`"
The mayor then angrily answered,
"`Whoever said if the principal rendered his body in discharge of his bail,
that it ought to be received and the bail discharged,
he would say he was a fool and would lay him by the heels.`"

I replied, "`There are some who know the law as well as yourself, and will say,
what I desire in discharge of my bail is according to law and justice,
and ought not to be denied me; I desire but justice.`"

"`You ought,`" said the mayor,
"`to give me thanks for the justice I did you last court-day.`"

"`All the justice,`" replied I, "`that was done me then,
was but an undoing of some injustice that was done me before.`"

At that the mayor was in a rage and said, I affronted him and charged him with injustice;
and thereupon he commanded the sergeant to put me
in the cage and keep me there all that day,
it being the fair-day, for, said he, "`I`'ll make him an example to all others.`"

I desired liberty to speak in my own defence, but the mayor would not hear me;
but exclaiming against me, commanded the sergeant to take me away.
The sergeant said, he had not the keys of the cage;
whereupon the mayor commanded to send for the constable; but he came not.
Then he commanded the sergeant to put me in the stocks;
and the sergeant seeing the mayor in such a fury dared delay no longer,
but taking me by the arm, led me gently out of the hall and then let me go.
I seeing the stocks were near, went and sat me down on them for awhile;
but the sergeant slunk away like a man ashamed.
Now the mayor thought I had been put in the stocks;
and after some time when his rage was over, he sent a sergeant to release me.
This ill usage of me brought a concern upon my mind to write to the mayor about it;
which I did as follows, thus directed:

[.embedded-content-document.letter]
--

[.letter-heading]
To Richard Pocock, Mayor of Newbury, These.

[.salutation]
Friend,

I have a few words to communicate to you concerning your dealing with me the last court-day:
therefore I desire you in the coolness of your spirit,
to consider what cause or occasion was given on my part,
that should move you to do by me as you did.
You may remember v.`'hat my words were, which you took offence at,
and the occasion of them; which was thus.
As I was pleading for the discharge of my bail,
and urged that what I desired was according to law and justice, you told me,
I ought to give you thanks for the justice you did me the last court-day.
To which I replied,
all the justice that was done me then was but an
undoing of some injustice which was done me before.
These were the words you took offence at.
And now do but in soberness consider what ground you had to be offended at those words,
which may easily be proved true from your own words, namely,
That I had justice done me the last court-day;
which you know was in disannulling and reversing what had been done against me before;
and surely that must needs be injustice which was disannulled and made void by justice.

Now I write this, not to upbraid you or glory over you;
but to let you know that my suffering by you is not for evil-doing.
For the Lord of heaven and earth has revealed his living Truth unto me,
and in his fear and by his strength I stand a witness
for him against all deceitful hireling priests,
their works and wages; and against all corrupted lawyers and laws,
and all those that act contrary to the righteous law of God in the heart,
which leads to do to all men as they would be done unto.
So I desire you to weigh and consider what you have done.
And this know,
that I am so far from seeking revenge that I can from my heart not only forgive you,
but even pray for you,
that you may come to repentance that the Lord may forgive you also,
and may open an understanding in you,
that you may see and discern in this your day the
things which belong to your soul`'s everlasting peace,
before they be hid from your eyes; which is the real desire of

[.signed-section-signature]
O+++.+++ Sansom.

[.signed-section-context-close]
The 30th of Eighth month, 1673.

--

The court was adjourned to the second day of the tenth month, 1673,
at which time I appeared; as also I did three several court-days following, namely,
the 9th, 16th, and the 33rd days of the same month; but my adversary, John Anderton,
put in no declaration against me in all that time, only continued the suit.
But on the 13th of the eleventh month, when the court met again,
there was a declaration put in against me.
To which I appeared the next court, held on the 20th of the same month,
and offered to pay that which they called the king`'s duty.
But the mayor and some of the lawyers opposed it,
alleging that if such a thing should be permitted,
that a man should defend his cause without an attorney
it would hinder the lawyers`' calling,
and they might beg their bread whose education had been so chargeable to their parents;
with much more to the like effect.

I said, "`There is no need of such lawyers, for generally they do more hurt than good.`"

They still pressed me much to employ an attorney, which I refused;
yet still urged my personal appearance and answered
to my name as often as I was called in court.
I also offered to render my body to discharge my bail.
Yet the mayor would take no notice of it;
but entered judgment against me for non-appearance,
though I appeared there in open court before them all.

I further pleaded,
that seeing my adversary had put in his declaration without an attorney`'s name to it,
I might have the like privilege to make my defence in my
own person and to go to trial without an attorney.
But the mayor said, it could not be; it must not be permitted:
and then he permitted my adversary to amend his declaration
by putting in an attorney`'s name to it,
after it was filed in the court.

On the 27th of the eleventh month, 1673, I went to the court again;
where were two justices of the peace, viz: John Kingsmell and William Craven,
besides the mayor and justice of Newbury.
The mayor spoke to me and said, "`Will you yet employ an attorney;
if you will yet employ an attorney the judgment shall not stand; what say you?`"

I stood up on a bench because of the throng of people and began to speak;
but the mayor would not allow me to stand there, but caused some to pull me down,
and said, if I would stand below by the table I should be heard.
So room being made for me I stood by the table; and before I could speak,
some that stood by me would have pulled off my hat; but John Kingsmell forbade them,
saying, let his hat alone.
Then in answer to the mayor`'s question I said,
"`I cannot employ an attorney because the matter in controversy is not a common case,
as depending merely between man and man;
but on my part is a case of conscience towards the Lord.
For there are many doubts and scruples in my mind which are very weighty to me,
which if I were resolved and satisfied in, the controversy would soon be at an end.
For I have formerly declared and do now declare,
that if I were satisfied in my conscience that Christians ought to pay tithes,
by any either command or example from Christ or his apostles,
then I shall be willing not only to pay tithes of
all that I possess for the time to come,
but also, for all the time that is past to restore sevenfold for what I have kept back.
But that envious priest who has dealt most unchristian-like by me,
in spoiling my goods and casting me into prison, and keeping me there until his death,
did always refuse to answer those scruples which lay so heavy upon my conscience,
as doubts in my mind, that if I should pay tithes I should sin against God,
and deny that Christ is come in the flesh, which I dare not do whatsoever I suffer.
And I have been informed and have cause to believe,
that by the laws of this land this court ought not
to determine anything concerning tithes.
And therefore I do deny the proceedings here,
and do appeal to such other courts as are by the king`'s
laws appointed to hear and determine such matters.`"

When I had thus spoken.
Justice Kingsmell said jestingly, "`What court would you appeal to?
Will you go to the court of heaven?
and if so, you may be sure the lawyers will not come there.`"

After this many more words passed from him and others to persuade me to employ an attorney,
which I refused, telling them,
no attorney was sensible of the ground and cause of the controversy on my part,
and therefore I must commit my cause only to the Lord who has hitherto preserved me.

Then was my personal appearance again refused,
whereupon I again offered to render my body to discharge my bail;
to which my adversary`'s attorney answered, we will not have your body,
we will have none of your carcase; we are of the mind to go another way to work with you.
While the attorney said this, my adversary himself was whispering the mayor in the ear;
and then the court adjourned until after the term.
