== Chapter IV.

[.chapter-synopsis]
* His prosecution at Newbury Court
* Letter to the lawyer on the ground of his refusal to pay tithes
* Injustice of the Mayor
* Letter to him
* Is committed to Newbury Compter Prison
* His sickness there
* Letter to his wife
* Letter to the late priest`'s widow, his prosecutrix
* Remarkable liberation
* Letter to a Presbyterian priest who had preached against Friends
* This priest`'s charges
* Oliver Sansom`'s replies
* Further correspondence between them.

On the 17th day of the twelfth month, 1673, the court sat again, and I appeared;
but the mayor not being present, nothing was done further in my business;
only the clerk said the judgment was affirmed against me.

But on the 24th of the same month, when the court sat again,
my cause was called and the mayor asked me, if I would yet employ an attorney?
Whereupon I produced a paper which I desired might be entered
into their book and I would pay for the entry.
The mayor took it and read it openly in the court; and this is a copy of it.

[.embedded-content-document.paper]
--

[.letter-heading]
Memorandum

That whereas there was an action entered in the name
of Charity Anderton against Oliver Sansom,
in the Borough-court of Newbury;
and judgment was given against the said Oliver for not appearing by an attorney,
and also execution taken thereupon;
but by reason the declaration was found so defective
that the plaintiff was ashamed of it,
the judgment was reversed and the proceedings made void.
But yet the mayor gave order for the action to be renewed,
and to go to trial upon a new declaration;
but the said Oliver would not consent to it unless he might change his bail.
And then he did offer to render his body into the Sergeant`'s
hands to abide a prisoner until he did get other bail;
but all was denied.
And then a second declaration being put in, a second appearance was also required;
and Oliver Sansom was called by name to appear in the court,
and he made answer and offered his personal appearance accordingly;
and desired that he might appear and make his defence in his own proper person;
which he claimed as his common right, and tendered sixpence in the court,
as the king`'s duty for such an appearance.
But the mayor would by no means admit of his personal appearance.
Whereupon the said Oliver did render his body to be a prisoner to discharge his bail;
but it was refused.
This was done in the open court, on the 27th of the eleventh month, called January,
in the twenty-sixth year of the reign of Charles the Second, now king over England, etc.,
A+++.+++ D. 1673.

And this is also further to be noted.
That Gabriel Buck who did engage for Oliver Sansom`'s first
appearance and is the bail first mentioned above,
did engage no further than only for that first appearance
unto the first action and declaration;
but for the second appearance there was no bail engaged either by consent or intent;
unless it can be by force.

--

When the mayor had read this paper openly in the court,
he could not object anything against the truth of it; but asked me,
why I would have it entered into the book?

I answered, "`Seeing this paper contains a short account of the proceedings against me,
and also the time when I rendered my body to discharge my bail;
therefore I judge it may stand me in stead,
and be of service to discharge my bail in time to come if need require.`"
The mayor then said "`You may have it entered, but what will you give?`"
"`I will give a shilling,`" said I "`to the clerk, for entering it into the book,
and for him to set his name as witness to it.`"
"`If you will give five shillings,`" said the mayor, "`you may have it entered;
otherwise it shall not be done.`"
I replied, "`Seeing I have offered a shilling, which is more than it can be worth,
I think it very unreasonable in you to desire more.`"
"`You may let it alone then,`" said the mayor; "`and if you will yet employ an attorney,
the judgment may be reversed.`"

Just as this discourse ended, an attorney spoke privately to me,
and in a loving manner said, if I would but employ him,
he would undertake to put an end to the business and throw it out of the court.
I asked him, what ground he had to think so?
he said, "`Because an action for tithes ought not to be tried in this court,
as he could produce statutes to prove.`"
Then I began to reason in my mind about it, whether the Lord might not make use of him,
as an instrument, to free me from that court;
and so in my simplicity too hastily consented to him, and gave him his fee;
whereupon he entered my appearance presently, in order to proceed in my defence.
But I was much troubled and burdened in my spirit afterwards,
and could not have peace until I had written a letter
to forbid his proceeding any further on my behalf;
which I did as follows.

[.embedded-content-document.letter]
--

[.salutation]
Friend,

I am pressed in my spirit to write unto you concerning my business,
which you did enter upon at the last court-day in Newbury;
because you do not understand the ground of the controversy on my part;
which in short is this.
About ten or eleven years since, I was convinced by the light of Christ in my conscience,
of the deceit and hypocrisy of the hireling-priests of the nation,
who serve not the Lord Jesus Christ, but their own bellies;
and the Lord required me to stand up for him a witness against them in their ministry,
both as to their call to it, their practice in it, and maintenance of it.
And in true obedience to the Lord and in his fear, have I denied the payment of tithes,
even to the hazarding of all that I have in this world.
For which cause I have suffered both the spoiling
of my goods and the imprisonment of my body;
and in all my sufferings the Lord has so preserved
me that it has all wrought for good unto me.
And to His glory be it spoken, he has not only made me willing to serve him,
but has given me strength and power to do it.
And in all my sufferings hitherto I have committed my cause unto the Lord,
knowing the cause to be his,
who gave me faith and patience to endure until he wrought deliverance.
And so I quietly rested in content,
and never troubled myself to contend with my adversary;
though advantages in the law might have been taken.
And so it is with me still, that I must commit my case to the Lord;
for in him is my strength and power, my peace and comfort;
and trusting nakedly in him I can rest in quiet, in the midst of trials and sufferings,
who has never failed me hitherto.
And as the cause for which I suffer is the Lord`'s, so I hope I shall experience,
as well now as heretofore, the power of my preservation to be his:
so shall the glory of my deliverance be ascribed to Him, as his peculiar right,
forevermore.

Now as the Lord has kept and delivered me out of the mouth of the old lion,
so I believe he will so far shut the mouth of the
young one that his teeth shall not hurt me.
What if his paw should tear away some outward things?
yet the Lord my God will limit him that he shall not go beyond his bounds.

Therefore I desire you to go no further on in my defence;
for I cannot have peace in committing my cause into your hands.
For if it were really in your power to deliver me, I tell you plainly,
as the matter stands, I cannot accept of it, because I expect deliverance another way;
and yet I do not question but that you might possibly perform what you did promise me.
And indeed at that instant when I retained you, before I had thoroughly considered of it,
I thought the Lord might peradventure make use of you as an instrument for my deliverance;
but having since more seriously weighed and considered better of it,
the Lord has showed me that it is nothing so.
And he has also given me to see, that your end is nought;
and that you and your fraternity there are so bad
and corrupt in your practices and proceedings,
that the Lord does abhor you and will one day plead with you for them.
Now by what is here written you may take notice,
that I do utterly deny your proceeding any further in this business;
but would have you let it alone as if you had never meddled with it.

And in tender love to your soul I advise you to turn in
your mind to the light of Christ in your conscience,
which does search your heart and will show you in secret all that ever you have done.
And if you will heed it and obey it,
then you may come to witness that it will not only show you sin and reprove you for it;
but it will also save you from it, and salvation cannot be obtained any other way.
This is all at present from him, who is your friend,

[.signed-section-signature]
O+++.+++ Sansom.

[.signed-section-context-close]
The 26th of Twelfth month, 1673.

--

These to the hands of +++_______+++ Brooker, an attorney in Newbury-court,
dwelling at or near Woolhampton in Berks.

At the next court, which was held on the third day of the first month called March,
1678-4, this attorney Brooker related how that I had sent him a letter,
to forbid his going on any further in my defence; and he showed my letter to the lawyers;
and they were angry and said that letter was a charge against them all;
and some threatened to lay an action upon me for it.
But I told them I would stand by what I had written,
and bid them clear themselves of it if they could.

Then addressing myself to the mayor, I said, "`I have committed my cause to the Lord,
who is able to deliver me if he pleases, but if he do not deliver me out of your hands,
yet I cannot employ any of these corrupted lawyers for my defence.`"

One of these lawyers thereupon said, "`Oh! he will commit his case to God:
God was never a lawyer!`"
I replied, "`Neither did the Lord set any of you on work to do as you do,
but you are employed by another power, and your reward will be accordingly.`"

Then turning my speech to the mayor again, I said, "`You do well know,
that this matter which I am sued for ought not to be determined in this court.
Yet if you are resolved to proceed and allow the law to be prosecuted against me,
contrary to the intent of it, then here I am to answer it and suffer the penalty of it.
But I do wish you may not permit that to be acted in your name and by your authority,
which will be a dishonour to you afterwards.`"
Upon this the court broke up.

The next court-day was on the seventeenth of the first month, 1673-4,
where I appeared again and said openly, "`I am grieved with your proceedings against me;
for the mayor knows that the controversy wherein
I am concerned ought not to be decided in this court;
and it has been depending here near half a year already.
Therefore I desire that an end may be put to it without any further delay.`"

The mayor thereupon interrupting me said angrily, "`Where is your attorney?`"

I answered, "`If my case ought not to be tried here,
what need have I of an attorney here?`"

The mayor then, being in a rage, said,
"`I have offered you very fair and delayed the business for your sake;
and still you do refuse to employ an attorney, but abuse me for it,
you shall not think to escape so.
Constable, I command you to take him away and lay him by the heels.`"
The constable not making haste, he said again, "`Take him away; put him in the stocks;
he shall not think to do as he did last time, only sit upon the stocks.`"

Upon this I said,
"`I desire you to make known openly what evil I have
done for which I must now be set in the stocks?`"

"`You have abused me,`" said the mayor; "`and told me I do not know the law.`"

"`Where is your evidence, replied I, to prove this?`"
And then calling out aloud I said, "`Is here any man that can bear witness for you,
that what you have now said is true?`"
But no man said anything for him.
Whereupon he being in a great rage, said, "`Constable, I command you to take him away,
for I am in earnest.
I`'ll bind him to his good behaviour.`"
Then the constable haled me out into the street, but did not put me in the stocks.

On the 24th day of the same month,
as soon as the mayor and his company were settled in the hall,
I spoke to them as follows.
"`It is generally known to you all, that the case here depending, wherein I am concerned,
ought not to be meddled with in this court.
And I have often appealed to such other courts as by the laws of
this nation are empowered to hear and determine such matters,
but I cannot be heard.`"

The mayor thereupon hastily said, "`Where is your order to remove it out of this court?
Show your authority and then you shall have it out.`"

I answered, "`If you had not allowed it to have been prosecuted here,
my adversary could not have proceeded.
And seeing I am likely to suffer by this court, here I am ready to undergo it.
But I desire that no snare may be laid to cause my bail to suffer,
by making return that I am not to be found;
seeing I am here ready and do render my body to undergo such sufferings
as this court has lawful power to inflict upon me.`"

"`You shall hear by and by,`" replied the mayor, "`what will be done in the court.`"

At that word came in my adversary, John Anderton, and said to me,
you must now go home on foot, for I have seized your horse.
And rejoicing in his wickedness he told his companions
that he had watched where I set my horse,
and having got a _"`Fieri facias`"_ sealed, he went with the Sergeant and took him,
and then made return of it in the court.

When I heard this I said, "`Seeing I am a sufferer by this court,
I desire to be resolved,
whether my now rendering my body to be a prisoner will not fully answer the law,
redeem my horse, and discharge my bail?`"
"`No,`" said the mayor, "`your horse cannot thereby be redeemed.`"
"`Why,`" said I, "`can my adversary keep my horse and yet come to trouble my bail,
seeing I do offer to render myself to be a prisoner?`"
"`No,`" said the mayor jokingly,
"`he will rather expect that you will come to town
again with another horse before it be long.`"
But my adversary, John Anderton, said, he would keep the horse,
and yet come upon my bail for the remainder.

The mayor, who was indeed my adversary also, told me,
I did trouble the court and was worthy to be set in the stocks.
"`Why,`" said I, "`what evil have I done or said?
If I have said or done any evil, make proof of it, and here I am ready to suffer for it.`"

Then the mayor asked me,
"`Are you provided with sureties for your future good behaviour?`"

I answered, "`I need not until some evil behaviour be first proved against me.`"
And after some more words to the same effect the court broke up.

At the next court, which was on the 31st of the first month, 1674,
return was made in the court, that my horse was sold for four pounds and five shillings.
But the horse with bridle and saddle, as he seized him, was well worth six pounds.

Then said I to the mayor, "`Is my attendance at this court any longer required,
or will any suffering come upon my bail if I should not be present here?`"

"`You may ask your attorney,`" said the mayor scoffingly,
because I would not retain an attorney.

"`But,`" said I, "`seeing you sit judge of this court,
it is but reasonable that you should resolve me this question,
that I may thereby understand what the court requires of me.`"

"`But,`" replied the mayor, "`I may choose whether I will answer you or not.`"

"`Well then,`" said I, "`so far as I understand the ground of my suffering by this court,
it is, because I cannot employ an attorney.`"

"``'Tis true,`" said the mayor; "`and I had once persuaded you to employ an attorney,
but afterwards you forbade him again.`"

"`I have given my reasons,`" replied I, "`wherefore I cannot do it; which are,
because the case wherein I am concerned is truly
a matter of conscience to me towards the Lord;
and none of these lawyers can take cognizance of it.
And besides, they are so self-ended and corrupt in their practices,
and deceitful in their proceedings,
that I have chosen rather to suffer by this court
unjustly than to have anything to do with them.
And although I seem vile and contemptible in your eyes, yet be it known unto you all,
that I am a witness for God against your corrupt and abominable practices.`"

"`Will you pray for them,`" said the mayor scoffingly,
"`and try if you can make them better?`"

I replied, "`I have peace with the Lord in my testimony against them.
And if they will go on still in their wickedness they will have a reward from God accordingly.
But I desire to know,`" said I,
"`whether my adversary`'s action against me is ended or not.`"

"`Your horse,`" said the mayor, "`is taken and sold; and they are so far satisfied.`"

"`But can they come upon my bail,`" said I.

"`I believe,`" said the mayor, "`they do not intend to trouble the bail,
but will rather stay to see when you will bring another horse to town.`"

Yet in a few days my bail was served with a "`Scire facias,`" as they call it,
to appear the next court-day.
And being called in court and not present to answer for himself,
I answered for him and said, "`The bail looks upon himself not to be concerned,
because my goods are taken away already, and I have often rendered my body for his,
which ought to have been received and he discharged long ago.
And if my goods which are taken away already do not satisfy,
or if my adversary have anything further against me,
I do here now also again offer to render my body
to be a prisoner that my bail may be discharged.`"

Hereupon the mayor said, "`You shall be heard anon; your turn is not yet come.`"
This put me by for the present; but after awhile the matter being in debate,
I spoke again and said: "`I desire there may be no proceeding against my bail,
but that he may be forthwith discharged;
seeing my adversary has taken away my goods and I have so
often rendered my body as you all know for his discharge;
it is altogether unreasonable and also unjust to proceed against him.`"

Then one Joseph Garrett, a counsellor at law, stood up, without my bidding, and said,
"`The bail ought to be discharged, because the principal has rendered his body.`"

The mayor then turning to me said, "`Have you employed him to plead for you?`"

I answered, "`There is no need of such a question; if he speaks truth,
he ought to be heard, whether I employ him or not.`"

"`If you will yet employ an attorney,`" said the mayor, "`his plea shall be heard;
but as for you, whatsoever you say, we will take no notice of it.`"

"`What!`" said I, "`shall I not have justice because I am not an attorney?`"

"`Yes,`" replied the mayor, "`you shall have justice; such as it is.`"

"`I know not any law,`" said I, "`that binds me to employ an attorney;
but you are bound both by the law and by your oath to do justice.
And if you, sitting judge in this court,
do see injury and injustice done and will not restrain it, but wink and connive at it,
it will certainly be charged upon you,
and before the Lord you will be found guilty of it.`"

"`It is true,`" said the mayor, "`I think so too.`"
But this spoke he in a scornful manner.

"`Then`" said I,
"`may not my bail have liberty until the next court-day;`"
and counsellor Garrett stood up again and desired it.
Whereupon the mayor said, "`Upon this motion of Mr. Garrett it shall be granted.
But take notice, I will not hear you after next court-day.`"
And then in a light manner he said to me,
"`You have learned skill and knowledge in the law by coming so often to the court.`"

Now after the court was risen, perceiving them still bent to go on wickedly and unjustly,
I was pressed in my spirit, in the consideration thereof to write again to the mayor;
and once more to warn him to fear the Lord and to do justice,
and to put a stop to and restrain those unjust and unrighteous proceedings,
which in their court they were carrying on against me.
And thus I wrote to him.

[.embedded-content-document.letter]
--

[.salutation]
Richard Pocook,

I desire you to consider and call to mind how you have dealt by me all along,
ever since you have been chief magistrate in Newbury; I say,
consider whether you have been as an impartial judge between me and my adversary;
and whether you have done towards me as you would be done by.
I appeal to God`'s witness in your conscience to give an answer,
and to plead with you on my behalf.
For the Lord God, the righteous Judge of heaven and earth,
knows your thoughts and searches your heart;
and the deceit and wickedness thereof is not hid from Him;
and unto Him an account must you give of all your deeds done in your body,
and a reward accordingly shall you receive, for there is no respect of persons with Him.
Therefore be not light and vain, but serious; and fear the mighty God,
for in His hand your life and breath is, who can take it from you when he pleases.
And in his fear and by his strength do I this day stand
a witness for him against the hypocritical hireling priests,
who serve themselves but not the Lord; and seek their gain from their quarters.
And also my testimony is against the greedy, covetous, fraudulent lawyers;
who for filthy profit sake will plead for anything, be it never so unjust.
I say, the Lord`'s controversy is against them all.
And he has raised me up to stand a witness on his behalf; and I do testify,
that they who do such things shall not escape his righteous judgments;
but his wrath and fury will surely be poured out upon them, except they speedily repent.
And for this my testimony, even for not feeding the priests,
and for not employing the lawyers, have I suffered by this court;
and am likely to suffer more, if the Lord prevent it not.
But as the cause for which I stand is the Lord`'s,
so into the Lord`'s hands have I committed both myself and it;
and he will surely plead it for me and take my part against all those that do oppose me.

Therefore I advise and warn you, to take heed what you do against me;
for whatsoever you do against me herein, the Lord will take it as done unto himself;
and will recompense you accordingly.
And if you do allow so great injustice to be done, as to cause my bail to suffer;
then know for certain,
that as such proceedings are hardly to be paralleled among tyrants and unjust judges,
and for such injustice you can scarcely find a precedent;
so shall your recompense be from the Lord.--Wherefore, in tender love to your soul,
I warn you to fear the Lord and do justice, if not for my sake,
yet for your oath sake and for your own soul`'s sake, let it be done,
and defer not to do it in this particular.
But if you are resolved thus unjustly to proceed,
then know assuredly that the Lord will appear for me and avenge my innocent cause,
and his judgments will seize upon you and his terrors
will compass you about as a perjured person,
and one that has been perfidious, and unfaithful, both to God and men.
Therefore, while you have time be faithful to do what the Lord requires of you;
which is to do justly and love mercy and walk humbly with him.
And remember you have been warned by him, who wishes your everlasting well-being.

[.signed-section-signature]
Oliver Sansom,

[.signed-section-context-close]
The 14th of Second month, 1674.

--

The same day I came with my bail to the court;
and the bail being called appeared and said,
here is the man himself who renders his body for my discharge,
wherefore I desire to be discharged.

The adversary, John Anderton, was not there himself; but his attorney pleaded saying,
"`It is now too late to render your body because the '`Scire facias`' is returned.`"
Whereupon I said,
"`I have offered to render my body almost every court-day for a great while,
only desiring to have my bail discharged;
and if the rendering my body before the _"`Scire facias`"_
was returned be sufficient to discharge the bail,
then surely this man ought to be discharged.`"

Thereupon two or three of the lawyers, being weary of me and willing to be rid of me,
stood up to plead for me, and said, they could bear witness that what I said was true;
for to their knowledge,
I had often rendered my body for his discharge before the _"`Scire facias`"_ was returned.
At that my adversary`'s attorney being offended asked them,
who employed them to plead my cause?
and many words thereupon passed between them in contending one with another.
But the Steward of the town, who bore a great sway in the court,
happening to be there at that time, when he understood the matter,
debated it with the rest, till at length he brought them to agree and conclude,
that the bail ought to be discharged upon my rendering myself;
and so forthwith he was discharged in open court.

Now was I a prisoner.
And as the sergeant was leading me out of court to the compter-prison,
some of the people asked why I would go to prison?
telling me it were better to refer the controversy into
men`'s hands to be ended between my adversary and me.

I told them, "`I had long ago proposed to his father,
and was still willing to stand to the same,
that if he could make it appear by the Scriptures of Truth,
that ministers of the gospel by any command of Christ or his apostles,
ought to receive tithes and force people to pay them,
then I would for whatsoever I had kept back restore seven-fold.`"

At this they seemed to deride me, and would hardly abide to hear it,
but told me that was not a place to talk of Scripture,
or to dispute about matters of the gospel.
Wherefore as I passed on from them I said, "`Seeing it is to me such a weighty matter,
and lies upon my conscience towards the Lord,
therefore I cannot commit it to be determined by men,
though they may be counted indifferent.
For in short it is thus with me,
that I shall rather choose to suffer the loss of all I have in this world, yes,
and my own life also, than consent to pay a farthing on this account.`"

Now I being a prisoner in the compter-prison,
the mayor gave a strict charge to the keeper that he should not
allow the Quakers to come to me lest there should be meetings.

After I had continued two weeks a prisoner,
the court sat again on the 28th of the second month, 1674.
And then my adversary John Anderton,
being vexed that in his absence the bail was discharged,
moved the court that he might come upon him again: and the steward not being there,
the mayor hearkened to him and granted his desire.
So that the poor man was constrained to employ an attorney to defend him,
although he had been before discharged in open court as aforesaid.
And then my adversary John Anderton entered another action against me also,
while I was a prisoner; which I continued to be,
upon process (as they called it,) but they did not proceed
to justice and execution until the 16th of the fourth month,
1674.
At which time the court being held,
the mayor commanded the sergeant to fetch me from the compter, which he did.
And when I was come into the court the mayor said to me,
"`I thought you had been at home before this time.
Come, here is an action laid against you for thirteen pounds
due to Charity Anderton upon account.`"

I, feeling the weight of their wicked spirits, stood still, and did not quickly answer.
Then some of the lawyers seeing the declaration laying before them, said to me,
"`Did you ever account with her for so much?`"
Whereupon I answered, "`I do owe her nothing,
nor did ever account with her for anything.`"
Then some interrupting me said, you had best employ an attorney;
and then you may defend yourself, overthrow your adversary, and recover costs.

But I replied, "`I cannot meddle with an attorney.
But this action is altogether unjust and the declaration most untrue.
For she might as truly declare against any man here
for accounting with her as against me,
for I never did account with her in all my life; neither do I owe her anything.`"

The mayor then, to ensnare me, said,
"`Bring here a book;`" which being brought he said to me, "`Come,
will you swear here before us that you owe her nothing,
and that you never accounted with her?`"
And as I began to speak, the mayor interrupting me said, "`Answer plainly,
will you swear or not?`"

"`I dare not swear,`" said I, "`whatsoever I suffer.
But I can testify, as in the sight of the Lord, that I owe her nothing;
nor ever accounted with her.`"
"`Then I must give judgment against you,`" said the mayor.
"`It seems then,`" said I, "`because I cannot swear, judgment must be given against me.`"
"`No,`" replied the mayor, "`that was offered but by the bye.
But you may employ an attorney, and then you shall have a legal trial.`"
"`Nay,`" said I, "`I cannot employ an attorney;
but I have committed my cause to the Lord who has hitherto preserved me;
and I believe he will now preserve me, and also deliver me in due time.`"

Then the mayor said to the sergeant, who was my keeper,
"`You had best look to him and keep him close; unless you will pay the thirteen pounds.`"
The sergeant said, he was not able to pay it.
But I said, "`I have been kept above two years already a close prisoner,
and not so much as saw my outward habitation,
and all for this very matter that this is grounded upon.
But what did he gain who was the cause of it?`"

"`But I,`" said my adversary, "`will keep you twenty years now if I live so long.`"
"`You can do nothing at all,`" said I, "`against me, unless the Lord, give you leave;
and then he will give me strength to bear it.`"

So judgment being entered against me, I was had back to prison;
and two days after an execution was taken forth upon which I was to be kept close.
And then my keeper dealt hardly and cruelly with me for some time;
seeking to compel me to satisfy his unreasonable demands for lodging, etc.
Which because I could not bow under nor submit to,
I suffered some hardship in the prison, upon which I fell sick;
and my sickness turned to the smallpox;
which was so sore upon me that I was nigh unto death.
But it pleased my tender God to be my good physician, and to raise me up in his own time.

[.offset]
+++[+++The following is a copy of a letter he wrote to his wife
from the Compter-Prison of Newbury at this period.]

[.embedded-content-document.letter]
--

[.salutation]
My Dear Wife,

My dear and tender love does truly reach unto you in the uprightness of my heart,
breathing for you as for my own soul that the Lord
may fill us both with his heavenly life,
and to cause the fresh supplies thereof to be renewed unto us,
as duly as the morning and evening comes upon us.
Oh! that our hearts and souls were always waiting for it,
then surely should we be as a well-watered garden, fresh and green and lively,
giving a pleasant smell unto the Lord our God in the sight of all people.

Dear heart, by this you may know that my distemper does wear over quickly,
and I am pretty well at present, blessed be the Lord;
and the beginning of next week my nurse intends to wash and air the clothes and room,
and to be ready to go home on fourth or fifth-day next,
if you do not send for her before.
Indeed I have longed much to hear from you,
as I believe you have desired to hear from me, but cannot hear very certain;
only this day I received a few lines from your sister,
which certified me you were very little amended of your distemper on last second-day,
but how is it with you since I cannot hear.
But if you are pretty well, I desire you not to venture to come to me,
until you hear further from me, but let me hear from you as often as you can.
My dear love is to your sister,
and her tender love and care of me is not by me forgotten,
but remains as a seal upon my heart by that tender
Spirit of Truth which is the cause of it;
but I do expect to write to her this day a nearer way if I can.
However, let her see this letter,
and my love is to Betty and also to all her friends that love the Truth.
I rest,

[.signed-section-closing]
Your dear husband,

[.signed-section-signature]
O+++.+++ S.

[.signed-section-context-close]
Newbury Compter-Prison, 9th of Fifth month, 1674.

--

While I was thus in prison, the woman at whose suit I was imprisoned,
whose name was Charity Anderton,
speaking with a Friend who was coming to visit me in the prison,
desired him to remember her love to me and to my wife;
whereupon something arose in my mind to write to her; which I did thus.

[.embedded-content-document.letter]
--

[.salutation]
Charity Anderton,

I understand that A. H. had some discourse lately with you concerning me,
and that you did bid him remember your love to me and my wife; and that you also said,
if I would send you some money,
then I should see how reasonable you would be with me or the like.
Now this I say, if you had any true love in your heart to me or my wife,
I think you could not deal so by us, as you have done;
for your son to forge a lie in your name against me, after this manner, viz:
that I accounted with you for such a sum of money,
on such a day of the month within the liberty of Newbury,
and that I promised you payment; yet notwithstanding, though often desired,
refused to perform my promise.
Upon such a wicked lie is your suit brought against me,
and an execution thereupon procured to keep my body close in prison.
And in that time I was visited with the small-pox in the prison:
whereupon my dear wife hearing that I was sick came to be with me,
and tarried with me about a week; and then she beginning to be sick also,
my keeper fearing she would have the same distemper,
would by no means allow her to continue in the prison with me.
And so she being ill and in danger of the distemper, was by force separated from me;
and though I lay then very weak,
she was constrained to get a man and a horse to carry her to our habitation at Farringdon,
being about twenty miles off.
I tell you truly,
that this thing was harder to me than anything I suffered by your husband.
And if this be some of the fruits of your love to us, then I must tell you,
this love of yours is very great cruelty.

But yet the tender love of the Lord my God has indeed been
manifested and extended to me in a very large measure,
in preserving and strengthening me and raising me up again;
so that now I am pretty well recovered;
blessed and praised be His Holy Name over all forever.

And as for sending you money, this I tell you in the integrity of my heart,
that I cannot nor dare do it, be it never so little;
for I am convinced and certainly persuaded and satisfied in my conscience,
that if I should do such a thing,
I should sin willfully against the Lord and bring condemnation upon my own soul.
Therefore I shall rather choose to suffer the loss of all I have in this world, yes,
my very life also, rather than consent to do such a thing:
therefore let your expectation concerning that matter be at an end.

And now the Lord has allowed you to cast my body into prison,
you may remember your husband did the like for the
very same wages which you do now pretend to claim.
O consider, what profit did he reap thereby?
Or what benefit was it to him?
Was it not his burden on his dying bed?
And do not you look for nor expect any other than the same reward that he had;
because your deeds are the same with his.
For the Lord who was with me then is with me now;
even the same God that kept me and delivered me out of the hand of your husband.
To him have I committed my cause and he will plead it with you in his due time;
for in his hand your life and breath is, and you shall not be able to escape his justice;
but his righteous judgments will overtake you and
your reward will be according to your deeds.

But I do hereby acquaint you, that I desire no revenge upon you;
but leave you to the Lord to plead with you and make known my innocency unto you.
And the Lord is my witness that in true love to your
soul I have besought the Lord for you,
desiring that he would put it into your heart to cease your cruelty towards me,
because I know it will turn to your hurt and sorrow in the end.
And that you may also come to do those things which the Lord requires of you,
which if you were faithful it would conduce to the
peace and well-being of your soul forever.
And I can truly say that I have true love in my heart towards you;
although you are my open enemy, and I am a sufferer by you.

[.signed-section-signature]
O+++.+++ Sansom.

[.signed-section-context-close]
Newbury Compter-Prison, the 23rd of the Fifth month, 1674.

--

Now I was settled in prison upon an execution not to stir so much as without the door;
and without any prospect of deliverance or ground to expect it.
But I was well satisfied in the will of the Lord, being fully resigned to him,
and desiring his will might be done in all things; and as he knew what was best for me,
so my breathings were unto him, that he would glorify himself in and by me,
whether in bonds or at liberty.
And as I was thus given up in my spirit and quietly satisfied in my suffering,
the Lord made way for my release in a sudden and unexpected manner;
which thus was brought about.

During the time of my imprisonment,
it pleased the Lord to send a great distraction among the magistrates of Newbury,
even such a confusion as had not been known nor heard
of in that place since it was a corporation.
For George Cowslade, who had been mayor the year before,
and who when he was going out of his office had granted the first warrant against me,
was taken away by death; and this Richard Pocock, the next imperious mayor,
in the height of his pride and ambition was pulled down from his chair with shame,
as I had forewarned him he should be.
For the Lord, in his justice,
does allow confusion to fall upon the wicked who have despised his mercy;
so that one wicked man becomes a scourge unto another;
and by such ways and means the Lord sometimes does
bring deliverance unto those that trust in him;
and so with respect to my imprisonment, it was in that place at that time.

For the priest of that town and this lofty mayor fell at strife about
the receiving of that which they call the Sacrament of the Supper,
and being both of them proud and high-minded men,
so that neither of them could well abide an equal in that town, they fell out,
as was said, about their bread and wine to that degree,
and the enmity on both sides rose up to that height,
that no agreement could be hoped for between them; but to law they would go,
and did with might and main.
And being both of them exceeding subtle and expert in the law,
for the mayor was a lawyer by education;
and the priest was better acquainted with the law than with the gospel;
they seemed for a great while so equally matched every way,
that the lookers on could not discern which of them was most likely to have the victory;
though most thought the mayor would have carried the cause until the very last.
But when at the court session, which was held at Abingdon in the fifth month 1674,
they came to trial, the priest overcame and got the victory over the mayor,
and brought him under so low that he was fined in a great sum of money,
and turned out of his place of mayoralty beside.
And he being thus shamefully degraded from his office,
all the proceedings which had been in that court,
and the judgments thereupon given under his authority from the time called Easter past,
were made null and void; and thereby my imprisonment became contrary to law.

Whereupon one of my relations began to stir in the business,
both to procure my liberty and to call my adversary
John Anderton in question for my false imprisonment.
Which when he understood, he sought by all means to have it put to reference;
which that relation of mine hoping to be awarded a great
sum of money for my false imprisonment agreed unto,
without any either consent or knowledge of mine.
But the persons to whom the matter was referred never brought it to any conclusion,
and so it rested ever since.
But within something more than a year after,
my envious adversary John Anderton died miserably, having been a filthy, lewd,
unclean person.

Thus it pleased the Lord to work my deliverance;
so that on the 22nd day of the seventh month, 1674,
after I had suffered imprisonment twenty-three weeks,
not without some hardship and much hazard of my life, I was set at liberty;
but the whole time that I was entangled in that court from the first to the last,
was a whole year and some days over.
But in all my sufferings and exercises the Lord was with me and supported me;
so that I have great cause to say, the Lord is worthy to be trusted in and waited upon,
for his fatherly care and tender compassions never fail; but his mercy endures forever.

During the time of my exercise and sufferings in Newbury-court aforesaid,
an exercise of another kind befell me in a controversial way with one Benjamin Woodbridge,
a preacher to the Presbyterians there.
Which though it began and ended before I was set at liberty,
and so in point of time should have come in sooner,
yet I chose rather to reserve it to this place, than by bringing it in before,
to interrupt the account of my trials there.

This Benjamin Woodbridge had been priest of Newbury in the times of the Protectors.

But when King Charles the Second was restored to the crown he was displaced;
and thereupon lurking up and down, hid himself in holes and corners to avoid persecution,
until the time that the king sent forth his declaration for liberty of conscience;
and then he crept out again and coming to Newbury, where he had been priest,
preached openly; and had great meetings for some time in the Market-house,
and afterwards in a barn.
In one of those meetings more especially,
did this non-conforming priest open his mouth wide against us the people called Quakers.
Which I hearing of, a concern came upon my spirit to write to him about it,
and that drew on for some time an exchange of letters between us;
but the occasion of my first writing to him,
was upon some words which I was told he spoke privately against us,
to a young man to dissuade him from coming to our meetings.
And that which I wrote to him was thus.

[.embedded-content-document.letter]
--

[.salutation]
Benjamin Woodbridge,

I had lately some words with a young man who was a follower of you,
but he has since come among us at our meetings.
Yet before he left you,
being well persuaded of the way and truth which we believe in and profess,
and not finding that with you, which could truly satisfy, he went to you,
as I understand, for advice,
desiring you singly to give your judgment concerning
going to the meetings of the people called Quakers,
Whether it was a duty or a sin to go to them?
And your answer to him was, Doubtless it is a sin.

Now for the truth`'s sake, which is dearer to me than my life,
I am at this time concerned to write unto you, and in the fear of the Lord to charge you,
as you will answer it before Him in the dreadful day of account,
that you declare plainly what you know or can prove
concerning the doctrines which we hold forth,
or our usual practice of meeting together to worship the Lord,
which may be any ground for your assertion before-mentioned, namely,
That it is a sin for people to hear us.
For if it be a sin for people to hear our doctrines surely then
it must needs be a greater sin to them who preach those doctrines;
and the doctrines themselves must needs be sinful and contrary to truth and righteousness,
which cannot be heard without sin to them that hear them.
Therefore I do again in God`'s fear,
charge you to declare and make known in writing plainly and publicly,
wherein the doctrines which we hold forth do any way tend to lead people into sin.
And further, I challenge you to make it appear, wherein and in what particulars,
our doctrines and principles are contrary to the doctrines of Christ and his apostles,
recorded in the Scriptures.
Leave off back-biting, come forth and be plain-hearted for we desire no favour from you.
If our meetings be so sinful and dangerous,
make them appear so if you can in the sight of all people.
But if our meetings are indeed only to wait upon the Lord,
and to worship him in Spirit and in Truth;
and our preaching and doctrines are only to stir up people to righteousness and holiness,
and you can not prove the contrary,
then you ought to confess you have wronged us and suggested falsely against us.
So come forth plainly and honestly, and let us know what you have against us;
or else lay your hand upon your mouth,
and let your silence be a clear evidence to testify for us,
and for the purity of that way and worship which the Lord has made known unto us,
and has owned and preserved us in, I remain, A lover of truth and plainness,
but a witness against backbiting and deceit,

[.signed-section-signature]
O+++.+++ Sansom.

[.signed-section-context-close]
The Second month, 1673.

--

This letter was delivered to him, but he never returned any answer.
So that although, serpent-like,
he had crept behind us and attempted to have bruised our heel,
by smiting secretly at us behind our backs;
yet it was clearly manifest by his silence at that time,
that he dared not appear openly to our faces to make good what he had said against us,
notwithstanding he was challenged and provoked to it.
And so his silence in not answering my letter might be taken as a clear evidence for us.

After this I heard not of anything he said concerning us for about half a year.
In which time our Friends having taken a house to meet in,
which stood in a more public place than where they met before,
he from there began to break forth against us in
preaching before a great assembly of people;
so that it was generally talked of both in town and country,
how he endeavoured to render us and our principles odious to his auditory.
Yet had it not altogether the effect he wished;
for many of his hearers were not pleased with him for it,
and some of them spoke to me about it, relating much of what he had said against us;
and one of them in displeasure, said he never heard the like before.

When I had pondered these things in my mind,
I was troubled and grieved in my spirit for the man; considering how unmanly, yes,
how uncivilly, and most unchristian-like he had dealt with us,
in refusing to answer my letter,
whereby he might have let us understand plainly what he had against us;
and yet to retain such envy and malice in his heart against us,
and to belch it out in such a noisome manner,
even as much as in him lay to incense the peoples`' minds with prejudice,
and to raise them into enmity against us.
Wherefore I was much pressed in my mind to write to him again in much tenderness,
desiring and even entreating him to give me under his hand
in writing what he had declared openly against us;
and this I did, to the end that if possible I might bring him forth,
openly upon the stage as it were, either to prove what he had charged us with,
or else to clear us of it.
Wherefore I wrote thus unto him.

[.embedded-content-document.letter]
--

[.salutation]
Benjamin Woodbridge,

Forasmuch as it is commonly reported both in town and country hereaway,
that upon the 9th day of this month, you preaching at Newbury,
did in your sermon speak very much against the people called Quakers;
charging them to hold very dangerous principles,
and as deniers of the chief fundamental points of religion,
and the true marks of a Christian; and also,
that what they made a show of outwardly in point of worship, etc.,
is but mere deceit and hypocrisy, to gain proselytes; and much more to this purpose,
it is generally reported,
you did then and there speak and declare to a multitude of people,
who were at that time congregated together.

Now I being a man who for some time have walked among those despised people,
and being in my heart well-persuaded of the truth of their doctrines and principles;
and in the fear of the Lord God I can speak it,
it has been and is the real intent and purpose of my heart
to serve the Lord and to be given up to follow him fully,
and to obey him in all things that he requires of me,
according to the light and understanding he has given me.
I can truly say,
I count not anything in this world dear unto me so that I may receive the end of my hope,
even the salvation of my soul,
and that I may finish my course with joy and lay down my
head in peace when time here to me shall be no more.
This is the real intent and purpose of my heart, and the sincere desire of my soul;
as the Lord, who searches the heart, knows and can bear me witness.
And I have often desired and do truly wish that all people, yes, my very enemies might,
if it were possible, know and understand the most secret intent and bottom of my heart,
as the Lord does.
And so, I myself detesting all deceit and hypocrisy, and having no manner of reserve,
but desiring to appear the very same outwardly before men,
as I am inwardly before the Lord; and being innocent myself,
I have no ground to question,
but have good cause to believe my brethren and sisters are so as well as I. Therefore
I marvel how you could speak against us and judge so hardly of us,
as you did; as to charge us with hypocrisy, or the like.
And I do in meekness desire this of you,
that you will give me under your hand the substance of what you did then speak;
and whatsoever you have more against that people.
For this I dare promise you, in the fear of the Lord God,
that if you can prove that the people who in scorn are called Quakers,
do hold any tenets or principles,
or teach anything for doctrine that is contrary to the commands of God,
or disagreeing with the doctrines and precepts of Christ and his ministers,
mentioned and recorded in the Holy Scriptures;
I shall be willing and ready openly to revoke and disown all such principles and doctrines,
which by the Scriptures can be proved to be contrary to the principles and doctrines,
of Christ and his apostles.

And as truth seeks no corners and innocency needs no covering,
so I desire you in plainness of heart to grant me this request;
and expecting to hear shortly from you,
I remain A true lover of all those that love truth in sincerity.

[.signed-section-signature]
Oliver Sansom.

[.signed-section-context-close]
The 26th of the Ninth month, 1673.`"

[.postscript]
====

P+++.+++ S.--When you write, direct your letter to be left with Robert Wilson in Newbury for me.
I wrote to you about half a year ago, but never yet received any answer;
I desire to know the reason.

====

[.signed-section-signature]
O+++.+++ S.

--

This letter was delivered to him, and seemingly well received by him;
and some of his hearers who were intimate with him reported he did say,
he would answer it as soon as he was able to use a pen.
For suddenly after he had preached so bitterly against us,
he was taken with a great weakness of body,
which some said was from the gout in his hands and feet;
but after about three weeks time he began to handle his pen again,
and sent me the answer following:--

[.embedded-content-document.letter]
--

[.salutation]
Oliver Sansom,

I received a letter from you about a fortnight since,
when I was under so much bodily weakness that I could not write,
nor am I yet well able to do it;
but for some reasons am unwilling your letter should lie any longer unanswered;
the rather because it is written with more sense
and sobriety than any that I have formerly received,
either from yourself or any of your party.
For the reports you may hear, I neither am nor will be accountable;
and if you have heard all you write, you have heard more than is true.
That which I delivered, in reference to your party in general,
was briefly to this purpose.
Namely,
that I heard there was a certain sort of infidels
(meaning thereby you Quakers) setting up in town,
no doubt in hopes of a great harvest of proselytes,
against whom I thought it was my duty to caution my hearers.
Having used the word infidel, I gave the reason of it,
as the matter I was then upon led me to; namely,
that I did not know any visible sign or mark by which
men were known in the world to be Christians,
and distinguished from all other religious sects, according to the Scriptures,
which you did own.
I instanced particularly in four, the most known and universal marks of Christians.

1.--Baptism into the name of our Lord Jesus Christ;
without which no man is to be owned as a Christian,
in communion with the church of Christ.
But neither do you baptize your proselytes into the name of the Lord Jesus Christ;
and the baptism you received in your infancy you reject.

2.--The celebration of the Lord`'s Supper; a special act of Christian worship,
to be continued in the church in remembrance of Christ to the world`'s end.
But neither have you this supper of the Lord celebrated among you;
and some of your authors write contemptibly, that I may not say blasphemously, of it.

3.--The sanctification of the Lord`'s Day, which you also disclaim;
indeed you keep your meetings then as you do upon occasion on any other day of the week,
but not in acknowledgment of any special sanctity by the
Lord`'s institution in that day more than any other,
or of any special duty which lies upon you to keep that day holy more than any other.

4.--The offering up all our worship to God in the name of our Lord Jesus Christ,
as our only mediator and advocate,
through whom alone we can expect that we or our services can be accepted of God,
But neither do you seek mercy of God for the sake of Christ, nor do you offer up prayers,
praises, thanksgivings, etc., in his name.
And if some of your speakers do sometimes mention him with some kind of honour;
yet it is no more than the Turks do, who are yet far from being Christians;
for they acknowledge him a great Prophet sent of God.
Upon all of which considerations I declared then, and now declare the same to you,
that you are not to be owned as Christians;
nor may the church of Christ or any particular Christian
have any communion with you as such.

This was the substance of what I then spoke more at large;
which for preventing of uncertain rumours I have sent you written,
as well as I am at present able, with my own hand and my name subscribed.

[.signed-section-signature]
Benjamin Woodbridge.

[.signed-section-context-close]
December the 18th, 1673.

--

[.offset]
Unto this letter I returned the following reply:

[.embedded-content-document.letter]
--

[.salutation]
Benjamin Woodbridge,

Your answer to my last letter I received, and I take it kindly from you,
that you have so far fulfilled my desire, as to give me under your hand,
the substance of what you did declare,
and yet remains in your heart against us the despised people called Quakers.
And upon the perusal of what you have written, and searching the Scriptures,
I find that your charge against us,
and your judgment and sentence thereupon is not agreeable to the Scriptures,
nor can be proved or maintained thereby.
And being willing to open my mind plainly and nakedly to you,
and desiring in the uprightness of my heart that all scruples might be removed,
that the plain truth might clearly appear and be manifest in the sight of all people;
and expecting you will not be backward to explain and prove
by the Scriptures what you have charged upon us--I shall,
according to the understanding the Lord has given me,
mention those things by way of reply concerning which I am dissatisfied.

You are pleased to term us infidels, etc., and speak of our setting up in town,
in hopes to reap a great harvest of proselytes.
Which words, as it seems to me are written in derision of us;
therefore at present I shall pass by that,
and reply to that which in your letter seems to be more weighty.

And to prove us infidels, you say you know no visible sign or mark by which men,
according to Scripture, were known in the world to be Christians, which we did own;
and you instance four marks or signs.

The first mark was baptism into the name of the Lord Jesus Christ.
These words, as you have laid them down we do clearly own;
and do believe that none can be owned as Christians,
nor have communion with the church of Christ, but they who are baptized into his Name,
which is mighty and powerful, as it is written, Phil. 2:10-9.
"`That God has given him a Name, which is above every name;
that at the name of Jesus every knee should bow,
and every tongue should confess that he is Lord, to the glory of God the Father.`"
Now the outward name Jesus, which signifies a Saviour,
was given as a signification of that inward virtue, life and power,
by which he would save his people from their sins; as it is written,
"`His name shall be called Jesus: for he shall save his people from their sins.`"
And "`He shall reign over the house of Jacob forever,
and of his kingdom there shall be no end,`" Matt. 1:21. Luke
1:23. And as his kingdom is an everlasting spiritual kingdom,
so His name and power, by which he saves his people from their sins,
and delivers them from their soul`'s enemies, must needs be spiritual.
And this is the name, and there is no other given among and in men,
whereby they must or can be saved from their sins. Acts 4:16.
And the apostle Paul mentioned some who had been great sinners,
but were cleansed and washed, etc., in the Name of the Lord Jesus,
and by the Spirit of our God, 1 Cor. 6:11. And so,
this inward washing is no other than the baptism of the Spirit.
By one Spirit, said the apostle, we are all baptized into one body, 1 Cor. 12:23.
And although in Scripture this inward washing is in several ways expressed,
yet the power is but one by which it is effected; and the baptism also is but one,
which is effectual to salvation.
For as there is but one Lord and one Faith, so also but one Baptism.
And this only is available; and in the church of Christ will ever remain.
And this one inward, substantial baptism, into the name of the Lord Jesus Christ,
we do own as fully as you can do.

And this which is the foundation of your first charge being removed,
the charge that is built thereupon must needs fall to the ground.
And as concerning sprinkling of infants,
I suppose you are not ignorant that it was an institution of the Church of Rome,
invented and set up in the night of popery, with the sign of the cross,
godfathers and godmothers and the like, being an unscriptural practice,
I think you will hardly plead for that.

Your second mark is the Lord`'s supper; which, as you have worded it,
we do clearly and fully own;
and we do believe it will always be continued in the church of Christ:
not only in the remembrance of him, but in the sensible enjoyment of his presence;
and our communion herein with the Lord and one with another is in Spirit,
as all true Christian worship is, as Rev. 3:20. 2 Cor. 5:16. John iv.
And so this which is the ground of your second charge being taken away,
the charge that is founded thereupon must needs tumble down.

And as for outward bread and wine, (which you do mean,
yet you have not mentioned,) about which there has been in Christendom so much contention,
strife, confusion, and bloodshed, it is, and ever was, at the most,
but a sign or shadow of this substantial spiritual supper.
But I desire you to let me know the names of those authors who have written
either blasphemously or contemptibly of the supper of the Lord.
Let the books and pages be quoted; and as a minister of Christ said in another case,
so say I in this; he is not a Christian who is one outwardly;
neither is that the true baptism and supper which are visible
and can reach only but to wash and feed the body,
which are but the shadows of the true.
But he is a true Christian who is one inwardly;
and that is the true baptism--that the true supper, which is inward in the Spirit,
not in the letter or shadow, whose praise is not of men, but of God.
And I believe that wicked men may have these outward marks,
and yet be no better than infidels.
But they that are, with the Holy Spirit, baptized of Christ into His name and power,
and feel his fan thoroughly to purge the floor,
and his fire unquenchable to burn up the chaff, and then come to sup with him,
and abiding faithful, follow his leadings,
taking up the daily cross in the true self-denial, I am persuaded that such,
however they may be accounted of by men, will never be condemned by the Lord,
for not practising the signs or shadows before expressed.
For the saints in days past did not look at the things that were seen,
but at the things that were not seen; because the things that were seen, were temporal;
but the things that were not seen, were eternal.

Your third mark is concerning the Lord`'s day: which you say we disclaim.
This seems to be a downright charge, but grounded upon little or no foundation;
and as little proof.
But to consider simply of your words; what day is it,
which according to Scripture testimony may most properly be called the Lord`'s day?
I believe that as the Lord, who is from everlasting to everlasting, is a Spirit;
so His day is a spiritual everlasting day.
And this is clear from the words of Christ, John 8:56, who said,
"`Abraham rejoiced to see my day; and he saw it, and was glad.`"
And so He who was before Abraham was, who is King of kings and Lord of lords,
that day which he owned and called His, who shall gainsay or contradict?
for every tongue must confess that he is Lord.
And this spiritual everlasting day of the Lord Jesus
Christ may most properly be called the Lord`'s day,
and in the light of this blessed day are the things
of God seen and revealed by the Holy Spirit,
according to his own will and pleasure.
On this blessed day was John in the spirit when those deep things were revealed to him.
Rev. 1:10, which are left upon record in that book.
Much more might be said concerning this holy day of the Lord.
But this may let you know that we do not disclaim,
but according to the Scriptures do truly own the Lord`'s day: and blessed be the Lord,
we do in measure joyfully witness the glorious dawning and appearance of it.

By your following words, I guess your meaning to be an outward day.
Now I do believe that it is the duty of every true Christian
to be always in the Spirit serving the Lord,
and to live to him every day: for it is clear to me, that every day is the Lord`'s day.
But if it be not our principle to observe a day altogether according to your persuasion,
that is for any special sanctity by the Lord`'s institution,
in that day more than in another, as you express it;
yet seeing in practice we are as diligent, for ought I know, in keeping our meetings,
as any of you are; therefore, I think your censure is exceedingly harsh.
And therein it plainly appears, you are not of the apostle Paul`'s mind, who said, Rom. 14:5.
"`One man esteems one day above another; another esteems every day alike.
Let every man be fully persuaded in his own mind.
He that regards the day, regards it unto the Lord,`" etc.
And he exhorted them not to judge one another for it.
And he also reproved some who, after they had begun in the Spirit,
were in the observation of days and times, which he called weak and beggarly elements. Gal. 4:10.
And further he said, "`Let no man therefore judge you in food or in drink,
or in respect of a holy day, or of the new moon, or of the Sabbath-days,
which are a shadow of things to come; but the body or substance is Christ.`" Col. 2:16.
And he that is in Christ does find rest for his soul;
and so is ceased from his own works to keep the holy Sabbath-day in Christ:
and here is the true Christian Sabbath known,
of which the seventh-day was but a sign or shadow.

As for your fourth mark, you are greatly mistaken in us,
and do very much wrong us to conclude so of us as you do.
But I am tender in judging you,
until I hear what ground you pretend to have for this assertion; for I assure you,
this charge is altogether false:
therefore let me know from what ground or information you did write it; for I testify,
that our meetings are in the name of our Lord Jesus Christ; and his presence,
according to his promise,
is witnessed and enjoyed in the midst of us to our great comfort and refreshment;
and in his name are prayers, praises and thanksgivings offered up to God the Father;
who has sent the spirit of his Son into our hearts whereby we can call God our Father.
And without this Spirit we cannot pray as we ought, but it "`helps our infirmities,
and makes intercession for us with groanings which cannot be uttered.
And he that searches the hearts knows what is the mind of the Spirit;
for it makes intercession for the saints,
according to the will of God,`" Rom. 8:26-27. And it is only in and
by this Spirit of Christ Jesus that our offerings and services are accepted:
for without him, as himself said,
we can do nothing that is acceptable or well-pleasing to the Lord.
And all they that have received Christ Jesus, who is a quickening spirit,
come to be quickened and made alive to God by him,
and come more and more to be renewed in the spirit of their minds,
even to bear His image and appear in his likeness.
And by his power and virtue they do bring forth fruits
of righteousness to the glory of God the Father;
and as Christ Jesus was, so are they, in this present world;
but the world knows them not,
"`because it knew not him,`" 1 John 3:1. And this is the
true spot or mark by which the children of God are manifest;
as the children of the devil are by the lack of it: he that does righteousness is of God;
but he that does not righteousness is not of God, nor he that loves not his brother,
1 John iii.
And thus every tree is known by the taste and relish of the fruit it bears,
and not by the gloss or colour of the leaves only.

By what has been said,
it is evident that those outward marks or signs which
the scope of your letter seems to point at,
as water, bread and wine, and the observing of one certain day in every week,
and to cry Lord, Lord: all this a man may have and do, and yet not be a real Christian,
but a worker of iniquity, and be excluded the kingdom of Heaven.

Now for the further clearing of these things before treated of,
I shall propound two or three queries, which I desire you to return a plain answer to,
according to the Scriptures:

Q+++.+++ 1. Whether there is any express command from Christ that
the baptism with water must always remain in the church,
yes or no?
If yes,
then who are now sent of Christ to baptize that have
larger commission than the apostle Paul had,
who said, that he was not sent to baptize, but to preach the gospel.

Q+++.+++ 2. Whether there is any express command from Christ or his apostles,
that outward bread and wine, which is but a sign or shadow,
must always be received in remembrance of Christ`'s death by every member of the church,
when Christ is come who is the substance,
and his life risen and witnessed dwelling in them?
Answer, yes or no?
If yes, then declare how and in what manner it ought to be celebrated.
For I suppose you are not ignorant what division there has been,
and `'tis likely still is, in the world about the form and Manner of it.

Q+++.+++ 3. What command or institution is there from Christ,
which does require or enjoin Christians to keep one day in a week more holy than another?
or to prefer one day above another?
seeing the Lord does every day provide for us and does not fail to feed us;
giving us day by day our daily bread,
and affording us life and being and all things needful both outwardly and inwardly;
then surely, ought we not rather to live to the Lord every day,
and to serve him with all our might, and to keep every day holy to Him?
For which day is not the Lord`'s day?
Did not he create all the seven days?
And did he not create man to serve him all the days of his life?

And as to your judgment against us in the conclusion of your letter,
in condemning us for infidels;
and your sentence of excommunication from having any communion
with the church of Christ or any particular member thereof;
surely this is not only harsh and cruel, but it seems to me to be altogether unjust.
What! condemn a man or a people without hearing?
As Nicodemus who was a ruler of the Jews once said,
"`Does our law judge a man before it hear him and know what he does?`"
And by the laws here in England,
the greatest malefactors are called to the bar and hear
their indictment read and are permitted to plead to it,
guilty or not guilty; and before they can be condemned,
there must be sufficient evidence brought to prove the indictment true.
I desire you to consider of these things,
and seeing you have taken upon you to be our judge, I only desire justice of you,
and do crave no more than the law allows transgressors.
And if those things charged against us in your letter must be our bill of indictment,
then let this my reply serve for a plea to it, that we are not guilty.
And now it remains that you bring sufficient evidence
to prove that which you have laid to our charge,
and so let us come forth fairly to trial;
and if upon trial we cannot clear ourselves of these things charged against us,
by and according to the Scriptures of truth;
then let judgment be given against us and sentence passed upon us.
But if we do appear clear,
and you are not able to prove the things you have charged upon us; or if,
being conscious to yourself that it cannot be done,
you will not come forth to a fair hearing and trial;
then this I desire of you and do claim as justice, that you give forth under your hand,
an acknowledgment that you have wronged us and were mistaken about us,
and that we are not such people as you did take us to be,
and that you be as diligent publicly to clear and
acquit us as you have been to charge and accuse us.

And although you now appearing as our accuser and judge,
and we standing at present as it were arraigned at your judgment seat,
I have not charged you with any unsound principle;
yet I would not have you or any other therefore think that
I can produce nothing justly against you and your party,
concerning matters of religion; for I hereby let you know,
that upon good ground I have cause to question, if not plainly to charge,
that those people called Presbyterians, do hold many things relating to religion,
which are not agreeable to nor warrantable by the Scriptures of truth.
But I shall pass that by at present;
being willing first to hear all that you can say
against us and to know your proof for it,
that I may appear clear myself, before I take upon me to question another.

Wherefore, whatsoever you know against us the despised people called Quakers,
I entreat you not to keep it back; and as I promised you before,
I am still in the same mind,
that if you can prove that we hold anything contrary to the Scriptures and sound doctrine,
I shall be ready and willing openly to revoke and disown it.
For my judgment is,
that it is as much a duty and as noble a mind in anyone to disown and renounce an error,
when convinced of it, as it is to contend for and vindicate the truth.
So upon your serious perusal of this my reply, I shall expect from you a more mild,
considerate and Christian-like answer; and do still, and hope ever shall remain,

[.signed-section-closing]
A lover of the truth, as it is in Jesus,

[.signed-section-signature]
Oliver Sansom.

[.signed-section-context-close]
The 24th of the Tenth month, 1673.

--

[.offset]
About a week after I received from him this following answer:

[.embedded-content-document.letter]
--

[.salutation]
Oliver Sansom,

Yours of the 24th instant I received.
When I had read the beginning of it I could not but expect that in the following part
I should have met with a denial of something which I had spoken against the Quakers,
a term which I use not in scorn but of necessity,
but my expectation failed me altogether; for I met with no such thing,
but rather a confession of all I said, except in the fourth particular.
So that if I needed it, I should henceforth make you my witness that I spoke the truth.
And yet after all this, you tell me towards the end of your letter,
that you are not guilty, and demand of me to prove,
and that from the Holy Scriptures too, what I have laid to your charge.
If you have no more understanding or regard of what you affirm or deny,
you must not expect that I should concern myself for anything you write to me.
I charged it upon the Quakers, that they denied the visible signs of Christianity,
as namely, baptism.
Lord`'s supper.
Lord`'s day.
Do you deny this?
not a tittle of it, but rather confess it plainly and fully.
Only you tell me of an internal baptism, Lord`'s supper and Lord`'s day; which,
whatsoever you mean thereby, I never accused you of disowning,
but of that only which is external and visible,
by which you may be seen and known in the world to be Christians,
and consequently owned as such by them who are Christians;
and without which you are not to be received into
visible communion with the church of Christ.
Not that I am forward to believe he can own the Lord Jesus in his heart,
or be a Christian inwardly, who shall willingly and deliberately,
and without temptation reject these institutions of his,
wherein it is his pleasure his name should be professed outwardly in the world;
but my matter not leading me to it, I speak not a word of it.

As to the fourth particular of your not offering your worship to God in
the name of the Lord Jesus Christ as our only mediator and advocate,
through whom alone we can expect that we or our services can be accepted of God;
you tell me this charge is false, and why?
because his spiritual presence is enjoyed in the midst of you,
and you offer up your prayers, praises and thanksgivings by his spirit;
and it is only in and by this spirit of Christ Jesus
that your offerings and services are accepted.
If this last clause be true,
it seems you have so good an opinion of the perfection of your services by the spirit,
that you need no mediator or advocate at the right hand of God to further their acceptance.

But you should not have perverted my plain meaning:
I mentioned the offering up of our worship to God in the
name of Christ as the visible mark of a Christian,
and therefore must needs mean the Lord Jesus so expressed in our worship,
that whosoever comes in and hears he may thereby know by the witness of his sense
that we professedly hope for acceptance with God through Christ Jesus,
as our only mediator and advocate with the Father.
And this I said, and say it again,
you do not nor could you have put me upon the proof
of anything which I can prove with more assurance.
For your contempt of the Sacrament of the Lord`'s Supper,
I read it six or seven years since in a wretched pamphlet of one Solomon Eccles,
which is not now by me, nor can I assure you of the words;
but the sense of it was as if that which made that ordinance
desirable was the hope of a good draught of wine.
Your rejection of the Lord`'s day I knew by a large discourse
I had about it with one who was a great man among you,
what he is now I know not, nor am concerned,--Billing, a brewer in Westminster.
But what I am now speaking of I have it not by information of any man,
but from my own personal knowledge,
for I have been often at a great meeting of Quakers in Westminster;
and once in special I forced myself to stay it out to the end.
I heard many men and women too, a shameful thing in Christian assemblies,
and five or six of them pray with a great deal of bodily fervour and strainedness;
but not one of them in all their prayers throughout, from the beginning to the end,
made the least mention of our Lord Jesus Christ,
either by that name or any other that might give a stander-by
the least hint of their acknowledgment of any such person,
or of any respect they had to him or hope in him as their mediator,
for his sake to find mercy with God; or give a man the least evidence,
that for religion they were Christians and not Jews;
for the Jews acknowledge one true and living God as well as they.

I therefore take this last part of my charge as confessed to,
while you deny not what only I affirm here,
that you offer not up your worship to God in the name of Christ,
so expressed with the mouth,
that standers-by may hear you do so professedly own
him as your only mediator and advocate with God;
what you do internally is known only to God and your own souls.
It is your external acknowledgment of Christ in your worship
by which men can know that you are Christian worshippers,
offering up your worship in his name.
After all this you require me to prove what I have laid to your charge by the Scriptures.
A strange request!
I have charged you with nothing but matter of fact.
Would you have me prove from Scripture that these and these are the Quaker`'s tenets,
when neither they nor their tenets were in being
till 1600 years after the Scriptures were written?
What would you have me to prove by the Scriptures?
Is it that you are not to be owned for Christians?
This, I confess, is more matter of doctrine than the other;
but that is no part of that which I accused them of, but a natural inference,
which you call an excommunication, from the premises;
for if you reject the visible marks of Christianity,
you are not to be owned for Christians.
My whole charge against you is in the four particulars above mentioned,
of which you confess three and deny not the fourth;
but either ignorantly or willfully mistake my plain meaning;
so that what is left for me to prove from Scripture I profess I know not.

As for the three queries you put to me, they are not of difficult resolution,
at least the two first of them.
But I perceive by what you add about the Lord`'s coming in the second question,
and every day being the Lord`'s, in the third, that you aim not at resolution,
but to draw me into further disputes with you;
which unless you were able to write more strictly and closely to the matter,
without multiplying words to no purpose, I shall not be drawn to;
and therefore forbear to answer your queries, yet remain,

[.signed-section-closing]
Willing to do you any good I can,

[.signed-section-signature]
Benj. Woodbridge.

[.signed-section-context-close]
December the 31st, 1673.

--

When I had received this letter I was troubled to see so little plainness appear:
and how subtly he did seek to hide and cover himself, and to waive the matter.
So that I did not write again presently, but laid it by a while;
and made inquiry after Solomon Eccles`' his book which he quoted;
but could not hear of such a one.
But after some time I wrote a pretty sharp reply to his last letter as follows:

[.embedded-content-document.letter]
--

[.salutation]
Benjamin Woodbridge,

I have perused your answer to my reply,
which indeed is rather a mere evasion of the matter than any plain answer.
For you say that I have denied nothing of what you did accuse us of;
but have confessed it altogether, except the fourth particular; and you boastingly speak,
that if you did need it you should make me your witness that you have spoken the truth.

Reply,--If I may be a witness then let my evidence be heard and considered.
First you did charge and conclude us to be infidels for denying
those four marks or signs which you say are according to Scripture,
the most distinguishing marks of Christianity.
Did I confess this?
not in the least; but showed according to Scripture,
the most distinguishing mark to know Christianity from infidelity by;
because that murderers, adulterers, thieves and covetous, yes,
the worst of men here in England have these visible marks, and yet are as bad as may be;
and many such are condemned and executed year after year,
notwithstanding their having those visible marks or signs.

And I did also signify what was the manifest mark
and special spot of the children of God,
who are the only true Christians;
which was the fruits of righteousness and holiness brought forth in and by them
through the power and spirit of Christ Jesus working effectually in them.
Neither have I denied anything more that I know of than the apostle Paul did.

Concerning sprinkling infants, a thing not known that I read of in his time, I said,
it was an invention of the Church of Rome, which I did suppose you were not ignorant of,
and now your silence in that part confirms what I said,
and therefore you can not plead for it.

Was the apostle Paul an Infidel, for his not being sent to administer water baptism;
and for his setting up the baptism of the Spirit, and affirming "`there is one Lord,
one faith, one baptism?`"
And what more have I said or confessed of all that you have charged upon us;
but the Scriptures testify the same, as may be seen at large in my former reply?
And must we be accounted infidels for believing and owning the Scriptures?
or must we be accounted infidels for denying the Church of Rome?
Answer plainly.
And therefore, if you make me your witness I must needs plainly testify,
as in the presence of the Lord to your shame, that you have told a great untruth;
and it does still lie upon your head to prove us infidels.
For true faith stands in the power of God and is his gift,
and stands not in the wisdom of words nor in visible things.

And now this I query of you concerning baptism,--whether dipping or sprinkling
infants is an express command and institution of the Lord?
Produce if you can one Scripture to prove that if we do not practice it we are infidels.

And I further query concerning receiving the Lord`'s Supper,
after what sort it ought to be celebrated?
Whether kneeling, standing, sitting, lying, walking?
for all these sorts of ways I understand are practised in the world?
and in the use of shadows the outward manner of performance
is held to be absolutely necessary.
But do you produce one scripture to prove,
that if we do not practice it in some such sort and manner, we are infidels.

And further, what authority have you to preach?
By whom were you ordained?
By the bishops, or no?
Can you prove your ordination successively from the apostles`' times?
And can you prove your own qualification to render you fit to administer such sacraments,
as you call them, and to pray and preach publicly for the instruction of others?
Answer these queries plainly, in the spirit of meekness, if you are a true minister.

Again, concerning the observation of a day; it is so far from being a Christian mark,
that the apostle Paul makes it a Jewish one.
And therefore by the rule of contraries upon your own principles,
judge you by consequence who is the infidel.
Do not the reformed churches, beyond the seas, both Lutheran and Calvinist, so called,
deny the morality of the first-day of the week,
and practice it only as an apostolic tradition, as they speak?
Are they therefore all infidels?
But since they who pretend to keep it on the account of its morality, keep it so badly,
what a crew of infidels are there in England?
Put it to the consciences of all sorts,
whether the Quakers show such looseness on that day,
as many of those assertors of the morality of it do.

And as concerning your fourth particular charge,
which you go about to prove from your being at Westminster meeting:
you being an envious person prejudiced against us, your testimony is not to be taken.
What did you go so often there for?
If you did hear any preach or pray contrary to sound doctrine,
why did you not inform them, and instruct them, and show them their error?
If you had been indeed a true minister of Christ,
you would surely have preached Christianity to them;
and not have come among them like Satan, watching for occasion on purpose to accuse them.

And since you call it a shameful thing in a Christian assembly for women to speak, I ask,
if the Lord according to his promise has poured out his spirit upon sons and daughters,
then why may not daughters prophesy as well as sons?
and that without shame, unless it be to those that despise them.

However, inasmuch as you have prejudged us,
I must tell you in plainness as before is hinted,
you have made yourself too much a party to be received as a competent witness against us.
Therefore your testimony is not to be taken or regarded.
And I do not question but many hundreds of impartial
persons who have frequented that meeting will appear,
if need be, to testify the contrary to what you have charged us with in that particular.
And besides our books which are public, do show forth to all people who will read them,
that we do own Christ Jesus to be our Lord and Saviour;
and it is our joy and comfort and the seal of our assurance,
that we know him to be our King, Priest and Prophet,
and the only Mediator between God and man.
And thereby it is evident that your proof is no proof,
but your charge still remains altogether false, a mere slander uttered by you against us.

Wherefore, to come yet more closely to you,
consider whether it did become a man who himself is a dissenter,
and who has played at hide and seek, and shrunk in times of trouble,
and not stood to suffer for his testimony, to fall so untruly,
unneighbourly and uncharitably upon a harmless people that had done him no wrong?
And whether these things do not tend rather to division and animosity than to quietness?

And lastly, consider whether it was not unworthily and basely done,
in a public assembly thus to brand us for infidels;
and to express it after such a manner as if we were about
to set up infidelity in the town of Newbury as a trade.
The Lord rebuke your envy and make it manifest.
But this way which you have taken, will please none but hypocrites and persecutors:
for sober moderate people may come by this means
to be informed both of your enmity and our innocency.

As for the book you mention of Solomon Eccles,
and which you unhandsomely call a wretched pamphlet, I have sent and enquired after it,
which was some reason why I was so long before I wrote this,
but cannot hear of any such book;
so that it remains for you to bring it forth to acquit yourself
from being accounted a slanderer in that also.
So expecting a plain answer without evasion to the several heads before mentioned,
I remain.

[.signed-section-closing]
An earnest contender for the true faith against infidelity,

[.signed-section-signature]
Oliver Sansom.

[.signed-section-context-close]
The 19th of Eleventh month, 1673.

[.postscript]
====

P+++.+++ S. Whereas in the conclusion of your letter you
query what I would have you to prove by the Scriptures;
I answer, you have, as you know,
accused us of infidelity for denying those four particulars, which,
you say are according to Scripture,
the distinguishing marks between Christianity and infidelity.
But if these be the Scripture marks, is it then such a strange request,
as you would make it, that they should be proved so by the Scriptures?
and not only so,
but also to prove by what express command the practice of those things is enjoined,
so that whosoever is not found in them is an infidel.
And when you have so done, then prove the matter of fact, as you call it,
that we deny or reject those practices.

The substance of those things was contained in the three queries I sent you;
which if you had plainly answered,
your nakedness and shame would have been more discovered.
But what a pitiful shift have you made to avoid the answering of them!
doubtless you yourself are sensible that you have charged us falsely,
and now would eagerly slip out of it.

As for your saying that our tenets were not in being
until 1600 years since the Scriptures were written;
this is a false affirmation returned back upon you to be repented of: for I testify,
that our tenets and principles are the same that
the apostles and ministers of Christ believed,
taught, and held forth, and the Scriptures bear witness to them;
prove you the contrary if you can.
And though the term Quaker is cast upon us in derision
and reproach by the scorners of this generation;
yet that reproach does not make void the truth of our principles,
nor the antiquity of our tenets;
any more than the term Christian formerly did the Christian principles and doctrines,
when it was first cast by the scoffing heathen on the followers of Christ.

====

[.signed-section-signature]
O+++.+++ S.

--

After Benjamin Woodbridge had received this letter,
which I sent him by an eminent hearer of his,
I was certified that he was not willing to answer me any more in writing,
but rather to speak with me privately;
and the said messenger also desired that we might speak together.
Whereupon I sent him word to this purpose,
that seeing he had openly charged us in a public assembly,
therefore I could not go about to smother it up in secret;
but if he were willing to have a public dispute,
concerning the matters in controversy between us, to be soberly debated in moderation,
with free liberty to as many as should desire to be present on either side;
I did not question but my friends would join with me to engage him.
To this effect I spoke several times to the aforesaid messenger,
whose name I forbear to expose, not having asked his consent.
But when after about two months waiting,
I could not find him any way willing to appear in public,
I wrote another letter to him as follows:

[.embedded-content-document.letter]
--

[.salutation]
Benjamin Woodbridge,

I have long waited to receive an answer from you to my last letter,
dated the 19th of the eleventh month, 1673.
And to stir you up to return a plain answer,
I have sent you several verbal messages by your friend N. C.
to provoke you to come forth honestly and answer fairly;
but by your delays I perceive that your design is to answer me, as the saying is,
by silence.
Which indeed, if it were only a personal or private controversy, might serve,
if not to satisfy, at least to put an end to it;
because it might be taken as a manifest evidence
that you are not able to prove what you have charged,
and therefore would willingly have it die in silence,
that so it might be buried in oblivion.
But because it is the blessed way and worship of the living God which you have reproached,
and us for our practice therein have branded for infidels;
and have also endeavoured to cast stumbling-blocks in the way to hinder
those who might have a desire to prove and try and be acquainted with
the way and worship which the Lord has gathered us into;
and moreover it may be an occasion to stir up the magistrates against us,
through your false instigation, to persecute us as infidels;
therefore this may let you know, that for the Truth`'s sake,
which is dear and precious to us, we are engaged and concerned to clear and vindicate,
in a public way and manner, both the Truth and ourselves,
as to our belief of it and our worship to the Lord in it;
and also to satisfy and inform both magistrates and people,
that although you have in public appeared against us,
and openly charged and branded us for infidels,
and so bespattered the precious Truth which we profess,
yet when you should come to proof and trial you are not able to stand before it.
For the Truth is strongest; and as it has, so will it prevail, and have the victory.

And as I doubt not but you are sensible that you
have falsely charged us and done us wrong;
so I desire that the sense and weight of it may come so close and heavy upon you,
that you may repent of it,
and give forth a public acknowledgment to clear us and your own conscience;
and thereby make some sort of satisfaction for the wrong and injury you have done us.
So in the love of God I remain,

[.signed-section-closing]
A well-wisher to you and all men,

[.signed-section-signature]
O+++.+++ Sansom.

[.signed-section-context-close]
The 22nd of First month, 1674.

--

But neither did this letter draw him forth to give us a public meeting.
Wherefore, after I had thus cleared my hands of him,
the Friends of our meeting in Newbury,
looking upon themselves to be concerned to give forth some vindication
more public on behalf of Truth and of the precious faith,
which we through mercy have obtained,
against this envious man`'s imputation of infidelity;
they abstracted out of the foregoing letters the heads of the matters in controversy,
and having drawn them in a fit form and method,
delivered copies thereof to several persons of note in the town of Newbury.
All which this evil man chose rather to lie under the censure of,
than come forth in public to acquit himself therefrom.
