== Chapter V.

With Samuel Burgis starts for the yearly meeting--Are arrested at Windsor--Their
examination there--To the yearly meeting in 1676--Proceeds to Liverpool,
taking meetings on the way--Delays--Sail for Dublin--Travels in Ireland on a religious
account--Three letters to his wife--Returns home--Epistle to Friends in Ireland.

Some time after this, the yearly meeting at London coming on,
to which my dear friend and brother in the truth, Samuel Burgis and I intending to go,
we set forward together on our journey thitherwards.
And as we travelled on the way we felt drawings on our spirits
to visit our Friends at their weekly meeting at Windsor;
which caused us to turn in there.
But after we were come into the town and before the meeting began,
there fell a great weight of darkness upon us,
which brought so sore an oppression upon our spirits,
that we were sensible the meeting would be disturbed
and that sufferings would attend us that day.

When the meeting time was come and Friends were gathering together,
we went and sat down in silence with them.
And after we had waited awhile, I having something by way of testimony to declare,
stood up and spoke for about an hour; and being pretty clear sat down again.
And then my dear brother S. Burgis stood up and began to declare;
but had not spoken long before the Mayor and a justice of the town,
with several other officers, came into the meeting, and commanded him to hold;
but he not heeding their words went on still.
Whereupon the Mayor commanded the officers to pull
him down and to have us all away to the Town-hall,
and there secure us until we were examined.

There we were had, and our names being taken, we were kept there a long time,
while the magistrates held a consultation privately between themselves concerning us.
Which done, and they sitting in the place of judgment,
we were all called together before them,
and part of the Act against seditious conventicles was read;
upon which the justice put such a construction,
that in his sense he concluded us transgressors.
But yet he very nobly said, that if any of us had anything to say in our own defence,
to show why he should not proceed against us, as persons convicted by the said Act,
they were ready to hear us.

It so happened that John Swinton,^
footnote:[John Swinton of Scotland, formerly called Lord Swintowne,
frequently mentioned in that interesting and valuable work by the late John Barclay,
The Diary of Alexander Jaffray, etc. with Memoirs of the Rise, Progress,
and Persecutions of the people called Quakers in the North of Scotland.
At page 217 of that work a biographical notice is given of John Swinton,
to which the reader is referred.]
of Scotland, being in the town at that time upon business depending on the court,
was taken at the meeting among us; and being first called he spoke first,
and his examination proved somewhat long, at least I thought it so;
for I began to be uneasy, as wanting room to speak what was upon my mind.
So upon my request liberty was granted me; whereupon I spoke as follows:
"`I do not understand, said I, that we are such people as this Act is provided against;
for we are no seditious sectaries nor disloyal persons;
neither can it be proved that we were ever found in seditious
practices to the disturbance of the peace or raising insurrections;
therefore being innocent and clear from all those dangerous
practices which this Act provides remedies against,
I cannot see wherefore we should suffer by it.`"

At this the justice was angry and charged me with a lie,
for affirming that no Quakers were ever disturbers of the peace,
or found raising insurrections; for he said there were many in the wars in times past.

I mildly replied, "`I do confess that several which had been in the wars,
and had borne arms came afterwards to own the Truth and leave the wars;
but I did and do deny that any, after they came to own and abide in the Truth,
did ever take up arms or use a carnal weapon.`"

After this, Samuel Burgis being called and charged with deluding the people,
he asked them whether it was an offence or breach
of the law to exhort people to fear God?
The justice said, "`Yes.`"
Then said Samuel Burgis,
"`If it be an offence to fear the Lord and to exhort people to it,
then am I here ready to suffer for it, if it be to the laying down of my life.`"
The justice said again, "`In your sense it is.`"
Whereupon I said further,
"`Seeing this Act is not made to suppress the true worship of God,
nor to punish any for worshipping God in sincerity and truth,
but against seditious practices; and seeing we are real,
upright and innocent in all our intentions both towards
God and man as touching all our meetings,
therefore it cannot reasonably be supposed that we
are the people meant or intended by this statute.`"

The mayor said, the Quakers are expressed in this Act, as he thought.
But when I desired him to show it me and he had taken up the Act to look after it,
the justice interposing said, he thought the word Quaker was not in it; but added,
that it was ground enough to conclude our meeting a seditious meeting,
because several of us were found there whose dwellings
were so far remote from that place.
I answered, "`Some of us were on our journey to London,
and did but visit our Friends in our travel, and John Swinton had business there,
to speak with the king upon, as you have heard.`"

The justice thereupon said, "`We are as unwilling to cause you to suffer,
as you can be to suffer; but if we don`'t fine you,
we are liable by this Act to be fined ourselves £100.`"

To which I answered, "`Except we are proved seditious the Act clears us;
and then there is no need for you to fear the hundred pounds fine.`"

"`But,`" replied the justice, "`I will not venture that.`"

Thereupon I asked him, if he knew of any magistrate that had suffered in that kind,
for not putting this Act in execution against us?

"`Yes,`" said he, "`I know of two that suffered; one was at Chichester.`"

I answered, "`This I confess I have not heard of before, and can say nothing to it;
but I can say, and that in truth, we are truly innocent concerning sedition.
And to meet in reality to worship God is neither contrary to this Act nor to the liturgy;
for the liturgy does acknowledge that it is very right and fitting,
and our bound duty at all times and in all places to pray and give thanks unto God.`"

"`I see,`" said the justice, "`you are not ignorant of the liturgy;
but that will not excuse you.`"

"`Well,`" said I, "`we do commit our cause to God;
but I desire that in your proceedings against us
you may have regard to the royal law of Christ Jesus,
which is, to do to all men as you would be done unto;
and consider if it were your own case and our condition were yours,
could you be willing to suffer yourself in this manner?`"

"`Yes,`" replied the justice, "`I should fulfill the law passively;
for there is no withstanding an Act of Parliament.
The whole nation,`" added he, "`had a hand in making it; and you yourself,
speaking to me, had a hand in making this Act.`"

"`If,`" said I, "`it might be concluded that I had a hand in making this Act,
then surely, I may justly claim a right to interpret and explain it.`"

"`No,`" replied the justice, "`you had a hand by your representative in making it;
but it is left to the judges of the law to interpret it.`"

When this discourse with some more to like purpose had passed,
they proceeded to impose fines;
and they fined me and the rest of the Friends five shillings each, except Samuel Burgis,
whom they fined as a preacher twenty pounds;
for which his corn was afterwards distrained and carried to market, but not sold,
nobody being forward to buy it;
and after it had lain in a garner in Newbury a considerable time,
it was at length delivered to him again.

About this time the mystery of iniquity was secretly
at work in this county of Berks in several,
some of whom had been great sufferers for the Truth; but in the late time of liberty,
growing high and lofty, they lost the sense of their former tenderness.
And being carried away with a high admiration of two wandering stars,
John Story and John Wilkinson, an exalted, opposing, separating spirit,
by that means prevailed in the fleshly wisdom, to the defiling of some and grief of many.
Of which, occasion may be offered to say more hereafter.
Wherefore I shall now go on to relate some other services,
which the Lord was pleased to employ me in.

About the time before mentioned of my going to London by Windsor,
I felt some drawings on my spirit to go over into Ireland in the service of the Gospel;
and very hard it was for me to give up to that journey;
but in waiting upon the Lord and shutting out carnal reasoning,
the Lord in time made me willing to be resigned to his guidance in that exercise;
and so the thing remaining near two years, grew still more weighty upon me.
Then I acquainted my dear brother Samuel Burgis therewith,
and he was made free and willing to go along with me,
and be my companion in that journey, although he came from there not long before.

So we went up first to the yearly-meeting in the year 1676.
And soon after our return from there we set forward from our own homes,
on the 11th day of the fifth month; our wives and several Friends that lived near us,
in love accompanying us to bring us on our journey.
We went first to Cricklade, where was a weekly meeting that day;
where several Friends of Cirencester having notice of our coming, met us;
and we were well refreshed together in the sense of the renewed love of our God.

After the meeting we went with our Friends to Cirencester,
and the next morning after we had waited awhile together,
and prayers and supplications were poured forth unto the Lord,
that he would be wisdom and strength unto us,
to direct and preserve us in our weighty undertaking,
and in tender love and brokenness of heart,
committing each other to the care and keeping of the Almighty;
we took our leave of our dear wives and Friends there, and having heavenly encouragement,
we went the same day to Cheltenham; where we had a meeting with Friends that evening,
and the Lord`'s blessed presence and power was with us,
which caused a great tenderness over the meeting.

Next morning we travelled to Worcester, and had a good meeting with Friends,
at their weekly-meeting that day, and Friends were very kind and loving to us.

From there we passed next day to Stourbridge;
and it being market-day we had a meeting with Friends there in the evening.
They were desirous to have us tarry with them until the first-day also; but we,
being pressed in spirit to go forward, went on next morning,
which was the seventh-day of the week, to Shrewsbury; where we tarried the first-day.
At our entering into that town we felt a great weight of darkness over the place,
and soon after we understood the court session was held there at that time.
At the meeting, one of the Sheriff`'s bailiffs and several more people were present,
and continuing many of them to the last,
behaved themselves soberly and gave great attention.
It being the monthly meeting, it was large;
and very precious through the goodness of the Lord,
who is worthy to have the glory over all forevermore.

Afterwards in the evening many Friends being together with us,
we had then also a good time toa;ether to our comfort through the favour of the Lord.
Then we went to visit two Friends that were in prison;
and there also waiting together awhile in the prison we
felt and tasted something of that spring of divine life,
whereby we had been so often refreshed.
Holy, pure praises be ascribed to the everlasting Fountain forever and ever.

The next day we passed to Chester, and had a meeting among Friends there;
and the power of the Lord reached to most in the meeting,
which caused great tenderness among them; endless praises be to his name forever;
and much love was manifested unto us from them.

Then hearing next day, being the fourth-day of the week,
of a ship laden with coals and bound for Dublin ready to set sail,
we disposed of our horses, and hasted away to Nesson, where the ship lay:
and there we waited for a wind until the seventh-day in the morning,
at which time the wind blew and sat very well for us.
Whereupon about sun-rising we with many other passengers got all on board;
but the wind blowing very strongly tossed the boat in such sort,
that many passengers were sick before they could get aboard the ship.

Then hoisting up their sails they put forth and went away
very swiftly for about three quarters of an hour.
But passing over a shoal the ship struck upon the sand once or twice,
and then she stuck fast in the sand and could not get off.
And it being an ebbing tide,
the water went clean away from the ship so that it was dry
land round about for a great distance from the ship.
Wherefore many of us went down out of the ship,
and walked four or five hours on the sands which
lay dry for two or three furlongs in length,
but encompassed round with water at a distance,
that none could get to the land if they had desired it;
but when the tide came in again we all went up into the ship.
And when it was high water the ship floated, being borne up by the flood above the sands.
Whereupon we endeavoured to get forward; but the wind being turned almost against us,
the seamen toiled hard and sailed to and again until the evening,
yet were they then eager to cast anchor.

Next morning, being the first-day of the week,
as soon as it was day-light the sailors went to work again,
and having weighed anchor and spread their sails, endeavoured again to get forward;
but the wind was still strong against them.
And when they had laboured till near the middle of the day
the wind grew more turbulent with rain and stormy weather;
which forced them to cast anchor there again.

This unexpected stop and delay of our passage brought afresh to our remembrance,
that when we were at Chester, treating with the shipmaster,
and just as we had concluded for our passage, a great weight came upon my spirit;
and I had some drawings to go to Liverpool, to visit Friends there, and thereabouts,
and in that part of Lancashire before we left England,
But we having suddenly disposed of our horses, and being not well able to travel on foot,
and thinking it long before we were got over into Ireland,
did take that weight which fell upon me at Chester,
to be a forewarning from the Lord of some hardship
or suffering that was like to come upon us at sea.

There were on board the ship about fourscore passengers in all,
many of them as lewd and wicked, I think as any the earth did bear,
but others of them were more sober; though as to religion very dark.
Yet the Lord by his power preserved us, so that none of them offered any abuse unto us,
so much as in words; though they were very vain and frothy among themselves;
and the weight of their iniquity lay heavy upon us.

While thus we lay at anchor in the afternoon, when all had dined,
but we ourselves were fasting all the day,
we went up upon the deck in the fear and dread of the Lord God,
and my brother S. B. opening his mouth with an audible voice,
declared to them of the mercy and love of the Lord, exhorting them to repentance.
When he ceased I spoke to them also after the same manner,
putting them in mind of their latter end and reproving them for their vanity,
exhorted them to turn to the grace of God, which had appeared to them,
to teach them to deny all ungodliness and worldly lusts, and to live soberly,
righteously and godly in this present world.

When first S. B. began to speak they came forth and drew near unto us,
standing together upon the deck like a pretty large congregation,
and gave diligent attention.

Among them was one called a lady, and several other persons of quality,
who showed much soberness in giving heed to what was declared.

The lady came up close to my elbow because the wind was high and she was desirous to hear.
And afterwards she asked me several questions which I answered to her satisfaction.
The master of the ship also, and the seamen seemed well pleased,
and were kind and courteous to us; for indeed,
the powerful presence of the Lord was with us, and most of them were so far reached,
as to confess that what we said was true.
Only some Frenchmen, who were said to be fiddlers and fencers,
and such like seemed to be hardened;
yet they also were bounded from offering us any abuse.

As soon as we had done our service among them,
the weather being likely to be more tempestuous,
they weighed anchor and tacking about returned back to Nesson in about an hour`'s time.
And we, having been thus strengthened by the Lord to sound forth his truth among them,
when being brought into a straight they were willing to hear,
were greatly comforted by the Lord our God in our
obedience to him in that exercise and service;
blessed and praised be his holy name forever.

But being thus set on shore again at Nesson on the first-day at night,
which was the 28rd of the fifth month 1676, we tarried there until the morning;
and the wind still standing contrary, we then took our journey on foot into Lancashire;
and passing through Liverpool without hearing of any Friend here,
we went on about three miles further to the house of a Friend,
whose name was Henry Baker, where we were kindly received and lodged that night.

Next morning we went back to Liverpool, the Friend our host accompanying us;
and he brought us to a Friend`'s house there, where we stayed awhile.

There was that day a great fair at Liverpool,
and my dear companion S. Burgis being under a great exercise of spirit,
was constrained to go into the midst of the fair, near the exchange;
and having given a man money to let him stand upon the end of his stall,
he cried out aloud in the dread of the Lord,
against the pride and wickedness of the people, warning them to repent.

This gave an alarm through the town, there being at that time a multitude of people;
yet none offered any violence to him.
When he had cleared himself of what was at that time upon him he stepped down,
and I being next to him all the time, we came forth from among the great throng,
and went back to the Friend`'s house again,
where many Friends who were come to the fair came to visit us,
and were exceeding kind and loving to us,
inviting us to come into the country among them, until we might have our passage.
But we hearing of a ship ready to set sail for Dublin, and waiting only for a wind,
went back again that night to Henry Baker`'s house;
and next morning finding the wind set fair,
we went again to Liverpool that we might be in readiness if the ship should sail:
but when we came there we were informed that no ship would sail from there that day.

Some Friends of the country hearing of us came to see us there,
and very kindly proffered to lend us horses to go into the country with them.
But we, having a desire to have a meeting in Liverpool,
which we could see no likelihood of obtaining that day, went about a mile out of town,
and lodging there that night, returned next day to Liverpool again.
And then finding no other way open,
I sent a Friend about in the town to see if he could hire a room for a meeting that day;
he soon met with one, who willingly for money offered his house; and we,
being very glad of it, appointed the meeting to begin at the sixth hour in the evening,
it being the fifth-day of the week.

Notice being given thereof much people came in, and we had a good meeting;
for the Lord`'s power was manifested and many hearts were tendered;
and the Friends who were there were well refreshed and greatly satisfied.
They said there had not been a meeting in that town for sixteen or seventeen years past;
about which time Richard Hubberthorne^
footnote:[The name of Richard Hubberthorne often
occurs in the early part of the history of Friends,
as an able gospel minister and patient sufferer for the Truth.
He was a native of Lancashire, and the only son of his father,
a yeoman of good repute.
{footnote-paragraph-split}
In his youth he obtained a post in the parliamentary army,
which on his embracing`' the Truth he quitted and testified publicly against it;
and became a valiant soldier under the banner of the Prince of Peace.
After passing through many inward probations,
he became qualified to direct others in their way to the kingdom of heaven,
and was one of the first of our Society who travelled in the work of the ministry.
See G. Fox`'s Journal, where he is frequently mentioned, Leeds edition, vol.
1, p. 193.--Richard Hubberthorne was a man of much meekness, humility, patience,
and brotherly kindness, clear in judgment, and quick of understanding;
and although he was of low stature and had an infirm constitution and weak voice,
he was a powerful and successful minister, and great numbers were convinced by him,
and brought over to the faith and practice which he preached.
Me travelled in the exercise of his gift for the space of nine years,
and shared at different times in the sufferings to which our early Friends were exposed.
{footnote-paragraph-split}
In the fourth month, 1662,
he was violently haled from a meeting at the Bull and Mouth in London,
and taken before that implacable persecutor Alderman Brown, who,
after abusing him with his own hands, committed him to Newgate.
Here the throng was so great, and the air so impure, that he soon fell sick.
His disorder increased upon him, and within two months from the time of his commitment,
with an unclouded prospect of a resting-place "`where the
wicked cease from troubling,`" he was released by death.]
was there: but the magistrates then drove Friends out of the town,
through the instigation of a wicked envious priest,
who advised them to beware of the Quakers, and not to allow them within their borders;
telling them it would be too late to seek a remedy when the mayor`'s throat was cut,
and all his officers slain.
But between that time and this.
Friends were better known and their principles better understood.

Among the many people that were at this meeting,
there was one of the chief men of the town; and he was so very courteous and kind to us,
that he even constrained us to go to his house and drink a glass of wine with him; which,
more for his sake than of his wine, we consented to.

About an hour after the meeting was over,
our spirits being clear and greatly comforted in the goodness of the Lord our God,
who had given us our hearts`' desire,
we went on board the ship and passed away in much inward joy and satisfaction.
But when we came out at sea, the winds proving something contrary as well as rough,
we were three days and three nights upon the water;
which caused my companion to be sea-sick; but I was as well as at other times.

We arrived at Dublin on the 30th of the fifth month, 1676.
And when we were come into that city a hard travail of exercise came upon us,
by reason of the power of darkness`' which had wrought
strongly and mysteriously I in the hearts of some,
who had once known a better state while they were little and low.
But when the Lord had given them rest and increased them in outward things,
the love of this world entering their hearts, became as a root of bitterness in them,
from which sprang prejudice, enmity, contention, high-mindedness, self-love,
and the like.

We tarried there the weekly meeting, and the two meetings on the first-day following;
and although the power of the Lord was over all in those meetings,
to the comfort and refreshment of the tender-hearted;
yet inasmuch as there were some other travelling Friends also from England,
we had not then opportunity fully to clear ourselves among the Friends of that place,
but tarried longer among them; and on the second-day went to a women`'s meeting there;
and we have cause to say, the Lord owned them,
by affording them the enjoyment of his refreshing, powerful presence among them,
for the strengthening and encouraging of us all, as we are humbly resigned to obey him.

Next day there was a men`'s meeting, to which also we went;
and the power and presence of the Lord was mightily revealed,
which enabled us to discover and give warning against that spirit of darkness,
which was the troubler of Israel.
After this, not yet finding ourselves fully clear,
we tarried their Meekly meeting on the fifth-day,
and the Lord was with us as at other times, blessed forever be his Holy name,
and the upright and tender-hearted were refreshed
and made glad in the feeling of the love of God,
which flowed forth through us towards them in the time of our being there among them.

Now after we had tarried eleven days in Dublin, we left that city,
and passing away towards the north of Ireland, had a meeting near Drogheda,
at a place called Killmeer, where many people came in,
and the Lord`'s power was blessedly with us;
which caused great openness and tenderness in the meeting;
glory over all and endless praises be given to the God of our life and strength,
forevermore.

We travelled the next day forty Irish miles or upwards to Leggekore; and on the morrow,
being first-day, we went to a meeting at Balyhagen;
where we were comforted together with Friends in the goodness of the Lord.

We were next day at a women`'s meeting,
and the day following we went to another women`'s meeting seven miles from there; where,
notice having been given of our coming, the meeting was large;
and at both these meetings the Lord`'s blessed presence in the midst was enjoyed,
and life received by the thirsty ones to their great comfort and refreshment.

Next day we went to Francis Robson`'s house near Lurgan,
where was a large and good meeting.
And from there next day we passed to a meeting near Lisnegarvy,
which also through the great love of our God was made good unto us.
From there went to the city of Antrim that night, and the next day to Grange;
where we tarried a little time with Friends, and then passed on to James Moores,
who lived near Ballimurry, and lodged there; and the next day,
being the seventh-day of the week, leaving our horses there,
we went on foot to a Friend`'s house, whose name was Gilbert Crocket, near Colerain,
where the meeting was to be on the morrow, and a large and precious meeting it was,
through the goodness of the Lord,
in which we with Friends were comforted and refreshed together.

On the second-day we came back to Grange, and had a meeting there on the third-day;
and were comforted in the Lord with Friends there also.

We came to Antrim on the fourth-day, and stayed the meeting there;
and the next day we came to Carriclvfergus, and had a meeting there;
and in all these places the Lord was still with us to our comfort,
blessed be his Holy name forever.

Next day, being the sixth of the week,
leaving Carrickfergus we passed along by Belfast
and Lisnegarvy and came to Lurgan at night.
And on the seventh-day, many Friends accompanying us,
we went to Ballyhagan to the province meeting, which lasted two days;
here we met with Roger Longworth and John Symcock;
and a very precious meeting there was through the lovingkindness of our tender God;
to whom for all his goodness be the praise and glory ascribed,
and offered up over all forever more.
Amen.

After the meeting on first-day was ended we travelled to Armagh,
and had a meeting there that evening, to which many people came,
and a good time we had with them through the continued love of our merciful God.

We went next day to a meeting near Charle-Mount,
where also the Lord comforted us with his people.
And from there we went to Dungannon where we had a meeting that evening,
to which many rough people came and heard pretty quietly;
for the Lord`'s power was over all, which kept their spirits down.

The next day we travelled to Cavan, which was about forty-miles.
And the day following we went to Belturbet meeting seven miles,
and back to Cavan that night: and were at the weekly meeting there on the fifth-day;
and still the love and favour of our gracious God
was renewed and continued to us for our great encouragement,
and to the confirming and refreshing of his heritage where ever we came; all glory,
honour and endless praises be returned to him forevermore.

On the sixth-day we travelled to a Friend`'s house near Trim, an old decayed city,
and had a meeting there on the morrow:
and after the meeting we rode twenty miles to Dublin,
and were there at both the meetings on the first-day.
Those meetings were full and large, abundance of people thronging in;
and some rudeness there was among them for some time;
but for the most part they behaved themselves soberly; and blessed be the Lord,
his power was felt over all,
in which the word of truth was sounded forth in his divine
authority over the meetings to the comfort of the faithful.

On the second-day we were at the women`'s meeting
in that city and the Lord was with us there also.

+++[+++The following letter written to his wife may be appropriately introduced here.
Two letters at subsequent dates, written also from Dublin, are inserted in their places.]

Dublin, 11th of Seventh month, 1676

My dear Wife,

In that love which sea or land cannot separate does
my soul salute you and truly reach unto you,
and the secret breathings of my life are often poured forth unto the Lord,
that you may daily partake with me of the same heavenly comfort and sweet refreshment,
which the Lord in his love has opened as a spring in me;
whereby my soul has been daily strengthened and encouraged,
that all my travels and exercises inward and outward have been made easy unto me,
so that I can say that the way of the Lord has been pleasant unto me,
and my soul has found true peace in walking in his path.
As I have patiently been resigned to take the yoke of Christ upon me,
he has enabled me to bear it with ease and delight,
so that I have cause to say he is not a hard master,
but does give power and strength sufficient to fulfill all his commands
unto all his servants who daily wait upon him for it;
therefore, dear heart, wait daily upon the Lord,
and let the exercise of your soul be poured forth in breathings unto him continually,
for he sees in secret and takes notice of that man
or woman whose heart inclines after him.
He will watch over them to do them good, and to keep and preserve them in perfect peace,
when the mind is stayed upon him.
So labour against all worldly thoughts, and shut out all worldly desires,
and wait for heavenly desires and a stayed heavenly spirit,
that so your affection may be wholly set on things that are eternal Then
all that we can suffer here will seem light and easy unto us,
and not worthy to be compared to that glory which our heavenly Father is revealing in us.
Therefore let us forever dwell low and look not out,
but keep the eye within and live by faith, and we shall surely obtain victory,
and in time come to be made more than conquerors through Him that has loved us,
who is blessed forevermore.
Now this may let you know that I and my companion S. B. are very well,
and so have been ever since our arrival here.

The Lord has been very good unto us, and his blessed presence has been with us,
and the savour of his divine power been manifested
through us in all places where we have been,
for which our souls are deeply engaged to return honour
and glory and immortal praises over all unto him forevermore.
After our arrival here we tarried eleven days at Dublin, and were at several meetings,
where we had very good service, and Friends were very glad of us;
and then having provided us horses,
we went to the meetings of Friends in the province of Ulster,
where we spent something like three weeks and travelled about 330 miles,
and came again to Dublin on the seventh-day at night,
to be at their meeting on the first-day.

We had a very large meeting, both in the forenoon and also in the afternoon,
for abundance of the world`'s people thronged in;
so that here is a great service on the first-days in this great city,
which we are constrained to supply as much as may be while we are in this nation.
We have thoughts to go into the country tomorrow,
where we think we may visit about four meetings this week,
and return again to be at Dublin next first-day, and then if the Lord enable us,
we think to go into the south, as into the province of Munster, Leinster and Connaught,
which will take up pretty much time, I received a letter from you,
which T. Robinson sent, and was glad of it,
but I expected another from you before this time,
which was the cause that I wrote no sooner now.

I sent a letter to you by the first post after we came ashore,
and about ten days after I sent a letter to Joan Vokins,
to whom I desire you to mind my very dear love, and to her husband and family.
I have received no letter from her as yet but what was annexed to yours.
I also then sent a letter to my brother John,
and this day received one in answer from him.
Mind my dear love to him when you see him, and also to his wife,
and to all Friends thereaway as if named.
To M. W. and D. A. whom I desire may not be negligent
in their endeavour for settling a women`'s meeting;
you are all concerned, for the Lord requires it of you.

Therefore look not out, but go on in the faith and His presence you will feel.
I could say much more: we have been at three women`'s meetings in Ireland,
and we are witnesses the Lord owns them,
and I am persuaded and am very confident that you cannot neglect it and be guiltless.
And mind my dear love to all Friends thereaway belonging
to Farringdon meeting and Ufliington and Charlow,
etc., I cannot particularize their names, but my dear love is unto them all,
desiring and breathing for their well-being in the Truth.
My dear love is to your father and brother and their families.

I should be glad to hear from you how things are and how Truth prospers,
and what Friends have been there.
So in that tender love of our Heavenly Father, which is shed abroad in our hearts,
and has made us near unto himself,
and thereby united and joined us together with all the faithful, in one body,
as with joints and bands; oh! let us in that same love dearly feel one for another,
and breathe one for another, and therein I rest and remain,

Your dear husband,

O, S.

Next day we went to Kilbalin and had a I meeting there,
in which the Lord answered the desire of the upright, for the diligent received a;
good reward, and the slothful and lukewarm;
were warned and exhorted to zeal and diligence in the obedience of the truth.

The same day we went to Castle-Dermot, and the next day,
being the fourth-day of the week, to New-Garden meeting,
and the day following to the weekly meeting at Ballinakill;
from which we returned next day to Castle-Dermot,
where was a large meetings at which many people were present.
And in all these meetings the faithful goodness of
our tender God was still extended to his people,
to our mutual refreshment and comfort together;
to Him alone the praise is due and the glory belongs,
and to Him be it ascribed forever and ever.

On the next day, being the seventh of the week, we returned to Dublin,
and were at their two meetings on the first-day which were very large;
and the Lord`'s power and presence was sensibly enjoyed to the comfort of the tenderhearted,
for which thanksgivings and living pure praises be given unto him forevermore.

We left Dublin on the third-day of the week, which was the 12th of the seventh month,
and being accompanied by many Friends went to Wick low,
where was a meeting on the next day; and the day following we had a meeting at Ballicave;
in both which the Lord`'s comforting presence still
accompanied and refreshed us with his people;
blessed forever be his holy name.

Next day we travelled in the county of Wexford, and lodged at a place called the Deeps,
From which next day, being the first-day of the week, we went to Thomas Holme`'s house,
where was a large and blessed meeting.
And the day following we went into the Barony of Fort,
and had a meeting at Balliconnick on the third-day, to which many people came;
and here also the Lord blessed us with his refreshing presence; glory be to him forever.

From there we went next day to a meeting at Wexford;
and the day following to a meeting at Lambs-town;
and to another meeting at Edward Goddin`'s the day after.
At which five last meetings, that honest, ancient labourer in the Lord`'s work,
Thomas Briggs,^
footnote:[Thomas Briggs was born in Cheshire about the year 1610.
In 1653 he was convinced by George Fox; in whose Journal, as well as in Sewel`'s History,
and other early writings, his name frequently occurs.
He, like Paul, "`was before a blasphemer and a persecutor,
and injurious;`" and like him also,
"`having obtained mercy,`" became a faithful minister and servant of Christ.
(See G. Fox`'s Journal, vol. i. p. 202.)
This Friend found it required of him publicly as well as privately,
to testify against the cruel and deceitful priests and their practices,
which exposed him and his exercised companions to much persecution.
{footnote-paragraph-split}
"`He was,`" says Whiting,
"`commanded to preach repentance through many towns and cities in England,
and the Lord`'s power and presence did wonderfully accompany him.`"
For a more detailed account of some of his labours,
the reader is referred to "`Persecution Exposed, in some Memoirs of John Whiting,`"
first edition, p. 133-7.
Both Whiting and Sewel mention his preaching through
the streets of London previous to the great fire,
and in Cheapside,
foretelling of the destruction of that city.
{footnote-paragraph-split}
He travelled much in Wales and other places in the service of the gospel;
becoming in many as a sign unto the people, "`a spectacle unto men,
a fool for Christ`'s sake;`" but was wonderfully preserved in his testimony,
and very instrumental where he was sent,
"`to open their eyes and to turn them from darkness to light,
and from the power of Satan unto God.`"
Not only did he suffer personally by imprisonment and the violence of wicked men,
but was fined five times for having meetings in his house, under the Conventicle Act;
his goods being taken to the value of £50.
{footnote-paragraph-split}
In his travels he frequently accompanied his dear brother George Fox,
and with him visited Ireland in 1669, and the West Indies in 1671.
A short time before his decease, "`being become old and weak, he wrote to George Fox,
in which he signified his perseverance in godliness.`"
He died near Nantwich about the beginning of 1685,
and bore "`a large testimony the first-day before
his decease;`" being aged about seventy-five years;
a minister thirty-two years.]
was with us; and very good precious meetings they were,
in which the life and power of our God was over all; blessed forever be his worthy name.

On the first-day following we were at the meeting at Wexford, where many people came in;
and a heavenly sweet meeting we had in the enjoyment of
the renewed love and life of our God in the midst of us,
to our comfort and great encouragement; to him forever be the glory rendered,
for all his goodness extended to us at all times and in all places.

The next day we went again into the Barony of Fort,
to a meeting that was appointed to be on the morrow at Leonard Lerlye`'s house,
and there also many people came in, among whom were some men of note,
as having been formerly officers in the army;
and a very good meeting it was for the opening and clearing
of Truth to the understandings of the honest enquirers;
and the authority of the power of our God was over all, blessed be his holy name forever.

We went next day to a meeting at John Fennel`'s house at Ballimonybig;
and the next day we had a meeting at Newbridge;
at both which places many of the world`'s people coming in, the meetings were large,
especially the last; and the presence and power of the Lord was with us,
being feelingly witnessed to the refreshment of the faithful, and for the awakening,
and stirring up the slothful and backsliders,
to diligence in the work which the Lord has called them unto.

The next morning being the 29th of the seventh month,
we had a meeting at Edward Goddin`'s in the forenoon;
and though it was but little yet it was a comfortable meeting,
the fresh living presence of the Lord being with us, blessed be his name forever.

From there going along with Friends to a fair at Enniscorthy,
we passed to Francis Randell`'s at the Deeps at night,
in order to be at a monthly meeting at Lambs-Town on the first-day following,
which was the first of the eighth month.
The meeting there was very large,
and the Lord made it also very good for us by appearing, according to his kindness,
in the midst, to the refreshing and comforting his heritage.

On the second-day we travelled to Waterford,
and had a meeting there on the third-day another
at Clonmell on the fourth-day in the evening;
another at John Fennel`'s on the fifth-day; and another at Tullow on the sixth-day;
at all which places the Lord our God was still with us,
and gave us his precious reward into our bosoms,
to our own and his people`'s great refreshment;
magnified and exalted be his name over all forever.

On the seventh-day we went to Youghal, and on the first-day had two meetings there,
in which the refreshing presence of our never-failing
God was sweetly enjoyed in the midst,
to the tendering the hearts of many.
On the second-day we went to Cork, and were at the meeting there on the third-day;
and on the fourth-day we went to Bandon, and so forward to John Allen`'s,
commonly called Major Allen, at night, and had a meeting there on the fifth-day;
from which, returning to Bandon we had a meeting there on the sixth-day.
And the Lord our God still continued his love and favour to us,
so that in all these meetings he was pleased to accompany us with his presence,
which made our meetings with his people,
to be times of refreshing and of renewing of strength to all his sincere waiting ones.
Oh! the glory over all and pure living praise is His due,
and to Him alone be it returned forevermore.
Amen.

We returned to Cork on the seventh-day and were at their two meetings there on the first-day.
We tarried there on the second-day also that we might be
at the six-weeks`' meeting for the province of Munster,
which began on the third-day, and ended on the fourth-day in the evening.
A very precious time we had with our friends in all those meetings;
for the Lord our God was exceedingly good unto us
in filling our cups and causing them to overflow,
and in a wonderful manner did he refresh his heritage;
and Friends`' hearts were exceedingly tendered and
enlarged towards us in the love of God.

On the fifth-day in the morning we left them and went to Malla,
where was a pretty large meeting.
And the next morning after we had a little time with Friends,
and had committed them to the Lord who had refreshed us together,
we passed from there to Charlowfield, and had a meeting there that afternoon.
It was a large and good meeting;
for notice had been given to Friends beforehand of our coming.
But it happened that the Bishop of Limerick was in the town
at that time with many priests and two or three justices,
and they consulting together caused the chief magistrate of that place,
who is called the Sovereign,
to send the constable with a company of men to our meeting to fetch away the speaker.

After the meeting had continued about three hours, the constable came in,
but very soberly, and stood still and heard a pretty while,
I being then declaring the Truth; and after some time the constable came near,
and taking hold of my arm, said, you must go along with me before the Sovereign.
I desired him to be sober and stay a little, and I should go with him without haling;
whereupon he let go his hold.
Then I spoke a few words in the dread of the Lord unto him,
to warn him to take heed how he laid hands on the innocent;
at which he seemed to be struck, and was much down in his spirit and silent.
Then I kneeled down and prayed, and the constable put off his hat while I prayed,
and stood quiet afterwards until the meeting broke up;
and then I went with him to the Sovereign; who, as soon as I was brought before him,
asked me, pretty courteously, pray what is your name?

I said, "`I hope you have no evil intent in this your asking,
and although I am not either afraid or ashamed to discover my name,
yet I would gladly know your purpose in it.`"

"`I ask you,`" said he, "`for no hurt.`"

"`Then I am very free,`" said I, "`to tell you that my name is Oliver Sansom.`"

"`Where,`" said he, "`is your dwelling?`"

"`My outward habitation,`" said I, "`is in Berkshire, in England.`"

"`What did you come over here for?`"
said he.

"`To preach the gospel,`" answered I, "`and to visit my friends.`"

"`What friends?`"
said he; "`have you kindred here?
or have you any business in merchandise?
I desire to know the chief cause of your coming here.`"

"`As for kindred,`" said I, "`after the flesh, I have none here that I know of;
nor for any gain of this world am I come; but I am come in obedience to the will of God,
who appeared unto me and laid a necessity upon me to preach the gospel;
and sent me here by the same Spirit,
by which he sent forth his ministers in the primitive times.`"

"`Then,`" said he, "`if you have no dwelling place you are a wanderer.`"

Upon that, a Friend that stood by interposing said, "`He is no vagabond,
I will be bound for him for a hundred pounds.`"

"`I did not speak so gross,`" said the Sovereign, "`as to say he is a vagabond;
but if he has no dwelling here I must account him a wanderer.`"

Thereupon I said, "`I am no more a wanderer than the ministers of Christ were,
as the scriptures bear witness; and if Christ himself were here or his apostles,
you might as well judge them wanderers as me.
For Christ said, he had not where to lay his head;
and his ministers left all and followed him, and had no certain dwelling-place.`"

"`Well!`" said the Sovereign, "`I might ask you for miracles,
but you will say they are ceased.`"

"`Were you at Cork?`"
said he.

I answered, "`I was at Cork.`"

"`Had you,`" said he, "`no dwelling there?`"

"`When I was there,`" replied I, "`I lodged at the house of Thomas Cook, a merchant.`"

"`I know Thomas Cook well,`" said he; "`but how long have you been in Ireland?`"

I told him "`Two months.`"

"`Then`" said he, "`you know the times are dangerous;
towns have been fired and plots have been contrived;
and you being one that wanders and can give no good account of your business,
I cannot let you go unless some will be bound for your good behaviour.`"

Thereupon I said to him,
"`I have declared the naked truth unto you concerning
my coming over here and travelling here.
And to the witness of God in your conscience do I appeal,
whether you do judge me a person suspicious to plot
against the government or to fire towns or cities.
But whether you will let me go or not, I take no thought for that;
for I am given up to the will of God, not only to preach the gospel but to suffer for it;
yes, even to seal my testimony with my blood if I am called to it.`"

Then said he to the Friends that were present,
"`If you will promise that this man shall come before
me again tomorrow morning at nine o`'clock,
I will let him go with you tonight.`"

They said they would promise, and so I went away with them.

Next morning one of the Friends went with me to the Sovereign`'s house,
and he being in bed sent to have the Friend brought up to his bedside;
and then told him, that the bishop of Limerick and several justices had been in town,
and hearing of the meeting, had sent to him to break it up, and secure the speaker.
"`Now,`" said he, "`I being a minister of the law could do no less than I did.
But however,`" added he,
i`'f you will promise and engage that he shall not come here again, I will let him go.`"

"`I cannot promise any such thing`" said the Friend;
"`for it may be the Lord may require him to come again.
But this I can say, that his intent at present, as I understand,
is to pass away if he has his liberty,
and I believe he has no purpose at all to return here before he goes for England;
but I cannot enter into any engagement for it.`"

"`Then,`" said the Sovereign, "`he may go where he pleases.`"
I was waiting below all this while, and when the Friend came down,
and acquainted me what had passed between the Sovereign and him,
and that I had my liberty to go away, I felt an exercise come upon my spirit,
so that I was not clear to go.
Whereupon I desired to speak with the Sovereign myself; which being granted,
when I came up to his bedside, he thus began with me.

"`How do you do, Oliver?
Would you speak with me?`"

"`Yes,`" said I.

"`Pray, what is your will?`"
said he.

"`When I was brought,`" said I, "`before you yesternight,
you did ask me several questions concerning the occasion of my coming into this nation,
and I told you the naked truth from my heart, how that I came in the name of the Lord.
But I then perceived by you that if I had come in my own name and on my own business,
as a merchant, to buy and sell, or the like,
you would have received me courteously and entertained me kindly.
But I am now come in obedience to the Lord Jesus Christ,
as his messenger and servant to preach the gospel in his power and authority.
And seeing you profess yourself a Christian, and in words do call Christ, Lord,
now let it be manifest what entertainment you have for his servant.
Will you receive me and hear my message?`"
To this he gave no answer; wherefore, after a little pause, I went on and said,
"`If you will hear me then call up your family together,
and here I am ready to declare what I have received from the Lord.`"

To this he answered, "`No, no.`"

"`Then,`" said I, "`if you will not receive me nor hear my message,
the substance whereof is that the heavenly kingdom and government of Christ is at hand;
and behold, it is to be sought and waited for within,
then must I shake off the dust of my feet as a testimony against you.
Yet notwithstanding, be you assured of this, whether you will hear or forbear,
that the kingdom of heaven is at hand, and very nigh unit you.`"

Hereupon the Sovereign said, "`I have not faith to believe,
and many do run before they are sent.`"

"`Such,`" said I, "`are the hirelings who run for gain and profit,
by whom you and others have long been deceived.`"

"`I do not yet believe,`" said he, "`that you are a true messenger.`"

"`You did hear,`" said I, "`the last evening, the evidence of them that heard me,
and of their owning my message, which may be looked upon as a seal to my ministry.
But I would have you retire within and hearken to God`'s witness in your own conscience,
and mind the testimony thereof, whereby you may be fully satisfied.
And moreover, I am not ashamed nor afraid to appear to vindicate my call and message,
through the help of God, to the faces of any that shall oppose it,
either by word or writing, though it be any of them whom you do judge true ministers,
and to whom you pay hire; that so it may be openly manifest who are sent of God,
and who are sent by man.
And, as I told you before,
I came not here for either gold or silver or any thing of this world, nor in my own will,
but in obedience to the will of my Lord Jesus Christ, who has said,
it shall be more tolerable in the day of judgment for Sodom and Gomorrah,
than for those that slight his servants and reject their testimony.`"

To this the Sovereign only said, "`I have not faith to believe.`"

Then, with respect to his having asked my friend to promise that I should not come there again,
I said to him,
"`I do now let you know that I cannot consent to any promise
or engagement concerning my passing away or not coming again.
Here I am in the will of God offered up;
if he gives you power to detain me I seek not my liberty.`"

"`You may go about your business,`" replied he, "`I have done with you.`"

"`Then`" said I, "`the Lord God in whose hand my breath is,
knows that I have nothing in my heart but tender love towards you;
and I believe that one day you will repent, I wish it be not too late first,
that you have slighted this opportunity.`"

Then finding myself pretty clear of him, I left him, and as I turned from him, he said,
"`pray God bless you.`"

Being thus set at liberty, I with my dear companion S. B., went the same day,
being the seventh-day of the week, and the 21st of the eighth month, 1676, to Limerick,
where we tarried the first-day, and were at both the meetings,
and the good presence and power of our God was with us,
to the refreshing of us with his people, blessed be His holy name forever.

Very loving and tender to us were the Friends of this place,
and many of them came to visit us in the morning at our lodging,
where we sat together awhile and had a good time with them;
and then taking leave with prayer we passed away,
and some of them accompanied us as far as to Birr, which was thirty-two miles.

There we had a meeting on the third-day,
and on the fourth-day we went to Abraham Fuller`'s at Lehinch,
and were at the meeting at the Moat of Grange on the fifth-day;
and returning back again to Lehinch had a meeting there on the sixth-day.
On the seventh-day we went to Mount-mellick and were at the meeting there on the first-day,
and passed from there to John Pim`'s at night.
And at all these meetings the Lord still continued his love and goodness to us,
and wonderfully strengthened and upheld us by His mighty power;
blessed and praised be His worthy name forever.

On the second-day we went to Ballinakil and visited the Friends there,
and having tarried some time with them we went to William Harris`' to lodge.

On the third-day, being the 31st of the eighth month, we had a meeting at Kilkenny,
where abundance of people came in, and the presence of the Lord was with us;
and His life and power were over the meeting,
to the convincing of gainsayers and refreshing the faithful;
praises over all be to our God forevermore.

Next morning we went to John Watson`'s, where we had a meeting on the fifth-day;
and on the sixth-day we had a meeting at Carlow.
And at both these meetings the Lord continued his love and tender mercy
to us as at other times everlasting praises be returned to Him forever.

On the seventh-day we went to the six weeks`' meeting for the province of Leinster,
which was held at Castle-Dermot and lasted two days;
and a very good and large meeting it was.

Dublin, 7th of Ninth month, 1676.

My dear Wife,

My dear and tender love does reach unto you and does dearly salute you,
with your dear sister and all the upright in heart thereaway,
earnestly desiring that you may be preserved and kept by the power
of God unto the everlasting salvation of your souls,
that so we may see one another face to face with joy,
if the Lord do bring us together again.
Dear heart, my breathing is truly for you,
that you may grow in the life of Truth and press
on from one degree of godliness to another,
that fruits may be brought forth daily unto Him in due season,
who is the good Husbandman, who long ago has sown the good seed in our hearts,
and watered it from time to time with the dew from heaven;
and surely now the time for fruit is come, and he expects it from us all.
Oh! that ripe fruits of righteousness and holiness might be brought forth,
and yielded unto Him from all the plants of His own right hand planting,
that He may be glorified, who alone is worthy of all glory and honour,
and immortal praises to God over all blessed forevermore.

Dear heart, I wrote to you from Cork,
and the next day I received a letter from your sister and you, and was right glad of it,
and was truly refreshed in the sense of the tender love of our heavenly Father,
who has answered the expectation of my heart,
and fulfilled and satisfied the desires of my soul,
in carrying on His own work by His own blessed power, in His own way and time,
by His divine wisdom and counsel, to the satisfaction of the upright in heart;
blessed be His holy name and glorified be His unsearchable wisdom forevermore.

Now this may let you know that I and my companion are very well,
his love is to you and Friends, and the Lord has been exceeding good unto us,
and tender over us from day to day and from time to time, and from meeting to meeting,
since we parted from you.
Oh! his mercies are infinite and inexpressible,
and the sense of his tender love does even overcome and break my heart,
and even force tears from my eyes in the writing of it.
Oh feel! feel the power of it and be refreshed,
and let it constrain you to breathe with me and travail with me that I
may feel you as a helpmate in spirit unto me in the work of the Lord,
that His righteousness may be brought forth,
and His salvation be revealed more and more in the hearts of the children of men,
and that I may finish my testimony with joy,
to His praise and glory who alone is worthy of it forever.
We have gone through this nation and came to this city yesternight.
Here is a general meeting begins tomorrow for the whole nation;
abundance of Friends are come already to town.
John Banks is here, his love is to you; and when one first-day more is over,
we see nothing at present but we may be clear to return to England.
So in dear and tender love to you and to your dear and tender sister,
and to your and my relations as you have opportunity,
and remember my dear love to all upright-hearted Friends in general that ask after me,
as if named; hoping in the Lord`'s will and time to see your faces again,
I shall cease to write further.
But in that which was before words and writing were, feel and read me,
in which I rest and remain your dear husband.

O+++.+++ S.

On the second-day we went to the half-year`'s general meeting at Dublin,
which began on the fourth-day of the week, being the 8th day of the ninth month,
at the ninth hour in the morning;
and the meeting for worship continued until after the first hour.
About an hour after.
Friends met again in order to consider of the affairs of the church;
but the power of the Lord broke forth so mightily among Friends in many testimonies,
prayers and praising the Lord, that there was no time to enter upon business that day,
and so the meeting broke up.

Next morning the meeting began again about the ninth hour,
and continued until near the third hour in the afternoon,
and a precious heavenly time it was; then adjourning for an hour.
Friends came together again to go upon the business of the meeting;
but then again the Lord`'s power mightily appeared,
whereby many mouths were opened to declare of the goodness of the Lord,
and to offer up prayers and praises to him; which took up the time of that day also,
so that very little could be done as touching business.

But early next morning Friends went about the business of the meeting,
and continued at it the greatest part of that day and the next day also.
And in much unity and harmony generally was the business
managed and carried on all the time,
only there happened some difference between some particular persons,
which occasioned some trouble for a little while;
but the diligence of Friends was not slow to put
an end quickly to it and proved successful therein;
and the Lord`'s presence was preciously enjoyed,
and his mighty power was over all and broke forth through many vessels, in testimonies,
prayers and praises;
so that the business could not be accomplished until the seventh-day in the evening.

Next day, which was the first-day of the week, there were two public meetings,
which were very large and lasted almost all the day;
and a very heavenly season it was all the time that the Friends were together,
in those five days;
in which time there were nine meetings held at the largest meeting-house.
And the powerful presence of the Lord was greatly manifested;
blessed and praised and magnified be His holy name forever.

On the second-day morning the country Friends began
to disperse and depart out of the city;
but we stayed some days longer;
and in the afternoon we visited the women Friends at their meeting;
where we found the good presence of the Lord was among them,
for the comforting and encouraging them in his work and service.

We went also the next day to the men`'s meeting; where the Lord in his goodness to us,
did make us sensible witnesses that he is no respecter of either persons or sexes;
but as male and female are faithful and diligent in their duty,
in doing the work and service he has called them unto in their respective places,
they are accepted with him and owned by him.

On the fourth-day in the evening, we had a little meeting at a Friend`'s house,
where many of the world`'s people came in and were very sober;
and the Lord`'s power was over all; praised be his name forever.

Their weekly meeting was on the fifth-day, at which we were;
and on the sixth-day we went to a meeting, appointed for us at Chapel-Lizzard;
unto which many of the world`'s people came.
And there also our gracious God, who never fails his,
did answer our sincere desires to our satisfaction.

We spent the seventh-day in visiting Friends at their houses in Dublin.
And on the first-day, there being three public meetings in the city,
we were at two of them with our dear friend John Banks^
footnote:[John Banks was born in Cumberland, in 1637.
At sixteen years of age, which was before he heard the doctrines of Friends preached,
he was convinced of the Divine Light in the heart as professed by them;
and being inwardly directed to go to one of their meetings, he went to one at Pardshaw,
where few words were spoken, but a great impression made on his mind.
He subsequently became a minister among Friends,
and travelled in that character through several counties.
He laboured zealously and very extensively,
in the promulgation of the gospel in Scotland and Ireland.
In the course of his labours he encountered many difficulties and dangers,
and crossed the sea twelve times.
He was weightily concerned to go forth into those districts,
where the spirit of separation, originating with Story and Wilkinson,
as mentioned by O. Sansom at page 68, had gained ground,
in order to bear his testimony against it.
It was also his lot in common with his contemporary fellow professors to suffer persecution
by imprisonment and spoil of goods.
{footnote-paragraph-split}
In the year 1696,
he removed into Somersetshire, and died at Street in that county, in the eighth month,
1710.
His end was peace, as appears from his dying words, "`It is well with me:
I have nothing to do but to die, and I shall end in the Truth as I began.`"
For further particulars, see his valuable journal.--Vol.
2nd of Friends`' Library.]
from England.
They were very large and precious meetings, and that which made them so,
was the Lord`'s refreshing presence,
which was sweetly enjoyed to the satisfaction of the upright-hearted;
everlasting praises be offered up to him forevermore.

We went next day into the country, beyond Edenderry,
where we had a meeting on the third-day; to which many tender people came in;
and the power of the Lord was wonderfully felt over the meeting,
which caused a great tenderness and openness,
to the great satisfaction of the hungry souls;
the Lord alone is worthy to have all the glory forevermore.

Being greatly comforted at that meeting, and our desires fully answered there,
we returned with joy to Dublin on the fourth-day,
and were at the weekly meeting there on the fifth-day.
On the sixth-day we went again to a meeting at Chapel-Lizzard,
and there being no meeting on the seventh-day,
we spent that time in visiting Friends at their own homes.

On the first-day we were at three meetings;
whereof two were in the great meeting-house and were very large,
the other was in the evening and at a private house;
and at all these meetings the Lord was with us,
and both strengthened and refreshed us with his people,
in the enjoyment of his living presence and power;
blessed and praised be his worthy name forever.

On the second-day we visited the women Friends of that city at their meeting;
and on the third-day the men Friends at theirs;
that we might take a solemn farewell of them, before we left Ireland;
which we purposed to do the next day.

Dublin, 25th of Ninth month, 1676.

My dear Wife,

Yours I received with your dear sister`'s dated the 1st of this month,
and am truly glad to hear from you and greatly refreshed
in the tender love of our heavenly Father,
in which our unity and communion stands, which sea or land cannot divide or separate.
And in this unchangeable love let us feel for one another and breathe for one another,
that we may always be a help and strength one unto another,
and one another`'s comfort and joy in the Lord,
that all our exercises and trials may work together for our good,
and for the glory of the Lord, who is worthy of all glory,
honour and praise of all His redeemed ones forevermore.
Dear heart,
we could not be clear to leave this nation according as I expected in my last,
but we have been back in the country since, and we are not yet clear of this city,
but we hope we may towards the latter end of next week, and if the wind serve,
and we are clear we may go to sea;
for the Lord has been so good unto us and tender over us all along,
in keeping and preserving us in all our exercises,
that our souls are engaged and constrained to wait upon Him,
that we may feel and enjoy his presence with us in our returning back.
But indeed we had a desire to return according as I wrote to you,
and had partly agreed with a shipmaster to carry us,
but I could not have peace until we had got off again.
So now we desire to stand single to the Lord, knowing that his time is the best time,
and believing that He will make way, that we may before long see each other`'s face,
and so I shall cease at present to enlarge in writing.
Yet look not out for me until you see me, but if we tarry longer than we expect,
I may write again.
Hereby you may know that I am very well and lack nothing, for the Lord is my Shepherd,
who takes care of me every way, blessed be His name forever.
So unto Him do I commit and leave you,
who also is and will be the same to you as He is to me,
if you hearken to His voice and follow Him.
And so in that unchangeable love which was before ink and paper were,
does my soul salute you, with your dear sister and all the upright in heart,
and rest your dear husband,

O+++.+++ S.

But in the morning when we were almost ready to depart,
many of the Friends came to our lodging,
with whom we spent some time in prayer to the Lord;
and then committing them to the word of his grace,
in great love and tenderness of spirit we took our leave of them;
and several of them accompanying us to the ship we went on board,
and in much clearness and satisfaction,
in the fruition of our Heavenly Father`'s love we left that nation.

Thus through the Lord`'s supporting power,
which bore up our spirits and kept us from fainting,
were we exercised as is before expressed, in the service of the Lord,
with all our might and utmost diligence during the time we were in Ireland,
which was four months; in which time we travelled nine hundred and fifty miles,
going to and fro from meeting to meeting in that nation.
And the only aim and end that was sought by us in this undertaking,
was singly the glory of God, in doing our duty in obedience to his requirings,
for the gathering of the scattered ones to Christ the great Shepherd,
and for the building up and confirming in the faith them that were gathered,
to the measure of grace and ability the Lord was pleased to bestow upon us.

About the second or third hour in the afternoon, the ship wherein we were set sail;
and the wind being at south and southwest, and blowing strongly,
the vessel ran so swiftly that we got near Holy-head before midnight,
but towards sunrising it grew pretty calm,
and near the middle of the day the wind coming easterly and blowing stiffly,
the seamen were eager to toil and tack about often to and fro;
yet through the mercy of the Lord we came to anchor before sunset,
and were set on shore two miles from Nesson, and going to a village that was nigh,
we got lodgings there that night.

Next morning, being the 1st day of the tenth month, we went back to the ship;
and having got our horses out, we went to Liverpool;
and having stayed there with Friends a little time,
we passed on three miles further to Henry Baker`'s house,
where we had lodged before we went over;
and there we tarried the seventh-day resting ourselves.

On the first-day we went to a meeting at Liverpool;
where our tender God in his kindness did sweetly
comfort and refresh us together with his people,
by affording His good presence in the midst of us, blessed be His worthy name forever.

We had also a meeting that evening at a Friend`'s house without the town,
where many baptists and other people came among us; but all was quiet and well,
for the Lord`'s power was over all to our great comfort and satisfaction.

On the second-day we went to a quarterly meeting in Cheshire,
and lodged at Alexander Lawrence`'s at night.
On the third-day we travelled towards Stafford;
and on the road we fell in company with a friendly man,
who had us with him to his house three miles from Stafford,
where we had a meeting that evening to which many of his neighbours came.
Next day we passed to Stafford, and having visited two Friends that were in prison,
and called upon Thomas Taylor`'s wife and daughter, he himself being from home,
we went on to Birmingham, and had a meeting therein the evening.

From there going on the fifth-day to Warwick, we had a meeting there also in the evening;
and went next day to a monthly-meeting at Lamb-cut in Warwickshire.
In all which meetings the Lord our God was with us and upheld us by his mighty power,
and refreshed us with his living presence among his people in all places where we came;
so that to the praise and glory of His great name we have good cause to say,
our God has been with us and blessed us both in our
going forth and in our returning home;
and all along by his mighty power,
He has preserved us and strengthened us to do his will.
Wherefore in humility of heart and soul we can sincerely say, not unto us,
poor weak worms, not unto us, but unto his powerful name, be all the glory, honour,
wisdom and strength ascribed and returned forever and evermore.
Amen.

After I had been some time at home,
the remembrance of Friends of Ireland and of my travels and labours
among them in the Truth was weighty upon my spirit;
and in a sensible feeling of the renewings of the love and life of my God,
which I had often enjoyed among them,
my heart was overcome and greatly tendered towards them; so that I could not contain,
but was thereby moved and even constrained to visit them with an epistle in writing,
the copy whereof here follows:

To Friends of Truth in the County of Wexford, and elsewhere, in Ireland.

Dear Friends,

Brethren and sisters, born of the immortal seed,
whereby you become heirs of life and immortality,
and who are daily striving to inherit and possess that immortal life,
which through the spiritual birth, you have a right unto and interest in.
The salutation of my dear and unfeigned love truly reaches unto you all,
in the innocent life of the Lamb, in whose spirit is no guile,
having you often in my remembrance;
and the living sense of the blessed presence of the Lord,
which in meetings I with you enjoyed, does often refresh my soul;
and as the same life arises and is tasted of and fed upon, then are you often before me;
and tender breathings arise in me for you all, as one man, that as a united body,
you may together be preserved, holding in all things the head Christ Jesus.
And that, as members one of another,
you may in the spirit and life of Jesus be united one to another,
being all bound up in one bundle of life by the swaddling band of tender love,
which in all your hearts is shed abroad by the Holy Spirit.
That a holy care may be in all for each others`' good and welfare in the Truth,
even as for his own; having an inward feeling one of another,
that if one member be hurt or bruised, or comes to suffer, all suffer with him;
and if one member be comforted, all take part of it; and so here,
one cannot say to another, I have no need of you; but we are all helpers one of another,
with that help which we receive from the Lord; and therein we are a help,
strength and comfort one to another.
Here now is seen how pleasant, sweet and precious it is for brethren and sisters,
the begotten of one Father, and born of and nursed by one mother,
to dwell together in heavenly unity.
Oh, feel Christ our life herein; and feel our nearness in the same one unto another.
That so the true unity of the right Spirit you all may keep and hold,
which is the living bond of peace; for that soul, whoever it be,
that goes out of this bond goes out of peace into trouble.

O Friends! watch and stand upon your guard,
and hold fast your living fresh zeal for the cause of the Lord,
and be valiant for his Truth upon earth.
And keep out of the false spirit,
which under a disguise or show of Truth waits for an opportunity to creep in among you;
for if he prevail in any he will draw the mind down
from the heavenly habitation in the light,
into the earth, and then lukewarm ness instead of zeal,
and jealousies and secret prejudice will get in,
and the love which thinks not evil will come to be
weakened and by degrees grow cold and die.
Oh Friends! there is as much need for us to be watchful now as ever there was;
for the enemy is working in the deepest deceit and most secret subtlety.
He appears now in his transformed shape, like an angel of light;
and where any are wandering in their minds or scattered in their imaginations,
letting in earthly desires, they can hardly escape his snares.
For they only who abide fixed on the Rock shall be preserved;
and they are the true Church, which Christ is the builder of;
against which the gates of hell cannot prevail.
And these also are the very elect which cannot be deceived.

Therefore, my dear Friends,
let every one of you be diligent to witness your
calling and elec tion to be made sure unto you;
that none of you may be deceived or beguiled by the subtlety of the wicked one,
and that no evil bitter root may spring up among you to trouble or disquiet any of you,
tending to divide or make you at a distance one from another.
But keep this evidence every one always in your hearts,
that you are passed from death to life, because you love the brethren.

And dear Friends, as wise virgins, always wait to feel the oil of life,
and be careful to retain it in your own vessels.
This will keep the lamp, which the Lord has lighted, from going out,
and give you an entrance into the marriage-chamber to enjoy the beloved of your souls.
For as surely as our heavenly Father has given the light
of the life of His dear Son for the salvation of mankind,
and caused it to shine in our hearts; so surely does he require of us all,
that we should submit and yield obedience to it, and let it shine in our conduct;
that we may do the works of it in sincerity; and men, who are yet in the world`'s spirit,
beholding our good works, may be convinced and come to glorify our God,
and to testify that he is in us of a truth.
This is more effectual than all words that can be spoken; yes,
it is indeed the seal of our ministry and testimonies,
and an answer of the travail of our souls, who have faithfully laboured among you.
And seeing it is so,
that we are commanded to let our lights shine for the good
of others that are without and not gathered to God,
then consider how much we are enjoined,
and in an especial manner commanded to take care of our own family,
even the household of faith;
that at all times we watch for the good and benefit one of another.
And all who do believe in the light of Jesus, and walk in it,
as their minds are exercised in His life and love,
the care of the Churches of Christ comes upon them daily, for the good of the whole body;
that every member may keep his place in the body and wait to know his office,
even his work and service appointed by the Lord.
And then as the eye is kept single in the head Christ Jesus,
every one will be serviceable in his place;
for there are no needless members in the body,
no useless vessels in the house of our God:
for as a gift is given to every particular one,
so is a service as certainly required by the Lord of every individual,
according to the gift given.
And as obedience is yielded to the leadings of the blessed Spirit in the gift received,
here is a vessel of mercy that is given up to be used by the Lord; and in his using,
it comes to be made a vessel of honour,
to the praise of the glory and excellency of the
heavenly treasure which the Lord reveals there n.

So dear Friends,
much might be said as to this matter to stir you up to diligence in pressing
forward towards the mark of your high calling in Christ Jesus,
which is set before you,
and to exhort one another daily to watchfulness and faithfulness,
each in his place and station,
and to take heed that there be not a drawing back into the world again,
for the Lord has said, '`He that draws back,
my soul shall have no pleasure in him:`' but that
all hold fast the holy Testimony of Jesus,
which you have received; and press forward in the meek spirit, and walk circumspectly,
that our holy profession may be adorned with a holy, harmless and unblameable conduct.
But I know there are many faithful brethren who labour among you,
and frequent testimonies you have to this purpose.
And although you know these things already,
yet I have a sense that a word of exhortation will be tenderly received by you;
as the same love is felt in you from which it does proceed,
although through a weak instrument.

And moreover this is my testimony,
that if true obedience be yielded to the inward leadings of the Holy Spirit,
a godly care and weighty concern for the prosperity of the blessed Truth,
and the preservation of all that are convinced of it,
will certainly come upon every one according to his measure.
And for this blessed end is the use and service of men`'s and women`'s meetings,
which in the wisdom and power of God have been set up and established among you,
+++[+++and are]
seen to be very proper and necessary.
Wherefore having such frequent and heavenly opportunities,
O be diligent in the improving of them,
as you see the heavenly day more and more increasing.
And exhort one another daily while it is called today,
and labour to stir up and provoke one another to love and to good works.

So dear Friends, be faithful to the Lord,
and true and honest to your own souls and one unto another,
in keeping diligently to your meetings; which,
as you therein faithfully discharge your duty,
will conduce much to the honour and glory of the name of the Lord,
and the welfare of all your souls both here and hereafter.
And of this be assured, that where there is a slackness in any in coming to meetings,
there is first a slackness of spirit in such in obeying the Lord.

I can truly say, my heart is enlarged towards you in the love of my God,
beyond what I can express; and it lay upon me to send these lines unto you,
as a token of that brotherly love which lives in my heart
towards all the flock of my heavenly Father`'s fold;
breathing unto Him, who is the God and keeper of his spiritual Israel,
who never slumbers nor sleeps, but watches day and night over us all for our good.
Oh! the cries of my soul in secret are,
that the whole flock and family may be preserved in unity,
yielding pure obedience unto the heavenly Shepherd;
that they may be always led and guided by Him into the fresh pastures of life,
where the soul`'s true satisfaction is enjoyed.

So, dear Friends,
in all your meetings wait to feel the self-denying life of our Lord Jesus;
for therein only can you find acceptance with the Lord.
And whatever you do for the Lord, or on behalf of his Truth, do it in the name of Jesus,
in and by the leadings of His meek, patient, and self-denying Spirit.
That so nothing may be done among you through strife or vainglory;
but let humbleness of mind be as a crown upon every one of your heads;
that in the love which thinks not evil, you may be willing to serve one another daily.
For all who will follow the Lord and bring honour to His name, must deny themselves.
And so in the holy, self-denying life of Jesus, the meek Lamb of God,
do I at this time bid you all farewell, and therein rest.

Your dear brother,

O+++.+++ Sansom.

Farringdon, the 20th of Fifth month, 1677.

Let this be carefully copied over and communicated among Friends in Ireland,
as in the wisdom of God a service is seen.

I sent this epistle directed to Leonard Kerly, in the county of Wexford;
from whom afterwards I received an account that it
was read at their following half-year`'s meeting,
and from there dispersed among Friends through that nation.
