== Chapter VII.

[.chapter-synopsis]
* His letter with the two books to Justice Parrel
* Three letters to his wife from the prison
* All the goods taken from his house and shop while in prison
* To the Sessions at Newbury and recommitted for not swearing
* Two letters to his wife
* His epistle to Friends under suffering
* Sessions at Wantage
* With other Friend is recommitted for not swearing
* The Sessions at Reading
* Is still continued in jail
* His letters to Justice Fettiplace.

Mention being made before, that Charles Parret, called a justice,
had manifested much envy, in seeking to have the oath tendered to me,
to deprive me of my liberty; and among other expressions alleging,
that I had sent him two books and a letter:
I think fit here since I could not so well do it there,
to give the reader briefly an account of the occasion which led me to write to him;
which was thus.

He had dealt very hardly with a Friend that lived near him,
belonging to Appleton meeting; and I having a concern upon me to seek to moderate him,
sent him two little books, whereof one was entitled,
A "`Dissuasive from Persecution;`" the other,
"`Christian Religious Meetings Vindicated.`"
These books I enclosed in a sheet of paper, and wrote therein as follows:

[.embedded-content-document.letter]
--

[.salutation]
Justice Pareet,

Having an understanding of some late rigorous proceedings
against some of your honest neighbours,
and the king`'s peaceable subjects called Quakers, living in and about Appleton,
by warrants from you, only for the exercise of their tender consciences,
in sincerity towards God in matters purely spiritual, concerning faith and worship,
relating to his kingdom.
Wherefore in love and Christian respect to you, and on the behalf of them,
I do herewith in humility present to your view two little books;
hoping to find that nobility and moderation in you,
as to bestow a serious and candid perusal on them.
And so at present I do leave them to your Christian consideration;
desiring the Lord to incline your heart to justice, mercy and truth;
that you may be happy eternally.
I am,

[.signed-section-closing]
A friend to all that love righteousness,

[.signed-section-signature]
O+++.+++ Sansom.

[.signed-section-context-close]
Farringdon, the 1st of Sixth month, called August, 1683.

--

This letter I sent by the post: but could not understand that he had received it,
until he, about five months after, spoke of it himself in the open sessions;
and then charged it as a crime upon me.

[.offset]
+++[+++While imprisoned at this period, he wrote the letters which are subjoined, to his wife.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Reading Jail, 26th of Twelfth month, 1683.

[.salutation]
My dear Wife,

The dear and tender salutation of my endeared love truly reaches unto you,
wishing and praying above all things,
for your preservation and establishment in the precious Truth with my own soul,
that we may pass the time of our pilgrimage here according the will of our God,
and faithfully finish that testimony which he has given us to bear,
to the laying down of our heads in peace forever, where the wicked cease from troubling,
and where the weary are at rest;
where the prisoners rest together and hear not the cry of their oppressors.
Oh let us be cheerful, for it will not be long before we come there,
as we abide faithful and heed not the rage of the wicked, so as to be cast down at it;
for our God, as we wait upon him, will give us more strength to bear afflictions,
than they shall be able to inflict upon us.
Oh, it is a precious thing to be kept in the patient innocent spirit of Christ Jesus,
which enables us to love our enemies and pray for our persecutors;
when we are reviled not to revile again,
but to commit our souls to him who judges righteously, who is our faithful Creator,
and mighty preserver, and the sure deliverer of all them that trust in him;
who is the only wise omnipotent God, blessed forever.
Amen.

Dear heart, I received yours, and was glad to hear of yours and Friends`' welfare.
Though hardships do continue yet, they will have an end,
and am well satisfied that E. L. stands so singly resigned in his testimony for the Lord,
his reward will be sure as he continues so.
It seems very strange to me that old T. R. should continue so cruel and be so
very wicked--I am sorry for him that he should thus hasten on to his own destruction;
let an account be taken and kept of his wicked and cruel doings,
and mark and see the end that will come upon him.

I have received the bed, but have not yet opened it, with two cheeses besides,
I have been,
and am still very busy in drawing up papers to lay the sufferings
of Friends before the judges and grand jury at this court session;
what the effects of it may be, I may let you know the next opportunity.

So desiring my very dear and fervent love may be remembered to all Friends,
as if named one by one, and to your sister Vokins when you see her, with all her family,
and also to them at Gooses, and to my brother D. B. and sister, at Charney, and to Sarah,
and E. B., and E. W., and once more to yourself is my entire love,
and rest your dear husband.

[.signed-section-signature]
O+++.+++ S.

[.postscript]
====

When E. Wightwick is out of her Bible,
let her read the first book of Chronicles and Nehemiah over again.

====

[.signed-section-context-close]
Reading Jail, 4th of First month, 1684.

--

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

My true and entire love salutes you, sincerely wishing your welfare,
and breathing to my God for your preservation and establishing in the truth,
as for my own soul; that being founded on the heavenly Rock,
no storm may ever be able to shake us or cause us to waver,
but may be surely settled forever, to praise and magnify our tender God,
who has been so good unto us, who is over all blessed and worthy forever.
These may let you know through the Lord`'s love I am pretty well,
and did expect to have heard from you yesterday, by Thomas George,
to have known how you and Friends are in your present exercises.

There was nothing done more at the court session about Friends, as to outward appearance,
by reason of the printed summonses there were none called, until quite at last,
they called them over as they used to do.
Our jailer, by Parrot`'s means, was sorely checked for letting us have liberty.

+++[+++Then follow instructions with regard to disposing of part of their business,
the patten-making, which he appeared to follow in prison,
as there are orders to bring him "`leather, irons, and rivets.`"
He also wanted "`some line to make a cord for a bed.`"]

So with my dear love once more to you, and J to E. L., G. A., and M. R.,
and all the rest of Friends as if named,
to S. A. and the children whom I desire may take heed and do well.

[.signed-section-closing]
I remain your dear husband,

[.signed-section-signature]
O+++.+++ S.

[.signed-section-context-close]
11th of First month, 1684.

--

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife.

My true and entire love salutes you, desiring your prosperity in the precious truth,
which is better than all the increase of the fading things of this world.
This is to let you know that I have been, and spoken with John Hankin and his wife,
and have agreed with them at a rent for their house and land in Farringdon,
and the terms I may let you know when I see you.
Let Mary Butcher know that her letter was received,
and her sister desires that if in case the barn be in danger to fall in a little time,
she would get a workman to prop it up until she comes,
which may be about the time called Easter, or shortly after, if she be well,
and then intends to take course to repair the house and barn.

Mind my love to all Friends;
as your freedom is you may let them privately know that I cannot come to Charlow,
on the first-day to be at the meeting, as I spoke to you of,
but do hope to be there on the second-day at night, after the women`'s meeting is over,
or on the third-day, and to tarry thereabouts to be at the men`'s meeting,
if it be at a place convenient, +++[+++line not plain,]
where I hope we may settle things in a better method than it is now.

I shall look for the writings of the meeting house,
(with what lacing you have to tagg,) next second-day by Thomas George or John Church;
send my drawers too, and let me know how you all do, and how your meetings are.
My dear love is to your sister J. V., (Joan Vokins,) and tell her I perused her letter,
and was comforted in the sense of the tender love of God in her heart towards me.
Mind my kind love to E. L. and his sister, and to G. A. and his wife,
and M. R. and his wife, and T. R. and his wife and his brother William,
and to my brother and sister, and Thomas Strange at Charney, and also to them at Gooses,
and to R. B. and to all the rest of Friends as if named one by one; desiring that grace,
mercy and peace, with Christian courage and valour,
may continually be increased and renewed in and among you all,
that the Lord our God always may have the praise, and honour, and glory,
in all our doings and sufferings for unto Him it all belongs,
who is blessed and worthy over all forevermore.
Amen.
In haste,

[.signed-section-closing]
I rest your dear husband,

[.signed-section-signature]
O+++.+++ S.

--

But to proceed, while I was now in prison, these two wicked imformers,
Thomas Welman and Angel Smith, having before sworn against me,
for having been at many meetings, procured warrants from Humphry Hyde,
(called a justice) to levy above a hundred pounds on my goods.
And these warrants being all in the hands of one Thomas Reynolds,
the officer who then swayed all the rest,
he made no distress so long as I was at liberty; but still made excuses to save himself.
But when I was in prison and within one month after my commitment, he came to my house,
having only the said two informers with him to assist him,
and seized and carried away all my shop goods, as linen cloth, fustians, tapes,
filletings, laces and thread, even all they could light on, with brass, pewter,
and other household goods, only when they were carrying it all away,
he threw back a small brass kettle,
saying he would leave that to boil the children`'s milk in;
for I had then two children in my family, whereof one was a relation`'s daughter,
and the other an orphan that was left to my care, as her guardian.

Besides these goods, they took also out of my stable a mare that was not mine,
but borrowed of a Friend, and with her my bridle and saddle.
And though the Friend, who was the owner of the mare,
endeavoured what he could to recover his mare again, yet he could not:
for no justice could then be had;
oppression and cruelty were the portion of faithful Friends at that time,
while the informers were in power.

The said Thomas Reynolds would not allow any account
to be taken of those goods thus taken away from me.
For which, I suppose his reason was,
that judging them not sufficient to answer all the fines that were imposed upon me,
and mentioned in his warrants,
he was not willing the rest of those fines should be levied upon others;
fearing perhaps his own son, who was a Friend, might come to suffer thereby.

But, as near as could be guessed, the goods then taken away were worth thirty pounds,
or upwards; and he took such a time for taking away my goods,
that there was nobody in the house but the two small children whom I mentioned before.
I myself was in prison at that time,
my wife was gone abroad to visit one that was not well,
and my maid-servant happened to be then from home.

This Thomas Reynolds, flushed with the booty he had gotten,
became afterwards more hardened,
and acted more cruelly towards Friends in their meetings;
not only shutting them out of their meeting-house,
and thereby forcing them to meet abroad in the cold winter; but haling, pushing,
and abusing them in a fierce violent manner.

But it was not long before the Lord removed him out of the way by death;
and when he was on his dying bed he did somewhat relent;
and desired that son of his who was a Friend, and whom he had sorely abused at meetings,
to pray by him; and charged another of his sons whom he made his executor,
to restore Friends their goods again, in case he did not recover.
But that executor son being a chip of the old block,
refused to fulfill his father`'s command for restoring the goods,
but kept them from Friends; and within a short time after he also was cut off by death,
and the goods thereupon falling into the hands of other mercenary officers,
were most of them embezzled and lost.

Having given this brief account of the havoc they made of my goods at home;
I proceed to relate how they dealt with me at prison.

When the next quarter sessions after my commitment was come, which was held at Newbury,
on the 9th of the second month, 1684, I,
with some other Friends who were also prisoners was conveyed there,
and after my brethren had been called and put by till the afternoon, I was called;
and Thomas Medlicott being chairman, he said to me,
"`Will you take the oath of allegiance?`"
Whereupon the clerk read the oath; and then the chairman asked me again.
"`Will you take this oath?`"

I answered, "`I look upon myself not to be in that capacity,
nor under such circumstances,
as the statute describes them to be for whom this oath was provided;
for the title of the Act is,
An Act for the better Discovering and Repressing Popish Recusants;
and the preamble of it is to this purpose,
that whereas many Jesuits`' seminaries and popish priests,
the better to hide their treacherous designs, and to cover their false hearts,
do sometimes repair to church, etc., and as an instance of their treachery,
mentions the gunpowder plot;
now we being clear and free from all designs against the king and government so that
we could never yet be charged with plotting or contriving insurrections or the like;
therefore it seems improper as well as unequal to impose this oath upon us.`"

But notwithstanding this, the chairman still urged upon me, saying,
you must give your answer whether you will take it or not.

I replied, "`Truly it is a great strait that you drive me to; for first,
if I refuse this oath,
then I know the penalty--which is to lose all my estate and my liberty,
and to be as it were buried alive in prison;
which may be deemed as bad or worse than death itself.
And on the other hand, if to escape this penalty I should take this oath,
notwithstanding that I am persuaded in my heart and conscience,
and do firmly believe that the Lord has forbidden me to swear,
I should therein sin against God,
and thereby bring a wound and terror upon my own conscience;
and you know the Scripture says,
'`a wounded spirit who can bear!`' So that in this strait that you force me upon,
I must either run the hazard of losing my estate and liberty for refusing the oath;
or else fall under that intolerable burden of a wounded conscience by the taking of it.`"

Here I was interrupted by many of the justices who speaking all together said,
"`We cannot stand trifling with you in this manner; you must give your answer,
whether you will take the oath or not.`"

To bring them to a better temper and more patience, I said to them,
"`Pray be not so hasty, the matter is very weighty;
for my estate lies at stake and my liberty too, which is my all in this world,
except my life, therefore you should not seek to enforce a hasty answer.`"
But they were in haste to be gone to dinner;
wherefore the chairman seeing I delayed them, asked me,
if I would have a little time to consider further of it?
Whereupon I said,
"`You may if you please give me the same time that
you have given the rest of my friends here.`"
"`You shall have it,`" said the chairman, and presently bid the crier adjourn the court,
which he did, to the third hour in the afternoon.

After dinner there came but four of these justices to the bench, and three of the four,
namely, Anthony Craven, John Wight wick and John Smith, were very envious persecutors.

After the other Friends had been called and their refusal to take the oath entered,
I was called, and Craven, sitting in the place of chairman, said to me; "`Come Oliver,
have you considered of it?
What say you?
Will you take the oath?`"

"`Surely,`" said I, "`by right I ought to be excused from having it tendered to me,
because, as I told you today, it was made for Papists,
neither was there any just ground at all to tender it to me at the last sessions;
for it was through the false information of two wicked persons that I was brought there,
and the court then finding no matter against me, instead of discharging me,
which they ought to have done, tendered me the oath without any cause,
but that justice Parret said, it was not fit I should have my liberty;
giving for his reason, that I dispersed books and the like,
having sent two books and a letter to him.
It was no crime I hope, to send him a letter or books either,
for if he had aught to object against the books or the letter,
he might have produced them in court against me;
and have both showed what he accounted amiss in them,
and have convicted me of the breach of any law therein if he could.
But to tender me the oath for only sending him books and a letter,
and that too when you knew beforehand,
as one of the justices then on the bench observed to you, that I could not swear at all;
it seems to me to be offered for no other reason but merely to ensnare me.`"

"`Ay!`" said justice Smith in a scoffing manner, "`a mere snare and trap I warrant you!`"

Then said justice Craven to the crier, hold him the book: and said to me,
"`Will you take the oath or not?`"

The crier thereupon holding out the book, I took it in my hand, and Craven said,
"`it is a bible Oliver, come will you swear?`"
I answered, "`I say as I told you before, this oath was not provided for such as I am,
therefore it is unfair to tender it to me.
And besides, the statute says,
it should be tendered at the general quarter sessions before the whole bench of justices,
or the greater number of them; and now here are but four, which I know, you cannot say,
are the greater number, for here were ten today.`"

To that both Craven and Wightwick answered, "`Here are enough to make a sessions.`"

And then two or three of them speaking together said, "`You do refuse to take the oath;
take him away.`"

"`Pray, be not so hasty,`" said I; "`the matter is of more weight than you make of it;
and therefore you may give me leave and time to answer.
And take notice, I have not refused the oath as yet,
but I am brought here as an offender; and now, it seems,
you lack matter out of my mouth to charge me with.
Therefore this I say to you, if anyone has anything against me,
let him appear and accuse me to my face.`"

Then justice Wightwick cried out, "`Take the bible from him.`"
But I said, "`Stay a little, I have more to say, I have not yet done with it.
Here you give me a bible to swear upon; and the bible itself forbids me to swear at all:
now what greater affront can there be given to Christ Jesus the King of kings;
and what greater contempt of his laws and government,
whose command is '`Swear not at all,`' than for men
to take that very book wherein this command is written,
and both swear upon it themselves,
and force others against their consciences to swear upon it also!`"

"`We shall have somewhat to do by and by`" said justice Wightwick;
"`take him away`" cried he, "`take the bible from him,
he`'ll forfeit his twenty pounds if we let him alone.`"

The crier thereupon sought to get the book from me.
But I desired him to let it alone, I would have it a little longer I said,
for I had not yet done with it.
But he bawled out, "`You shall not keep my book;`" and with violence plucked it from me.

Then two or three of them speaking together said, "`If you will take the oath, say so:
but you do refuse it, therefore, jailer, take him away.`"

I answered, "`The Lord Jesus Christ commands me not to swear at all;
and the bible testifies the same; yet you command me to swear: now whom shall I obey?
God? or man?`"

Then with one voice they commanded the jailer to take me away; which he did.
And about six weeks after, the clerk of the peace sent an order to the jailer,
to keep me and three other Friends prisoners until the next sessions.

[.offset]
+++[+++In the interval he wrote to his wife as follows.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Reading Jail, 14th of Second month, 1684.

[.salutation]
Dear Wife,

After the tender salutation of my endeared love,
heartily desiring and praying for your welfare every way,
but most especially in the precious unchangeable Truth, which lives and abides forever;
these are to acquaint you that things are so fallen out,
I cannot come forth this week to go to Purton as I intended, but you may do well to go;
and remember my dear love to all Friends,
and let them know that it is not from lack of love,
that I do not come from Reading to Purton on foot to visit them; but being in bonds,
I cannot go as I would with my body, but as for my mind in the word and spirit of life,
it is not bound but free and present with them in the unity and bond of love and peace.
And I have hopes that next week I shall not fail,
but come to Charlow on second-day if the Lord enable me, and tell M. Shurmer,
I shall be glad to see her there, and bring her accounts with her,
that we may reckon and set things right between us, and you may bring my books also.

My dear love is to your sister J. V. when you see her, and to all their family,
and to all Friends at Farringdon, as if named one by one.

Several of the wicked justices seek occasion against our jailor,
because of his kindness to us, and would put him out of his place, if they could;
I may tell you more when I see you.

The magistrates of Reading disturbed the meeting in the town last first-day,
and twelve men Friends were committed prisoners to the compter, until near night,
then had before the mayor and fined five shillings a man, and so dismissed.
So having not much more to write at present,
but with that love which distance of place cannot separate, nor time wear out,

[.signed-section-closing]
I remain your dear husband,

[.signed-section-signature]
O+++.+++ S.

[.signed-section-context-close]
Reading Jail, 13th of Fourth month, 1684.

--

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

My true and entire love does sincerely reach forth unto you in
tender breathings to the Lord for your welfare and preservation,
and for all tender-hearted Friends thereaway.
Oh, the exercise of my spirit and travail of my soul for you all lately have been more,
than at present I think expedient to express, but shall leave it to the Lord my God,
who sees and knows all things,
and from His righteous hand shall every one receive according to their works,
and his holy name and truth shall be exalted over all more and more,
and they that sincerely seek to do it,
shall be preserved through all trials in safety unto the end.
So dear heart, trust singly in the Lord,
and he will make our way easy that he has set before us,
and cause our path to become pleasant and delightsome more and more,
that we may run on in our race cheerfully without weariness or fainting,
even unto the end, and to finish and conclude with joy to our immortal souls,
and with endless praises, thanksgiving and glory,
and hallelujahs in the highest over all, forevermore, Amen.

Dear heart, by this you may know that I intend, if the Lord will,
to be at Bothamstead next second-day, and tarry there about two or three days,
and if you are pretty well, I desire you to meet me there.
And I desire you to mind my dear love to E. L., G. A., M. R., T. R.,
and all the rest of Friends as if named, and to all your maids,
who I desire may live in the fear of God,
and grow up together in the truth as plants of righteousness to the glory of the Lord,
that they may be blessed and happy both here and hereafter.
So hoping to see you at Bothamstead, I shall cease to write further at present,
but conclude with my very dear love to your sister, and to all Friends at Charlow,
and at Charney, and elsewhere, and once more to yourself.

[.signed-section-closing]
I remain your dear husband,

[.signed-section-signature]
O+++.+++ S.

--

About this time our Friends at Farringdon, and the parts thereabout,
were under great sufferings, by means of the wicked informers and persecuting justices;
and I being confined in prison could not be with them to comfort
and encourage them in those their great and heavy exercises.
Yet having a true sympathizing sense and fellow-feeling of their suffering condition,
it came upon me to write to them in tenderness of love,
to exhort them to hold fast their confidence in the Lord`'s power;
and not to look out at what had happened or might yet further come upon them,
for the trial of their faith and patience.
What I wrote was directed to the Friends of the monthly
meeting of the Vale of White Horse;
and was as follows.

[.embedded-content-document.epistle]
--

[.salutation]
Dear Friends,

Unto whom is given in mercy from the Lord,
not only to believe in and profess his name in the world,
but to possess power from him to enable you to suffer on his behalf.
O Friends, prize his tender love,
and prize your present reproaches and sufferings for his sake,
to be as precious to you now as they were to Moses in his day, of whom it is said,
that he esteemed the reproaches of Christ greater riches than the treasures of Egypt;
for he had an eye to the recompense of reward.

And Friends,
I beseech you to be diligent and watchful to keep
your minds constantly exercised in that power,
which you have received in your hearts from the Lord;
which is given unto you for our safety and preservation,
and wherein alone all your strength lies,
to bear you up and carry you through all your trials.

And I tenderly entreat you all,
to wait for the renewings of that same living power
of Christ Jesus in your own bosoms day by day;
and dwell low in it in patience;
and you shall surely feel and witness the mighty operation of it,
even to renew and change you into his own nature.
And then you will rejoice that you are accounted worthy to suffer for His sake,
and will be glad when you are persecuted,
and all manner of evil is spoken falsely by wicked men against you for His name sake;
knowing that great is your reward in heaven.

And it is in my heart to advise and warn you,
that you enter not into reasoning and disputing with your adversaries,
who have sold themselves to work wickedness,
and are willfully given up and hardened in their sin against God, in persecuting you.
For by reasoning or disputing with them,
you will be far from convincing them or prevailing with them, but may hurt yourselves,
if you are not very wary, by letting a wrathful spirit arise in you.
And when with that you have strove with your adversaries, and find it to be in vain,
then in the same wrath, you will be ready, if you are not watchful,
to run against your friends and brethren, and to smite at them;
when the very cause has been in yourselves in not abiding low in your own measures,
whereby you would have been enabled to bear all reproaches with patience,
and to give a testimony against the spirit of persecution,
denouncing the righteous judgments of God against all that are found in it.
So avoid reasoning with them, as knowing this,
that the triumphing of the wicked is but short;
and the rejoicing of the ungodly but for a moment.

And dear Friends, I have something in my heart to write unto you concerning the appeals,
wherein a great disappointment seems to have befallen;
and that way whereby we hoped to have had redress,
and to have stopped the rage of the wicked, has proved quite the contrary,
even to the increasing our sufferings and encouraging our adversaries.
I say, although it be thus, yet let us not be offended at it,
nor find fault one with another about it;
seeing we were all agreed at first in that thing,
and we would willingly have obtained redress and have received deliverance in that way,
if the Lord had so ordered it; as well as many of our Friends in other places did.
But what if our God saw it fitting to disappoint our expectations,
and for the greater trial of us to cross our desires;
for it may be he saw that some would not have given the glory to Him, but to man,
if the Lord had wrought our deliverance that way.
And so he, in His infinite wisdom,
right well knowing what would fend most to his own glory and our greatest good,
has disposed all things accordingly.
And shall we not in patience submit to what he brings upon us, and receive it as the best?
For hereby he has given us to see the great wickedness
and injustice that lodged in the hearts of men,
and is now hereby drawn forth into practice.
For we could not have believed that so many men in authority,
would have allowed such horrible injustice to have been done, if we had not proved it;
there being so much right on our side and such clearness in our case.
But truly I am persuaded and do believe in my heart, that in tender love to us,
our God has brought things thus to pass as it is this day;
that we may be brought into the more single dependence upon Him.
And there is no question, but he will make way for our deliverance in due time;
even when the set time is come which he has appointed for the fulfilling of our sufferings.

Therefore I say, my dear Friends, let us trust perfectly in the Lord our God,
and steadfastly depend upon him,
and we shall all at length obtain our desired and expected end.

And finally, my Friends, in that love with which our God has loved us,
let us all live and dwell, that therein we may edify and strengthen one another:
praying fervently one for another,
that in true tenderness we may always be as epistles written in one another`'s hearts;
always breathing for and desiring the preservation one of another.
For we have great cause to love one another, and to watch that we may resist the enemy,
who labours daily to beget prejudices and hard thoughts one against another.
So in that love which edifies the body, and which thinks no evil,
but bears and endures all things, I take my leave and bid you all farewell.

I desire this may be distinctly read in the men`'s meeting
in the Vale of White horse or elsewhere thereaway,
as any Friend finds freedom and a service is seen.^
footnote:[This epistle was written on one large sheet,
and the original in O. S`'s writing is carefully preserved.]

[.signed-section-closing]
Your dear brother in bonds,

[.signed-section-signature]
Oliver Sansom.

[.signed-section-context-close]
Reading Goal, the 19th of the Fourth month, 1684.

--

I mentioned before, that I and three other Friends with me,
were by an order of the last sessions continued prisoners till the next.
The reason why there were but four then named, seeing we were five in all, was,
that Samuel Burgis, who was the fifth,
not being well enough in health to be brought to the last
sessions was not called or taken notice of there.
But vigilant justice Craven was so careful to secure all that he had in hold,
that when the sessions at Newbury was ended,
he commanded the jailer to bring Samuel Burgis before him,
and some other justices at Speenhamland,
where they tendered him the oath to continue his confinement to the next sessions.
Which being appointed to be held at Abingdon,
the jailer received an order from Justice Craven to bring us there at his peril.

There accordingly we were all five carried, that is, Samuel Burgis, George White,
Edward Swain, John Sansom and myself; but when we came there, we were not called;
for they adjourned the sessions to Wantage, to be held on the 29th of the fifth month,
1684.
Where we were taken.

When we came there and were called, Tho.
Medlicott, being chairman, asked for the court order; which the jailer giving him,
he said to us,
you are here committed for the second time refusing the oath of allegiance.

Before he could go further, he was interrupted by the clerk of the peace,
who having looked over the records of the last sessions, said softly to him,
they had it tendered but once.
Whereupon beginning again, he said,
"`It seems the oath of allegiance has been tendered to you by two justices of the peace,
and you have refused it.
Now if you shall refuse it again, you will be convicted of a premunire,
which is to forfeit all your goods and chattels, and to be kept in prison during life:
it being the greatest penalty, next to felony, the law provides.
I speak this to show you the danger,
that you may not run yourselves unadvisedly into it.`"
Then our names being called over, the clerk spoke softly to him again, and told him,
Oliver Sansom had the oath tendered twice to him already.
Upon which the chairman directing his speech to me said, "`Mr. Sansom,
although you have had the oath tendered twice already, and you have refused it, yet,
if you will now take it you shall be acquitted.
You shall hear it read;`" and when the clerk had read it,
the chairman said to John Sansom, "`Mr. Sansom, will you take this oath?`"
and earnestly pressed for his positive answer.
And when John Sansom had signified his conscientious refusal to swear at all,
because forbidden by Christ, the chairman turning to me said, "`Mr. Sansom,
you have now heard the oath read, will you take it or not?`"

I stood silent for a while; which justice Hyde observing, said in a kind of flouting way,
"`I`'ll warrant you, he will have something to say by and by.`"
After some little pause I said, "`I look upon it as unfair to tender this oath unto us,
because it was not intended for such as we are, who cannot swear in any case;
and I am persuaded,
that justice Medlicott does know that this statute was made against papists, or however,
that this oath is to be tendered to none but them that in other cases will swear,
and was never intended for us who cannot swear at all.
For it is a very improper,
and altogether unsuitable way to try or prove our allegiance to the king by swearing,
when it is well known we dare not swear at all in any case,
though it be never so much to our advantage.`"

The chairman here interposing said, "`What my judgment is in that case,
you must pardon me in that.`' But I suppose,
you stick at that scripture where it is said '`swear not at all.`'
But here you greatly mistake in taking it in a literal sense;
you must interpret one scripture by another, to understand the meaning of it.
What say you to that, '`an oath for confirmation shall be an end of strife?`'`"

More he said in his way, to prove the lawfulness of swearing, but desired a short answer;
for, said he, "`we have much business and but little time; we cannot stand long with you.
We think it our duty to swear; and we are upon our oaths to execute the king`'s laws;
and this oath being lawfully tendered, you must give your answer,
whether you will take it or not.`"

"`Then`" said I,
"`it is very apparent that the king and parliament did not
look upon us as liable to have this oath tendered to us,
and to undergo the penally provided for the refusal of it,
merely for our conscientious refusing to swear at all;
because there is an act since made, in the 13th and 14th of this king`'s reign,
purposely against us;
wherein are penalties provided for such as refuse to swear in any case.
And if the imposing the oath of allegiance had, in the judgment of the lawmakers,
being applicable to us,
then would the introducing of this latter statute have been altogether superfluous.
I do not mention this latter statute as desiring its execution:
but would rather it were repealed.`"

Upon that, justice Hyde, in a reflecting manner, said, "`What is against you,
you would have repealed?`"
The chairman said, "`affirmative laws remain still in force;
although some are made since of the same tendency, yet they do not abrogate the former,
as in the case of conventicles.`"

I said, "`We are a peaceable people,
and never refused allegiance to the king or government.
So that you have no more cause or reason to go about to make us to swear allegiance,
than to compel us to swear to eat our food when we are hungry;
for we cannot practice contrary to allegiance.
Nay, further, if all of you should join together,
and do the utmost you can to make us practice contrary, you cannot possibly do it.`"

Here I was interrupted by justice Hyde, who said, "`Oh! you talk strangely.
Don`'t you keep up your meetings against the king`'s laws?`"
Before I could answer him, which I might easily have done,
by showing wherein our allegiance to the king was due, namely,
not in spiritual or religious things, but in civil or temporal matters;
and that therefore, our keeping up our meetings for the worship of God,
though forbidden by law, is no breach of our allegiance to the king,
any more than the primitive Christians,
and the early protestants and martyrs keeping up the irreligious meetings,
contrary to law, was a breach of their allegiance to their respective princes; I say,
before I could answer, the chairman interposing said, "`Come, pray let us know,
whether you will take the oath of allegiance or not; for we have a great deal to do.`"

I answered, "`I do not deny or refuse allegiance,
but shall perform it as faithfully as any of you all.`"

"`You make comparisons`" said the chairman;
"`but will you take up arms to aid and assist the king if need should require?
We will venture our lives for the king.`"

"`If we do not fight,`" replied I, "`we may do the king as much good as those that do.`"

When I had said this they put me by and called George White; and after him Edward Swain;
and having asked them severally, if they would take the oath and entered their refusal,
they then called Samuel Burgis.
And the question being put to him, whether he would take the oath or not,
he desired liberty to speak; which being granted,
he with an audible voice declared in what manner he had been dealt with.
As that at first, he with others were sent for from their own houses,
to appear before three justices of the peace,
who tendered them the oath of allegiance and sent them all to prison.
Then going on, he showed how he and the rest of us had all along been used.
And that we were always peaceable, and no manner of evil could be laid to our charge;
for which he gave thanks to God.
And having in this wise pretty fully and very notably spoken, he ceased.

Then said justice Parrett to the rest, "`Ask him when he received the sacrament,
whether or no he has received it within this twelve-months.`"

To which a Friend answered, "`We have been in prison above these twelve months.`"
So after some more discourse to the same purpose they recorded all our refusals,
being in haste as they said to go upon other business;
and the chairman said to the jailer, "`I think you must take them home with you again.`"

Thus we, the before-named five prisoners being remanded back to prison,
were by the jailer kept there until the next sessions,
held at Newbury in the eighth month, 1684,
where we were then had and kept in an inn until the session was ended.
For neither did the justices call for us, nor did the jailer bring us forth,
but kept us out of their sight; so that it is likely, we being out of sight,
were also out of mind.

Then were we had back and continued prisoners, not only without bail or mainprize,
but even without warrant or court order, until the next sessions.
For the jailer told us, that although he had no warrant to keep us,
yet he dare not let us go; "`for,`" said he, "`they will hang me if it be in their power,
if I let you go.`"
But the jailer, to give him his due, did show us what kindness he could.

The next sessions being at Reading,
we were all five called to the bar on the 14th of the eleventh month, 1684,
and an indictment was then read against us,
for obstinately refusing the oath of allegiance, having been twice tendered to us.
Whereupon we were severally required to plead to it guilty or not guilty;
and Sergeant Holt being chairman, began with John Sansom, saying, "`John Sansom,
are you guilty or not guilty?`"

"`I desire,`" said John Sansom, "`to know what will follow if I do not plead.`"

"`I`'ll tell you,`" said the chairman, "`what will follow.
You will be convicted of a premunire; the penalty whereof is,
to endure imprisonment during life, and forfeit all your goods and chattels.`"

"`Then`" said John Sansom, "`I am not guilty, as is there expressed.`"

"`Then set down,`" said the chairman to the clerk,
"`that he pleads not guilty as to manner and form.`"

In like manner, Edward Swain, George White and Samuel Burgis, were called severally,
one after another, and their answers were all one,
in denying the manner and form of the indictment, and so they were set down.

Then the chairman said to me, "`Oliver Sansom,
are you guilty of this indictment or not guilty?`"

I said, "`I desire to be answered one question.`"

"`What is that,`" said the chairman?

"`Is this,`" said I,
"`the same indictment we shall have when we come to trial next sessions,
or will it be altered?
or will you have another?`"

He answered, "`This is the same indictment you shall have next sessions at your trial.`"

"`I ask,`" said I, "`because I did hear it expressed in the beginning of it,
that we were charged with refusing the oath of allegiance, being twice tendered;
but I do not remember that I heard mentioned the place where,
or the time when the first tender was made.`"

Upon that word, Thomas Staples, one of the justices on the bench,
speaking softly to the rest, said,
"`they will get off from this indictment next sessions.`"

That made the old chairman angry; and thereupon he said,
"`We will not read it any more now; it was more than we needed to have read it before.
But you shall know the time and place,`" said he to me, "`when you come to trial.
But will you plead guilty or not guilty?`"

I answered, "`I did not obstinately refuse the oath of allegiance;
but did conscientiously refuse to swear at all.`"

Then was I as the rest, set down as pleading not guilty;
and were all remanded back to prison again.
But within about an hour, after we were come from the court,
we were sent for to the George Inn, in Reading, where the justices dined.
And after dinner, three of the worst of them, namely, Anthony Craven,
Thomas Fettiplace and John Smith, ordered the jailer to bring us before them,
and began to tender us the oath afresh; and Thomas Fettiplace, being a forward man,
began to read the oath to us.

But I, perceiving they were preparing a new snare for us, made bold to interrupt him,
and desired to know their intent, and what they did mean in tendering us the oath now.

At that he was angry, and refused to give any reason for their so doing, saying to me,
"`I will not be examined by you.`"
So he went on and read it through, and then they asked us severally,
whether we would take it; and our answers were all one in effect,
that inasmuch as we were all required, in open court this day,
to plead to an indictment for refusing the oath of allegiance;
we therefore desired to know whether we were clear from that indictment,
before we give answer to this question.

They would not speak to clear us from that indictment, but still urged upon us,
will you take the oath now read?
and we still severally replied to this effect,
that we do not look upon ourselves obliged to answer to,
or take any notice of this new tender, until we are cleared from the former indictment.
Whereupon they appeared very fierce and angry,
and caused a court order to be presently made for sending us to jail again;
of which the copy here follows:

[.embedded-content-document.legal]
--

[.salutation]
Berks.

We send you herewith the bodies of Samuel Burgis, John Sansom, Oliver Sansom,
George White and Edward Swain, for refusing to take the oath of allegiance,
being the first time tendered to them, upon this 14th day of January instant;
there to remain, without bail or mainprize, until the next session of the peace,
to be held for this county.
Dated under our hands and seals, the 14th day of January, Anno.
Dom. 1684 R. R. Car. Secund. xxxvi.

[.signed-section-signature]
Anthony Craven.

[.signed-section-signature]
Tho. Fettiplace.

[.signed-section-signature]
John Smith.

[.signed-section-context-close]
To the keeper of his Majesty`'s jail in Reading, for the said county.

--

Between this time of our new commitment and the next sessions,
I had occasion to expostulate our case with one of
those three justices that committed us;
namely, Thomas Fettiplace, of whom, and his dealings with us I think fit,
before I proceed further, to give the reader some short account.

He having been in commission for the peace formerly, and put out,
by the procurement of Hardwick the informer, when afterwards he got in again,
became a cruel persecutor; and being a man of an eager, busy, restless spirit,
he would take great pains to bring to pass his envious designs against dissenters.

He somewhat appeared at the sessions at Wantage, showing his teeth in what he could,
and thereby discovering what lodged in his heart against us,
but what he said there was but little heeded by any;
he being inferior to all or most of the rest.

Shortly after that, I sent him a book, entitled,
'`A Treatise on Oaths and Swearing,`' for his better information,
hoping he might come to be of a better mind by the next sessions; but he,
on the contrary, appeared much worse than ever before; which I observing,
a concern came upon me to write to him as follows:--

[.embedded-content-document.letter]
--

[.salutation]
Thomas Fettiplace,

In a serious consideration of your late severe and
rigorous deportment at the sessions at Reading,
towards us, who have been long detained prisoners contrary both to law and justice,
it came in my heart thus to query concerning you.
What does this man mean, that he takes upon him to prosecute this cruelty against us?
Would he outdo those that dealt with us before?
Did you, thought I, but understand what you were about to do, surely then,
you would desist and forbear to proceed any further,
and not endeavour to drive and force us, whom you can not charge with evil doing,
under the penalty of a premunire.
Oh I thought I, will you go on directly in the way of Cain, in envy against us;
that for lack of power to kill you would bury us alive in prison,
and become as an executor to our estates for the king.
Surely this, considering our innocency, is an extremely hard measure,
and very great cruelty.
Then I pondered in my mind what you could propose,
of advantage to yourself by this undertaking;
that you should thus strain yourself beyond your usual natural temper,
in appearing so fierce against us;
and I did question whether it was not to please Anthony Craven and some others;
that so by setting your foot to tread upon us,
you might lift up yourself and endeavour to raise your reputation,
which lately seemed at an ebb,
to that degree of greatness and worldly glory which ambitious minds aspire after.
Now whether this be your state, and that it is so really with you,
I shall leave to God`'s witness in your own conscience to declare.
But this I am certain of, your end in this business cannot be good.
And as sure as ever you have set your heart, and lifted up your hand against us,
so surely will the just God in whom we trust, plead our cause, and visit you for it,
even with his righteous judgments, except you repent.

It is foretold, and stands upon record in the Holy Scriptures, John xvi.
ii.,
that the true believers in Christ should be haled
before magistrates and rulers for keeping his commands,
and some should be put to death; and their persecutors would be so greatly blinded,
by the envy of the devil, that they would think they did God service in so doing.
Again, it is also written and signified by the Spirit of God,
that for trial of the members of Christ`'s church,
the devil should cast some of them into prison, Rev. 2:10.

Now this I have to say to you,
that these Scriptures are fulfilling as really now in our day and age,
as in any time before us.
And in tender love, I advise and warn you to cease from persecuting of us,
as you do desire your own welfare.
For it is certain and true that they are actually in the devil`'s work,
who are persecuting and imprisoning people for obeying
Christ`'s commands and worshipping God as he requires.

Therefore look to it;
for it is but a little time and the separation will
be made to the right hand or to the left;
and the righteous Judge will account what is done
against his people as done against himself.
And when that dreadful sentence.
Go you cursed, shall be pronounced, the pretence of laws or human authority,
can neither reverse it nor excuse from it.

Therefore I entreat you to consider, and be advised in time,
and as you are sharp and dexterous in worldly matters,
let your abilities be employed to break the bonds of wickedness,
and let the oppressed go free; and be merciful that you may be blessed,
and may obtain mercy; for it is said,
'`he shall have judgment without mercy that does
not show mercy.`' So in being kind and merciful,
the greatest gain will be to yourself,
for no man can have so much need of mercy from you as you have of mercy from God.

In true love is this written, by him who desires your welfare both in soul and body,

[.signed-section-signature]
Oliver Sansom.

[.signed-section-context-close]
Reading Jail, the 13th of Twelfth month, 1684.

[.postscript]
====

P+++.+++ S. I desire you to return that book which I sent you in love to peruse,
for your information concerning oaths and swearing;
which I did hope might have satisfied and have convinced you,
that for sufficient reasons and approved grounds, we have refused to swear at all.
But seeing you were pleased to say at the George Inn, at Reading,
that it was a seditious book, I desire you to manifest in writing,
your ground and reason as proof for your so saying,
and send it with the said book unto my wife in Farringdon.

====

[.signed-section-signature]
O+++.+++ S.

--

The foregoing letter not working the desired effect upon him,
but I still hearing by several hands, of the continued cruelty, violence and spoil,
that was made upon our Friends, by and through the occasion of this Thomas Fettiplace,
I was moved to write a second letter to him,
to lay the weight of Friends sufferings upon him.

[.offset]
And after this manner I wrote to him.

[.embedded-content-document.letter]
--

[.salutation]
Thomas Fettiplace,

Forasmuch as I had lately a sight of an account of your actions
and proceedings against our Friends in and about Farringdon,
which was drawn up to be registered to after ages,
I am indeed truly sorry for you that you should do so badly as it appears you have done;
for your acts of cruelty being recorded, your name among persecutors will be enrolled,
and will be of an evil savour unto succeeding generations.
Wherefore I once more desire and entreat you to read in moderation,
and consider seriously these following lines:
that if you will be advised to desist from cruelty,
and exercise yourself in justice and mercy, we shall take notice of your change,
and more willingly record your clemency than your cruelty.

Now I place this persecution upon you, because you, as I am certified,
are the most busy in this bad business.
For although your brother Hide, and sometimes one justice more,
may be present at your petty sessions, yet it is you that take upon you to be speaker,
and the rest being passive, you earnest on matters according to your own will;
so that we can do no other than give every one his due,
and lay the propagating and managing of these bad proceedings at your door.

The two main matters objected as crimes against our Friends, and for which they suffer,
are these.
First, their conscientious absenting from that worship,
which they believe is not the true worship of God.
And secondly,
their practising that which they believe to be true worship in obedience to God.
And seeing that faith is the gift of God,
who is both the author and finisher of it in the hearts of his people--and it is written,
whatsoever is not of faith is sin--how dare you endeavour to compel people
to sin against God by acting contrary to their faith as aforesaid?

And besides,
your practice in compelling by corporal and pecuniary
punishments about religion and worship,
is utterly contrary to the gospel of Christ and true Christianity;
as by the testimony of the Holy Scriptures and other ecclesiastical histories,
it evidently appears.
For it is clearly manifest,
that Christ himself and his faithful followers were hated and persecuted,
but never did persecute any for not conforming to them in the practice of the true religion.
So that it is clearly evident, that the church or people that persecutes about religion,
is not of Christ, but of antichrist.
For consider, if Christ and his apostles had done like you,
to have gone with a company of magistrates, having warrants and court orders ready,
to fine and imprison all that would not receive the gospel,
what a pitiful parcel of proselytes do you think would then have been gathered?
Nay, verily, it is far below the nobility of a true Christian spirit,
to meddle with such tools as these,
or to wrestle with flesh and blood to make members of the true church.
We read, that Christ himself did whip some out of the temple,
but never that he went to whip any in.

Truly I have been concerned for you,
because of your going on in persecution against God and his people;
knowing that a bitter cup you must come to drink from the Lord`'s hand for the same,
unless you repent; and I have often considered, in pity to you,
poor man! that it would have been far better for you, if,
when your commission was taken away, you had never obtained it again,
to do as you have done.

Also it is apparent to me, that you have acted quite beside your proper business,
as you stand authorized both by God and man.
For first the Lord requires that you should not bear the sword in vain;
but should be a terror to evil-doers, and a praise to them that do well.
Consider now, whether you have ruled for God in punishing and terrifying evildoers,
as drunkards, swearers, and profane persons,
that they might not go on in their evildoing,
to the dishonour of God and the grief of sober people; or have not such been rather,
by connivance at least, encouraged, and the godly sober people discouraged and punished.
Secondly, your commission from man is to keep the outward peace;
consider whether you do not cause the peace to be frequently broken,
by forcing one neighbour to rifle and distrain the goods of another,
and sometimes haling to prison those whom you can
in no way charge with doing any man wrong,
but must acknowledge they have lived peaceably in godliness and honesty;
yet are made to suffer by you only because, for conscience sake,
they cannot go along with the hypocrites,
drunkards and swearers to say after the hirelings,
that they have left undone that which they ought to have done,
and have done that which they ought not to have done;
and that there is no health in them: whereas the Lord, in mercy has given them,
who are thus made to suffer, to know that he is their saving health,
the physician of their souls, and hope of eternal glory revealed in them.
For which let endless praises, thanksgiving and glory be given to the Lord our God,
and to his Christ the heavenly Immanuel, over all forevermore.
Amen.

And now in tender love to your poor immortal soul,
I advise and warn you to cease from disturbing and troubling your honest peaceable neighbours.
For why should it be said that it is now become a crime,
and brings us more in danger of punishment, now that you are in authority,
to worship`' God aright, as He by His spirit gives to believe; and to live a godly life,
than to be drunkards, swearers or debauched profane persons?
Has not sad experience given too clear an evidence of these things in this our age?
which to them that have power in their hands to redress it,
and do not endeavour to do it, is a reproach,
and a shame to their profession of Christianity.

But be you assured of this, that the Lord who searches the heart,
has your life and breath in his hand, and will not be mocked by you;
but will give you to reap according as you sow,
and render you a just reward according to your works;
and in his fear is this written for your everlasting good,
By him who has learned to love and pray for enemies and persecutors, called

[.signed-section-signature]
Oliver Sansom.

[.signed-section-context-close]
Written in Reading Jail, where I suffer for believing and obeying him,
who said "`swear not at all,`" 6th of Second month, 1685.

[.postscript]
====

P+++.+++ S.--Truly as the state of things now stands, your doings seem very strange.
What if he that now sits at the helm,
should permit or encourage you and others of your mind, on purpose to try you,
and to see what you would do,
to prosecute other protestants that dissent from you even unto blood?
Which if the Lord should allow,
you seem too likely to be an instrument for the carrying on such a tragedy,
in whose heart the old enemy who was a murderer from the beginning has ruled and does.
And when you have done the worst you can against us,
may not the Lord then in his justice, cause you to drink of the same cup,
and to receive the same measure from others that you have meted to us?

I hear you are very liberal to your clerk, in giving him what you have no right unto,
for writing your warrants, viz: Twelve-pence a warrant, and if I mistake not,
sometimes more; to be paid out of the spoil of the poor Quakers`' goods,
for all the warrants and court orders that your cruel hand has signed against them,
besides the penalties imposed.
May we not well question whether you allow him any other wages than this,
which is thus oppressively extorted, because of the multitude of your warrants.
Let it be plainly understood by what law you thus proceed;
for these doings of yours give a general dissatisfaction.
One formerly said, there was nothing worse than legal tyranny.
Take heed that you are not found in it.

And furthermore consider, do you not think that other justices,
who are more moderate and tender to their neighbours,
are as good subjects to the king as yourself,
and keep as clear a conscience in discharging their duty, expressed in their commission,
as you do?
who yet never had a hand in persecution, and do scorn to make a spoil upon sober people,
as you have done.
And as their tenderness will be for their honour here and peace hereafter;
so your rigour will be both to your shame here and torment hereafter,
without timely repentance.

But although I do write thus sharply,
yet I can truly say it is not in wrath or enmity against you;
but in a fervent zeal for God against unrighteousness, and in love and good will to you;
that you might not go on in that way which will end in misery.
And as a testimony of my love I have an intent, and some hopes,
to visit you at your house before many months more be expired,
if the Lord enable and make way for me;
and then I think to speak with you about my book which I lent you,
and you have neglected to return.
I am,

====

[.signed-section-closing]
A lover of truth and just government,

[.signed-section-signature]
O+++.+++ S.

--

[.offset]
Underneath I wrote these Scriptures.

[.embedded-content-document.letter]
--

[.offset]
"`He that rules over men must be just, ruling in the fear of God.`" 2 Samuel 23:3.

[.offset]
"`Whatsoever you desire that men should do unto you,
do even so to them; for this is the law and the prophets.`" Matt. 7:12;

[.offset]
Says the only judge and lawgiver who is to be heard in all things;
and He and His sayings ought to have the preeminence above all men and their laws.

--
