== Chapter X.

Religious liberty extended--The poll-tax;
Oliver Sansom`'s goods seized for not paying the tax as a priest--Removes to Abingdon--Goods
twice seized for the poll-tax--Goods distrained for "`Easter offerings`"--Again for
tithes--His address to the mayor and justice--Another to
the priest--Further persecution--Conclusion.

After my return home,
I laboured in the strength of the grace which the Lord had given me,
in his work and service,
visiting the meetings of Friends in our own county and other adjacent counties,
and sometimes at London and Bristol, and other remote places;
of which to give a particular narrative here would be too tedious.

It was now a time of settled liberty and toleration from the government,
brought about by the providence of our God,
that the weak and feeble ones might be strengthened and built up;
and such as had been scattered in the late stormy times
of persecution might be gathered again into the fold.

But though general sufferings were for the present removed,
yet particular suffering still remained, as for tithes and other ecclesiastical demands,
which lay heavy where they fell.
Besides which, occasional sufferings sometimes fell on some,
of which some part fell to my share on the following occasion.

In the year 1690, there came forth a poll-tax, by act of Parliament;
in which all priests and ministers, so called,
having a benefice of fifty pounds per year, were taxed to pay twenty shillings.
And all preachers or teachers belonging to any dissenting
meetings were ranked with them to be taxed.
And hereupon I, though very unjustly,
was numbered among the hirelings that had fifty pounds per annum for preaching,
and as they, so I was taxed twenty shillings,
although I never received a penny for preaching in my life.
And because I refused to pay the said tax, and thereby to own myself a hireling,
which I never was, my goods were distrained by Philip Farmer,
one of the collectors of the said tax, who, with James Mills, tithingman,
came to my house on the 14th day of the sixth month, 1690,
and carried away one end of dyed cotton fustian, being twenty yards; which,
at the lowest price, was worth twenty shillings.

Some little time after this, it pleased the Lord,
in whose hand are the hearts of all men, to bring a close exercise upon me,
for the removing of my outward habitation from Farringdon to Abingdon.
I had had some little touches on my mind about it at certain seasons,
for some years before.
But now in the tenth month of the year, 1690,
the concern came upon me with greater weight,
and was backed with these considerations,--that three of the men Friends of Abingdon,
had lately been removed by death; that the meeting there was very small,
and hardly likely to be continued, without some additional assistance.
Whereupon a travail of spirit came upon me, and a secret cry was often in me,
"`O that the Lord would be pleased to make me an instrument in his hand,
to reach to some of the professors in that place!`"
For there were abundance of professors, Baptists and others,
and many of them I was sensible, had tender breathings after the Lord,
but were greatly clouded under their forms,
and too many of them prejudiced against the Truth,
through the false insinuations of their preachers and teachers.

After I had thus been exercised for a while,
at length in a yearning of bowels for the good of souls,
and for the interest and advancement of Truth, I did with the unity of faithful Friends,
before whom I had timely laid the matter, remove from Farringdon in true self-denial,
and to my outward detriment for Truth sake, as I had done before in coming to Farringdon,
and began to settle in Abingdon in the seventh month, 1691.

But I was scarce fully settled there, before another poll-tax came forth,
granted by act of Parliament; by which, among other matters, it was enacted,
that all ministers, so called, having a benefice of sixty pounds per year or upwards,
and all preachers and teachers in any congregation whatsoever, should be taxed,
and made to pay twenty shillings quarterly for one year.
Upon this I was taxed by the assessors and set down
in their rate to pay twenty shillings quarterly.
But when the collectors came and demanded it, I refused to pay it,
for conscience sake towards God; because I had never received a penny for preaching,
and therefore I could not be clear to agree to pay anything for it.
For as what I preached, I received Ireely from the Lord,
so I freely communicated the same unto others.
Wherefore I could not consent to be numbered with the hirelings,
or ranked among them who took sixty pounds per year, or upwards for preaching.

There were then several Baptist preachers in Abingdon, who were also taxed for preaching;
and some of them spoke big, pretending they would not pay it, whatever they suffered,
but at length to escape suffering they did comply.

But for my refusing to pay the said tax, the officers, namely, Robert West, John Bowles,
Thomas May, William King, Harim Pledell and Nathaniel Hart,
the six collectors of the poll-tax, with two constables, two tithingmen, and the bellman,
came to my house on the 14th day of the third month, and distrained and carried away,
as follows, viz: Seventeen yards and a quarter of cotton-fustian,
worth seventeen shillings and threepence; ten dozen of best laces two yards long,
worth eight shillings and fourpence; five dozen and three laces more,
worth three shillings and ten-pence; total, one pound nine shillings and fivepence.

When the officers had sold these goods, they came and brought one shilling,
and throwing it into the house went away.

The commissioners that signed the warrant for this distress, were Robt.
Sellvood, John Payn, Robt.
Blackaller, James Corderoy.

When the time came for the second quarterly payment, two of the before-named collectors,
Robert West and John Bowles, with Robert Pumpliry, constable,
came to my house and distrained, and carried away a new furnace,
which cost one pound two shillings; a new quarto Bible, worth ten shillings; total,
one pound twelve.

A while after, these three officers came again, hectoring and raging,
and there being nobody at home but my maid-servant only,
they searched my house from room to room,
and at last took off from one of the beds a pair of blankets and a coverlet or rug,
well worth together one pound two shillings;
and with them they took also six yards of fustian, six shillings and ninepence; total,
one pound eight shillings and ninepence: but they brought the furnace again;
so that what they took for this quarter was one pound eighteen shillings and ninepence,
without returning anything.
And thus I was welcomed to Abingdon.

But to do the commissioners right, they afterwards took my case into consideration,
and excused me from the other two quarterly payments.

In the twelfth month of this year, 1692, we lost a very honest Friend,
and serviceable man among Friends in our county, William Austell of Oare.
He was an honest, faithful man to the last,
and died a prisoner for his testimony to the Truth.

I continued in the work of the Lord in my measure,
sincerely seeking the advancement of Truth, and the welfare of Friends therein;
and from the time of the last poll-tax, in 1692,
no outward suffering came upon me until the year 1696.

Then one James Canaries, called a doctor of Divinity, and the chief priest of Abingdon,
sent Ambrose Seeney his clerk, on the first-day of the sixth month,
to demand of meten-pence per year, for five years, for Easter offerings;
and I not answering his demand,
the said priest complained of me to John Payn the then mayor, and James Curtain,
that year justice of the peace.
They sent a warrant to summon me to appear before them,
which I did on the 26th of the seventh month, 1696,
and called for the priest to prove his charge.
He was not there, but they showed me the paper of his complaint,
and said that was his proof.
I told them that was only his say-so, which I denied,
and it ought to be plainly proved before them to my face,
else they should take no notice of it.

I heard very little more of this matter, until near a year after.
About which time the priest prevailed with the then mayor,
whose name was Robert Blackaller, and John Payn,
who having been mayor the year before was then a justice in the borough,
to summon me afresh to appear before them at the council-chamber,
adjoining to the town-hall, where I accordingly appeared on the 31st of the sixth month,
1697.

When I came in, the mayor said, how do you do, neighbour?
What is the reason you don`'t pay the vicar his dues?
I answered,
I never read in the Holy Scriptures of any vicars among the ministers of Christ,
but the vicars are all of the Pope`'s making,
and both them and their maker I utterly deny; and no dues from me belong to any of them.

So there was nothing further done against me at that time,
by reason that the mayor only was there, and not the justice.

But on the 14th of the seventh month following, the mayor and justice being together,
and the priest with them, they sent for me to come before them at the town-hall.
And when I appeared, the mayor said to me, "`Neighbour,
I would have you pay the doctor,`" meaning the priest, "`his dues.`"
Thereupon the priest said, "`I do not claim it upon a spiritual account,
but by the law of the land; and but what is my due by act of Parliament,
which,`" said he, "`all subjects of what persuasion soever ought to submit to.`"

I answered, "`You can not claim by that act merely as a subject; but only as a vicar;
for as a subject, any other man that is a subject has as much right to claim as you.
But you being in place and office termed a vicar, which the Pope was the author of,
on that score it must needs be that you claim;
for if you should cease from and not perform your pretended office,
you would have no law whereby to make any claim at all.`"

Then the priest used many words to set forth his right by law for five years past.
But I told him his law, that he pretended to claim by, had not been made one year as yet;
and surely no law can punish a man for an offence
committed before such law had its being;
for the scripture says, where no law is, there is no transgression.

Then I showed him the judgment of the Attorney-General, which expressly says,
"`none could justly be sued by that act, for any refusal of paying tithes or offerings,
etc., which were due before the sessions of Parliament in which that act was passed.`"

The priest thereupon said, "`If I should claim but for the time since the act was made,
what will you say to that?`"

I answered, "`If you would excuse me for one penny, and say,
if I would pay that willingly, it should satisfy for all,
I tell you I cannot do it for conscience sake; for indeed,
though law has been occasionally mentioned, I came not here to plead law,
but to plead conscience towards God, in what I refuse and testify against.`"

The priest said,
"`I do marvel that any man should make conscience of that
which was a right by law,`" and further he said,
"`if the priests under the law had a right, I have the like now,`" or to that effect.

I told him,
"`The priests under the law had a right by the express command of God to receive tithes,
etc., which you have not; and yet they had no authority to take them by force.`"

He said, "`I can prove by scripture that which is equivalent thereunto.`"

But I told him he could not:
and that those then that took it by force were sons of Belial; as were the sons of Eli,
though they were priests.
"`I thought indeed,`" said I, "`and I have said it to some,
that I took you to be a wiser man than to stain your coat for such trifles.`"

He said he was bound by his oath to maintain the accustomed dues;
and began to plead that it was matter of conscience to him for his oath`'s sake,
to prosecute me if I did not pay.
And many more words he spoke to the same purpose;
which they would not give me liberty to reply to;
for they had determined before hand what to do, and had prepared a warrant in readiness,
which lay then on the table before I came there;
and the mayor and justice afterwards signed it, to make distress on my goods.

The priest before reported asserted, that "`Dissenters had their liberty by law,
on the condition of paying their dues, etc.,`" and said he,
"`if they refuse to pay their dues,
they have no right by law to enjoy their liberty in the exercise of their religion.`"

I said, "`You do much mistake:
for though the act does not exempt them from paying
such things as are unduly called dues;
yet if they do refuse to pay them,
they cannot therefore be deprived of the liberty granted them by that law.`"

Then as we were all passing away together, I said to the priest,
"`Such doings as these will be a blot in your escutcheon,^
footnote:[A stain or mark against one`'s reputation.]
and remain to your shame when you are in your grave.`"

About fourteen days after came Francis Giles, the tithing-man,
with the warrant before mentioned, and with him Ambrose Seeney, the priest`'s clerk,
and Richard Painter the bellman,
and for five years pretended dues unjustly claimed by the
priest for Easter offerings for me and my wife,
which he computed to be 4s. 2d+++.+++, they distrained and took from me two gross of laces,
worth at the lowest price nine shillings, and returned nothing.
But in about half a year after, this high priest and doctor James Canaries, died.

Sometime after this, I had a particular exercise on an unusual occasion,
which thus happened.

There was a man who had lived long in Abingdon, whose name was Robert Payn,
by trade a woollen draper, and by religious profession a baptist:
but his wife was one of our Friends and frequented our meetings.
It came to pass that this man fell sick and died, and on the 12th of the tenth month,
1697, his body being to be laid in the ground,
his wife invited me with many other of her neighbours to her husband`'s funeral:
and I feeling some drawings there, went.
When I came to the house there were two large rooms
nearly full and mostly of the baptist people.
And having sat a little time, the word of the Lord came weightily upon me;
whereby I was moved to go into the middle of the largest room;
and the people being all silent, I declared the truth,
in a short testimony to the light or manifestation of the spirit of Christ,
which all people are visited by and enlightened; with more to the same effect,
which I spoke for about a quarter of an hour.
And when I ceased, one John Tompkins, an old Baptist Teacher, made some opposition.
But I not having then opportunity to reply,
I wrote him a letter in vindication of my testimony, to which I never received an answer.

I mentioned before, that Dr. James Canaries, the chief priest of Abingdon,
who caused my goods to be taken away for his Easter offerings, as they call them,
died about half a year after.
And as the proverb says, "`seldom come a better;`" so bad as he was,
a worse succeeded him.
His name was Anthony Addesson, and he, as the former,
was priest of the Parish called St. Helen`'s in Abingdon.

This man prosecuted me for wages, though very unjustly,
because I not only never employed him, but always denied his work.
He proceeded upon the act for the more easy recovery of small tithes, etc.,
and made his complaint to John Spinnage, the then mayor, and John Selwood,
the town justice, in the year 1702, not against me only, but some others also,
for not paying him tithes and offerings.
Whereupon they gave forth a summons, for me to appear to answer the priest`'s complaint,
but there was neither time nor place mentioned in the summons.
I therefore told the officer that served it, that that summons signified nothing,
which perhaps they might tell the mayor; for the same evening,
the mayor sent one of his officers to me after the ninth hour,
to have me come before him then to answer the priest`'s complaint.
I told the officer it was an unseasonable time, and I was going to bed,
being partly undressed, and I thought the priest`'s business was not of so great haste,
but he might stay for a more convenient time; and I desired him to tell the mayor,
that I should be willing to come to him at any seasonable time.

And to prevent any misunderstanding, I went next morning to the mayor, and let him know,
that it was not in contempt of his authority that I did not come at his verbal command;
but only because it was so late in the night,
and he confessed it was an unseasonable time.
Then I told him "`I would willingly have a hearing,
to give my answer to the priest`'s complaint face to face.`"
And after some more discourse he promised me fair dealings, and so we parted fairly.

After this I heard no more of it for several weeks.
But about two months after, one of the officers came and acquainted me,
that a warrant was granted to make distress upon my goods for the priest.
And the same day, happening to meet with John Selwood the justice,
I asked him if there was a warrant against me?
He said there was.
I asked him how they could grant a warrant without letting me have a summons to appear,
that I might be heard in what I had to offer, in answer to the priest`'s complaint?
"`Why!`" said he, "`had you no summons?`"
I told him there was something called a summons,
but neither time nor place mentioned in it for appearance.
"`But`" said he, "`had you not a summons to appear last Tuesday at the Guild-hail?`"
I told him I had none at all.
Then he said, he would advise me to pay the minister, and make an end of it.
And so he passed away, and we had no more discourse.

Now when this warrant had lain in the officers`' hands some time,
the priest went to them, and, as they reported, did threaten them;
that seeing the warrant had been so long in their hands,
and they had neglected the execution of it:
if they did not forthwith execute the warrant, within three hours time,
and help him to his money, he would put them, every man into the crown-office.

Upon this high menace, the parish-officers, namely, John Linsie, Flora Read,
Thomas Bedwell, constables, and William Wells and Edward Baseley, called churchwardens,
came in all haste to my house, on the 31st of the fifth month 1702,
to make distress upon my goods, and showed me their warrant; which when I had read,
I desired them to let me take a copy of it, and they with one consent granted it.

So I went to writing, and they went on to take what goods they pleased the meanwhile;
but when I had just wrote out the copy,
John Linsie came and took hold of the paper I had written, and tore it away from me,
saying,
they were advised that it was not safe for them to let me have a copy of their warrant.
So they seized and carried away of my goods as follows:
Seventy three yards and a half of flat silk lacing,
which cost twelve shilling and threepence, one gross and a half of round thread laces,
worth at lowest, six shillings and ninepence; five dozen and a half of flat penny laces,
worth four shilling and three half-pence: three dozen of bobbin laces, two yards long,
worth two shillings and sixpence;
these goods at the lowest price came to five shillings and seven pence halfpenny.

The priest`'s claim, according to the custom used in Abingdon,
for two year`'s offering for me and my wife, could be but twenty pence.
But there was ten shillings set down in the warrant;
for which they took the value of one pound five shillings and sevenpence halfpenny,
and returned nothing again then.
But about a year and a half after, part of the goods,
to the value of nine shillings were sent back to my house,
with two and fourpence in money.
The goods, being my own, I received, but the money I refused,
and the messenger that brought it carried it back again.

Soon after they had taken my goods away,
in the consideration of their unjust and illegal proceedings,
I wrote a letter to the mayor and the justice thus directed.

To the Mayor of Abingdon, and John Selwood, justice for the same borough, these:

Friends and Neighbours,

If the oppressed may have leave to complain,
then I hope you will not blame me for these ensuing lines,
in relation to the case depending between the greedy hireling and me,
whom he persecutes for wages, though I never hired him.

First, as touching his complaint against me,
the law directs it should be made in writing twenty days after demand;
but this priest never made any lawful demand of me,
not so much as to let me know what or how much he did claim.

And as to your summons, which was indeed but a mock summons,
having neither time nor place mentioned in it, for appearance;
I think no man can judge this to be a lawful summons.
Which defect I thought at first to be an oversight of the clerk;
but since considering what has followed,
I rather conclude it to be a design to hide the hireling, lest by appearing face to face,
he should be made manifest.

And as for sending for me at ten at night without any warning;
it was both unseasonable and unlawful, for the law allows reasonable warning.
And although I did not come at that unseasonabe time, yet on the morrow I went,
and told the mayor that my neglect of coming was not in any contempt of his authority,
but only because it was so late at night;
and the mayor knows that he confessed it was an unseasonable time.
And then I requested the mayor to let me have an
opportunity to meet with the priest face to face,
that I might hear him prove his charge.
And the mayor said he would have me and the priest speak together,
and agree between ourselves.
To which I replied, that seeing he had openly complained against me,
therefore I thought it reasonable he should as openly prove, if he could, before my face,
what he had complained against me behind my back, or to that effect I then spoke,
as the mayor well knows.
And I further said, that I desired and expected to meet my adversary,
when and where the mayor should appoint.
To which the mayor answered and said, he hoped I should have no cause to call him,
meaning the priest, my adversary.
So he promising I should have fair dealing, I parted with him.
But he knows, there was not one word of what the priest demanded,
or of my refusing to pay, that passed between us.

So I waited long, expecting a summons to appear,
that I might give in my answer to the priest`'s charge or accusation as the act allows.
But instead thereof, after some weeks time,
I was informed there was a warrant granted to make
distress upon my goods for what the priest demanded,
and what that was, I did not know, before I saw it in the warrant.

The iniquity of this priest`'s covetousness is much greater than was his predecessor`'s,
whose demand was only tenpence a year; but this man`'s demand is five shillings a year,
for I know not what.

Pray consider, is this fair or just;
to give judgment without hearing the accused as well as the accuser.
It has been laid down as a maxim, that he who gives judgment in a case,
upon hearing only one party, though the judgment may be just, yet he is an unjust judge.

And how could you say in your warrant that Oliver Sansom did appear, but refused to pay,
etc.? I desire you to consider, when did I appear,
and before whom that anything was demanded of me?
Can anything be more untrue?
You know an appearance in this case ought to be before two justices,
for the law does not empower one to act alone in it.

And whereas your officers having given me leave to take a copy of your warrant,
just as I had wrote it, one of them tore it away and would not let me have it,
that the shame of your doings might not appear: I do claim it asmy common right,
being a subject, to have copies, I being at the cost,
of all proceedings against me that are under colour of law,
both of the priest`'s complaint and of your summons, and warrant for distress:
you know you ought not to carry things on clandestinely.
Moreover, the act allows the liberty of appeal, in case I am grieved with your judgment;
and ten days after notice given of what is adjudged before any procedure to distrain;
pray consider how illegally you have dealt with me.

And for the priest to threaten the officers as they say he did,
that if they did not execute your warrant within three hours,
he would put them every man into the crown-office.
Does not such language clearly discover that he is not in the meek spirit of Christ,
or practice of his ministers; but in the persecuting spirit of antichrist,
and in the steps of popish hirehngs; and that he serves not the Lord Jesus Christ,
but his own belly, and his reward will be according to his works.

You are my neighbours, and because I love you, I am thus plain with you,
and would not have you have a hand in gratifying the avarice of evil-minded men.
So committing my case to the righteous judge of heaven and earth,
to whom you as well as I must give an account,
and receive a reward according to our deeds, I remain,

Your well-wishing friend,

Oliver Sansom.

Abingdon, the 3rd of Sixth month, 1702.

The priest was highly displeased with me for the foregoing letter;
and meeting me in the street, he threatened to sue me at law for it.
Whereupon, after sometime, it came upon me to write to the priest thus:

Anthony Addesson,

I have had for sometime a concern upon my mind to write to you,
and in the love and fear of God to deal plainly with you,
because you do profess yourself to be a minister of Christ:
but your fruits declare you to be false, and of antichrist,
like to the false prophets and hirelings, which the true prophets,
Christ and his apostles testified against; as by the Holy Scriptures is apparent.
For Isaiah cried against them in his day, and called them greedy dumb dogs,
that could never have enough, that sought for their gain from their quarter.
Consider and see if you are not in the same steps.
And Jeremiah said, a wonderful and horrible thing is committed in the land,
"`The prophets prophesy falsely, and the priests bear rule by their means,
and the people love to have it so, etc.`" Jer. 4:30.
and chap, xxiii.
throughout.
See if you have not the very same marks.
And Micah declared against such in his days that did preach for hire,
and would cry peace, peace, to them that fed them;
but them that would not put into their mouths, they prepared war against.
Mic. iii.
Now see if this be not your practice.
Many other places of the prophets`' writings might be mentioned,
which mark you out plainly: and Christ himself said, beware of false prophets,
which come in sheep`'s clothing, but inwardly are ravening wolves; but by their fruits,
he said they should be known.
So that it was not by their clothing, or their words,
but their works or fruits should betray them, what spirit they were of.
And he also pronounced woes against those who walked in long robes,
and loved greeting in the markets, and the uppermost rooms at feasts,
and to be called of men rabbi or master.
Consider whether you are not exactly pointed out here by Christ Jesus himself.
Also the apostles in several of their epistles declared
against such as taught for filthy profit sake,
and through covetousness, with feigned words, made merchandise of the people;
and pronounced a woe against them that went in the way of Cain,
and ran greedily after the error of Balaam, who loved the wages of unrighteousness.
Now see if you are not as bad or worse than these: let your doings speak,
which do evidently manifest you to be worse than your father Balaam:
for although he loved the wages of unrighteousness, yet he dared not take it:
but you will have it, and take it by force; and bare such rule by your means,
making the magistrates do your drudgery,
and compelling the parish officers by severe threats to be your executioners,
for your dishonest gain, to make a spoil upon those you did never preach to.
Oh! be ashamed, and blush for your wickedness;
and do not presume any longer to make a trade of the prophets`' words,
and Christ`'s and the apostles`' words, written in the Holy Scriptures:
when as the Holy Spirit, which was in them, has given forth, in the same Scriptures,
such large and repeated testimonies against you and your doings, and all such as you are;
who have run, but the Lord never sent you, and so have not at all profited,
but deceived the people.
So these things I lay before you,
which by the Holy Scriptures (you call your rule,) are justly charged upon you:
and to the witness of God in your own conscience, I do appeal for judgment,
which will one day answer to the truth herein testified.
And whether you will hear or forbear,
I have cleared my conscience of what lay upon me from the Lord to warn you of:
desiring you may seek, and find a place of repentance before it be too late.
And if ever you do obtain repentance unto life you will know that I am your friend,
that desires your soul`'s eternal welfare,

Oliver Sansom.

Abingdon, the 29th of Ninth month, 1702.

It was about two years after this before I heard of this priest again.
And then in the tenth month, 1704,
he made another complaint against me for more tithes and offerings.
Whereupon the mayor (whose name was John Spinnage,) and John Selwood the justice,
sent a verbal summons for me to appear before them.
I appeared accordingly, and the priest was present to charge;
but had no evidence to what he claimed, so the matter was for that time deferred.

But so subtle was this greedy priest, that a while after he wrote a paper,
containing on the one side his complaint against me and many others;
and on the other side our names, with the several sums he charged on us.
And under his complaint there was drawn up a warrant
bearing date the 14th of the month called January,
1705, for levying those sums by distress,
which the priest had so charged in case payment was refused.

To this warrant the priest prevailed with the mayor
and justice to set their hands and seals,
against at least forty persons, without giving us any summons,
or hearing what any of us had to say in our defence.

This warrant was kept private for near half a year;
so that neither I nor any of our friends concerned in it knew anything of it.
But about two months after the date of it,
the mayor pretended that I and two more of our Friends should have a fair hearing,
to give our answer to the priest`'s complaint.
Whereupon according to his appointment, we went to his house;
and found the priest at the mayor`'s door when we came; but when he saw us,
he would not go in but slunk away, so that nothing could then be done.
Yet the mayor then promised us, we should have a fair hearing,
before any further proceedings should be against us.
So we heard no more of it until the 5th day of the seventh month following,
at which time the parish officers came to my house, and showed me the warrant,
and gave me notice that they must shortly make distress upon my goods, by that warrant,
unless I would pay the priest`'s demand.

Thereupon I went to the mayor, and reminded him of his promise which he acknowledged,
and said he would speak with the priest again about it, which I suppose he did,
for after two or three days,
he sent me a note to desire me and another Friend to come to his house.
We went accordingly on the 11th day of the seventh month, 1705, and the priest came also.
And there had I a good opportunity,
in the strength of the Lord to clear my conscience to the priest`'s face,
in bearing my testimony against his unchristian practices, showing by plain scripture,
that he was in the very way and steps of the false prophets,
hirelings and false ministers; which the true prophets,
Christ and his apostles testified against.

But the mayor, though a moderate man, being unwilling to displease the priest,
took his affirmation without other proof, and granted his demand,
which was twice as much as he could by law claim.
And the priest having written a new copy of his old complaint,
and written a copy of the old warrant under,
got the mayor and justice to set their hands and seals to this transcript of his,
wherein were the names of abundance of persons of the parish,
with a certain sum of money set to every man`'s name,
what the priest was pleased to tax them at for his pretended dues.
And his paper of names, filling near a side of a whole sheet of paper,
was tacked to the warrant; which bore date the 14th of January as before.

With this warrant the two constables, William Lewis and William Hutt,
with John Linsie and Henry Hall, called church-wardens,
came to my house on the 21st of the said seventh month, 1705,
and for five shillings and eightpence unjustly demanded,
distrained and carried away a brass kettle and a pot.
The kettle, which was worth fourteen shillings,
they sold for eleven shillings and sixpence, and brought the pot home again,
with four shillings and tenpence in money, which they said was the overplus.
The pot I received, but refused to take the money; whereat they seemed displeased,
and as they went away, threw it on the table, and there left it.

By what is above related,
it may clearly be seen how the priests make the magistrates their servants,
to do their drudgery for them, though against equity and justice.

Again in like manner, the said priest Anthony Addesson, in the year 1708,
made his complaint against me to the then mayor, John Selwood; and Richard Ely,
justice for the borough of Abingdon, for not paying his pretended dues, namely,
tithes and offerings.
The said complaint was in writing, and a warrant close to it on the same piece of paper,
and all one handwriting,
which the priest prevailed with the said mayor and
justice to set their hands and seals unto,
in which warrant was liberty granted for the priest to endorse on the backside
thereof the names of all in the parish that were behind in paying what he claimed,
and to charge them with what sums he pleased,
and to make distress on their goods in case of non-payment.
And I was charged six shillings and eightpence,
which was more than twice as much as by law he could claim.

The said warrant was dated the 17th of the first month, 1708,
and I heard nothing of it until the eighth month following,
and on the 29th of the eighth month, 1708, the parish officers, namely Richard Sanders,
constable, Edmund Bowel, church-warden, John Hawkins, Sergeant and Edward Snow,
the priest`'s clerk, came to my house with the said warrant, which they let me see,
but would not allow me to take a copy of it, though I much desired it,
they seized and carried away two hundred and thirty-four yards of clock line,
worth eighteen shillings and upwards.

The said Richard Ely, called a justice of the peace,
whose hand and seal was to the warrant aforesaid,
who had as to outward appearance carried himself smooth and loving towards me,
but because he did so unjustly, in signing this illegal warrant,
I could not be clear but to write a letter to him; a copy whereof here follows.

Neighbour Ely,

Yesterday some of the parish officers came to my house with a warrant,
bearing date the 17th of the month called March last, signed by John Selwood and you;
whereby I was charged with six shillings and eightpence,
pretended to be due from me to your vicar:
and for the said sum of six shillings and eightpence,
they seized and carried away of my goods to the value of eighteen shillings.

Truly I do wonder that reputed wise men should be thus imposed upon by a false accuser,
as to grant his accusation without proof; for of the said six shillings and eightpence,
there must be five shillings of it charged upon the tithe of the
fruit of the orchard at our burying ground for two years;
and the fruit that I had from there at that time should be worth fifty shillings.
But I can truly say from a certain assurance,
that the fruit that I had at that time was not worth fifteen shillings,
and I challenge your vicar and all his agents,
to prove that it was worth more if they can:
now you know it is unjust to charge a man for tithe
of fifty shillings when not worth fifteen shillings.
I desire you to consider of it,
whether your leader has not caused you to err greatly in this matter,
and in love I advise you to take heed in time how you follow such leaders,
lest you fall before you are aware into the ditch of eternal misery.
I am concerned to be more plain with you, because I desired you when you were mayor,
not to grant the aforesaid vicar a warrant,
unless he brought good evidence to prove what he demanded,
according to the act you pretend to proceed by; though I must acknowledge,
that your laws for forced maintenance, I cannot own, so as actively to obey them,
because not agreeable to the law of God and the Holy Scriptures,
yet I always submit passively by patient suffering without resistance,
according to our peaceable Christian principle,
what the Lord permits to be exercised upon us.

But if you had proceeded according to the direction and intention of the aforesaid act,
as to cause the complainant to prove his charge, by substantial witnesses before my face;
then you had not made yourselves guilty of so great injustice in this matter.
I do not complain as being grieved for the loss of my goods,
because it is for the testimony of my conscience against false teachers,
who are such as the prophet called dogs, Isaiah Ivi.
10-12. Yes, greedy dogs, that could never have enough,
who sought for their gain from their quarter;
surely it will not be easy to find a man more greedy than my accuser,
whose fruits make him manifest to be but one of them, that Christ said,
would come in the sheep`'s clothing, but are inwardly ravening wolves.

I can truly say, that in love and good will to you,
and for the clearing of my conscience, I have written and sent these lines;
desiring you may repent before it is too late, of what you have done amiss;
that it may be well with you both here and hereafter.

And know this, that I am not troubled for the loss of my goods,
nor angry with you though unjustly deprived of them, for I can say,
through the Lord`'s goodness to me,
that I have a treasure which the thief or robber cannot reach;
yet I am somewhat concerned for your sake,
that you should be so drawn aside to do injustice, as is before expressed;
which may bring a blemish upon your name,
and be of an ill savour when your body is in the dust; so in that love of God,
which can forgive injuries, and do good for evil, I take my leave and remain,

Your well-wishing friend,

Oliver Sansom.

P+++.+++ S. If you please, you may let John Selwood see this letter,
he has dealt unjustly by me in the like case formerly.
But I did clear my conscience to him in writing then; and to John Spinnage also,
the then mayor; but I did hope for better dealing from you,
though I have missed of my expectation.

O+++.+++ S.

Abingdon, 30th of Eighth month, 1708.

Some time after, the said Richard Ely meeting me in the street, said to me,
he had received a letter from me, and was sorry for what was done,
but he did not think any harm of it;
for the warrant was brought to him with the mayor`'s hand and seal to it;
and he was desired to set his hand and seal, which he did, not designing any hurt to me,
with more such words.

I told him, he ought to have done justice,
and not to condemn a man without hearing or evidence; so we parted.

And it was a month or so, before the officers could sell the goods,
but at length they sold them at a very low price, twelve shillings and sixpence.
But when they had the money in their hands,
the greedy priest being not content with the six
shillings and eightpence charged upon the warrant,
caused them to give four shillings, as one of them informed me,
upon pretence that something was due to him for former arrears.

In consideration of this priest`'s unjust and illegal proceedings,
I could not be clear without writing a letter once more to him.
Which letter was delivered to his own hand, but he returned no answer.

And about the same time, two of the officers that took away my goods,
came to my house and said, they had brought me some money, which they said,
was the over-plus after the priest was paid.
I then said, as I never employed them to sell any goods of mine,
so I should not concern myself with their account; and when they saw I would not take it,
they left ten-pence on the table and went away.

* * *

+++[+++This concludes the narrative of this faithful minister of the gospel,
and patient sufferer for the Truth,
as recorded by himself It appears from the date of the last letter,
the transactions subsequent thereto, and the date of Oliver Sansom`'s decease,
that he brought down his account to within a few
months of the time when that event occurred.
That which follows is from the pen of John Field,
the compiler of three volumes of that valuable work,
"`Piety Promoted,`" and author of several short pieces.]

Notwithstanding the aforegoing account of the Labours, Travels and Sufferings,
as also the Testimonies concerning that ancient and innocent servant of Christ,
Oliver Sansom, I am willing briefly to add what follows.
He was a man sound in doctrine, of a savory and exemplary conduct,
careful to observe Christian discipline,
and for promoting good order in the church of Christ;
faithful in his testimony for the blessed Truth,
diligent in attending meetings at the appointed times, not only on first-days,
but other days of the week, and to wait upon the Lord therein.
And as the Lord was pleased to make him a minister of the word of life,
so as he was opened by the power of it,
he would therein exhort Friends to faithfulness and perseverance,
in the work and service of the Lord, and to keep up their testimonies for Him,
and to watchfulness pursuant to our Lord`'s general command to all,
that none by the enemy of the soul`'s peace,
might be drawn into that which would chill their love, cool their zeal,
and cause them to decline therein: but that they might all go on in faithfulness,
by knowing their strength renewed in a diligent waiting upon the Lord,
might hold on their way to death that they might have the crown of life.

I have long known the sincerity of my deceased friend and brother,
being acquainted with him above thirty years, and loved him for the Truth`'s sake,
and his diligent service therein, and readiness to help, assist,
and counsel the poor widow and the fatherless,
and such that did apply to him for the same.

I held a correspondence with him for many years,
upon the affairs of Truth and the sufferings of Friends for its sake;
and his letters were grave and seasoned with that which made them savory,
and showed that he wrote in a sense of the holy truth he possessed and suffered for.

What I thus write is principally to commend that holy life and power, and those virtues,
that by the work thereof he was endued with; and my friend,
so far as he was worthy of commendation, as he was by being endowed therewith.

And it is my desire, that those that are yet on this side of the grave,
may be excited more and more to love and obedience to the Lord,
and thereby come to possess the like Christian virtues.
And through faithfulness be fruitful in holiness, and therein continue unto death,
and be a follower of our deceased friend as he followed Christ.

Then though we continue here many days or kw, we all shall be blessed,
for the righteous are blessed in their death, and their souls are in the hand of God,
and shall be in peace with him forever.

So with what our friend and brother said, a little before his departure,
I shall conclude; '`By reason of age,
it is not likely I should continue long with Friends here.
But, said he, be you faithful as I have been,
and you will have the same reward as I am likely to have, and be you followers of Christ,
as you have had me for an example,
for I have been true to what the Lord committed to my charge.

He departed this life the 23rd of the second month, 1710,
and was buried at Abingdon on the 26th.

JOHN FIELD.

London, 15th of Fifth month, 1710.

* * *

A TESTIMONY From the monthly meeting at Charlnw in the Vale, in Berkshire,
the 12th of the Third month, 1710, concerning our ancient and beloved brother,
and servant of Christ, Oliver Sansom.

It lives in our hearts to give forth the following Testimony,
from an experimental knowledge of him and his faithful labours of love,
that his ministry was plain and prevalent,
and in the power and demonstration of the spirit;
and he was not only a preacher up of love and good works, but practised them;
and was one of whom it may be truly said,
with respect to his readiness freely to impart of
his outward substance to the poor and needy,
as it was said of the merciful man, "`He has dispersed, he has given to the poor,
his righteousness endures forever.`"
Ps. 112:9.

And his testimony was against all the pollutions of the world, against all pride,
and the vain fashions and customs thereof,
and he laboured that Truth might be in dominion among us,
and that such who professed it might prosper and grow therein,
according to the gift and grace of God bestowed upon them; and we can truly say,
he was very serviceable both in his , ministry and the other services of the Church,
and was preserved even to a good old age,
in a holy life and exemplary conduct unto death.

He was a good husband, master, and neighbour,
and a serviceable instrument in the hand of the Lord,
for turning many from darkness to light, and from the power of Satan unto God,
and for the convincing, converting and confirming them in the faith of the gospel;
and his memorial lives, and he is gathered as a shock of wheat in its season.

He was mindful to entertain strangers, to visit the prisoners,
that suffered for Christ`'s sake, sympathized with the afflicted,
and was careful over the widows and fatherless.

He admonished the disorderly walkers, and laboured with them and backsliders,
to bring them to repentance and amendment of life.

And although it is our loss to part with him, it is to his gain;
and the full persuasion thereof mixes our sorrow with joy,
being fully satisfied he has his part in the kingdom of God,
and is crowned with immortality and eternal life, and has left us a good example,
which we hope will not be forgotten by us,
to keep to that power that wrought so effectually in him, that we, who are left behind,
may trust in the Lord, and faithfully obey Him who is the Fountain of all our mercies,
that we may answer his great love in visiting us both immediately and instrumentality,
to persevere in well-doing, and be followers of our deceased friend,
as he was a follower of Christ unto the end.

Thus we have given this short testimony for the glory of God,
the magnifying of his living power,
which through Christ Jesus was revealed and manifested in this our friend, elder,
and brother in the Truth, who departed this life, the 23rd of the second month, 1710,
and was buried the 26th following, in Friends`' burying-ground at Abingdon;
being accompanied with many Friends,
and faithful testimonies were then borne to the Truth.

Signed on behalf of the said meeting, by us, Thomas Withers, Robert Withers,
Adam Lawrence, William Orpwood, Daniel Bunco, Jun., Jeremiah Harman.

We whose names are hereunto subscribed,
have unity with our Friends of the monthly meeting of Charlow in the foregoing testimony,
concerning our dear and well-beloved friend and brother, Oliver Sansom;
and because it is very well and particularly set forth,
we need here say no more for brevity sake concerning him.

From our monthly meeting at Reading, in the county of Berks, the 1st of the sixth month,
1710.

John Buy, Sen.
William Laniboll, Sen.
Daniel Bullock, John Thorn.
John Reason.
William Penn.
William Lawrence.
Richard Hoskin.
Joshua Chesterman.

N+++.+++ B.--William Cooper, Mary Cooper, Sarah Withers, and Elizabeth Vokins, Daniel Flaxney,
and Oliver Sansom, junior,
having given distinct testimonies concerning the said Oliver Sansom,
the substance whereof being included in the foregoing,
the said particular testimonies therefore are not thought needful to be printed.

The Testimony of Oxford Friends Concerning Oliver Sansom.

In the remembrance of our dear friend deceased, whose memory remains sweet to us,
we have this to say of him, our meeting being often visited by him.
He had a tender care for the prosperity of truth in this place as well as in Abingdon,
the place of his abode; where, with his testimony for the truth,
his life and conduct was altogether consistent; which gave him an acceptable character,
not only among Friends, but other sober people also;
and when he was concerned to visit us at our meeting in Oxford,
and had anything given him from the Lord to declare, he was supported to clear himself,
and in his testimony took little notice of the rude behaviour of the scholars;
but after the meeting would say, he had not seen the like in any place,
especially at our burials, and bemoaned our exercise,
yet he would often sit down with us to wait on the Lord
and we cannot forget his labours of love among us,
and in our county, and have great satisfaction of his well-being with the Lord;
and though our loss be his gain, yet the loss of holy men,
sound in doctrine and clean in example is very great;
and except the succeeding generation have a sense of the loss of such men,
as fear and serve God in their age,
it cannot be expected their services should be supplied by them; which,
that it may be so, is, and shall be our desires to the Lord.

Signed on behalf of the meeting at Oxford, the 21st of the third month, 1710.

Thomas Nickolls, Jun.

Thomas Ellwood`'s Testimony Concerning Oliver Sansom.

That the righteous shall be had in everlasting remembrance,
we are assured by the royal Psalmist; and that the memory of the just is blessed,
we are told by his wise son; the truth of which is confirmed to us by our own experience:
for from the beginning of the world, so far as the holy records reach,
the righteous of all ages, whose names are therein mentioned,
are to this day had in remembrance, and their memory is still sweet and blessed among us,
though but briefly touched in the holy text.
Enoch, it is said, walked with God, Gen. 5:24.
That is a short but full remembrance of him.
The like we read of Noah, Gen. 6:9.
"`He was a just man and perfect in his generation; and walked with God.`"
"`Job was a perfect and upright man; one that feared God, and eschewed evil,`" Job 1:1,
for which he is still had in remembrance by the righteous,
and his memory is precious to this day.

The like, without drawing any comparison,
may be truly said of our deceased friend and brother,
Oliver Sansom;--that he was a just and upright man,
one that feared God and eschewed evil: whose life, labours, travels,
and sufferings are briefly recited in the foregoing sheets.

Though he came later into the Lord`'s vineyard than many others,
yet from the time he did come in,
he came not behind many others for painful diligence
and watchful industry in the work he was called to.

For the last twenty years or more of his life, I knew him well,
and conversed with him often, either personally or by writing.
And from the knowledge I thus had of him,
and the sense which dwells upon my spirit concerning him, I have this testimony to bear,
in a few words of him,
as to his honest and innocent life:--that he was a good steward of his Master`'s treasures;
a faithful dispenser of the divine mysteries committed to him;
an inward and heavenly-minded man, more in substance than in show;
greater in power than in expression; a man meek and quiet in spirit, yet full in zeal;
but that so well tempered with and governed by knowledge,
that it tended to the good of all, not the hurt of any.
Adorned he was with humility, temperance, and self-denial, valiant in the Lamb`'s war,
and bold in defence of the truth; patient in suffering for the truth,
through which he obtained the victory; so addicted he was,
and wholly given up to the service and promotion of the Truth,
that he spared not on all good occasions to spend as well as to be spent therein;
contracting his own private expenses, and rather straitening himself,
that (his outward estate not being great) he might be able the more freely
to lay forth himself and it in public services for Truth and Friends.

The Lord send forth more such faithful labourers into his vineyard,
and support and bless them in their labours therein till their work be finished,
as he did him;
of whom in a word it may be truly said--he lived and died a servant of the Lord.

Thomas Ellwood.

The Testimony of Jane Sansom, concerning her dearly beloved husband, Oliver Sansom.

This testimony I have to give forth concerning my dear husband,
whom the Lord in his great mercy was pleased to give me,
which I can truly say was a great blessing from the Lord to me,
for he was convinced of the blessed truth before me,
and very helpful to me in my convincement,
and always very careful for my prosperity in it; so that the loss of him is very great,
and a trying exercise to me.
But having had such a pattern before me as my dear husband was in meekness and humility,
engages me to submit to the will of the Lord, which I find is most acceptable to him,
and profitable to me; for the Lord gives and he takes away,
and I may say with one of old, blessed be His name,
in that he was pleased to spare my dear husband so long with me, as he did,
to be a comfort to me,
and to be serviceable in that work which the Lord in his mercy had called him to.
I can truly say,
that I never saw him cast down at any suffering that
he met with for the testimony of Jesus,
but was borne up in the heavenly patience, which is a great comfort to me now,
yet his tender counsel and good example lives with me.

So having given forth this short testimony for the glory of God,
and for the encouragement of the faithful to trust in the Lord along,
who raises up instruments for his own work and takes them away in his own time;
this I can say to the praise of the Lord, that my dear husband was preserved to the last,
in all his illness, in the heavenly patience.

Jane Sansom.
